// ============================================================================
// src/content/about/old-sites.ts
// ----------------------------------------------------------------------------
// THE EARLIER SITES, RECONSTRUCTED (PRIME, 2026-10-05 11:03: "let users
// navigate a modernized local CLONE of the old sites. Complete with animated
// banner and the tools that were available on the historical sites").
//
// The clones themselves are static files under public/archive/sites/<slug>/,
// generated by scripts/old-sites/build-clone.py from the hosting account's
// export of 5 March 2013 (PRIME's own files, kept out of the repository). This
// module is the typed registry the wrapper pages read: which clones exist, which
// inventory era each belongs to, where the home file is, and the manifest the
// generator wrote (pages, orphans, repairs and the count of every change), so a
// number on the wrapper page is one the generator counted, never one typed in.
// ============================================================================

import { ARCHIVED_ERAS, type ArchivedEra, type ArchivedPage } from "@/content/about/earlier-sites";
import nn2004 from "@/content/about/old-sites/nutzmann-net-2004.json";
import ntz2013 from "@/content/about/old-sites/ntz-com-br-2013.json";

/** One page of a clone, as the generator recorded it. */
export interface ClonePage {
  /** Path within the clone (and within the original site). */
  path: string;
  /** The page's own <title> as published; empty when it had none. */
  title: string;
  /** The original encoding declared by the file (iso-8859-1 or windows-1252). */
  encoding: string;
  /** The change kinds the generator applied to this page. */
  changes: string[];
  /** Size of the rewritten page in bytes. */
  bytes: number;
}

/** One reference the generator repaired (the server would have failed it). */
export interface CloneRepair {
  /** The page that carried the reference. */
  page: string;
  /** The reference as written. */
  url: string;
  /** The file it now points at. */
  to: string;
  /** How it was repaired: "root" (same path from the site root), "imgdir" (the other image folder name), "ext" (.htm/.html twin). */
  how: string;
}

/** The manifest written by scripts/old-sites/build-clone.py next to each clone. */
export interface CloneManifest {
  /** The export folder (the domain). */
  site: string;
  /** The clone slug. */
  slug: string;
  /** The day the clone was made. */
  made: string;
  /** The date of the hosting export the clone was built from. */
  exportDate: string;
  /** Every page written, sorted by path. */
  pages: ClonePage[];
  /** Pages on the server that no menu reached (included, listed apart). */
  orphans: string[];
  /** Number of asset files copied. */
  assets: number;
  /** The count of every change kind (per page for charset/analytics/flash/forms/eval, per reference otherwise). */
  changes: Record<string, number>;
  /** Files of the export not carried over. */
  excluded: string[];
  /** References left broken because they were broken in the original too. */
  unresolved: { page: string; url: string }[];
  /** The references repaired. */
  repairs: CloneRepair[];
  /** The pages the original linked but never had, with the Internet Archive's record (Portuguese, as written on the reconstruction pages). */
  dead: Record<string, string>;
  /** The never-published tools (path to kind). */
  toolsMissing: Record<string, string>;
  /** Number of pages. */
  pageCount: number;
}

/** One reconstructed site. */
export interface OldSiteClone {
  /** The URL slug under /about/earlier-sites/ and /archive/sites/. */
  slug: "nutzmann-net-2004" | "ntz-com-br-2013";
  /** The inventory era this clone belongs to (its copy and its capture list). */
  era: ArchivedEra["id"];
  /** The domain as it was. */
  domain: "nutzmann.net" | "ntz.com.br";
  /** The year the clone represents (the files' own dates). */
  year: number;
  /** The home file within the clone. */
  home: string;
  /** The bits-and-bytes calculator page within the clone (the one tool that was published and works). */
  calculator: string;
  /** The reproduced Flash bar's encode name under /archive/earlier-sites/flash/. */
  bar: "barra2_topo" | "topbar";
  /** A rendering of the reconstruction's home page at 800 x 600 (the bar paused one second in), the card's thumbnail. */
  thumbnail: string;
  /** The day that rendering was made, YYYY-MM-DD. */
  thumbnailDate: string;
  /** The generator's manifest. */
  manifest: CloneManifest;
}

/** The public prefix of every clone. */
export const CLONE_PREFIX = "/archive/sites/";

/** The day the clones were made (every provenance comment carries it). */
export const CLONE_MADE = "2026-10-05";

/** The hosting export the clones were built from. */
export const CLONE_EXPORT_DATE = "2013-03-05";

/** The day the Internet Archive's CDX index was read for the dead-link facts. */
export const CLONE_CDX_READ_DATE = "2026-10-05";

/** The two clones of this wave, oldest first. */
export const OLD_SITE_CLONES: readonly OldSiteClone[] = [
  {
    slug: "nutzmann-net-2004", era: "nn-2004", domain: "nutzmann.net", year: 2004, home: "index.htm", calculator: "bitsandbytes.htm", bar: "barra2_topo",
    thumbnail: "/archive/earlier-sites/clone-nutzmann-net-2004.png", thumbnailDate: "2026-10-05", manifest: nn2004 as CloneManifest,
  },
  {
    slug: "ntz-com-br-2013", era: "ntz-2013", domain: "ntz.com.br", year: 2013, home: "index.html", calculator: "bitsandbytes.html", bar: "topbar",
    thumbnail: "/archive/earlier-sites/clone-ntz-com-br-2013.png", thumbnailDate: "2026-10-05", manifest: ntz2013 as CloneManifest,
  },
];

/** The clone for a slug, or undefined. */
export function findClone(slug: string): OldSiteClone | undefined {
  return OLD_SITE_CLONES.find((c) => c.slug === slug);
}

/** The public URL of a file within a clone (the home when no file is given). */
export function cloneUrl(clone: OldSiteClone, file?: string): string {
  return `${CLONE_PREFIX}${clone.slug}/${file ?? clone.home}`;
}

/** The wrapper page's path (locale-relative). */
export function cloneWrapperPath(clone: OldSiteClone): string {
  return `/about/earlier-sites/${clone.slug}`;
}

/**
 * The Internet Archive capture of a clone page, when the inventory has one under the same file name (the home is
 * inventoried as index.html, the capture of the bare domain). Undefined when the archive never captured that file.
 */
export function captureFor(clone: OldSiteClone, path: string): ArchivedPage | undefined {
  const era = ARCHIVED_ERAS.find((e) => e.id === clone.era);
  if (!era) return undefined;
  const wanted = path === clone.home ? "index.html" : path;
  return era.pages.find((p) => p.file === wanted);
}

/** The change kinds in the order the wrapper page lists them (a kind with a zero count is not shown). */
export const CHANGE_KINDS = [
  "charset", "flash", "analytics", "forms", "eval", "missingTools", "deadLinks", "pathFixes", "linkTypos", "absoluteSelf", "crossSite", "externalLinks", "caseFixes", "mirrors",
] as const;
