// ============================================================================
// src/lib/tools/charset-equivalency/golden-vectors.ts
// ----------------------------------------------------------------------------
// GOLDEN VECTORS for the charset converter and mojibake repair
// (set "charset-equivalency-golden-2026-10-03"). GENERATED by scratchpad/cs/gv/gen-cs.mts.
//
// Three kinds of vector. An encoding pins the bytes, the byte order mark, what
// could not be held, three output styles, the same text in all fourteen
// charsets and the bytes read back in all fourteen. A decoding pins the
// format read (hex dumps, escapes, %XX, Base64), the charset used and why,
// the text, every replaced sequence with its offset, length and reason, and
// the same bytes in all fourteen charsets. A repair pins the candidates, their
// steps and the kind of evidence.
//
// Expected values were captured from compute.run() on 2026-10-03, then checked:
// 49 reference checks, 49 agree (CPython 3.11 codecs for every
// charset; Node 22's WHATWG TextDecoder for UTF-8, UTF-16 and windows-1252; the
// dump inputs are real util-linux hexdump -C and xxd output; ftfy 6.3.1's
// fix_encoding for the UTF-8 repairs; CPython round trips for the others).
// Characters outside printable ASCII are written as \uXXXX escapes.
// ============================================================================

import { run, type CharsetInput, type CharsetResult } from "./compute";

/** The set id: the tool slug and the date the expected values were captured. */
export const GOLDEN_VECTOR_SET_ID = "charset-equivalency-golden-2026-10-03";

/** One vector: a name, what it shows, an input, and the pinned fields of its result. */
export interface CharsetVector {
  // A short stable name.
  id: string;
  // What it shows.
  note: string;
  // The input, exactly as the tool takes it.
  input: CharsetInput;
  // The pinned fields of the result.
  expect: Record<string, unknown>;
}

/** Bytes as upper-case hex pairs. */
const hex = (b: readonly number[]) => b.map((x) => x.toString(16).toUpperCase().padStart(2, "0")).join(" ");

/** Reduce a result to the fields a vector pins. */
export function pin(r: CharsetResult): Record<string, unknown> {
  // An encoding: bytes, BOM, counts, three styles, every charset, the read-back.
  if (r.mode === "encode") return { mode: r.mode, charset: r.result.charset, bytes: hex(r.result.bytes), bom: r.result.bom ? hex(r.result.bom) : null, codePoints: r.result.codePoints, unencodable: r.result.unencodable, failed: r.result.failed, styles: { python: r.styles.python, base64: r.styles.base64, percent: r.styles.percent }, everywhere: r.everywhere.map((w) => [w.charset, hex(w.bytes), w.unencodable]), readBack: r.readBack.map((x) => [x.charset, x.text, x.errors]) };
  // A decoding: what was read, how it decoded, every charset.
  if (r.mode === "decode") return { mode: r.mode, parsed: { format: r.parsed.format, dump: r.parsed.dump ?? null, error: r.parsed.error ?? null, bytes: hex(r.parsed.bytes) }, result: r.result ? { requested: r.result.requested, charset: r.result.charset, guess: r.result.guess ?? null, bom: r.result.bom, bomOverride: r.result.bomOverride, text: r.result.text, errors: r.result.units.filter((u) => u.error).map((u) => [u.at, u.len, u.error]) } : null, everywhere: r.everywhere.map((x) => [x.charset, x.text, x.errors]) };
  // A repair: the candidates.
  if (r.mode === "repair") return { mode: r.mode, inputScore: r.result.inputScore, candidates: r.result.candidates.map((c) => ({ text: c.text, steps: c.steps.map((s) => `${s.misread}>${s.original}`), evidence: c.evidence, lossy: c.lossy, lost: c.lost })) };
  // An error.
  return { mode: r.mode };
}

/** The vectors. */
export const VECTORS: CharsetVector[] = [
  // Portuguese text in UTF-8: two bytes for each accented letter, three for the en dash.
  {
    // Name.
    id: "encode-portuguese-utf8",
    // What it shows.
    note: "Portuguese text in UTF-8: two bytes for each accented letter, three for the en dash",
    // Input.
    input: {"mode":"encode","text":"Requisi\u00E7\u00E3o bloqueada \u2013 caf\u00E9","charset":"utf-8"},
    // Pinned result.
    expect: {"mode":"encode","charset":"utf-8","bytes":"52 65 71 75 69 73 69 C3 A7 C3 A3 6F 20 62 6C 6F 71 75 65 61 64 61 20 E2 80 93 20 63 61 66 C3 A9","bom":null,"codePoints":27,"unencodable":0,"failed":false,"styles":{"python":"b'Requisi\\xc3\\xa7\\xc3\\xa3o bloqueada \\xe2\\x80\\x93 caf\\xc3\\xa9'","base64":"UmVxdWlzacOnw6NvIGJsb3F1ZWFkYSDigJMgY2Fmw6k=","percent":"Requisi%C3%A7%C3%A3o%20bloqueada%20%E2%80%93%20caf%C3%A9"},"everywhere":[["utf-8","52 65 71 75 69 73 69 C3 A7 C3 A3 6F 20 62 6C 6F 71 75 65 61 64 61 20 E2 80 93 20 63 61 66 C3 A9",0],["utf-16le","52 00 65 00 71 00 75 00 69 00 73 00 69 00 E7 00 E3 00 6F 00 20 00 62 00 6C 00 6F 00 71 00 75 00 65 00 61 00 64 00 61 00 20 00 13 20 20 00 63 00 61 00 66 00 E9 00",0],["utf-16be","00 52 00 65 00 71 00 75 00 69 00 73 00 69 00 E7 00 E3 00 6F 00 20 00 62 00 6C 00 6F 00 71 00 75 00 65 00 61 00 64 00 61 00 20 20 13 00 20 00 63 00 61 00 66 00 E9",0],["utf-32le","52 00 00 00 65 00 00 00 71 00 00 00 75 00 00 00 69 00 00 00 73 00 00 00 69 00 00 00 E7 00 00 00 E3 00 00 00 6F 00 00 00 20 00 00 00 62 00 00 00 6C 00 00 00 6F 00 00 00 71 00 00 00 75 00 00 00 65 00 00 00 61 00 00 00 64 00 00 00 61 00 00 00 20 00 00 00 13 20 00 00 20 00 00 00 63 00 00 00 61 00 00 00 66 00 00 00 E9 00 00 00",0],["utf-32be","00 00 00 52 00 00 00 65 00 00 00 71 00 00 00 75 00 00 00 69 00 00 00 73 00 00 00 69 00 00 00 E7 00 00 00 E3 00 00 00 6F 00 00 00 20 00 00 00 62 00 00 00 6C 00 00 00 6F 00 00 00 71 00 00 00 75 00 00 00 65 00 00 00 61 00 00 00 64 00 00 00 61 00 00 00 20 00 00 20 13 00 00 00 20 00 00 00 63 00 00 00 61 00 00 00 66 00 00 00 E9",0],["us-ascii","52 65 71 75 69 73 69 3F 3F 6F 20 62 6C 6F 71 75 65 61 64 61 20 3F 20 63 61 66 3F",4],["iso-8859-1","52 65 71 75 69 73 69 E7 E3 6F 20 62 6C 6F 71 75 65 61 64 61 20 3F 20 63 61 66 E9",1],["windows-1252","52 65 71 75 69 73 69 E7 E3 6F 20 62 6C 6F 71 75 65 61 64 61 20 96 20 63 61 66 E9",0],["iso-8859-15","52 65 71 75 69 73 69 E7 E3 6F 20 62 6C 6F 71 75 65 61 64 61 20 3F 20 63 61 66 E9",1],["macintosh","52 65 71 75 69 73 69 8D 8B 6F 20 62 6C 6F 71 75 65 61 64 61 20 D0 20 63 61 66 8E",0],["ibm437","52 65 71 75 69 73 69 87 3F 6F 20 62 6C 6F 71 75 65 61 64 61 20 3F 20 63 61 66 82",2],["ibm850","52 65 71 75 69 73 69 87 C6 6F 20 62 6C 6F 71 75 65 61 64 61 20 3F 20 63 61 66 82",1],["ibm037","D9 85 98 A4 89 A2 89 48 46 96 40 82 93 96 98 A4 85 81 84 81 40 6F 40 83 81 86 51",1],["ibm500","D9 85 98 A4 89 A2 89 48 46 96 40 82 93 96 98 A4 85 81 84 81 40 6F 40 83 81 86 51",1]],"readBack":[["utf-8","Requisi\u00E7\u00E3o bloqueada \u2013 caf\u00E9",0],["utf-16le","\u6552\u7571\u7369\uC369\uC3A7\u6FA3\u6220\u6F6C\u7571\u6165\u6164\uE220\u9380\u6320\u6661\uA9C3",0],["utf-16be","\u5265\u7175\u6973\u69C3\uA7C3\uA36F\u2062\u6C6F\u7175\u6561\u6461\u20E2\u8093\u2063\u6166\uC3A9",0],["utf-32le","\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD",8],["utf-32be","\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD",8],["us-ascii","Requisi\uFFFD\uFFFD\uFFFD\uFFFDo bloqueada \uFFFD\uFFFD\uFFFD caf\uFFFD\uFFFD",9],["iso-8859-1","Requisi\u00C3\u00A7\u00C3\u00A3o bloqueada \u00E2\u0080\u0093 caf\u00C3\u00A9",0],["windows-1252","Requisi\u00C3\u00A7\u00C3\u00A3o bloqueada \u00E2\u20AC\u201C caf\u00C3\u00A9",0],["iso-8859-15","Requisi\u00C3\u00A7\u00C3\u00A3o bloqueada \u00E2\u0080\u0093 caf\u00C3\u00A9",0],["macintosh","Requisi\u221A\u00DF\u221A\u00A3o bloqueada \u201A\u00C4\u00EC caf\u221A\u00A9",0],["ibm437","Requisi\u251C\u00BA\u251C\u00FAo bloqueada \u0393\u00C7\u00F4 caf\u251C\u2310",0],["ibm850","Requisi\u251C\u00BA\u251C\u00FAo bloqueada \u00D4\u00C7\u00F4 caf\u251C\u00AE",0],["ibm037","\u00EA\u00C1\u00C9\u00CD\u00D1\u00CB\u00D1CxCt?\u0080\u00C2%?\u00C9\u00CD\u00C1/\u00C0/\u0080S\u00D8l\u0080\u00C4/\u00C3Cz",0],["ibm500","\u00EA\u00C1\u00C9\u00CD\u00D1\u00CB\u00D1CxCt?\u0080\u00C2%?\u00C9\u00CD\u00C1/\u00C0/\u0080S\u00D8l\u0080\u00C4/\u00C3Cz",0]]},
  },
  // the euro sign: 0x80 in windows-1252, 0xA4 in ISO-8859-15, 0xDB in Mac OS Roman, not in Latin-1, IBM 437/850 or EBCDIC 037/500.
  {
    // Name.
    id: "encode-euro-everywhere",
    // What it shows.
    note: "the euro sign: 0x80 in windows-1252, 0xA4 in ISO-8859-15, 0xDB in Mac OS Roman, not in Latin-1, IBM 437/850 or EBCDIC 037/500",
    // Input.
    input: {"mode":"encode","text":"\u20AC","charset":"utf-8"},
    // Pinned result.
    expect: {"mode":"encode","charset":"utf-8","bytes":"E2 82 AC","bom":null,"codePoints":1,"unencodable":0,"failed":false,"styles":{"python":"b'\\xe2\\x82\\xac'","base64":"4oKs","percent":"%E2%82%AC"},"everywhere":[["utf-8","E2 82 AC",0],["utf-16le","AC 20",0],["utf-16be","20 AC",0],["utf-32le","AC 20 00 00",0],["utf-32be","00 00 20 AC",0],["us-ascii","3F",1],["iso-8859-1","3F",1],["windows-1252","80",0],["iso-8859-15","A4",0],["macintosh","DB",0],["ibm437","3F",1],["ibm850","3F",1],["ibm037","6F",1],["ibm500","6F",1]],"readBack":[["utf-8","\u20AC",0],["utf-16le","\u82E2\uFFFD",1],["utf-16be","\uE282\uFFFD",1],["utf-32le","\uFFFD",1],["utf-32be","\uFFFD",1],["us-ascii","\uFFFD\uFFFD\uFFFD",3],["iso-8859-1","\u00E2\u0082\u00AC",0],["windows-1252","\u00E2\u201A\u00AC",0],["iso-8859-15","\u00E2\u0082\u00AC",0],["macintosh","\u201A\u00C7\u00A8",0],["ibm437","\u0393\u00E9\u00BC",0],["ibm850","\u00D4\u00E9\u00BC",0],["ibm037","Sb\u00D0",0],["ibm500","Sb\u00D0",0]]},
  },
  // an emoji in UTF-16LE with a byte order mark: FF FE, then a surrogate pair.
  {
    // Name.
    id: "encode-emoji-utf16-bom",
    // What it shows.
    note: "an emoji in UTF-16LE with a byte order mark: FF FE, then a surrogate pair",
    // Input.
    input: {"mode":"encode","text":"\uD83D\uDE00","charset":"utf-16le","bom":true},
    // Pinned result.
    expect: {"mode":"encode","charset":"utf-16le","bytes":"FF FE 3D D8 00 DE","bom":"FF FE","codePoints":1,"unencodable":0,"failed":false,"styles":{"python":"b'\\xff\\xfe=\\xd8\\x00\\xde'","base64":"//492ADe","percent":"%FF%FE%3D%D8%00%DE"},"everywhere":[["utf-8","F0 9F 98 80",0],["utf-16le","3D D8 00 DE",0],["utf-16be","D8 3D DE 00",0],["utf-32le","00 F6 01 00",0],["utf-32be","00 01 F6 00",0],["us-ascii","3F",1],["iso-8859-1","3F",1],["windows-1252","3F",1],["iso-8859-15","3F",1],["macintosh","3F",1],["ibm437","3F",1],["ibm850","3F",1],["ibm037","6F",1],["ibm500","6F",1]],"readBack":[["utf-8","\uFFFD\uFFFD=\uFFFD\u0000\uFFFD",4],["utf-16le","\uFEFF\uD83D\uDE00",0],["utf-16be","\uFFFE\u3DD8\u00DE",0],["utf-32le","\uFFFD\uFFFD",2],["utf-32be","\uFFFD\uFFFD",2],["us-ascii","\uFFFD\uFFFD=\uFFFD\u0000\uFFFD",4],["iso-8859-1","\u00FF\u00FE=\u00D8\u0000\u00DE",0],["windows-1252","\u00FF\u00FE=\u00D8\u0000\u00DE",0],["iso-8859-15","\u00FF\u00FE=\u00D8\u0000\u00DE",0],["macintosh","\u02C7\u02DB=\u00FF\u0000\uFB01",0],["ibm437","\u00A0\u25A0=\u256A\u0000\u2590",0],["ibm850","\u00A0\u25A0=\u00CF\u0000\u00CC",0],["ibm037","\u009F\u00DA\u0015Q\u0000\u00FA",0],["ibm500","\u009F\u00DA\u0015Q\u0000\u00FA",0]]},
  },
  // UTF-32BE: one four-byte unit per code point.
  {
    // Name.
    id: "encode-utf32be",
    // What it shows.
    note: "UTF-32BE: one four-byte unit per code point",
    // Input.
    input: {"mode":"encode","text":"A\uD83D\uDE00","charset":"utf-32be"},
    // Pinned result.
    expect: {"mode":"encode","charset":"utf-32be","bytes":"00 00 00 41 00 01 F6 00","bom":null,"codePoints":2,"unencodable":0,"failed":false,"styles":{"python":"b'\\x00\\x00\\x00A\\x00\\x01\\xf6\\x00'","base64":"AAAAQQAB9gA=","percent":"%00%00%00A%00%01%F6%00"},"everywhere":[["utf-8","41 F0 9F 98 80",0],["utf-16le","41 00 3D D8 00 DE",0],["utf-16be","00 41 D8 3D DE 00",0],["utf-32le","41 00 00 00 00 F6 01 00",0],["utf-32be","00 00 00 41 00 01 F6 00",0],["us-ascii","41 3F",1],["iso-8859-1","41 3F",1],["windows-1252","41 3F",1],["iso-8859-15","41 3F",1],["macintosh","41 3F",1],["ibm437","41 3F",1],["ibm850","41 3F",1],["ibm037","C1 6F",1],["ibm500","C1 6F",1]],"readBack":[["utf-8","\u0000\u0000\u0000A\u0000\u0001\uFFFD\u0000",1],["utf-16le","\u0000\u4100\u0100\u00F6",0],["utf-16be","\u0000A\u0001\uF600",0],["utf-32le","\uFFFD\uFFFD",2],["utf-32be","A\uD83D\uDE00",0],["us-ascii","\u0000\u0000\u0000A\u0000\u0001\uFFFD\u0000",1],["iso-8859-1","\u0000\u0000\u0000A\u0000\u0001\u00F6\u0000",0],["windows-1252","\u0000\u0000\u0000A\u0000\u0001\u00F6\u0000",0],["iso-8859-15","\u0000\u0000\u0000A\u0000\u0001\u00F6\u0000",0],["macintosh","\u0000\u0000\u0000A\u0000\u0001\u02C6\u0000",0],["ibm437","\u0000\u0000\u0000A\u0000\u0001\u00F7\u0000",0],["ibm850","\u0000\u0000\u0000A\u0000\u0001\u00F7\u0000",0],["ibm037","\u0000\u0000\u0000\u00A0\u0000\u00016\u0000",0],["ibm500","\u0000\u0000\u0000\u00A0\u0000\u00016\u0000",0]]},
  },
  // EBCDIC 037: letters at 0xC1 and up, space at 0x40.
  {
    // Name.
    id: "encode-ebcdic",
    // What it shows.
    note: "EBCDIC 037: letters at 0xC1 and up, space at 0x40",
    // Input.
    input: {"mode":"encode","text":"HELLO, World","charset":"ibm037"},
    // Pinned result.
    expect: {"mode":"encode","charset":"ibm037","bytes":"C8 C5 D3 D3 D6 6B 40 E6 96 99 93 84","bom":null,"codePoints":12,"unencodable":0,"failed":false,"styles":{"python":"b'\\xc8\\xc5\\xd3\\xd3\\xd6k@\\xe6\\x96\\x99\\x93\\x84'","base64":"yMXT09ZrQOaWmZOE","percent":"%C8%C5%D3%D3%D6k%40%E6%96%99%93%84"},"everywhere":[["utf-8","48 45 4C 4C 4F 2C 20 57 6F 72 6C 64",0],["utf-16le","48 00 45 00 4C 00 4C 00 4F 00 2C 00 20 00 57 00 6F 00 72 00 6C 00 64 00",0],["utf-16be","00 48 00 45 00 4C 00 4C 00 4F 00 2C 00 20 00 57 00 6F 00 72 00 6C 00 64",0],["utf-32le","48 00 00 00 45 00 00 00 4C 00 00 00 4C 00 00 00 4F 00 00 00 2C 00 00 00 20 00 00 00 57 00 00 00 6F 00 00 00 72 00 00 00 6C 00 00 00 64 00 00 00",0],["utf-32be","00 00 00 48 00 00 00 45 00 00 00 4C 00 00 00 4C 00 00 00 4F 00 00 00 2C 00 00 00 20 00 00 00 57 00 00 00 6F 00 00 00 72 00 00 00 6C 00 00 00 64",0],["us-ascii","48 45 4C 4C 4F 2C 20 57 6F 72 6C 64",0],["iso-8859-1","48 45 4C 4C 4F 2C 20 57 6F 72 6C 64",0],["windows-1252","48 45 4C 4C 4F 2C 20 57 6F 72 6C 64",0],["iso-8859-15","48 45 4C 4C 4F 2C 20 57 6F 72 6C 64",0],["macintosh","48 45 4C 4C 4F 2C 20 57 6F 72 6C 64",0],["ibm437","48 45 4C 4C 4F 2C 20 57 6F 72 6C 64",0],["ibm850","48 45 4C 4C 4F 2C 20 57 6F 72 6C 64",0],["ibm037","C8 C5 D3 D3 D6 6B 40 E6 96 99 93 84",0],["ibm500","C8 C5 D3 D3 D6 6B 40 E6 96 99 93 84",0]],"readBack":[["utf-8","\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDk@\u6599\uFFFD\uFFFD",7],["utf-16le","\uC5C8\uD3D3\u6BD6\uE640\u9996\u8493",0],["utf-16be","\uC8C5\uD3D3\uD66B\u40E6\u9699\u9384",0],["utf-32le","\uFFFD\uFFFD\uFFFD",3],["utf-32be","\uFFFD\uFFFD\uFFFD",3],["us-ascii","\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDk@\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD",10],["iso-8859-1","\u00C8\u00C5\u00D3\u00D3\u00D6k@\u00E6\u0096\u0099\u0093\u0084",0],["windows-1252","\u00C8\u00C5\u00D3\u00D3\u00D6k@\u00E6\u2013\u2122\u201C\u201E",0],["iso-8859-15","\u00C8\u00C5\u00D3\u00D3\u00D6k@\u00E6\u0096\u0099\u0093\u0084",0],["macintosh","\u00BB\u2248\u201D\u201D\u00F7k@\u00CA\u00F1\u00F4\u00EC\u00D1",0],["ibm437","\u255A\u253C\u2559\u2559\u2553k@\u00B5\u00FB\u00D6\u00F4\u00E4",0],["ibm850","\u255A\u253C\u00CB\u00CB\u00CDk@\u00B5\u00FB\u00D6\u00F4\u00E4",0],["ibm037","HELLO, World",0],["ibm500","HELLO, World",0]]},
  },
  // Latin-1 has no euro sign: the HTML form encoder writes &#8364; instead.
  {
    // Name.
    id: "encode-html-mode",
    // What it shows.
    note: "Latin-1 has no euro sign: the HTML form encoder writes &#8364; instead",
    // Input.
    input: {"mode":"encode","text":"caf\u00E9 \u20AC","charset":"iso-8859-1","unencodable":"html"},
    // Pinned result.
    expect: {"mode":"encode","charset":"iso-8859-1","bytes":"63 61 66 E9 20 26 23 38 33 36 34 3B","bom":null,"codePoints":6,"unencodable":1,"failed":false,"styles":{"python":"b'caf\\xe9 &#8364;'","base64":"Y2Fm6SAmIzgzNjQ7","percent":"caf%E9%20%26%238364%3B"},"everywhere":[["utf-8","63 61 66 C3 A9 20 E2 82 AC",0],["utf-16le","63 00 61 00 66 00 E9 00 20 00 AC 20",0],["utf-16be","00 63 00 61 00 66 00 E9 00 20 20 AC",0],["utf-32le","63 00 00 00 61 00 00 00 66 00 00 00 E9 00 00 00 20 00 00 00 AC 20 00 00",0],["utf-32be","00 00 00 63 00 00 00 61 00 00 00 66 00 00 00 E9 00 00 00 20 00 00 20 AC",0],["us-ascii","63 61 66 3F 20 3F",2],["iso-8859-1","63 61 66 E9 20 3F",1],["windows-1252","63 61 66 E9 20 80",0],["iso-8859-15","63 61 66 E9 20 A4",0],["macintosh","63 61 66 8E 20 DB",0],["ibm437","63 61 66 82 20 3F",1],["ibm850","63 61 66 82 20 3F",1],["ibm037","83 81 86 51 40 6F",1],["ibm500","83 81 86 51 40 6F",1]],"readBack":[["utf-8","caf\uFFFD &#8364;",1],["utf-16le","\u6163\uE966\u2620\u3823\u3633\u3B34",0],["utf-16be","\u6361\u66E9\u2026\u2338\u3336\u343B",0],["utf-32le","\uFFFD\uFFFD\uFFFD",3],["utf-32be","\uFFFD\uFFFD\uFFFD",3],["us-ascii","caf\uFFFD &#8364;",1],["iso-8859-1","caf\u00E9 &#8364;",0],["windows-1252","caf\u00E9 &#8364;",0],["iso-8859-15","caf\u00E9 &#8364;",0],["macintosh","caf\u00C8 &#8364;",0],["ibm437","caf\u0398 &#8364;",0],["ibm850","caf\u00DA &#8364;",0],["ibm037","\u00C4/\u00C3Z\u0080\u0017\u0083\u0098\u0093\u0096\u0094\u009B",0],["ibm500","\u00C4/\u00C3Z\u0080\u0017\u0083\u0098\u0093\u0096\u0094\u009B",0]]},
  },
  // strict mode: IBM 437 holds ï and ½ but not the emoji, so nothing is written.
  {
    // Name.
    id: "encode-strict-fails",
    // What it shows.
    note: "strict mode: IBM 437 holds \u00EF and \u00BD but not the emoji, so nothing is written",
    // Input.
    input: {"mode":"encode","text":"na\u00EFve \u00BD \uD83D\uDE00","charset":"ibm437","unencodable":"strict"},
    // Pinned result.
    expect: {"mode":"encode","charset":"ibm437","bytes":"","bom":null,"codePoints":9,"unencodable":1,"failed":true,"styles":{"python":"b''","base64":"","percent":""},"everywhere":[["utf-8","6E 61 C3 AF 76 65 20 C2 BD 20 F0 9F 98 80",0],["utf-16le","6E 00 61 00 EF 00 76 00 65 00 20 00 BD 00 20 00 3D D8 00 DE",0],["utf-16be","00 6E 00 61 00 EF 00 76 00 65 00 20 00 BD 00 20 D8 3D DE 00",0],["utf-32le","6E 00 00 00 61 00 00 00 EF 00 00 00 76 00 00 00 65 00 00 00 20 00 00 00 BD 00 00 00 20 00 00 00 00 F6 01 00",0],["utf-32be","00 00 00 6E 00 00 00 61 00 00 00 EF 00 00 00 76 00 00 00 65 00 00 00 20 00 00 00 BD 00 00 00 20 00 01 F6 00",0],["us-ascii","6E 61 3F 76 65 20 3F 20 3F",3],["iso-8859-1","6E 61 EF 76 65 20 BD 20 3F",1],["windows-1252","6E 61 EF 76 65 20 BD 20 3F",1],["iso-8859-15","6E 61 EF 76 65 20 3F 20 3F",2],["macintosh","6E 61 95 76 65 20 3F 20 3F",2],["ibm437","6E 61 8B 76 65 20 AB 20 3F",1],["ibm850","6E 61 8B 76 65 20 AB 20 3F",1],["ibm037","95 81 57 A5 85 40 B8 40 6F",1],["ibm500","95 81 57 A5 85 40 B8 40 6F",1]],"readBack":[["utf-8","",0],["utf-16le","",0],["utf-16be","",0],["utf-32le","",0],["utf-32be","",0],["us-ascii","",0],["iso-8859-1","",0],["windows-1252","",0],["iso-8859-15","",0],["macintosh","",0],["ibm437","",0],["ibm850","",0],["ibm037","",0],["ibm500","",0]]},
  },
  // IBM 850, the DOS code page with Ã and Õ.
  {
    // Name.
    id: "encode-cp850-portuguese",
    // What it shows.
    note: "IBM 850, the DOS code page with \u00C3 and \u00D5",
    // Input.
    input: {"mode":"encode","text":"A\u00C7\u00C3O","charset":"ibm850"},
    // Pinned result.
    expect: {"mode":"encode","charset":"ibm850","bytes":"41 80 C7 4F","bom":null,"codePoints":4,"unencodable":0,"failed":false,"styles":{"python":"b'A\\x80\\xc7O'","base64":"QYDHTw==","percent":"A%80%C7O"},"everywhere":[["utf-8","41 C3 87 C3 83 4F",0],["utf-16le","41 00 C7 00 C3 00 4F 00",0],["utf-16be","00 41 00 C7 00 C3 00 4F",0],["utf-32le","41 00 00 00 C7 00 00 00 C3 00 00 00 4F 00 00 00",0],["utf-32be","00 00 00 41 00 00 00 C7 00 00 00 C3 00 00 00 4F",0],["us-ascii","41 3F 3F 4F",2],["iso-8859-1","41 C7 C3 4F",0],["windows-1252","41 C7 C3 4F",0],["iso-8859-15","41 C7 C3 4F",0],["macintosh","41 82 CC 4F",0],["ibm437","41 80 3F 4F",1],["ibm850","41 80 C7 4F",0],["ibm037","C1 68 66 D6",0],["ibm500","C1 68 66 D6",0]],"readBack":[["utf-8","A\uFFFD\uFFFDO",2],["utf-16le","\u8041\u4FC7",0],["utf-16be","\u4180\uC74F",0],["utf-32le","\uFFFD",1],["utf-32be","\uFFFD",1],["us-ascii","A\uFFFD\uFFFDO",2],["iso-8859-1","A\u0080\u00C7O",0],["windows-1252","A\u20AC\u00C7O",0],["iso-8859-15","A\u0080\u00C7O",0],["macintosh","A\u00C4\u00ABO",0],["ibm437","A\u00C7\u255FO",0],["ibm850","A\u00C7\u00C3O",0],["ibm037","\u00A0\u00D8G|",0],["ibm500","\u00A0\u00D8G!",0]]},
  },
  // Mac OS Roman holds Ω, ≤ and ∞.
  {
    // Name.
    id: "encode-mac-roman",
    // What it shows.
    note: "Mac OS Roman holds \u03A9, \u2264 and \u221E",
    // Input.
    input: {"mode":"encode","text":"\u03A9 \u2264 \u221E","charset":"macintosh"},
    // Pinned result.
    expect: {"mode":"encode","charset":"macintosh","bytes":"BD 20 B2 20 B0","bom":null,"codePoints":5,"unencodable":0,"failed":false,"styles":{"python":"b'\\xbd \\xb2 \\xb0'","base64":"vSCyILA=","percent":"%BD%20%B2%20%B0"},"everywhere":[["utf-8","CE A9 20 E2 89 A4 20 E2 88 9E",0],["utf-16le","A9 03 20 00 64 22 20 00 1E 22",0],["utf-16be","03 A9 00 20 22 64 00 20 22 1E",0],["utf-32le","A9 03 00 00 20 00 00 00 64 22 00 00 20 00 00 00 1E 22 00 00",0],["utf-32be","00 00 03 A9 00 00 00 20 00 00 22 64 00 00 00 20 00 00 22 1E",0],["us-ascii","3F 20 3F 20 3F",3],["iso-8859-1","3F 20 3F 20 3F",3],["windows-1252","3F 20 3F 20 3F",3],["iso-8859-15","3F 20 3F 20 3F",3],["macintosh","BD 20 B2 20 B0",0],["ibm437","EA 20 F3 20 EC",0],["ibm850","3F 20 3F 20 3F",3],["ibm037","6F 40 6F 40 6F",3],["ibm500","6F 40 6F 40 6F",3]],"readBack":[["utf-8","\uFFFD \uFFFD \uFFFD",3],["utf-16le","\u20BD\u20B2\uFFFD",1],["utf-16be","\uBD20\uB220\uFFFD",1],["utf-32le","\uFFFD\uFFFD",2],["utf-32be","\uFFFD\uFFFD",2],["us-ascii","\uFFFD \uFFFD \uFFFD",3],["iso-8859-1","\u00BD \u00B2 \u00B0",0],["windows-1252","\u00BD \u00B2 \u00B0",0],["iso-8859-15","\u0153 \u00B2 \u00B0",0],["macintosh","\u03A9 \u2264 \u221E",0],["ibm437","\u255C \u2593 \u2591",0],["ibm850","\u00A2 \u2593 \u2591",0],["ibm037","\u00A8\u0080\u00A5\u0080^",0],["ibm500","\u00A8\u0080\u00A5\u0080\u00A2",0]]},
  },
  // the output of hexdump -C, read as UTF-8 by the guess.
  {
    // Name.
    id: "decode-hexdump-auto",
    // What it shows.
    note: "the output of hexdump -C, read as UTF-8 by the guess",
    // Input.
    input: {"mode":"decode","bytes":"00000000  52 65 71 75 69 73 69 c3  a7 c3 a3 6f 20 62 6c 6f  |Requisi....o blo|\n00000010  71 75 65 61 64 61 20 e2  80 93 20 63 61 66 c3 a9  |queada ... caf..|\n00000020  0a                                                |.|\n00000021\n","charset":"auto"},
    // Pinned result.
    expect: {"mode":"decode","parsed":{"format":"hex","dump":"hexdump","error":null,"bytes":"52 65 71 75 69 73 69 C3 A7 C3 A3 6F 20 62 6C 6F 71 75 65 61 64 61 20 E2 80 93 20 63 61 66 C3 A9 0A"},"result":{"requested":"auto","charset":"utf-8","guess":{"charset":"utf-8","reason":"utf8-valid"},"bom":null,"bomOverride":false,"text":"Requisi\u00E7\u00E3o bloqueada \u2013 caf\u00E9\n","errors":[]},"everywhere":[["utf-8","Requisi\u00E7\u00E3o bloqueada \u2013 caf\u00E9\n",0],["utf-16le","\u6552\u7571\u7369\uC369\uC3A7\u6FA3\u6220\u6F6C\u7571\u6165\u6164\uE220\u9380\u6320\u6661\uA9C3\uFFFD",1],["utf-16be","\u5265\u7175\u6973\u69C3\uA7C3\uA36F\u2062\u6C6F\u7175\u6561\u6461\u20E2\u8093\u2063\u6166\uC3A9\uFFFD",1],["utf-32le","\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD",9],["utf-32be","\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD",9],["us-ascii","Requisi\uFFFD\uFFFD\uFFFD\uFFFDo bloqueada \uFFFD\uFFFD\uFFFD caf\uFFFD\uFFFD\n",9],["iso-8859-1","Requisi\u00C3\u00A7\u00C3\u00A3o bloqueada \u00E2\u0080\u0093 caf\u00C3\u00A9\n",0],["windows-1252","Requisi\u00C3\u00A7\u00C3\u00A3o bloqueada \u00E2\u20AC\u201C caf\u00C3\u00A9\n",0],["iso-8859-15","Requisi\u00C3\u00A7\u00C3\u00A3o bloqueada \u00E2\u0080\u0093 caf\u00C3\u00A9\n",0],["macintosh","Requisi\u221A\u00DF\u221A\u00A3o bloqueada \u201A\u00C4\u00EC caf\u221A\u00A9\n",0],["ibm437","Requisi\u251C\u00BA\u251C\u00FAo bloqueada \u0393\u00C7\u00F4 caf\u251C\u2310\n",0],["ibm850","Requisi\u251C\u00BA\u251C\u00FAo bloqueada \u00D4\u00C7\u00F4 caf\u251C\u00AE\n",0],["ibm037","\u00EA\u00C1\u00C9\u00CD\u00D1\u00CB\u00D1CxCt?\u0080\u00C2%?\u00C9\u00CD\u00C1/\u00C0/\u0080S\u00D8l\u0080\u00C4/\u00C3Cz\u008E",0],["ibm500","\u00EA\u00C1\u00C9\u00CD\u00D1\u00CB\u00D1CxCt?\u0080\u00C2%?\u00C9\u00CD\u00C1/\u00C0/\u0080S\u00D8l\u0080\u00C4/\u00C3Cz\u008E",0]]},
  },
  // Unicode Table 3-8: every byte of a non-shortest form is replaced.
  {
    // Name.
    id: "decode-unicode-table-3-8",
    // What it shows.
    note: "Unicode Table 3-8: every byte of a non-shortest form is replaced",
    // Input.
    input: {"mode":"decode","bytes":"C0 AF E0 80 BF F0 81 82 41","charset":"utf-8"},
    // Pinned result.
    expect: {"mode":"decode","parsed":{"format":"hex","dump":null,"error":null,"bytes":"C0 AF E0 80 BF F0 81 82 41"},"result":{"requested":"utf-8","charset":"utf-8","guess":null,"bom":null,"bomOverride":false,"text":"\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDA","errors":[[0,1,"overlong-lead"],[1,1,"continuation"],[2,1,"overlong"],[3,1,"continuation"],[4,1,"continuation"],[5,1,"overlong"],[6,1,"continuation"],[7,1,"continuation"]]},"everywhere":[["utf-8","\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDA",8],["utf-16le","\uAFC0\u80E0\uF0BF\u8281\uFFFD",1],["utf-16be","\uC0AF\uE080\uBFF0\u8182\uFFFD",1],["utf-32le","\uFFFD\uFFFD\uFFFD",3],["utf-32be","\uFFFD\uFFFD\uFFFD",3],["us-ascii","\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDA",8],["iso-8859-1","\u00C0\u00AF\u00E0\u0080\u00BF\u00F0\u0081\u0082A",0],["windows-1252","\u00C0\u00AF\u00E0\u20AC\u00BF\u00F0\u0081\u201AA",0],["iso-8859-15","\u00C0\u00AF\u00E0\u0080\u00BF\u00F0\u0081\u0082A",0],["macintosh","\u00BF\u00D8\u2021\u00C4\u00F8\uF8FF\u00C5\u00C7A",0],["ibm437","\u2514\u00BB\u03B1\u00C7\u2510\u2261\u00FC\u00E9A",0],["ibm850","\u2514\u00BB\u00D3\u00C7\u2510\u00AD\u00FC\u00E9A",0],["ibm037","{\u00AE\\\u00D8\u00D70ab\u00A0",0],["ibm500","{\u00AE\\\u00D8\u00D70ab\u00A0",0]]},
  },
  // Unicode Table 3-9: surrogates in UTF-8.
  {
    // Name.
    id: "decode-unicode-table-3-9",
    // What it shows.
    note: "Unicode Table 3-9: surrogates in UTF-8",
    // Input.
    input: {"mode":"decode","bytes":"ED A0 80 ED BF BF ED AF 41","charset":"utf-8"},
    // Pinned result.
    expect: {"mode":"decode","parsed":{"format":"hex","dump":null,"error":null,"bytes":"ED A0 80 ED BF BF ED AF 41"},"result":{"requested":"utf-8","charset":"utf-8","guess":null,"bom":null,"bomOverride":false,"text":"\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDA","errors":[[0,1,"surrogate"],[1,1,"continuation"],[2,1,"continuation"],[3,1,"surrogate"],[4,1,"continuation"],[5,1,"continuation"],[6,1,"surrogate"],[7,1,"continuation"]]},"everywhere":[["utf-8","\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDA",8],["utf-16le","\uA0ED\uED80\uBFBF\uAFED\uFFFD",1],["utf-16be","\uEDA0\u80ED\uBFBF\uEDAF\uFFFD",1],["utf-32le","\uFFFD\uFFFD\uFFFD",3],["utf-32be","\uFFFD\uFFFD\uFFFD",3],["us-ascii","\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDA",8],["iso-8859-1","\u00ED\u00A0\u0080\u00ED\u00BF\u00BF\u00ED\u00AFA",0],["windows-1252","\u00ED\u00A0\u20AC\u00ED\u00BF\u00BF\u00ED\u00AFA",0],["iso-8859-15","\u00ED\u00A0\u0080\u00ED\u00BF\u00BF\u00ED\u00AFA",0],["macintosh","\u00CC\u2020\u00C4\u00CC\u00F8\u00F8\u00CC\u00D8A",0],["ibm437","\u03C6\u00E1\u00C7\u03C6\u2510\u2510\u03C6\u00BBA",0],["ibm850","\u00DD\u00E1\u00C7\u00DD\u2510\u2510\u00DD\u00BBA",0],["ibm037","\u00D2\u00B5\u00D8\u00D2\u00D7\u00D7\u00D2\u00AE\u00A0",0],["ibm500","\u00D2\u00B5\u00D8\u00D2\u00D7\u00D7\u00D2\u00AE\u00A0",0]]},
  },
  // Unicode Table 3-10: beyond U+10FFFF and other bytes.
  {
    // Name.
    id: "decode-unicode-table-3-10",
    // What it shows.
    note: "Unicode Table 3-10: beyond U+10FFFF and other bytes",
    // Input.
    input: {"mode":"decode","bytes":"F4 91 92 93 FF 41 80 BF 42","charset":"utf-8"},
    // Pinned result.
    expect: {"mode":"decode","parsed":{"format":"hex","dump":null,"error":null,"bytes":"F4 91 92 93 FF 41 80 BF 42"},"result":{"requested":"utf-8","charset":"utf-8","guess":null,"bom":null,"bomOverride":false,"text":"\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDA\uFFFD\uFFFDB","errors":[[0,1,"too-large"],[1,1,"continuation"],[2,1,"continuation"],[3,1,"continuation"],[4,1,"invalid-lead"],[6,1,"continuation"],[7,1,"continuation"]]},"everywhere":[["utf-8","\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDA\uFFFD\uFFFDB",7],["utf-16le","\u91F4\u9392\u41FF\uBF80\uFFFD",1],["utf-16be","\uF491\u9293\uFF41\u80BF\uFFFD",1],["utf-32le","\uFFFD\uFFFD\uFFFD",3],["utf-32be","\uFFFD\uFFFD\uFFFD",3],["us-ascii","\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDA\uFFFD\uFFFDB",7],["iso-8859-1","\u00F4\u0091\u0092\u0093\u00FFA\u0080\u00BFB",0],["windows-1252","\u00F4\u2018\u2019\u201C\u00FFA\u20AC\u00BFB",0],["iso-8859-15","\u00F4\u0091\u0092\u0093\u00FFA\u0080\u00BFB",0],["macintosh","\u00D9\u00EB\u00ED\u00EC\u02C7A\u00C4\u00F8B",0],["ibm437","\u2320\u00E6\u00C6\u00F4\u00A0A\u00C7\u2510B",0],["ibm850","\u00B6\u00E6\u00C6\u00F4\u00A0A\u00C7\u2510B",0],["ibm037","4jkl\u009F\u00A0\u00D8\u00D7\u00E2",0],["ibm500","4jkl\u009F\u00A0\u00D8\u00D7\u00E2",0]]},
  },
  // Unicode Table 3-11: truncated sequences, one replacement each.
  {
    // Name.
    id: "decode-unicode-table-3-11",
    // What it shows.
    note: "Unicode Table 3-11: truncated sequences, one replacement each",
    // Input.
    input: {"mode":"decode","bytes":"E1 80 E2 F0 91 92 F1 BF 41","charset":"utf-8"},
    // Pinned result.
    expect: {"mode":"decode","parsed":{"format":"hex","dump":null,"error":null,"bytes":"E1 80 E2 F0 91 92 F1 BF 41"},"result":{"requested":"utf-8","charset":"utf-8","guess":null,"bom":null,"bomOverride":false,"text":"\uFFFD\uFFFD\uFFFD\uFFFDA","errors":[[0,2,"truncated"],[2,1,"truncated"],[3,3,"truncated"],[6,2,"truncated"]]},"everywhere":[["utf-8","\uFFFD\uFFFD\uFFFD\uFFFDA",4],["utf-16le","\u80E1\uF0E2\u9291\uBFF1\uFFFD",1],["utf-16be","\uE180\uE2F0\u9192\uF1BF\uFFFD",1],["utf-32le","\uFFFD\uFFFD\uFFFD",3],["utf-32be","\uFFFD\uFFFD\uFFFD",3],["us-ascii","\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDA",8],["iso-8859-1","\u00E1\u0080\u00E2\u00F0\u0091\u0092\u00F1\u00BFA",0],["windows-1252","\u00E1\u20AC\u00E2\u00F0\u2018\u2019\u00F1\u00BFA",0],["iso-8859-15","\u00E1\u0080\u00E2\u00F0\u0091\u0092\u00F1\u00BFA",0],["macintosh","\u00B7\u00C4\u201A\uF8FF\u00EB\u00ED\u00D2\u00F8A",0],["ibm437","\u00DF\u00C7\u0393\u2261\u00E6\u00C6\u00B1\u2510A",0],["ibm850","\u00DF\u00C7\u00D4\u00AD\u00E6\u00C6\u00B1\u2510A",0],["ibm037","\u00F7\u00D8S0jk1\u00D7\u00A0",0],["ibm500","\u00F7\u00D8S0jk1\u00D7\u00A0",0]]},
  },
  // a UTF-16LE byte order mark overrides UTF-8, as in a browser.
  {
    // Name.
    id: "decode-bom-overrides",
    // What it shows.
    note: "a UTF-16LE byte order mark overrides UTF-8, as in a browser",
    // Input.
    input: {"mode":"decode","bytes":"FF FE 63 00 61 00 66 00 E9 00","charset":"utf-8"},
    // Pinned result.
    expect: {"mode":"decode","parsed":{"format":"hex","dump":null,"error":null,"bytes":"FF FE 63 00 61 00 66 00 E9 00"},"result":{"requested":"utf-8","charset":"utf-16le","guess":null,"bom":{"charset":"utf-16le","length":2},"bomOverride":true,"text":"caf\u00E9","errors":[]},"everywhere":[["utf-8","\uFFFD\uFFFDc\u0000a\u0000f\u0000\uFFFD\u0000",3],["utf-16le","\uFEFFcaf\u00E9",0],["utf-16be","\uFFFE\u6300\u6100\u6600\uE900",0],["utf-32le","\uFFFD\uFFFD\uFFFD",3],["utf-32be","\uFFFD\uFFFD\uFFFD",3],["us-ascii","\uFFFD\uFFFDc\u0000a\u0000f\u0000\uFFFD\u0000",3],["iso-8859-1","\u00FF\u00FEc\u0000a\u0000f\u0000\u00E9\u0000",0],["windows-1252","\u00FF\u00FEc\u0000a\u0000f\u0000\u00E9\u0000",0],["iso-8859-15","\u00FF\u00FEc\u0000a\u0000f\u0000\u00E9\u0000",0],["macintosh","\u02C7\u02DBc\u0000a\u0000f\u0000\u00C8\u0000",0],["ibm437","\u00A0\u25A0c\u0000a\u0000f\u0000\u0398\u0000",0],["ibm850","\u00A0\u25A0c\u0000a\u0000f\u0000\u00DA\u0000",0],["ibm037","\u009F\u00DA\u00C4\u0000/\u0000\u00C3\u0000Z\u0000",0],["ibm500","\u009F\u00DA\u00C4\u0000/\u0000\u00C3\u0000Z\u0000",0]]},
  },
  // UTF-16LE: a leading surrogate followed by A.
  {
    // Name.
    id: "decode-utf16-unpaired",
    // What it shows.
    note: "UTF-16LE: a leading surrogate followed by A",
    // Input.
    input: {"mode":"decode","bytes":"3D D8 41 00","charset":"utf-16le"},
    // Pinned result.
    expect: {"mode":"decode","parsed":{"format":"hex","dump":null,"error":null,"bytes":"3D D8 41 00"},"result":{"requested":"utf-16le","charset":"utf-16le","guess":null,"bom":null,"bomOverride":false,"text":"\uFFFDA","errors":[[0,2,"unpaired-lead"]]},"everywhere":[["utf-8","=\uFFFDA\u0000",1],["utf-16le","\uFFFDA",1],["utf-16be","\u3DD8\u4100",0],["utf-32le","\uFFFD",1],["utf-32be","\uFFFD",1],["us-ascii","=\uFFFDA\u0000",1],["iso-8859-1","=\u00D8A\u0000",0],["windows-1252","=\u00D8A\u0000",0],["iso-8859-15","=\u00D8A\u0000",0],["macintosh","=\u00FFA\u0000",0],["ibm437","=\u256AA\u0000",0],["ibm850","=\u00CFA\u0000",0],["ibm037","\u0015Q\u00A0\u0000",0],["ibm500","\u0015Q\u00A0\u0000",0]]},
  },
  // the output of xxd, groups of two bytes and an ASCII column.
  {
    // Name.
    id: "decode-xxd",
    // What it shows.
    note: "the output of xxd, groups of two bytes and an ASCII column",
    // Input.
    input: {"mode":"decode","bytes":"00000000: 6361 66c3 a920 e282 ac0a                 caf.. ....\n","charset":"utf-8"},
    // Pinned result.
    expect: {"mode":"decode","parsed":{"format":"hex","dump":"xxd","error":null,"bytes":"63 61 66 C3 A9 20 E2 82 AC 0A"},"result":{"requested":"utf-8","charset":"utf-8","guess":null,"bom":null,"bomOverride":false,"text":"caf\u00E9 \u20AC\n","errors":[]},"everywhere":[["utf-8","caf\u00E9 \u20AC\n",0],["utf-16le","\u6163\uC366\u20A9\u82E2\u0AAC",0],["utf-16be","\u6361\u66C3\uA920\uE282\uAC0A",0],["utf-32le","\uFFFD\uFFFD\uFFFD",3],["utf-32be","\uFFFD\uFFFD\uFFFD",3],["us-ascii","caf\uFFFD\uFFFD \uFFFD\uFFFD\uFFFD\n",5],["iso-8859-1","caf\u00C3\u00A9 \u00E2\u0082\u00AC\n",0],["windows-1252","caf\u00C3\u00A9 \u00E2\u201A\u00AC\n",0],["iso-8859-15","caf\u00C3\u00A9 \u00E2\u0082\u00AC\n",0],["macintosh","caf\u221A\u00A9 \u201A\u00C7\u00A8\n",0],["ibm437","caf\u251C\u2310 \u0393\u00E9\u00BC\n",0],["ibm850","caf\u251C\u00AE \u00D4\u00E9\u00BC\n",0],["ibm037","\u00C4/\u00C3Cz\u0080Sb\u00D0\u008E",0],["ibm500","\u00C4/\u00C3Cz\u0080Sb\u00D0\u008E",0]]},
  },
  // git's octal quoting of a file name.
  {
    // Name.
    id: "decode-git-octal",
    // What it shows.
    note: "git's octal quoting of a file name",
    // Input.
    input: {"mode":"decode","bytes":"caf\\303\\251.txt","charset":"auto"},
    // Pinned result.
    expect: {"mode":"decode","parsed":{"format":"escaped","dump":null,"error":null,"bytes":"63 61 66 C3 A9 2E 74 78 74"},"result":{"requested":"auto","charset":"utf-8","guess":{"charset":"utf-8","reason":"utf8-valid"},"bom":null,"bomOverride":false,"text":"caf\u00E9.txt","errors":[]},"everywhere":[["utf-8","caf\u00E9.txt",0],["utf-16le","\u6163\uC366\u2EA9\u7874\uFFFD",1],["utf-16be","\u6361\u66C3\uA92E\u7478\uFFFD",1],["utf-32le","\uFFFD\uFFFD\uFFFD",3],["utf-32be","\uFFFD\uFFFD\uFFFD",3],["us-ascii","caf\uFFFD\uFFFD.txt",2],["iso-8859-1","caf\u00C3\u00A9.txt",0],["windows-1252","caf\u00C3\u00A9.txt",0],["iso-8859-15","caf\u00C3\u00A9.txt",0],["macintosh","caf\u221A\u00A9.txt",0],["ibm437","caf\u251C\u2310.txt",0],["ibm850","caf\u251C\u00AE.txt",0],["ibm037","\u00C4/\u00C3Cz\u0006\u00C8\u00CC\u00C8",0],["ibm500","\u00C4/\u00C3Cz\u0006\u00C8\u00CC\u00C8",0]]},
  },
  // a percent-encoded URL path.
  {
    // Name.
    id: "decode-percent",
    // What it shows.
    note: "a percent-encoded URL path",
    // Input.
    input: {"mode":"decode","bytes":"caf%C3%A9%20%E2%82%AC","charset":"auto"},
    // Pinned result.
    expect: {"mode":"decode","parsed":{"format":"percent","dump":null,"error":null,"bytes":"63 61 66 C3 A9 20 E2 82 AC"},"result":{"requested":"auto","charset":"utf-8","guess":{"charset":"utf-8","reason":"utf8-valid"},"bom":null,"bomOverride":false,"text":"caf\u00E9 \u20AC","errors":[]},"everywhere":[["utf-8","caf\u00E9 \u20AC",0],["utf-16le","\u6163\uC366\u20A9\u82E2\uFFFD",1],["utf-16be","\u6361\u66C3\uA920\uE282\uFFFD",1],["utf-32le","\uFFFD\uFFFD\uFFFD",3],["utf-32be","\uFFFD\uFFFD\uFFFD",3],["us-ascii","caf\uFFFD\uFFFD \uFFFD\uFFFD\uFFFD",5],["iso-8859-1","caf\u00C3\u00A9 \u00E2\u0082\u00AC",0],["windows-1252","caf\u00C3\u00A9 \u00E2\u201A\u00AC",0],["iso-8859-15","caf\u00C3\u00A9 \u00E2\u0082\u00AC",0],["macintosh","caf\u221A\u00A9 \u201A\u00C7\u00A8",0],["ibm437","caf\u251C\u2310 \u0393\u00E9\u00BC",0],["ibm850","caf\u251C\u00AE \u00D4\u00E9\u00BC",0],["ibm037","\u00C4/\u00C3Cz\u0080Sb\u00D0",0],["ibm500","\u00C4/\u00C3Cz\u0080Sb\u00D0",0]]},
  },
  // Base64.
  {
    // Name.
    id: "decode-base64",
    // What it shows.
    note: "Base64",
    // Input.
    input: {"mode":"decode","bytes":"Y2Fmw6kg4oKs","charset":"auto"},
    // Pinned result.
    expect: {"mode":"decode","parsed":{"format":"base64","dump":null,"error":null,"bytes":"63 61 66 C3 A9 20 E2 82 AC"},"result":{"requested":"auto","charset":"utf-8","guess":{"charset":"utf-8","reason":"utf8-valid"},"bom":null,"bomOverride":false,"text":"caf\u00E9 \u20AC","errors":[]},"everywhere":[["utf-8","caf\u00E9 \u20AC",0],["utf-16le","\u6163\uC366\u20A9\u82E2\uFFFD",1],["utf-16be","\u6361\u66C3\uA920\uE282\uFFFD",1],["utf-32le","\uFFFD\uFFFD\uFFFD",3],["utf-32be","\uFFFD\uFFFD\uFFFD",3],["us-ascii","caf\uFFFD\uFFFD \uFFFD\uFFFD\uFFFD",5],["iso-8859-1","caf\u00C3\u00A9 \u00E2\u0082\u00AC",0],["windows-1252","caf\u00C3\u00A9 \u00E2\u201A\u00AC",0],["iso-8859-15","caf\u00C3\u00A9 \u00E2\u0082\u00AC",0],["macintosh","caf\u221A\u00A9 \u201A\u00C7\u00A8",0],["ibm437","caf\u251C\u2310 \u0393\u00E9\u00BC",0],["ibm850","caf\u251C\u00AE \u00D4\u00E9\u00BC",0],["ibm037","\u00C4/\u00C3Cz\u0080Sb\u00D0",0],["ibm500","\u00C4/\u00C3Cz\u0080Sb\u00D0",0]]},
  },
  // windows-1252: 0x80 is the euro sign, 0x81 and 0x9D are C1 controls, 0x93 and 0x94 curly quotes.
  {
    // Name.
    id: "decode-windows-1252",
    // What it shows.
    note: "windows-1252: 0x80 is the euro sign, 0x81 and 0x9D are C1 controls, 0x93 and 0x94 curly quotes",
    // Input.
    input: {"mode":"decode","bytes":"80 81 9D 93 48 69 94","charset":"windows-1252"},
    // Pinned result.
    expect: {"mode":"decode","parsed":{"format":"hex","dump":null,"error":null,"bytes":"80 81 9D 93 48 69 94"},"result":{"requested":"windows-1252","charset":"windows-1252","guess":null,"bom":null,"bomOverride":false,"text":"\u20AC\u0081\u009D\u201CHi\u201D","errors":[]},"everywhere":[["utf-8","\uFFFD\uFFFD\uFFFD\uFFFDHi\uFFFD",5],["utf-16le","\u8180\u939D\u6948\uFFFD",1],["utf-16be","\u8081\u9D93\u4869\uFFFD",1],["utf-32le","\uFFFD\uFFFD",2],["utf-32be","\uFFFD\uFFFD",2],["us-ascii","\uFFFD\uFFFD\uFFFD\uFFFDHi\uFFFD",5],["iso-8859-1","\u0080\u0081\u009D\u0093Hi\u0094",0],["windows-1252","\u20AC\u0081\u009D\u201CHi\u201D",0],["iso-8859-15","\u0080\u0081\u009D\u0093Hi\u0094",0],["macintosh","\u00C4\u00C5\u00F9\u00ECHi\u00EE",0],["ibm437","\u00C7\u00FC\u00A5\u00F4Hi\u00F6",0],["ibm850","\u00C7\u00FC\u00D8\u00F4Hi\u00F6",0],["ibm037","\u00D8a\u00B8l\u00E7\u00D1m",0],["ibm500","\u00D8a\u00B8l\u00E7\u00D1m",0]]},
  },
  // the same bytes in ISO-8859-1: all C1 controls.
  {
    // Name.
    id: "decode-latin1",
    // What it shows.
    note: "the same bytes in ISO-8859-1: all C1 controls",
    // Input.
    input: {"mode":"decode","bytes":"80 81 9D 93 48 69 94","charset":"iso-8859-1"},
    // Pinned result.
    expect: {"mode":"decode","parsed":{"format":"hex","dump":null,"error":null,"bytes":"80 81 9D 93 48 69 94"},"result":{"requested":"iso-8859-1","charset":"iso-8859-1","guess":null,"bom":null,"bomOverride":false,"text":"\u0080\u0081\u009D\u0093Hi\u0094","errors":[]},"everywhere":[["utf-8","\uFFFD\uFFFD\uFFFD\uFFFDHi\uFFFD",5],["utf-16le","\u8180\u939D\u6948\uFFFD",1],["utf-16be","\u8081\u9D93\u4869\uFFFD",1],["utf-32le","\uFFFD\uFFFD",2],["utf-32be","\uFFFD\uFFFD",2],["us-ascii","\uFFFD\uFFFD\uFFFD\uFFFDHi\uFFFD",5],["iso-8859-1","\u0080\u0081\u009D\u0093Hi\u0094",0],["windows-1252","\u20AC\u0081\u009D\u201CHi\u201D",0],["iso-8859-15","\u0080\u0081\u009D\u0093Hi\u0094",0],["macintosh","\u00C4\u00C5\u00F9\u00ECHi\u00EE",0],["ibm437","\u00C7\u00FC\u00A5\u00F4Hi\u00F6",0],["ibm850","\u00C7\u00FC\u00D8\u00F4Hi\u00F6",0],["ibm037","\u00D8a\u00B8l\u00E7\u00D1m",0],["ibm500","\u00D8a\u00B8l\u00E7\u00D1m",0]]},
  },
  // EBCDIC bytes: the guess says IBM 037.
  {
    // Name.
    id: "decode-ebcdic-auto",
    // What it shows.
    note: "EBCDIC bytes: the guess says IBM 037",
    // Input.
    input: {"mode":"decode","bytes":"C8 C5 D3 D3 D6 6B 40 E6 96 99 93 84","charset":"auto"},
    // Pinned result.
    expect: {"mode":"decode","parsed":{"format":"hex","dump":null,"error":null,"bytes":"C8 C5 D3 D3 D6 6B 40 E6 96 99 93 84"},"result":{"requested":"auto","charset":"ibm037","guess":{"charset":"ibm037","reason":"ebcdic"},"bom":null,"bomOverride":false,"text":"HELLO, World","errors":[]},"everywhere":[["utf-8","\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDk@\u6599\uFFFD\uFFFD",7],["utf-16le","\uC5C8\uD3D3\u6BD6\uE640\u9996\u8493",0],["utf-16be","\uC8C5\uD3D3\uD66B\u40E6\u9699\u9384",0],["utf-32le","\uFFFD\uFFFD\uFFFD",3],["utf-32be","\uFFFD\uFFFD\uFFFD",3],["us-ascii","\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDk@\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD",10],["iso-8859-1","\u00C8\u00C5\u00D3\u00D3\u00D6k@\u00E6\u0096\u0099\u0093\u0084",0],["windows-1252","\u00C8\u00C5\u00D3\u00D3\u00D6k@\u00E6\u2013\u2122\u201C\u201E",0],["iso-8859-15","\u00C8\u00C5\u00D3\u00D3\u00D6k@\u00E6\u0096\u0099\u0093\u0084",0],["macintosh","\u00BB\u2248\u201D\u201D\u00F7k@\u00CA\u00F1\u00F4\u00EC\u00D1",0],["ibm437","\u255A\u253C\u2559\u2559\u2553k@\u00B5\u00FB\u00D6\u00F4\u00E4",0],["ibm850","\u255A\u253C\u00CB\u00CB\u00CDk@\u00B5\u00FB\u00D6\u00F4\u00E4",0],["ibm037","HELLO, World",0],["ibm500","HELLO, World",0]]},
  },
  // ASCII text in UTF-16LE: the guess reads the zero bytes.
  {
    // Name.
    id: "decode-utf16-auto",
    // What it shows.
    note: "ASCII text in UTF-16LE: the guess reads the zero bytes",
    // Input.
    input: {"mode":"decode","bytes":"48 00 69 00 21 00","charset":"auto"},
    // Pinned result.
    expect: {"mode":"decode","parsed":{"format":"hex","dump":null,"error":null,"bytes":"48 00 69 00 21 00"},"result":{"requested":"auto","charset":"utf-16le","guess":{"charset":"utf-16le","reason":"zeros"},"bom":null,"bomOverride":false,"text":"Hi!","errors":[]},"everywhere":[["utf-8","H\u0000i\u0000!\u0000",0],["utf-16le","Hi!",0],["utf-16be","\u4800\u6900\u2100",0],["utf-32le","\uFFFD\uFFFD",2],["utf-32be","\uFFFD\uFFFD",2],["us-ascii","H\u0000i\u0000!\u0000",0],["iso-8859-1","H\u0000i\u0000!\u0000",0],["windows-1252","H\u0000i\u0000!\u0000",0],["iso-8859-15","H\u0000i\u0000!\u0000",0],["macintosh","H\u0000i\u0000!\u0000",0],["ibm437","H\u0000i\u0000!\u0000",0],["ibm850","H\u0000i\u0000!\u0000",0],["ibm037","\u00E7\u0000\u00D1\u0000\u0081\u0000",0],["ibm500","\u00E7\u0000\u00D1\u0000\u0081\u0000",0]]},
  },
  // an odd number of hex digits.
  {
    // Name.
    id: "decode-odd-hex",
    // What it shows.
    note: "an odd number of hex digits",
    // Input.
    input: {"mode":"decode","bytes":"C3 A","charset":"utf-8"},
    // Pinned result.
    expect: {"mode":"decode","parsed":{"format":"hex","dump":null,"error":{"kind":"odd-hex","at":3},"bytes":""},"result":null,"everywhere":[]},
  },
  // UTF-8 read as windows-1252, as in a page whose charset label was not recognised.
  {
    // Name.
    id: "repair-utf8-as-1252",
    // What it shows.
    note: "UTF-8 read as windows-1252, as in a page whose charset label was not recognised",
    // Input.
    input: {"mode":"repair","text":"Requisi\u00C3\u00A7\u00C3\u00A3o bloqueada \u00E2\u20AC\u201C caf\u00C3\u00A9"},
    // Pinned result.
    expect: {"mode":"repair","inputScore":28,"candidates":[{"text":"Requisi\u00E7\u00E3o bloqueada \u2013 caf\u00E9","steps":["windows-1252>utf-8"],"evidence":"utf8","lossy":false,"lost":0}]},
  },
  // a right single quotation mark misread twice.
  {
    // Name.
    id: "repair-twice",
    // What it shows.
    note: "a right single quotation mark misread twice",
    // Input.
    input: {"mode":"repair","text":"\u00C3\u00A2\u00E2\u201A\u00AC\u00E2\u201E\u00A2"},
    // Pinned result.
    expect: {"mode":"repair","inputScore":23,"candidates":[{"text":"\u2019","steps":["windows-1252>utf-8","windows-1252>utf-8"],"evidence":"utf8","lossy":false,"lost":0},{"text":"\u00E2\u20AC\u2122","steps":["windows-1252>utf-8"],"evidence":"utf8","lossy":false,"lost":0}]},
  },
  // é misread three times.
  {
    // Name.
    id: "repair-three-times",
    // What it shows.
    note: "\u00E9 misread three times",
    // Input.
    input: {"mode":"repair","text":"\u00C3\u0192\u00C6\u2019\u00C3\u201A\u00C2\u00A9"},
    // Pinned result.
    expect: {"mode":"repair","inputScore":21,"candidates":[{"text":"\u00E9","steps":["windows-1252>utf-8","windows-1252>utf-8","windows-1252>utf-8"],"evidence":"utf8","lossy":false,"lost":0},{"text":"\u01F8","steps":["windows-1252>utf-8","windows-1252>utf-8","ibm850>utf-8"],"evidence":"utf8","lossy":false,"lost":0},{"text":"\u0329","steps":["windows-1252>utf-8","windows-1252>utf-8","macintosh>utf-8"],"evidence":"utf8","lossy":false,"lost":0},{"text":"\u00C3\u00A9","steps":["windows-1252>utf-8","windows-1252>utf-8"],"evidence":"utf8","lossy":false,"lost":0},{"text":"\u00C3\u0192\u00C2\u00A9","steps":["windows-1252>utf-8"],"evidence":"utf8","lossy":false,"lost":0}]},
  },
  // UTF-8 shown in a console using IBM 437.
  {
    // Name.
    id: "repair-utf8-as-cp437",
    // What it shows.
    note: "UTF-8 shown in a console using IBM 437",
    // Input.
    input: {"mode":"repair","text":"caf\u251C\u2310"},
    // Pinned result.
    expect: {"mode":"repair","inputScore":3,"candidates":[{"text":"caf\u00E9","steps":["ibm437>utf-8"],"evidence":"utf8","lossy":false,"lost":0}]},
  },
  // an IBM 850 file shown as windows-1252.
  {
    // Name.
    id: "repair-cp850-as-1252",
    // What it shows.
    note: "an IBM 850 file shown as windows-1252",
    // Input.
    input: {"mode":"repair","text":"a\u2021\u00C6o"},
    // Pinned result.
    expect: {"mode":"repair","inputScore":3,"candidates":[{"text":"a\u00E7\u00E3o","steps":["windows-1252>ibm850"],"evidence":"looks","lossy":false,"lost":0}]},
  },
  // a windows-1252 file shown as IBM 850.
  {
    // Name.
    id: "repair-1252-as-cp850",
    // What it shows.
    note: "a windows-1252 file shown as IBM 850",
    // Input.
    input: {"mode":"repair","text":"S\u00D2o Paulo"},
    // Pinned result.
    expect: {"mode":"repair","inputScore":2,"candidates":[{"text":"S\u00E3o Paulo","steps":["ibm850>windows-1252"],"evidence":"looks","lossy":false,"lost":0},{"text":"S\u00F1o Paulo","steps":["macintosh>windows-1252"],"evidence":"looks","lossy":false,"lost":0}]},
  },
  // EBCDIC 037 bytes shown as Latin-1.
  {
    // Name.
    id: "repair-ebcdic-as-latin1",
    // What it shows.
    note: "EBCDIC 037 bytes shown as Latin-1",
    // Input.
    input: {"mode":"repair","text":"\u00C8\u00C5\u00D3\u00D3\u00D6k@\u00E6\u0096\u0099\u0093\u0084"},
    // Pinned result.
    expect: {"mode":"repair","inputScore":26,"candidates":[{"text":"HELLO, World","steps":["iso-8859-1>ibm037"],"evidence":"looks","lossy":false,"lost":0}]},
  },
  // the last byte of a closing quotation mark was lost.
  {
    // Name.
    id: "repair-lossy",
    // What it shows.
    note: "the last byte of a closing quotation mark was lost",
    // Input.
    input: {"mode":"repair","text":"\u00E2\u20AC\u0153quoted\u00E2\u20AC"},
    // Pinned result.
    expect: {"mode":"repair","inputScore":13,"candidates":[{"text":"\u201Cquoted\uFFFD","steps":["windows-1252>utf-8"],"evidence":"utf8","lossy":true,"lost":1}]},
  },
  // correct text is left alone.
  {
    // Name.
    id: "repair-correct-text",
    // What it shows.
    note: "correct text is left alone",
    // Input.
    input: {"mode":"repair","text":"a\u00E7\u00E3o"},
    // Pinned result.
    expect: {"mode":"repair","inputScore":0,"candidates":[]},
  },
  // a text mixing correct and misread characters is left alone.
  {
    // Name.
    id: "repair-mixed-left-alone",
    // What it shows.
    note: "a text mixing correct and misread characters is left alone",
    // Input.
    input: {"mode":"repair","text":"caf\u00C3\u00A9 and caf\u00E9"},
    // Pinned result.
    expect: {"mode":"repair","inputScore":6,"candidates":[]},
  },
];

/** The outcome of running every vector. */
export interface VerifyReport {
  // The set.
  setId: string;
  // How many vectors ran.
  total: number;
  // How many matched.
  passed: number;
  // The ones that did not, with the first difference.
  failures: { id: string; reason: string }[];
}

/** Run every vector and compare its pinned fields byte for byte. */
export function verifyVectors(): VerifyReport {
  // Failures found.
  const failures: { id: string; reason: string }[] = [];
  // Each vector.
  for (const v of VECTORS) {
    // A throw is a failure too.
    try {
      // Run and reduce (through JSON, as the expected values were captured).
      const got = JSON.stringify(pin(run(v.input)));
      // The expected text.
      const want = JSON.stringify(v.expect);
      // Compare.
      if (got !== want) {
        // The first differing character, for a readable reason.
        let k = 0;
        // Walk to it.
        while (k < got.length && got[k] === want[k]) k++;
        // Record.
        failures.push({ id: v.id, reason: `differs at ${k}: got ...${got.slice(Math.max(0, k - 30), k + 50)}... want ...${want.slice(Math.max(0, k - 30), k + 50)}...` });
      }
    } catch (e) {
      // The error.
      failures.push({ id: v.id, reason: `threw: ${(e as Error).message}` });
    }
  }
  // The report.
  return { setId: GOLDEN_VECTOR_SET_ID, total: VECTORS.length, passed: VECTORS.length - failures.length, failures };
}
