// ============================================================================
// src/content/testimonials/data.ts
// ----------------------------------------------------------------------------
// THE TESTIMONIALS DATASET — verbatim, proofread, image-accurate, with
// build-time English translations for non-English entries.
//
// SOURCE: RN_Recommendations_Catalog_v2_proofread.xlsx, proofread line-by-line
// against the original screenshots (2026-06-23). EVERY `text` here is VERBATIM,
// original spellings and typos preserved (canon guardrail: verbatim-only).
//
// TRANSLATIONS: `textEnglish` holds a build-time English translation for the
// Portuguese entries, so the page can offer "translate to English" while
// keeping the verbatim original one tap away. `translationStatus` marks each:
//   - "original": already English, no translation
//   - "machine": MACHINE-GENERATED translation, UNREVIEWED — flagged for review
//   - "source-translated": entry was already a Google translation of a PT post
//   - "bilingual": reviewer wrote both languages; English already in `text`
// The original `text` is ALWAYS the source of truth; `textEnglish` is secondary.
//
// The exact duplicate (#25 == #23) is excluded. Owner responses are supporting
// context, not the reviewer's words. Generated data — do not hand-edit.
// ============================================================================

export interface Testimonial {
  id: string;
  source: string;
  author: string;
  title: string | null;
  date: string | null;
  relationship: string | null;
  rating: string | null;
  lang: string | null;
  text: string;                 // VERBATIM original — the source of truth
  textEnglish: string | null;   // build-time EN translation (null if already EN)
  translationStatus: "original" | "machine" | "source-translated" | "bilingual";
  ownerResponse: string | null;
  note: string | null;
  provenance: string | null;
}

export const TESTIMONIALS: Testimonial[] = [
  {
    "id": "9",
    "source": "Verified Student review (Red Education)",
    "author": "A (anonymized)",
    "title": "Verified Student",
    "date": "(within ~1yr of 2025-07 capture)",
    "relationship": null,
    "rating": "5★",
    "lang": "EN",
    "text": "Training Facilitator (Rod Nutzman) is very knowledgeable and thorough on the topics being delivered. His instructional strategies effectively engage students, making learning a dynamic and enjoyable experience. I greatly appreciate his commitment to creating a positive and inclusive online classroom environment. Rod's dedication to professional development contributes to student's continuous growth, and this is commendable.\nThank you, Rod.",
    "ownerResponse": "Thank you so much for your thoughtful review. We are pleased to hear that you found Rodolfo's knowledge and instruction impactful. Your appreciation for Rod's dedication to professional development truly highlights the values we stand for at Red Education. We look forward to seeing you in future sessions! Kind Regards, Mike Baird, CEO, Red Education",
    "note": "cross-post of #8 (Alvin Serwelas) — same text, anonymized 'A'; KEEP (different platform capture)",
    "provenance": "WhatsApp_Image_20250728_at_19_58_07_70eff91d.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "8",
    "source": "Google review",
    "author": "Alvin Serwelas",
    "title": "2 reviews",
    "date": "~Oct 2024 (\"9 months ago\")",
    "relationship": null,
    "rating": "5★",
    "lang": "EN",
    "text": "Training Facilitator (Rod Nutzman) is very knowledgeable and thorough on the topics being delivered. His instructional strategies effectively engage students, making learning a dynamic and enjoyable experience. I greatly appreciate his commitment to creating a positive and inclusive online classroom environment. Rod's dedication to professional development contributes to student's continuous growth, and this is commendable.\nThank you, Rod.",
    "ownerResponse": "Thank you for your excellent feedback! It's fantastic to hear that Rod's expertise and engaging approach have created such a positive learning environment for you. We value this across all our trainers and I'm pleased he hasn't let you down. I'm chuffed that you found the experience enjoyable. I'll be sure to pass along your appreciation to Rod—I'm sure he'll be delighted to hear how much of an impact he's had on your learning journey. Thanks again for taking the time to share your thoughts! Kind Regards, Mike Baird, CEO, Red Education",
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_19_47_03_3926fd54.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "5",
    "source": "Google review",
    "author": "Barreto",
    "title": "he 3 reviews",
    "date": "~Feb 2025 (\"5 months ago\")",
    "relationship": null,
    "rating": "5★",
    "lang": "EN (Google-translated from Portuguese)",
    "text": "Congratulations to instructor Rodolfo Nützmann. Excellent training on F5 Configuring BIG-IP Local Traffic Manager (LTM).",
    "ownerResponse": "Thanks Barreto, / Yes Rodolfo is a super star 🌟 / Thanks for the feedback / Kind Regards / Mike Baird / CEO / Red Education",
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_19_44_38_8228e8ab.jpg",
    "textEnglish": null,
    "translationStatus": "source-translated"
  },
  {
    "id": "6",
    "source": "Google review",
    "author": "Divino Costa",
    "title": "4 reviews",
    "date": "~Feb 2025 (\"5 months ago\")",
    "relationship": null,
    "rating": "5★",
    "lang": "EN (Google-translated from Portuguese)",
    "text": "F5 Configuring BIG-IP Local Traffic Manager (LTM) course with Rodolfo Nützmann was excellent!",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_19_45_05_4f8c1607.jpg",
    "textEnglish": null,
    "translationStatus": "source-translated"
  },
  {
    "id": "3",
    "source": "Google review",
    "author": "Felipe Mafra",
    "title": "Local Guide - 42 reviews - 50 photos",
    "date": "~Feb 2025 (\"5 months ago\")",
    "relationship": null,
    "rating": "5★",
    "lang": "EN (Google-translated from Portuguese)",
    "text": "I loved the F5 Configuring BIG-IP Local Traffic Manager (LTM) course I took with Rodolfo Nützmann. The instructor is knowledgeable and has excellent teaching skills. I highly recommend it.",
    "ownerResponse": "Hi Felippe / That is excellent feedback 👌 / Rodolfo is one of our best F5 trainers. / Thankyou for sharing your experience / Kind Regards / Mike Baird / CEO / Red Education",
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_19_43_36_0ab11a07.jpg",
    "textEnglish": null,
    "translationStatus": "source-translated"
  },
  {
    "id": "4",
    "source": "Google review",
    "author": "Jahangher M",
    "title": null,
    "date": null,
    "relationship": null,
    "rating": "5★",
    "lang": "EN",
    "text": "Really loved the training and the instructor Rodolfo Nutzmann is good and patiently respond to all the questions.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_19_44_12_e52601f4.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "10",
    "source": "Verified Student review (Red Education)",
    "author": "KP.Gonzales",
    "title": null,
    "date": null,
    "relationship": null,
    "rating": "5★",
    "lang": "EN",
    "text": "Our instructor sir Rodolfo is really fun, i know that the theory is quite heavy, but he can pull some ice breaker to make the topic lighter.",
    "ownerResponse": "Thank you so much for your glowing 5-star rating of Red Education! I appreciate your feedback and am pleased to hear that Rodolfo was able to make the learning experience enjoyable. We strive to provide not only valuable education but also an engaging and enjoyable atmosphere for our learners. Your feedback motivates us to keep up the good work and continue delivering high-quality training. Kind Regards, Mike Baird, CEO, Red Education",
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_04_51_eda383ba.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "1",
    "source": "Google review",
    "author": "Michael Messervey",
    "title": null,
    "date": null,
    "relationship": null,
    "rating": "4★",
    "lang": "EN",
    "text": "Rodolfo was a bright spot in the Netskope training. There were some technical issues with the labs but the lectures were presented fantastically.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_16_27_47_3d98afab.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "7",
    "source": "Google review",
    "author": "romano uson",
    "title": null,
    "date": null,
    "relationship": null,
    "rating": "4★",
    "lang": "EN",
    "text": "The training and lecture are really extensive, But ROD did a great job in explaining it in a simple form that anybody will understand each function of Fortinet firewall features. Saddly only the LAB was not able to extend for another day for us to fully complete the exercises.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_19_45_50_a5248e99.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "2",
    "source": "Google review",
    "author": "XingHui LAI",
    "title": "Local Guide - 43 reviews - 24 photos",
    "date": "~Mar 2025 (\"4 months ago\")",
    "relationship": null,
    "rating": "5★",
    "lang": "EN",
    "text": "I attended the Troubleshooting F5 Course by Rodolfo. Very intensive modules and chapters that were easily broken down for easier understanding by Rod.\n\nI could easily relate those examples, as I have experienced it firsthand as well. The course would excel even more if there was a summary of the content/cheatsheet of various troubleshooting methods rather than the course materials provided by F5 (outdated anyways).\n\nOverall, it has been sometime since I have attended quality courses.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_19_42_16_7a8ddb14.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "43",
    "source": "LinkedIn recommendation",
    "author": "Adilson Caputo",
    "title": "Engenheiro de Redes",
    "date": "May 2, 2014",
    "relationship": "Adilson worked with Rodolfo on the same team",
    "rating": null,
    "lang": "PT",
    "text": "Recomendo Rodolfo pelo pefil profissional, pela dedicação e comprometimento a suas atribuições na empresa e com os clientes.\nRodolfo possui um ótimo conhecimento técnico que faz a diferença para quem realmente necessita de uma solução e desenvolvimento de projetos.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_3c4e7531.jpg",
    "textEnglish": "I recommend Rodolfo for his professional profile, for his dedication and commitment to his responsibilities at the company and with clients.\nRodolfo has excellent technical knowledge that makes a difference for anyone who genuinely needs a solution and project development.",
    "translationStatus": "machine"
  },
  {
    "id": "65",
    "source": "LinkedIn recommendation",
    "author": "Adilson Gal, CISSP, CC",
    "title": "Senior Product Security Engineer @ HPE Aruba Networking",
    "date": "August 17, 2004",
    "relationship": "Adilson worked with Rodolfo on the same team",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo is an excellent professional that I had the pleasure to work with... Very smart, intelligent, quick learner, dedicated and skillful... Excellent team player.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_59de0160.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "68",
    "source": "LinkedIn recommendation",
    "author": "Adriano Mazza",
    "title": "OT Business Development Manager at Fortinet Protecting Industries against emerging cyber threats. | Industrial Cybersecurity - OT/ICS | IoT | Cloud Security",
    "date": "April 14, 2008",
    "relationship": "Adriano worked with Rodolfo but on different teams",
    "rating": null,
    "lang": "EN",
    "text": "With excellent technical background and business knowledge, Rodolfo understands that the customer needs are the key factor in the project development. It is a great pleasure to work with a competent guy and I hope to have this opportunity again.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_9a410148.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "59",
    "source": "LinkedIn recommendation",
    "author": "Alex Marques",
    "title": "Sales Director | MBA in Strategic Business Management | Business Advisor",
    "date": "April 22, 2008",
    "relationship": "Alex worked with Rodolfo on the same team",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo is a very dedicated professional, ever looking to improve his knowledge and seeking maximize his technical development.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_3c021d83.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "45",
    "source": "LinkedIn recommendation",
    "author": "Amir Hamad",
    "title": "Coach Holístico - Astrologia, Tarot, Xamanismo, Tantra, Magia Natural e Terapia Floral",
    "date": "January 27, 2009",
    "relationship": "Rodolfo was senior to Amir but didn't manage Amir directly",
    "rating": null,
    "lang": "EN",
    "text": "I´ve worked with Rodolfo when I was starting my career at Enterasys, and I can say that Rodolfo is really a expert in his area, I´ve learned many things from Rodolfo. He is a friendly person and till now, that we are in different companies, I consider him a friend.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_52dd5edc.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "27",
    "source": "LinkedIn recommendation",
    "author": "Andre Ricardo Ramalho Monteiro",
    "title": "Cyber Security Specialist - Pre-Sales at CYLK Technologing",
    "date": "May 27, 2020",
    "relationship": "Andre Ricardo worked with Rodolfo on the same team",
    "rating": null,
    "lang": "PT/EN",
    "text": "Rodolfo é um excelente profissional, muito dedicado e com grande espirito de time.\nRodolfo is an amazing professional that makes difference in the team. I'm glad to work with him.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_41_536256b2.jpg",
    "textEnglish": null,
    "translationStatus": "bilingual"
  },
  {
    "id": "42",
    "source": "LinkedIn recommendation",
    "author": "Andrea Ramos",
    "title": "Researcher and Historian focusing on Millennial Fermentation | Sommelier",
    "date": "March 23, 2012",
    "relationship": "Andrea worked with Rodolfo but they were at different companies",
    "rating": null,
    "lang": "PT",
    "text": "Trabalhei em parceria com o Rodolfo em um projeto onde precisávamos analisar o capacity do link de dados. Um desafio para nossa equipe. Seu conhecimento sobre o assunto, aprofundamento das análises e qualidade dos resultados apresentados, sua postura diante desse desafio foram fundamentais para o sucesso do projeto. Excelente profissional!",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_2f06b88f.jpg",
    "textEnglish": "I worked in partnership with Rodolfo on a project where we needed to analyze the capacity of the data link. A challenge for our team. His knowledge of the subject, the depth of his analysis and the quality of the results he presented, and his attitude in the face of that challenge were fundamental to the project's success. Excellent professional!",
    "translationStatus": "machine"
  },
  {
    "id": "41",
    "source": "LinkedIn recommendation",
    "author": "Andrey Tavares",
    "title": "Analista de Infraestrutura, Suporte e Segurança de Tecnologia da Informação no HU-UNIVASF/EBSERH",
    "date": "April 25, 2014",
    "relationship": "Andrey was Rodolfo's client",
    "rating": null,
    "lang": "PT",
    "text": "Rodolfo foi um excelente instrutor do curso de equipamentos da Extreme Networks. Demonstrou ter o domínio completo da tecnologia e a didática necessária para passar o conhecimento para nossa equipe.\n\nAlém disso, trabalhou na implementação da nossa rede metropolitana. Mais uma vez demonstrou ter domínio completo da tecnologia e criatividade para solução dos problemas.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_2ee76f91.jpg",
    "textEnglish": "Rodolfo was an excellent instructor for the Extreme Networks equipment course. He demonstrated complete command of the technology and the teaching skill needed to pass that knowledge on to our team.\n\nBeyond that, he worked on the implementation of our metropolitan network. Once again he demonstrated complete command of the technology and creativity in solving problems.",
    "translationStatus": "machine"
  },
  {
    "id": "51",
    "source": "LinkedIn recommendation",
    "author": "Antonio Martins",
    "title": "Pre-sales Engineer",
    "date": "May 12, 2008",
    "relationship": "Antonio worked with Rodolfo on the same team",
    "rating": null,
    "lang": "PT",
    "text": "Rodolfo é um profissional muito atento e responsável no desenvolvimento e implementação dos seus projetos. Extremamente técnico, além de uma exemplar habilidade de escrever documentos.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_d6265203.jpg",
    "textEnglish": "Rodolfo is a very attentive and responsible professional in the development and implementation of his projects. Extremely technical, with an exemplary ability to write documentation as well.",
    "translationStatus": "machine"
  },
  {
    "id": "69",
    "source": "LinkedIn recommendation",
    "author": "Arapoan Fernandes Filho",
    "title": "Senior Client Manager at NTT",
    "date": "April 18, 2008",
    "relationship": "Arapoan worked with Rodolfo but on different teams",
    "rating": null,
    "lang": "PT",
    "text": "Trabalhamos juntos em atendimento ao Serpro, quando Rodolfo executava a funcao de SPOC, hoje denominada HTOM aqui na Cisco.\nRessalto que se trata de um excelente profissional, tendo desempenhado sua função com eficiência e lealdade durante o período em que trabalhou conosco, não havendo nada, portanto, que o desabone.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_b5ed5e90.jpg",
    "textEnglish": "We worked together serving Serpro, when Rodolfo held the SPOC role, today called HTOM here at Cisco.\nI want to emphasize that he is an excellent professional, having performed his role with efficiency and loyalty during the period he worked with us, with nothing whatsoever to discredit him.",
    "translationStatus": "machine"
  },
  {
    "id": "15",
    "source": "LinkedIn recommendation",
    "author": "Augusto Batista de Paula",
    "title": "Cyber Security Analyst",
    "date": "August 8, 2023",
    "relationship": "Augusto and Rodolfo studied together",
    "rating": null,
    "lang": "PT",
    "text": "É com imensa alegria que compartilho minha experiência com o Professor Rodolfo Nützmann! 🎉\n\nDurante o período em que tive a honra de ser aluno do Curso de WAF, sua energia positiva e entusiasmo contagioso fizeram das video aulas um verdadeiro lugar de aprendizado. Sua habilidade em transmitir conhecimentos de forma clara e envolvente foi essencial para meu desenvolvimento técnico e pessoal.\n\nAlém disso, a vibe incrível do Professor Nützmann é simplesmente contagiante. Sempre disposto a transmitir conhecimento e dando aquela moral para quem está estudando para certificações.\n\nSou grato por ter tido a oportunidade de aprender com alguém tão excepcional quanto o Professor Nützmann. Sua vibe positiva e seu humor continuam a influenciar minha trajetória.\n\nObrigado, Professor Nützmann, por ser um educador extraordinário em minha jornada acadêmica! 🌞📊",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_40_81b8be43.jpg",
    "textEnglish": "It is with immense joy that I share my experience with Professor Rodolfo Nützmann! 🎉\n\nDuring the time I had the honor of being a student in the WAF course, his positive energy and contagious enthusiasm made the video lessons a true place of learning. His ability to convey knowledge clearly and engagingly was essential to my technical and personal development.\n\nBeyond that, Professor Nützmann's incredible vibe is simply contagious. Always willing to share knowledge and giving encouragement to anyone studying for certifications.\n\nI am grateful to have had the opportunity to learn from someone as exceptional as Professor Nützmann. His positive vibe and his humor continue to influence my path.\n\nThank you, Professor Nützmann, for being an extraordinary educator on my academic journey! 🌞📊",
    "translationStatus": "machine"
  },
  {
    "id": "55",
    "source": "LinkedIn recommendation",
    "author": "Benny Zatyrko",
    "title": "Regional Partner Executive Sales na Cisco",
    "date": "April 17, 2008",
    "relationship": "Benny worked with Rodolfo but on different teams",
    "rating": null,
    "lang": "EN",
    "text": "I have Rodolfo as a high committed professional, business oriented with good market knowledge.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_19339bae.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "76",
    "source": "LinkedIn recommendation",
    "author": "Bernhard Behn",
    "title": "Principal Program Manager - Azure Edge + Platform",
    "date": "July 22, 2004",
    "relationship": "Bernhard worked with Rodolfo on the same team",
    "rating": null,
    "lang": "EN",
    "text": "I have known Rodolfo for over 12 years and have always been impressed with his technical abilities. He takes pride in the quality of his work and is always excited to learn something new. I highly recommend Rodolfo as a very skilled individual.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_32_56_b7f7b702.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "64",
    "source": "LinkedIn recommendation",
    "author": "Carlos Mont'Alverne",
    "title": "Service and Support Manager; Service Assurance; Service Providers Processes",
    "date": "April 18, 2008",
    "relationship": "Carlos was senior to Rodolfo but didn't manage Rodolfo directly",
    "rating": null,
    "lang": "EN",
    "text": "I do recommend Rodolfo. He worked as a Cisco engineer in account Serpro - Servico Federal de Processamento de Dados - and was very successful in all his assignments. He is a very responsible guy, with a strong technical background and was proactive, focused on results and helped all the time the customer during all the period we worked together (around one year). Rodolfo also communicated well both with the customer and the account team (he team-worked very well with me and all the account team).",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_4cda2d4f.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "33",
    "source": "LinkedIn recommendation",
    "author": "Caroline Soares",
    "title": "Associate Customer Success Renewal Specialist @ SAS",
    "date": "July 24, 2020",
    "relationship": "Caroline worked with Rodolfo but on different teams",
    "rating": null,
    "lang": "PT",
    "text": "Rodolfo é um excelente profissional! Entende muito bem sobre o que faz e conseguiu me ajudar e me ensinar boa parte do que sei hoje sobre soluções de segurança da informação, mostrando-se um ótimo parceiro de trabalho.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_41_a82cfd11.jpg",
    "textEnglish": "Rodolfo is an excellent professional! He understands very well what he does and was able to help me and teach me much of what I know today about information security solutions, proving to be a great work partner.",
    "translationStatus": "machine"
  },
  {
    "id": "71",
    "source": "LinkedIn recommendation",
    "author": "Claudio Neiva",
    "title": "Field Technology Director @ CyberArk | Information Security, C-Suite Security Strategy",
    "date": "April 18, 2008",
    "relationship": "Claudio worked with Rodolfo on the same team",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo is a very talent professional who I had the pleasure to work with. His vast knowledge on Networking helped me to speed up my training on Enterasys products when I started at Enterasys. I highly recommends Rodolfo as an excellent and talent professional.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_ed4cfc12.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "31",
    "source": "LinkedIn recommendation",
    "author": "Dan Peres",
    "title": "Helping public and private organizations to solve mission-critical challenges.",
    "date": "June 12, 2020",
    "relationship": "Dan worked with Rodolfo but they were at different companies",
    "rating": null,
    "lang": "EN",
    "text": "I worked with Rodolfo for a couple of years while he was an engineer in Network1 and Westcon Brazil. Rodolfo always showed a unique set of technical skills and combined with his \"always available mode\" was a perfect combination for the success.\nHis tech abilities coupled with his ability to demonstrate the products differentiations make Rodolfo a great professional to any organization.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_41_6c0c6cf1.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "57",
    "source": "LinkedIn recommendation",
    "author": "Dave Potter",
    "title": "Sr Solutions Architect",
    "date": "October 17, 2005",
    "relationship": "Dave worked with Rodolfo but on different teams",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo possesses excellent team building and inter-group working skills. At Riverstone, he co-built the knowledge base, including the processes to input and use it. Additionally, Rodolfo authored the initial docs in the KB, improving the overall efficiency of the TAC.",
    "ownerResponse": null,
    "note": "capture contains 2 distinct Dave Potter recommendations; see also #80 (same capture)",
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_1e410b20.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "80",
    "source": "LinkedIn recommendation",
    "author": "Dave Potter",
    "title": "Sr Solutions Architect",
    "date": "October 17, 2005",
    "relationship": "Dave worked with Rodolfo but on different teams",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo has excellent case management and team working skills. He both quickly and professionally manages his case load with minimal impact to both the customer and the company.",
    "ownerResponse": null,
    "note": "2nd of 2 Dave Potter recommendations in the same capture as #57",
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_1e410b20.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "61",
    "source": "LinkedIn recommendation",
    "author": "David Kallas",
    "title": "Partner at KC&D, Board Member at Anefac, Assetz, Onvet and ICFOA, Teacher at Insper and Albert Einstein",
    "date": "August 22, 2004",
    "relationship": "David managed Rodolfo directly",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo is a brilliant professional with excellent communication and relationship skills. These points, plus his technical knowledge, make him a very interesting candidate for many positions.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_3f594a89.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "32",
    "source": "LinkedIn recommendation",
    "author": "Dieise Ramos",
    "title": "DFIR | BlueTeam | SOC Analyst | Cybersecurity | Cyber Threat Intelligence",
    "date": "May 27, 2020",
    "relationship": "Dieise worked with Rodolfo on the same team",
    "rating": null,
    "lang": "PT",
    "text": "Ótimo profissional e um excelente instrutor de F5.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_41_9381ef68.jpg",
    "textEnglish": "Great professional and an excellent F5 instructor.",
    "translationStatus": "machine"
  },
  {
    "id": "67",
    "source": "LinkedIn recommendation",
    "author": "Durval Stendard Filho",
    "title": "Services Sales Specialist @ HP",
    "date": "April 4, 2006",
    "relationship": "Durval was Rodolfo's client",
    "rating": null,
    "lang": "PT",
    "text": "Rodolfo,\nTrabalhando do outro lado - agora em um cliente e parceiro da Enterasys, tenho sido testemunho do reconhecimento do mercado ao seu profissionalismo.\nParabéns!\nDurval Stendard Filho\nGerente de Divisão - Implantação de Conatct Centers\nCobra Tecnologia S.A.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_71d37f81.jpg",
    "textEnglish": "Rodolfo,\nWorking on the other side now, at a client and partner of Enterasys, I have been a witness to the market's recognition of your professionalism.\nCongratulations!\nDurval Stendard Filho\nDivision Manager - Contact Center Deployment\nCobra Tecnologia S.A.",
    "translationStatus": "machine"
  },
  {
    "id": "77",
    "source": "LinkedIn recommendation",
    "author": "Durval Stendard Filho",
    "title": "Services Sales Specialist @ HP",
    "date": "July 22, 2004",
    "relationship": "Durval worked with Rodolfo but on different teams",
    "rating": null,
    "lang": "PT",
    "text": "Trabalhamos juntos por 4 anos. Da experiência profissional marcam:-Confiabilidade;-Competência;-Bom relacionamento;- Alta capacidade de coordenação e implementação em projetos críticos;-Criatividade e precisão em demonstrações estratégica; -Ótima didática em treinamentos( técnicos e marketing, internos e externos ).\nUm dos mais capacitados e hábeis Systems Engineer que a Enterasys já teve.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_32_56_dd7c417d.jpg",
    "textEnglish": "We worked together for 4 years. What stands out from the professional experience: reliability; competence; good relationships; a strong capacity for coordinating and implementing critical projects; creativity and precision in strategic demonstrations; excellent teaching in training (technical and marketing, internal and external).\nOne of the most capable and skilled Systems Engineers that Enterasys ever had.",
    "translationStatus": "machine"
  },
  {
    "id": "28",
    "source": "LinkedIn recommendation",
    "author": "Edson Lemos",
    "title": null,
    "date": "May 27, 2020",
    "relationship": "Edson worked with Rodolfo but on different teams",
    "rating": null,
    "lang": "PT",
    "text": "Nutzman é um profissional altamente capacitado e qualificado.\nPossui profundos conhecimentos em segurança.\nDiferenciado no mercado, digo isso porque, ele não é do tipo \"tenta e testa\". Ele diz que não tem tempo pra isso ( rsrs)\ne é efetivo no desenho dos projetos.\nEntão ele simplesmente entende o conceito de \"SEGURANÇA\" e aplica os conhecimentos dele na solução.\nTivemos bons desafios juntos e ele como sempre se saiu muito bem!",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_41_5546ae99.jpg",
    "textEnglish": "Nutzman is a highly capable and qualified professional.\nHe has deep knowledge of security.\nA standout in the market, and I say that because he is not the \"try and test\" type. He says he doesn't have time for that (haha)\nand he is effective in designing projects.\nSo he simply understands the concept of \"SECURITY\" and applies his knowledge to the solution.\nWe had some good challenges together and, as always, he came through very well!",
    "translationStatus": "machine"
  },
  {
    "id": "21",
    "source": "LinkedIn recommendation",
    "author": "Eduardo Casseano",
    "title": "Customer Engineer (Digital Natives) @ Google Cloud",
    "date": "July 8, 2020",
    "relationship": "Eduardo worked with Rodolfo but they were at different companies",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo is a great professional, we've have worked together in several occasions and he's was always super helpful and proactive. He is a very intelligent person and solid technical skills. I'm sure he's a valuable asset for any company.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_41_19f20a86.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "17",
    "source": "LinkedIn recommendation",
    "author": "Eduardo Mariano",
    "title": "Analista de Operações Telecom | Itaú Unibanco",
    "date": "August 10, 2023",
    "relationship": "Eduardo was Rodolfo's client",
    "rating": null,
    "lang": "PT",
    "text": "Excelente instrutor! Tive prazer de participar da academia de F5 BigIP e apesar de nunca ter trabalhado e nem ter contato com a tecnologia, consegui tirar as 2 primeiras certificações de LTM, graças ao treinamento com o Rodolfo.\nObrigado e até a próxima!",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_40_9cbf1090.jpg",
    "textEnglish": "Excellent instructor! I had the pleasure of taking part in the F5 BigIP academy and, despite never having worked with or even been exposed to the technology, I managed to earn my first 2 LTM certifications, thanks to the training with Rodolfo.\nThank you, and until next time!",
    "translationStatus": "machine"
  },
  {
    "id": "62",
    "source": "LinkedIn recommendation",
    "author": "Eduardo Ritter",
    "title": "Sales Executive | Strategic Financial Accounts | Crowdstrike | Helping Customers Stop Breaches",
    "date": "April 14, 2008",
    "relationship": "Eduardo worked with Rodolfo but on different teams",
    "rating": null,
    "lang": "EN",
    "text": "During the time I worked with Rodolfo I could identify that he is a very commited person when it relates to customer satisfaction and customer service. He is a very focused person and it is very pleasing to work in the same environment as him.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_43096dc2.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "26",
    "source": "LinkedIn recommendation",
    "author": "Eduardo Ushiama",
    "title": "Consultor de Segurança da Informação | Especialista de Segurança de Informação | Cloud Security | Network Security",
    "date": "August 8, 2023",
    "relationship": "Eduardo was Rodolfo's client",
    "rating": null,
    "lang": "PT",
    "text": "Excelente didática e com alto nível de conhecimento técnico, principalmente em soluções da F5.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_41_4fa4cafa.jpg",
    "textEnglish": "Excellent teaching and a high level of technical knowledge, especially in F5 solutions.",
    "translationStatus": "machine"
  },
  {
    "id": "22",
    "source": "LinkedIn recommendation",
    "author": "Fabiana Conz Weiler",
    "title": "Senior Customer Success Manager | Solutions Architect",
    "date": "May 31, 2020",
    "relationship": "Fabiana worked with Rodolfo on the same team",
    "rating": null,
    "lang": "PT",
    "text": "Tive o prazer de trabalhar com o Nützmann na Westcon, atuando juntos em diversos projetos do fabricante F5. É muito raro ter a oportunidade de ter um colega de equipe como ele: extremamente colaborativo, muita experiencia de mercado e com uma didática e generosidade ímpar para compartilhar seu profundo conhecimento técnico. Nützmann sempre tratou os clientes com empatia e simplicidade e destaca-se por sua capacidade de resolver problemas complexos e inesperados.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_41_210e2239.jpg",
    "textEnglish": "I had the pleasure of working with Nützmann at Westcon, working together on various projects for the manufacturer F5. It is very rare to have the chance to have a teammate like him: extremely collaborative, with a great deal of market experience and an unmatched gift for teaching and generosity in sharing his deep technical knowledge. Nützmann always treated clients with empathy and simplicity and stands out for his ability to solve complex and unexpected problems.",
    "translationStatus": "machine"
  },
  {
    "id": "37",
    "source": "LinkedIn recommendation",
    "author": "Fabio Correa",
    "title": "CSO at PLOT Visual Technologies",
    "date": "October 9, 2009",
    "relationship": "Fabio worked with Rodolfo on the same team",
    "rating": null,
    "lang": "PT",
    "text": "Trabalhei com o Rodolfo por pouco tempo, mas pelo pouco tempo que trabalhamos juntos na parceria das empresas Plot e Unicom, percebi que era um profissional diferenciado, principalmente tecnicamente. Com um vasto conhecimento em redes principalmente, pude perceber que estava bem assessorado tecnicamente nos projetos.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_1a15f11f.jpg",
    "textEnglish": "I worked with Rodolfo for only a short time, but in the little time we worked together in the partnership between the companies Plot and Unicom, I could tell he was an exceptional professional, especially technically. With vast knowledge in networking in particular, I could see that I was very well supported technically on the projects.",
    "translationStatus": "machine"
  },
  {
    "id": "20",
    "source": "LinkedIn recommendation",
    "author": "Fernando Camargo Filho",
    "title": "Consultant at F5",
    "date": "April 18, 2021",
    "relationship": "Fernando worked with Rodolfo but they were at different companies",
    "rating": null,
    "lang": "EN",
    "text": "I had the opportunity to get to know and act Rodolfo through the works and events of F5 Networks. Always very concerned with the client and how to give the best guidance to partners, today I see him highlighted as an Instructor, where he always seeks the best way to present the solution for the daily life of the Brazilian market. In my opinion, an excellent professional always innovating to the market.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_41_08538c69.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "49",
    "source": "LinkedIn recommendation",
    "author": "Fábio de Faria",
    "title": "Local Sales Manger na TDec Network Group",
    "date": "May 1, 2014",
    "relationship": "Fábio worked with Rodolfo on the same team",
    "rating": null,
    "lang": "PT",
    "text": "Excelente profissional e muito comprometido em tudo aquilo em que está envolvido. Sempre busca novos conhecimentos e formas de atualização profissional. Incansável na busca de soluções.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_b7a3d3c4.jpg",
    "textEnglish": "Excellent professional and very committed to everything he is involved in. He is always seeking new knowledge and ways to keep himself professionally up to date. Tireless in the search for solutions.",
    "translationStatus": "machine"
  },
  {
    "id": "60",
    "source": "LinkedIn recommendation",
    "author": "Hélder Farias",
    "title": "CISSP | Sophos Account Executive | Cybersecurity | Data Protection | Business Development | Enterprise Sales",
    "date": "April 13, 2008",
    "relationship": "Rodolfo was senior to Hélder but didn't manage Hélder directly",
    "rating": null,
    "lang": "EN",
    "text": "I had an oportunity to know and to learn very much with him. Rodolfo have a great technical skill, inteligency and spirit of team. I'm not alone in endorse your characteristics and recommend your talent.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_3c146af4.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "54",
    "source": "LinkedIn recommendation",
    "author": "Igor Giangrossi",
    "title": "Sr. Director, Consulting Engineering at Nokia",
    "date": "July 28, 2004",
    "relationship": "Igor worked with Rodolfo but on different teams",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo did a tremendous job creating the Technical Library at Riverstone. The knowledge base created by him became the central repository for all technical documentation inside Riverstone (both public and confidential), not only allowing the whole organization to easily find any technical document, but also introducing a culture of documenting everything to make it available to everyone.",
    "ownerResponse": null,
    "note": "capture contains 2 distinct Igor Giangrossi recommendations; see also #79 (same capture)",
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_05ba7d1e.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "79",
    "source": "LinkedIn recommendation",
    "author": "Igor Giangrossi",
    "title": "Sr. Director, Consulting Engineering at Nokia",
    "date": "July 28, 2004",
    "relationship": "Igor worked with Rodolfo but on different teams",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo was one of the most talented SEs of the Enterasys pre-sales group. Both his technical knowledge and his clear understanding of the customer needs were key to developing effective solutions for Enterasys customers. He has also helped our post-sales team many times with his large experience in the SSR/Xpedition switch-routers and routing protocols in general.",
    "ownerResponse": null,
    "note": "2nd of 2 Igor Giangrossi recommendations in the same capture as #54",
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_05ba7d1e.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "63",
    "source": "LinkedIn recommendation",
    "author": "Joel Ambar",
    "title": "Sales Director , Global Account Manager & Sales Executive",
    "date": "April 17, 2008",
    "relationship": "Joel was Rodolfo's client",
    "rating": null,
    "lang": "PT",
    "text": "Tive a felicidade como responsável comercial da Avaya de ter sido escolhido para fornecer uma solução completa de Telefonia IP/SIP e Gravação -SIP para atender uma das maiores corretoras do país que é ARKHE. O projeto e solução comtempla o que há mais novo em alta -disponibilidade, facilidades, SIP e gravação para atender as necessidades de negócio do cliente. Todo o desenho, concepção análise e implantação do projeto foi conduzida pelo Sr. Rodolfo Nutzmann, o qual devido seu conhecimento tecnológico experiência em gerência de projetos conseguiu desenhar um projeto onde todas as necessidades de um cliente que movimenta um enorme volume financeiro diariámente necessita. Destaco no Rodolfo a personalidade e ética e também o profissionalismo apresentado para liderar projetos e gerenciar conflitos em projetos onde vários forncedores foram envolvidos..",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_4a136031.jpg",
    "textEnglish": "As the sales lead at Avaya, I had the good fortune of being chosen to provide a complete IP/SIP Telephony and SIP Recording solution to serve one of the largest brokerages in the country, ARKHE. The project and solution encompass the very latest in high availability, features, SIP and recording to meet the client's business needs. The entire design, conception, analysis and implementation of the project was led by Mr. Rodolfo Nutzmann, who, thanks to his technological knowledge and project management experience, was able to design a project meeting every need of a client that moves an enormous financial volume daily. I highlight in Rodolfo his character and ethics, as well as the professionalism he showed in leading projects and managing conflicts on projects where several suppliers were involved.",
    "translationStatus": "machine"
  },
  {
    "id": "34",
    "source": "LinkedIn recommendation",
    "author": "Jonildo Cordeiro",
    "title": "Técnico na Universidade Federal do Vale do São Francisco",
    "date": "October 9, 2014",
    "relationship": "Jonildo was Rodolfo's client",
    "rating": null,
    "lang": "PT",
    "text": "Rodolfo é um excelente profissional, especialista no que faz!",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_08_19d5b91a.jpg",
    "textEnglish": "Rodolfo is an excellent professional, a specialist at what he does!",
    "translationStatus": "machine"
  },
  {
    "id": "29",
    "source": "LinkedIn recommendation",
    "author": "Jorge Barone",
    "title": "Certified Ethical Hacker (CEH) Master | Python | F5 Load Balance | WAF F5 Imperva | IPS | Firewall Checkpoint PaloAlto | LPI 2 | Information Security Specialist at Icatu Seguros",
    "date": "July 25, 2023",
    "relationship": "Jorge was Rodolfo's client",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo Nützmann is a great professional, he has excellent skills in Network Security Perimeter solutions like Load Balancing, Firewall, WAF, and so on. He was responsible for teaching me most of what I know about F5 solution. Also, he's a great person and teacher.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_41_5f872e18.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "16",
    "source": "LinkedIn recommendation",
    "author": "Josan Neves",
    "title": "Security Infrastructure Analyst | Curious?! Read on!",
    "date": "August 8, 2023",
    "relationship": "Josan was Rodolfo's client",
    "rating": null,
    "lang": "PT",
    "text": "Rodolfo é um excelente instrutor, que demonstra dedicação ao aprendizado dos alunos de seus treinamentos profissionais, aos quais oferece uma didática fácil e organizada. Apresenta alta capacidade técnica, aliada a experiência e domínio das tecnologias, o que possibilita sua facilidade na transmissão de conhecimentos e remoção de dúvidas. Recomendadíssimo!",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_40_8f3d9fd1.jpg",
    "textEnglish": "Rodolfo is an excellent instructor, who shows dedication to the learning of the students in his professional training courses, to whom he offers easy and organized teaching. He brings high technical ability, combined with experience and command of the technologies, which makes it easy for him to convey knowledge and clear up doubts. Highly recommended!",
    "translationStatus": "machine"
  },
  {
    "id": "36",
    "source": "LinkedIn recommendation",
    "author": "Jose P. Leal Junior",
    "title": "Country Manager @ Veeam Software",
    "date": "November 17, 2008",
    "relationship": "Jose P. managed Rodolfo directly",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo is a hard-working and result-oriented professional, getting along extremely well with his colleagues and partners, with an impecable track of records. His technical background and result-oriented perspective makes him a true asset to any organization.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_004538d5.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "23",
    "source": "LinkedIn recommendation",
    "author": "Josep Zabulon",
    "title": "Umpqua Services - Solutions for Business Perfomance",
    "date": "August 8, 2023",
    "relationship": "Josep Zabulon worked with Rodolfo but they were at different companies",
    "rating": null,
    "lang": "PT",
    "text": "Excelente profissional, comprometido com Resultado e aliado de seus parceiros...\nFortissimo skill em Transferencia de Tecnologias atraves do uso de Treinamentos Certificados... 👍👍👍",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_41_2bbbb363.jpg",
    "textEnglish": "Excellent professional, committed to results and an ally to his partners...\nVery strong skill in Technology Transfer through the use of Certified Training... 👍👍👍",
    "translationStatus": "machine"
  },
  {
    "id": "66",
    "source": "LinkedIn recommendation",
    "author": "João Paulo Felix",
    "title": "Life Long Learner | AI & DeepTech Strategist | Innovation Ecosystem Catalyst | Board Advisor | Global Tech Leadership | Exit to Nasdaq",
    "date": "April 16, 2008",
    "relationship": "João Paulo managed Rodolfo directly",
    "rating": null,
    "lang": "EN",
    "text": "\"I always enjoyed working with Rodolfo because he combined a positive attitude, a zeal for taking care of his customers, and a great depth of knowledge about the technology that he was supporting and recommending. He would be an asset to anyone's team.\"",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_5a6f4efa.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "39",
    "source": "LinkedIn recommendation",
    "author": "Julianna Knauer",
    "title": "Network System Engineer na Aruba, a Hewlett Packard Enterprise company",
    "date": "September 16, 2008",
    "relationship": "Julianna worked with Rodolfo on the same team",
    "rating": null,
    "lang": "EN",
    "text": "I had a great pleasure to work with Rodolfo at Enterasys Networks. He has the technical and soft skills to resolve customer issues effectively and to the customers satisfaction. I do recommend Rodolfo.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_2909235c.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "70",
    "source": "LinkedIn recommendation",
    "author": "Kristiane Cardoso de Araújo",
    "title": "Product Sales Specialist for Security",
    "date": "April 22, 2008",
    "relationship": "Kristiane Cardoso de worked with Rodolfo but on different teams",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo Nutzmann has an excellent technical background that he acquired on Enterasys Networks deploying complex environments specially those that require OSPF routing. He has international experience which he acquired when he worked for Riverstone. Last year I had the opportunity to work with him when he was working as consultant for one end user that was interested in Check Point solution. He did an excellent job presenting to the end user the advantages of Check Point solutions from security perspective and what would be the benefits of getting the Check Point solution based on end user needs. Clever, dynamic, auto-learning capability and self-manageable.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_c81ebd2a.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "30",
    "source": "LinkedIn recommendation",
    "author": "Leandro Sardim",
    "title": "Technical Specialist @ Microsoft",
    "date": "May 28, 2020",
    "relationship": "Leandro worked with Rodolfo but they were at different companies",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo is a great professional that I had the pleasure of having as a workmate more than once! One of the smartest and most capable people I know!",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_41_61293ba5.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "40",
    "source": "LinkedIn recommendation",
    "author": "Leonardo Luy Peixoto",
    "title": "CEO at Secure IT. Networking Professional. Enterasys Certified Architect",
    "date": "January 15, 2010",
    "relationship": "Leonardo was Rodolfo's client",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo is one of the major network experts that I had the pleasure to work with. Always ready to help and support with his great expert skills and very friendly. His deep knowledge of network solutions helped me more than once in the operation of UNIVALI's network. For me it's an honor to call him more than a Service Provider, but a real friend.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_2ed45fdf.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "38",
    "source": "LinkedIn recommendation",
    "author": "Luis Antonio Nascimento",
    "title": "Territory Manager | Executive Account | Driving Growth in Networking & Cybersecurity",
    "date": "May 2, 2008",
    "relationship": "Luis Antonio worked with Rodolfo but they were at different companies",
    "rating": null,
    "lang": "PT",
    "text": "Tive a oportunidade de compartilhar do trabalho do Rodolfo num cliente do segmento financeiro e ele fez um excelente trabalho de consultoria, relacionamento com fornecedores, definição de tecnologia, acompanhamento de negociação comercial e RFP.\nAlém disso foi o ponto de contato durante a fase de implantação, resolvendo com muito profissionalismo todos os conflitos existentes. Coordenou também a pós implantação, trazendo tranqüilidade para o cliente, pelo seu envolvimento e pró atividade apresentada durante todo o processo.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_24ab2588.jpg",
    "textEnglish": "I had the opportunity to share in Rodolfo's work at a client in the financial sector and he did an excellent job of consulting, vendor relationships, technology definition, oversight of commercial negotiations and RFP.\nBeyond that, he was the point of contact during the implementation phase, resolving all existing conflicts with great professionalism. He also coordinated the post-implementation, bringing peace of mind to the client through his involvement and the proactivity he showed throughout the entire process.",
    "translationStatus": "machine"
  },
  {
    "id": "75",
    "source": "LinkedIn recommendation",
    "author": "Luiz Eduardo",
    "title": "CTO, Security at HPE Aruba Networking",
    "date": "July 22, 2004",
    "relationship": "Luiz was senior to Rodolfo but didn't manage Rodolfo directly",
    "rating": null,
    "lang": "EN",
    "text": "Can't write up an endorsement for one company, since I worked w/ him in 3 different companies.\nThe simple endorsement is the fact that I recommended him for two out of the three places I worked w/ him.\nThere are few people in the networking industry that not only understand networking technologies, but actually \"feel them\", Rodolfo is one of these few blessed people.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_32_56_b39ac9c5.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "19",
    "source": "LinkedIn recommendation",
    "author": "Luiz Marcelo F. S. Serique",
    "title": "Gerente | CAESB - Companhia de Saneamento Ambiental do Distrito Federal",
    "date": "August 9, 2023",
    "relationship": "Luiz Marcelo was Rodolfo's client",
    "rating": null,
    "lang": "PT",
    "text": "Existem instrutores e existe o Rodolfo. Participei de cursos ministrados por ele para certificações F5, sua didática é excelente e percebe-se claramente sua experiência prática, que é um grande diferencial.\n\nRecomendo muito!",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_40_fd91f6e1.jpg",
    "textEnglish": "There are instructors, and there is Rodolfo. I took part in courses he taught for F5 certifications; his teaching is excellent and you can clearly see his practical experience, which is a great differentiator.\n\nHighly recommended!",
    "translationStatus": "machine"
  },
  {
    "id": "52",
    "source": "LinkedIn recommendation",
    "author": "Marcelo Fernandes",
    "title": "Solutions Consultant | Solution Architect | Customer Experience | User Experience",
    "date": "April 28, 2014",
    "relationship": "Marcelo worked with Rodolfo but on different teams",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo is a skilled professional with solid knowledge in networking field, and I had the opportunity to work with him at Enterasys where I saw the great level challenges he was able to deal with. He is an excellent professional and person.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_e4d52662.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "73",
    "source": "LinkedIn recommendation",
    "author": "Marcelo Rezende",
    "title": "Result-Oriented Leader: Championing Team Building | Revenue Discipline | Cost Management | Exceptional Customer Service.",
    "date": "July 26, 2004",
    "relationship": "Marcelo was senior to Rodolfo but didn't manage Rodolfo directly",
    "rating": null,
    "lang": "EN",
    "text": "Young, dinamic, very talented person with execution capabilities",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_32_56_00de916a.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "35",
    "source": "LinkedIn recommendation",
    "author": "Marcos Buzo",
    "title": "Network Engineer | CCIE #69084",
    "date": "June 26, 2014",
    "relationship": "Marcos was Rodolfo's client",
    "rating": null,
    "lang": "PT",
    "text": "Tive a oportunidade de trabalhar com o Rodolfo na implantação da Rede Metropolitana de Campinas.\nNesse projeto, ele se mostrou um profissional criativo, dedicado, pró-ativo e com muito conhecimento em tecnologias de rede.\nCertamente é um profissional que faz a diferença em uma equipe de alta performance.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_08_66545bf5.jpg",
    "textEnglish": "I had the opportunity to work with Rodolfo on the implementation of the Campinas Metropolitan Network.\nOn that project, he proved to be a creative, dedicated, proactive professional with great knowledge of network technologies.\nHe is certainly a professional who makes a difference on a high-performance team.",
    "translationStatus": "machine"
  },
  {
    "id": "56",
    "source": "LinkedIn recommendation",
    "author": "Marcus Klein",
    "title": "Customer Program Manager at Cisco Systems",
    "date": "September 13, 2004",
    "relationship": "Marcus managed Rodolfo directly",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo is a great professional, with good relationship skills, self learning skills and enterpreunership. I'm very pleased to have him as a team member in my group.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_1db764e3.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "74",
    "source": "LinkedIn recommendation",
    "author": "Mario Pires",
    "title": "Account Executive at OL Tecnologia | Infrastructure & Cybersecurity Solutions Expert | Fortinet | Aruba | Juniper | Netscout",
    "date": "July 22, 2004",
    "relationship": "Mario managed Rodolfo directly",
    "rating": null,
    "lang": "EN",
    "text": "Hi hired Rodolfo as probationary and he quickly moved to FE at Cabletron and then to SE at Enterasys. This movement shows how competent he is. Rodolfo is a complete human being as professional as well as personally. His work power is brilliant, his mind is quick and smart and his heart is so kind. I strongly endorse Rodolfo as professional and as personality.",
    "ownerResponse": null,
    "note": "capture contains 2 distinct Mario Pires recommendations; see also #81 (same capture)",
    "provenance": "WhatsApp_Image_20250728_at_20_32_56_aba65401.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "81",
    "source": "LinkedIn recommendation",
    "author": "Mario Pires",
    "title": "Account Executive at OL Tecnologia | Infrastructure & Cybersecurity Solutions Expert | Fortinet | Aruba | Juniper | Netscout",
    "date": "July 22, 2004",
    "relationship": "Mario managed Rodolfo directly",
    "rating": null,
    "lang": "EN",
    "text": "I hired Rodolfo as probationary and then he quikly move to a FE/SE position. He is a very very very competent professional and very kind person. It was a pleasure to work with so dedicated and brilliant professional and so carismatic and friendly person. I used to say that Rodolfo is part of a Brilliant Young Generation. I have proud of him.",
    "ownerResponse": null,
    "note": "2nd of 2 Mario Pires recommendations in the same capture as #74",
    "provenance": "WhatsApp_Image_20250728_at_20_32_56_aba65401.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "72",
    "source": "LinkedIn recommendation",
    "author": "Martin Gudmon",
    "title": "Manager at Capuava SA",
    "date": "November 4, 2005",
    "relationship": "Martin worked with Rodolfo on the same team",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo is a good solid network engineer. I worked with him personally for many years and have found him to be extremely hard working and customer focussed.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_f60e0ff8.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "46",
    "source": "LinkedIn recommendation",
    "author": "Mauricio Nazario",
    "title": "Tecnológo em Gestão Empresarial Scrum Master Cobit 5 Foundation",
    "date": "April 28, 2014",
    "relationship": "Mauricio worked with Rodolfo but on different teams",
    "rating": null,
    "lang": "PT",
    "text": "Ótimo profissional!!!\n\nAltamente capacitado e com profunda experiência em engenharia de redes e segurança.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_6e6901df.jpg",
    "textEnglish": "Great professional!!!\n\nHighly capable and with deep experience in network engineering and security.",
    "translationStatus": "machine"
  },
  {
    "id": "53",
    "source": "LinkedIn recommendation",
    "author": "Maurilio Antonio Gonçalves, MBA",
    "title": "Managed Services Manager | Driving Tech & Business Transformation | Product & Services Leadership | Cloud | Cybersecurity | Generative AI | Customer Experience | Mentor | Author | ANPPD® Member",
    "date": "May 27, 2009",
    "relationship": "Maurilio Antonio worked with Rodolfo on the same team",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo is an excelent professional with great High Technology knowledge. He's very responsible with his projects and always work in group.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_f19a7b1c.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "47",
    "source": "LinkedIn recommendation",
    "author": "Oscar Nogueira Neto",
    "title": "Helping teams to be more efficient with Generative AI",
    "date": "October 26, 2011",
    "relationship": "Oscar was Rodolfo's client",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo is a network expert who helped me with network appliance monitoring and capacity planning for Enterasys, Cisco, H3C and Linksys equipments.\nVery skilled he quickly gave me all the answers I needed for my project.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_8b1e0233.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "44",
    "source": "LinkedIn recommendation",
    "author": "Paulo M. Sousa",
    "title": "Network Specialist - Scala Data Centers",
    "date": "April 27, 2014",
    "relationship": "Paulo worked with Rodolfo on the same team",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo is one of the smartest and focused professionals I've ever worked. Its differential is leadership and focus on complex projects that combined with his exceptional technical knowledge makes him a distinguished professional in the market.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_477ed7c1.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "14",
    "source": "LinkedIn recommendation",
    "author": "Peterson Pereira",
    "title": "Enterprise Tech Support Analist",
    "date": "August 10, 2023",
    "relationship": "Peterson was Rodolfo's client",
    "rating": null,
    "lang": "PT",
    "text": "Excelente instrutor, não apenas pela grande qualidade técnica, mas também pela excelencia na didática e profissionalismo.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_40_80742746.jpg",
    "textEnglish": "Excellent instructor, not only for his great technical quality, but also for his excellence in teaching and professionalism.",
    "translationStatus": "machine"
  },
  {
    "id": "78",
    "source": "LinkedIn recommendation",
    "author": "Rodney Reis",
    "title": "CEO@Avalia: Software due diligence & advisory for M&A, CTOs, PE, VC",
    "date": "July 22, 2004",
    "relationship": "Rodney worked with Rodolfo on the same team",
    "rating": null,
    "lang": "EN",
    "text": "Nutz is the man. He's got the knowledge, the commitment, and is fun working with.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_32_56_ee5ea939.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "48",
    "source": "LinkedIn recommendation",
    "author": "Rodrigo Akira Hirooka",
    "title": "Developer Relations Regional Lead at Google | Ex-Amazon | Ex- Microsoft",
    "date": "April 14, 2009",
    "relationship": "Rodolfo was senior to Rodrigo but didn't manage Rodrigo directly",
    "rating": null,
    "lang": "EN",
    "text": "When I started working as a Professional Services Engineer at Enterasys, Rodolfo was my \"techinical reference\".\nRodolfo was a do it all kind of person, always ready to help you no mather when or how.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_8f2b7178.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "13",
    "source": "LinkedIn recommendation",
    "author": "Rodrigo Kowalski",
    "title": "Redes | TI | Infra | Telecom | GPON | Wi-Fi",
    "date": "August 11, 2023",
    "relationship": "Rodrigo was Rodolfo's client",
    "rating": null,
    "lang": "PT",
    "text": "Fiz 3 treinamentos da F5 Networks com o Rodolfo (Administração BIG-IP LTM, iRules e Troubleshooting) e aprendi muito com ele. Excelente professor e profissional com excelente bagagem na preparação para certificações F5 e também em metodologia de ensino. Recomendo o trabalho do Rodolfo!",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_40_696b278a.jpg",
    "textEnglish": "I took 3 F5 Networks training courses with Rodolfo (BIG-IP LTM Administration, iRules and Troubleshooting) and learned a great deal from him. Excellent teacher and professional with excellent grounding in preparing for F5 certifications and in teaching methodology as well. I recommend Rodolfo's work!",
    "translationStatus": "machine"
  },
  {
    "id": "24",
    "source": "LinkedIn recommendation",
    "author": "Rodrigo Larrabure",
    "title": "Diretor de Tecnologia e Produtos",
    "date": "May 27, 2020",
    "relationship": "Rodrigo managed Rodolfo directly",
    "rating": null,
    "lang": "EN",
    "text": "I had the pleasure of working with Rodolfo twice in the same company, but almost 10 years apart. Dedicated, customer-centric professional, has always demonstrated great technical knowledge and, above all, a great desire to learn and evolve. It's a pleasure to have him on the team!",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_41_2f8712a2.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "50",
    "source": "LinkedIn recommendation",
    "author": "Rodrigo Larrabure",
    "title": "Diretor de Tecnologia e Produtos",
    "date": "May 30, 2014",
    "relationship": "Rodrigo was senior to Rodolfo but didn't manage Rodolfo directly",
    "rating": null,
    "lang": "EN",
    "text": "I worked with Rodolfo for more than a year at CYLK. He is a proactive, customer oriented, highly commited professional. I strongly recommend him for any position he may be pursuing!",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_09_c6aa5a07.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "11",
    "source": "LinkedIn recommendation",
    "author": "Salvador Neves",
    "title": "Analista de segurança/redes",
    "date": "August 9, 2023",
    "relationship": "Salvador and Rodolfo studied together",
    "rating": null,
    "lang": "PT",
    "text": "Otimo instruto, tive o prazer em ralizar o treinammento em WAF é extremamente dedicado com conhecimentos consolidados em redes e segurança da informação. Esta sempre ponto para um auxilio.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_40_0024fb69.jpg",
    "textEnglish": "Great instructor, I had the pleasure of doing the WAF training; he is extremely dedicated with solid knowledge in networking and information security. He is always ready to help.",
    "translationStatus": "machine"
  },
  {
    "id": "12",
    "source": "LinkedIn recommendation",
    "author": "Thiago Marins da Silva",
    "title": "Especialista em Redes | F5 BIG-IP CA Administrator | AWS Cloud | CCNA | JNCIA | NSE4 | PFSENSE | SCRUM | ANPPD",
    "date": "August 8, 2023",
    "relationship": "Thiago was Rodolfo's client",
    "rating": null,
    "lang": "PT",
    "text": "Fui aluno do Professor Rodolfo no treinamento preparatório para o exame 201 F5 Big Ip.\nJá havia realizado treinamentos para esse exame anteriormente, entretanto, as aulas do Rodolfo foram um divisor de águas em meu aprendizado de F5.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_40_4033ebae.jpg",
    "textEnglish": "I was a student of Professor Rodolfo in the preparatory training for the 201 F5 Big Ip exam.\nI had already taken training for this exam before; however, Rodolfo's classes were a turning point in my F5 learning.",
    "translationStatus": "machine"
  },
  {
    "id": "58",
    "source": "LinkedIn recommendation",
    "author": "Valdir Bignardi",
    "title": "Presidente - VBN Participações Ltda",
    "date": "April 22, 2008",
    "relationship": "Valdir managed Rodolfo directly",
    "rating": null,
    "lang": "EN",
    "text": "Rodolfo is an excellent professional. He has deep technical knowledge and great execution skills. He works well with colleagues and has also natural leading skills.\nI was always following his achievement and I can testimony that he had developed a great job, working very professionally and achieving excellent results.\nRodolfo is very motivated and cooperate a lot to develop a nice and enjoyable working environment. He has been also very loyal with his friends and colleagues as well as with the company.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_31_10_241924e6.jpg",
    "textEnglish": null,
    "translationStatus": "original"
  },
  {
    "id": "18",
    "source": "LinkedIn recommendation",
    "author": "Wagner Valério",
    "title": "Network Analyst | Sonda Ativas Data Center S/A",
    "date": "August 18, 2023",
    "relationship": "Wagner was Rodolfo's client",
    "rating": null,
    "lang": "PT",
    "text": "Realizei 4 treinamentos com esse cara, Foi de extrema importancia seus conhecimentos e destreza frente as duvidas e repostas que precisava, extremamente solícito e interessado nas dificuldade enfrentadas, recomendo sem dúvidas a presteza desse cara, e graças os seus esclarecimentos pude contornar algumas situações ao qual ja passei prestando serviço encima do produto BIGip. Obrigado Rodolfo pelo apoio e sigo disponha no que for possivel.",
    "ownerResponse": null,
    "note": null,
    "provenance": "WhatsApp_Image_20250728_at_20_22_40_b389778a.jpg",
    "textEnglish": "I did 4 training courses with this guy. His knowledge and skill were extremely important in the face of the questions and answers I needed; he was extremely helpful and genuinely interested in the difficulties I faced. I recommend this guy's helpfulness without a doubt, and thanks to his explanations I was able to work around some situations I had run into while providing services on the BIGip product. Thank you, Rodolfo, for the support, and I remain available for whatever I can help with.",
    "translationStatus": "machine"
  }
];

/** Total count of unique, displayable testimonials. */
export const TESTIMONIAL_COUNT = TESTIMONIALS.length;

/** Count of entries that have a machine translation pending review. */
export const MACHINE_TRANSLATED_COUNT = TESTIMONIALS.filter(
  (t) => t.translationStatus === "machine"
).length;

/** Sources represented, with counts (for summary display). */
export function testimonialSourceCounts(): Record<string, number> {
  return TESTIMONIALS.reduce((acc, t) => {
    acc[t.source] = (acc[t.source] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);
}

/** True if any non-English content exists (controls the translate toggle). */
export const HAS_TRANSLATABLE = TESTIMONIALS.some(
  (t) => t.translationStatus !== "original"
);
