// ============================================================================
// src/lib/tools/cert-chain-builder/golden-vectors.ts
// ----------------------------------------------------------------------------
// GOLDEN VECTORS for the certificate chain builder: byte-exact expectations
// for the structural result (verdict, order, links, findings, the ordered PEM
// lengths) of run() over frozen inputs. Any change to compute.ts that moves one
// of these is a change in behaviour and must be made on purpose.
//
// THE TEST PKI. Generated once on 2026-10-04 with OpenSSL 3.0.13 (EC P-256
// keys, `openssl ca` with fixed validity windows so the vectors are
// clock-free): a root (2020 to 2040), an issuing CA with pathLenConstraint 0
// (2024 to 2034), leaves (2026 to 2027), and the deliberate faults each vector
// names. The private keys were discarded; nothing here is trusted by anything.
//
// THE REAL CHAIN. The three certificates valid-isrgrootx1.letsencrypt.org
// served on 2026-10-04 (leaf, Let's Encrypt YR1, ISRG Root YR cross-signed by
// ISRG Root X1) and the self-signed ISRG Root X1 from
// https://letsencrypt.org/certs/isrgrootx1.pem (read 2026-10-04). The leaf
// expires on 2026-12-22; every vector judges validity at a fixed instant, so
// its expiry does not move a vector.
//
// Every expectation below was cross-checked against `openssl verify`
// (-attime at the vector's instant) on 2026-10-04: the verdicts agree.
// ============================================================================

import { run, type ChainInput, type ChainResult, type FindingCode, type Verdict } from "./compute";

/** Identifies this vector set; bump the date when a vector is deliberately changed. */
export const GOLDEN_VECTOR_SET_ID = "cert-chain-builder-golden-2026-10-04";

const ROOT = "-----BEGIN CERTIFICATE-----\nMIIByzCCAXKgAwIBAgIUKoKR0z6MgNzKCtRTCYsUy4Nl0xkwCgYIKoZIzj0EAwIw\nRDELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kxGjAYBgNV\nBAMMEUFyc2VuYWwgVGVzdCBSb290MB4XDTIwMDEwMTAwMDAwMFoXDTQwMDEwMTAw\nMDAwMFowRDELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kx\nGjAYBgNVBAMMEUFyc2VuYWwgVGVzdCBSb290MFkwEwYHKoZIzj0CAQYIKoZIzj0D\nAQcDQgAENWBI6hTqvl+cerrv0L7qTy0TSQM1w8EHVT2xhkCQuwf++aaBlK1pEWKV\nzXVM2v8z7wHGYrK81u+t+iB1GzQ1FKNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNV\nHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFPqVStodJbMRudPVo0PbqDc4WZUjMAoGCCqG\nSM49BAMCA0cAMEQCIDP39PguTl05h2AGnzIyDf0Qy3xJsZIXJI/KEueeV9byAiBn\n6EzwawPcOyrwelNr4b9arp+Dg5eAl5wmD0aLjEFAEQ==\n-----END CERTIFICATE-----";
const INTER = "-----BEGIN CERTIFICATE-----\nMIIB9zCCAZ6gAwIBAgIUX2++5NueK8Ik1gxtFOQEKvQ+daAwCgYIKoZIzj0EAwIw\nRDELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kxGjAYBgNV\nBAMMEUFyc2VuYWwgVGVzdCBSb290MB4XDTI0MDEwMTAwMDAwMFoXDTM0MDEwMTAw\nMDAwMFowTDELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kx\nIjAgBgNVBAMMGUFyc2VuYWwgVGVzdCBJc3N1aW5nIENBIDEwWTATBgcqhkjOPQIB\nBggqhkjOPQMBBwNCAARDrjMQjjY2w9K1LseXSRxX1zqrWZA8X3lPdk8pIySyqwql\n9go3s2fcbHQ8nUU6xWltmLtigJqNrahXVDsPn9axo2YwZDASBgNVHRMBAf8ECDAG\nAQH/AgEAMA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4EFgQUjL0eGIdK2j1I7Mja78CP\nHR7qcbowHwYDVR0jBBgwFoAU+pVK2h0lsxG509WjQ9uoNzhZlSMwCgYIKoZIzj0E\nAwIDRwAwRAIgerq0n06GBos+/BXmljwltSEo5xzZt4eTtFZPB+Z6uZgCIEKwV3ke\nGrHTifO5H/tNJxZnbvwuZWZYk3BfimKebE1G\n-----END CERTIFICATE-----";
const LEAF = "-----BEGIN CERTIFICATE-----\nMIICBjCCAa2gAwIBAgIUdiGi7KxEOhEqWYye9Y0+OhbHIjMwCgYIKoZIzj0EAwIw\nTDELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kxIjAgBgNV\nBAMMGUFyc2VuYWwgVGVzdCBJc3N1aW5nIENBIDEwHhcNMjYwMTAxMDAwMDAwWhcN\nMjcwMTAxMDAwMDAwWjAgMR4wHAYDVQQDDBVjaGFpbi50ZXN0LnJvbnV0ei5jb20w\nWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ91/8ZsonatGamwh+Hv1QMGZeCC6s0\nJuQb/VThLUNa2SVNnmxkAfbyVj4PwiqK0eGhU95ya0TIvUdgUGdNR0rLo4GYMIGV\nMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUF\nBwMBMCAGA1UdEQQZMBeCFWNoYWluLnRlc3Qucm9udXR6LmNvbTAdBgNVHQ4EFgQU\nQrnApp94Eea/b1VEgrovg9Fmn08wHwYDVR0jBBgwFoAUjL0eGIdK2j1I7Mja78CP\nHR7qcbowCgYIKoZIzj0EAwIDRwAwRAIgbslQQLAEcJxlQpHb9+jG1VIYw2ozmNr1\nBrkinxl9TM4CIEWZHatgCOA4vbZEBUViYMWXtZkxlYqvqaDa0tzioJv5\n-----END CERTIFICATE-----";
const SUBCA = "-----BEGIN CERTIFICATE-----\nMIIB9zCCAZ2gAwIBAgIUNWHT2SfupfjDqpYLUy3T/lfNWEYwCgYIKoZIzj0EAwIw\nTDELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kxIjAgBgNV\nBAMMGUFyc2VuYWwgVGVzdCBJc3N1aW5nIENBIDEwHhcNMjUwMTAxMDAwMDAwWhcN\nMzAwMTAxMDAwMDAwWjBGMQswCQYDVQQGEwJCUjEZMBcGA1UECgwQQXJzZW5hbCBU\nZXN0IFBLSTEcMBoGA1UEAwwTQXJzZW5hbCBUZXN0IFN1YiBDQTBZMBMGByqGSM49\nAgEGCCqGSM49AwEHA0IABG1zpFoo2spuIyNMrz4fJQZenxTNMQkuCkxM5uy17A/E\nDNYXTS4IdYH70MOfTRnHWJzBBaLmGeD3NvpIgrepbFqjYzBhMA8GA1UdEwEB/wQF\nMAMBAf8wDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBTb/Zrz/T2+JfQEF86JvFK3\nl5vlSzAfBgNVHSMEGDAWgBSMvR4Yh0raPUjsyNrvwI8dHupxujAKBggqhkjOPQQD\nAgNIADBFAiEA2TgXcxA475uCuiEk85kjOFiJpFpthEpys6gO6lWqzsECICAlNT/f\nJuSDwN3Iq/tylvmuIbrGIrHgF7UW6pw0vx+n\n-----END CERTIFICATE-----";
const LEAF2 = "-----BEGIN CERTIFICATE-----\nMIICADCCAaagAwIBAgIUW7X0PfTv5IYwOhp6Pvc/sN2Kl44wCgYIKoZIzj0EAwIw\nRjELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kxHDAaBgNV\nBAMME0Fyc2VuYWwgVGVzdCBTdWIgQ0EwHhcNMjYwMTAxMDAwMDAwWhcNMjcwMTAx\nMDAwMDAwWjAfMR0wGwYDVQQDDBRkZWVwLnRlc3Qucm9udXR6LmNvbTBZMBMGByqG\nSM49AgEGCCqGSM49AwEHA0IABC1w1P08LmzlXLNFeuWkz7GMZzy16HL8pOGLer0N\nIYWtl0AxOz3QJ6i+YBO28A9SUpCpLk2E7eu4mk3DAMd/QnGjgZgwgZUwDAYDVR0T\nAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwEwIAYD\nVR0RBBkwF4IVY2hhaW4udGVzdC5yb251dHouY29tMB0GA1UdDgQWBBSowynvAcBD\n9aLoWMKJauGI1iCkSjAfBgNVHSMEGDAWgBTb/Zrz/T2+JfQEF86JvFK3l5vlSzAK\nBggqhkjOPQQDAgNIADBFAiEArDCbjCGbnp9jnV0gfI3jDKk4xuMooP6LucKq5+vh\no9gCIAxn5m/XO3E8N6N3H7EAHeT4Vgd2iAN9DV+5GyiUek3u\n-----END CERTIFICATE-----";
const INTER_NOCERTSIGN = "-----BEGIN CERTIFICATE-----\nMIIB/jCCAaWgAwIBAgIURMse4Nu0UffcBiQ8yIXROnO4pCEwCgYIKoZIzj0EAwIw\nRDELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kxGjAYBgNV\nBAMMEUFyc2VuYWwgVGVzdCBSb290MB4XDTI0MDEwMTAwMDAwMFoXDTM0MDEwMTAw\nMDAwMFowVjELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kx\nLDAqBgNVBAMMI0Fyc2VuYWwgVGVzdCBDQSBXaXRob3V0IGtleUNlcnRTaWduMFkw\nEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEAmJnTndMUZ9F+1L2qqLpvH6NlGz1bERB\nGQ5BJ7llW/IJlfxMOnJJZ9prdrMMWPP9N0Pjd1l2NmXSHgJDxnD8XKNjMGEwDwYD\nVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0OBBYEFA8IOaOSzJo3\nwGdrTyX+hKVjaZ90MB8GA1UdIwQYMBaAFPqVStodJbMRudPVo0PbqDc4WZUjMAoG\nCCqGSM49BAMCA0cAMEQCIAsfd86BCiTtRMAhVYNFw8NECrVP0KrtF/zY+lZmQhhp\nAiAUDHKEflofFmkawfJqcGiY71/34jQsELnsLY1O0rtc2Q==\n-----END CERTIFICATE-----";
const LEAF3 = "-----BEGIN CERTIFICATE-----\nMIICFjCCAbygAwIBAgIUN+n2LM4P0a9GP66PSBZKOnkLorEwCgYIKoZIzj0EAwIw\nVjELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kxLDAqBgNV\nBAMMI0Fyc2VuYWwgVGVzdCBDQSBXaXRob3V0IGtleUNlcnRTaWduMB4XDTI2MDEw\nMTAwMDAwMFoXDTI3MDEwMTAwMDAwMFowJTEjMCEGA1UEAwwabm9jZXJ0c2lnbi50\nZXN0LnJvbnV0ei5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQG23hpSDTZ\nN4LEcFHdj1hNghKAibfPUOdGNJPKvl3WJFRJo1oPh4tPKXD+35098LH7HcuS0FHA\no328mu1u/44no4GYMIGVMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgeAMBMG\nA1UdJQQMMAoGCCsGAQUFBwMBMCAGA1UdEQQZMBeCFWNoYWluLnRlc3Qucm9udXR6\nLmNvbTAdBgNVHQ4EFgQUR7Y9HMwnyyn2OMKEwQnlHE7IADYwHwYDVR0jBBgwFoAU\nDwg5o5LMmjfAZ2tPJf6EpWNpn3QwCgYIKoZIzj0EAwIDSAAwRQIgZfDWQdZ8Wbtp\n+ef+/R24Q9MROf4xydFcj5wLjZRTyMsCIQCO/GXV2NJvqSMWUHjTThusXGchCzko\nQ1/ic0go10nUYA==\n-----END CERTIFICATE-----";
const NOTCA = "-----BEGIN CERTIFICATE-----\nMIIB7TCCAZSgAwIBAgIUcITsiNFQRIzlOwfvJtlJyS9u4ZYwCgYIKoZIzj0EAwIw\nRDELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kxGjAYBgNV\nBAMMEUFyc2VuYWwgVGVzdCBSb290MB4XDTI0MDEwMTAwMDAwMFoXDTM0MDEwMTAw\nMDAwMFowSDELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kx\nHjAcBgNVBAMMFUFyc2VuYWwgVGVzdCBOb3QgQSBDQTBZMBMGByqGSM49AgEGCCqG\nSM49AwEHA0IABOEa8wEXh3SLAeMohbv/0hGs/Y0BVgPG0nLaN68ysapRSW2m0I5Z\n+MO+sboVApVJJ85cys3MA0uAq68LMNh2Cv2jYDBeMAwGA1UdEwEB/wQCMAAwDgYD\nVR0PAQH/BAQDAgeAMB0GA1UdDgQWBBSaO11mrNCiqTpmK1VuXBrVXen3QTAfBgNV\nHSMEGDAWgBT6lUraHSWzEbnT1aND26g3OFmVIzAKBggqhkjOPQQDAgNHADBEAiAv\nVxK3DaXbmGfhNIBCA58ujyMZLcVHbFvt7nX7Rr8VOQIgbOVsPTfMm86lZcmO3Tcx\nR1Puip/NbNwVfTdRtFs20NI=\n-----END CERTIFICATE-----";
const LEAF4 = "-----BEGIN CERTIFICATE-----\nMIICAzCCAamgAwIBAgIUckKGuKvjk23YSMkyC9aYHLlhx6QwCgYIKoZIzj0EAwIw\nSDELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kxHjAcBgNV\nBAMMFUFyc2VuYWwgVGVzdCBOb3QgQSBDQTAeFw0yNjAxMDEwMDAwMDBaFw0yNzAx\nMDEwMDAwMDBaMCAxHjAcBgNVBAMMFW5vdGNhLnRlc3Qucm9udXR6LmNvbTBZMBMG\nByqGSM49AgEGCCqGSM49AwEHA0IABOE/JeA35HEFpxCilhyGEVpb+N4f4Z8tLkuT\nb8AV2vzOopfRRvkeOFnfSooUZStIJFdNCG5QPH5NwWgfpNVR4ASjgZgwgZUwDAYD\nVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwEw\nIAYDVR0RBBkwF4IVY2hhaW4udGVzdC5yb251dHouY29tMB0GA1UdDgQWBBTJWycb\nMNfh0VE/bp7C7U7W5QWB8jAfBgNVHSMEGDAWgBSaO11mrNCiqTpmK1VuXBrVXen3\nQTAKBggqhkjOPQQDAgNIADBFAiEA8gUDAu+HVXYjkUe1hCPpCLXNp1T6aNa1ivsH\nXLrd/4ICIGHpZQUXHJaNHipfr3baqqpQkYBdBYrbphh77sxHRu+u\n-----END CERTIFICATE-----";
const INTER_SHORT = "-----BEGIN CERTIFICATE-----\nMIIB+jCCAaCgAwIBAgIUR+90D7bVBUCrYW147aWkLM5LzSkwCgYIKoZIzj0EAwIw\nRDELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kxGjAYBgNV\nBAMMEUFyc2VuYWwgVGVzdCBSb290MB4XDTI0MDEwMTAwMDAwMFoXDTI2MTEwMTAw\nMDAwMFowTjELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kx\nJDAiBgNVBAMMG0Fyc2VuYWwgVGVzdCBTaG9ydC1MaXZlZCBDQTBZMBMGByqGSM49\nAgEGCCqGSM49AwEHA0IABEL0poGZ5c6f3SuDWhcRLUmyAXYWYjzW0gUVz2IGa0T0\nl0Z/qeJxklaxBlvH/5GoY/sYHns2Wv0G5h0EVk6YFKajZjBkMBIGA1UdEwEB/wQI\nMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgGGMB0GA1UdDgQWBBSsB1snaMLm8tRu2u+3\nfgxBdzBiPTAfBgNVHSMEGDAWgBT6lUraHSWzEbnT1aND26g3OFmVIzAKBggqhkjO\nPQQDAgNIADBFAiBks2yKi/AITw5y6jbVbll8mkieFjBovd+wCvPz5Y5MDQIhAO2r\nzBbRWT7R3qF7dUIiY6LTZ8rbOyHh3NlY67zHUV9P\n-----END CERTIFICATE-----";
const LEAF5 = "-----BEGIN CERTIFICATE-----\nMIICCzCCAbKgAwIBAgIUHKKK/+GepF6wYW4ib1oUpFJ6uwEwCgYIKoZIzj0EAwIw\nTjELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kxJDAiBgNV\nBAMMG0Fyc2VuYWwgVGVzdCBTaG9ydC1MaXZlZCBDQTAeFw0yNjAxMDEwMDAwMDBa\nFw0yNzAxMDEwMDAwMDBaMCMxITAfBgNVBAMMGG91dGxpdmVzLnRlc3Qucm9udXR6\nLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCtYx1HHGK7eXVF5F3BHk+QN\nUEcgkBdbiGpNYgIEBdxjuvZ2vz7e7QgYkB1zTdkylBR1mqTgVoFcNTlYRaqCW+mj\ngZgwgZUwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYI\nKwYBBQUHAwEwIAYDVR0RBBkwF4IVY2hhaW4udGVzdC5yb251dHouY29tMB0GA1Ud\nDgQWBBR3Bv2sXRLovVHPv3C89Ty+Zqx+oDAfBgNVHSMEGDAWgBSsB1snaMLm8tRu\n2u+3fgxBdzBiPTAKBggqhkjOPQQDAgNHADBEAiBsle+Id0qloDGLixpY/TfOJMKp\nQMkyp41F0NquPsX1IQIgBC033Vvr9yxSfL8l0uBb6XoO29aVoyZ6GQ0VgB+S/fs=\n-----END CERTIFICATE-----";
const INTER_NOSKI = "-----BEGIN CERTIFICATE-----\nMIIBxjCCAWygAwIBAgIUDe2YwKrKR83EGAG94KeFA1nGZcEwCgYIKoZIzj0EAwIw\nRDELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kxGjAYBgNV\nBAMMEUFyc2VuYWwgVGVzdCBSb290MB4XDTI0MDEwMTAwMDAwMFoXDTM0MDEwMTAw\nMDAwMFowWjELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kx\nMDAuBgNVBAMMJ0Fyc2VuYWwgVGVzdCBDQSBXaXRob3V0IEtleSBJZGVudGlmaWVy\nczBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABAXmMXCaP9r8i4kFQg/tDfFGx+/q\nx1F93gRJEG56x56XjSD7crVxj8atDD0VXvRKYPF5jU+PPM4xR8fz9RPshE+jJjAk\nMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMAoGCCqGSM49BAMC\nA0gAMEUCIQD/KYYeg0bZH2x5Jy7e7mIV0Dg6Pieuw8E9yJ6UvwGEnQIgflhmAH0B\noSEbNcJjrrLSRildEa26ZCRMlitnPCvLSo0=\n-----END CERTIFICATE-----";
const LEAF6 = "-----BEGIN CERTIFICATE-----\nMIIB0zCCAXmgAwIBAgIUHgloVLFQq4/hvjcUHfG2CMLI0QEwCgYIKoZIzj0EAwIw\nWjELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kxMDAuBgNV\nBAMMJ0Fyc2VuYWwgVGVzdCBDQSBXaXRob3V0IEtleSBJZGVudGlmaWVyczAeFw0y\nNjAxMDEwMDAwMDBaFw0yNzAxMDEwMDAwMDBaMCAxHjAcBgNVBAMMFW5vYWtpLnRl\nc3Qucm9udXR6LmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABC2s0J39DGLN\nguZMzthidhi1UZYx+ig5mxS/9Cc5tbJMBGsx8y4dClON2nfncvKN3I1oFK0z+syv\nYGn7JzLCBPyjVzBVMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgeAMBMGA1Ud\nJQQMMAoGCCsGAQUFBwMBMCAGA1UdEQQZMBeCFW5vYWtpLnRlc3Qucm9udXR6LmNv\nbTAKBggqhkjOPQQDAgNIADBFAiA62kqDbagU+Ze+4jx5HZRSMUjUHZMMV1uEQUs7\nCnKicwIhAOKcRMjqBtGTDowYaQaYBG/F4F8hHU2eiugIfod7LzXK\n-----END CERTIFICATE-----";
const ROOT2 = "-----BEGIN CERTIFICATE-----\nMIIBzTCCAXSgAwIBAgIUJYE5ThdgP82pZIxWEUJV2fxoi1YwCgYIKoZIzj0EAwIw\nRDELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kxGjAYBgNV\nBAMMEUFyc2VuYWwgVGVzdCBSb290MCAXDTMwMDEwMTAwMDAwMFoYDzIwNTAwMTAx\nMDAwMDAwWjBEMQswCQYDVQQGEwJCUjEZMBcGA1UECgwQQXJzZW5hbCBUZXN0IFBL\nSTEaMBgGA1UEAwwRQXJzZW5hbCBUZXN0IFJvb3QwWTATBgcqhkjOPQIBBggqhkjO\nPQMBBwNCAASnnderz5xv8oqTP6Xa1VF9bpO0Z/MLO23OiJefeGCLNr8L4zGwWq6m\nl5P7kr/5bpNvrV+gh2slzBDqjaX1+e9oo0IwQDAPBgNVHRMBAf8EBTADAQH/MA4G\nA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUCS4rBkeeQrhVkPZrYxHFBEz3iJYwCgYI\nKoZIzj0EAwIDRwAwRAIgCOLa+hgDUmUg+7W9CvF4EQGZqMkyqnPSdh0/+V8BhOAC\nIHjPEkiXwj+LBgarNGXV+mvN3oIaOGD6t47iombIxnhP\n-----END CERTIFICATE-----";
const STRAY = "-----BEGIN CERTIFICATE-----\nMIIBczCCARqgAwIBAgIUIQRFqkFxmQOSaN156yh9KmTlm6IwCgYIKoZIzj0EAwIw\nGDEWMBQGA1UEAwwNc3RyYXkuZXhhbXBsZTAeFw0yNTAxMDEwMDAwMDBaFw0zNTAx\nMDEwMDAwMDBaMBgxFjAUBgNVBAMMDXN0cmF5LmV4YW1wbGUwWTATBgcqhkjOPQIB\nBggqhkjOPQMBBwNCAAQy0/nqBG6jdrXbh0JoOMhptvWYDn6nMutrEx/4x3kM/FCQ\npmu0gBG7rVEgy9QfebWlbwK0DRWDUfy9XtNT4QIZo0IwQDAPBgNVHRMBAf8EBTAD\nAQH/MA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUBMvBICBumLDbMFHWlY12ToUO\njnwwCgYIKoZIzj0EAwIDRwAwRAIgITXKYit46MMDGKOgUM30bOk2DFLl2dT05U/T\nP+NR9+oCIDfJSdrYnWjbdy0JJK5tWcQrDiFcLd2r2MYYlYomhsuD\n-----END CERTIFICATE-----";
const INTER_PL1 = "-----BEGIN CERTIFICATE-----\nMIIB9TCCAZugAwIBAgIUOM4V2Gh9UqTpH1vHETTCzBBSd9QwCgYIKoZIzj0EAwIw\nRDELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kxGjAYBgNV\nBAMMEUFyc2VuYWwgVGVzdCBSb290MB4XDTI0MDEwMTAwMDAwMFoXDTM0MDEwMTAw\nMDAwMFowSTELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kx\nHzAdBgNVBAMMFkFyc2VuYWwgVGVzdCBQb2xpY3kgQ0EwWTATBgcqhkjOPQIBBggq\nhkjOPQMBBwNCAAQmQTo1nCsRVFvZV6cstIBYDtF3q8dhsn27QroVADpWNr9zWnnf\nkE7EsrtrsryRI14Y3Aj2Nw9STjI0hJPR1w1Ko2YwZDASBgNVHRMBAf8ECDAGAQH/\nAgEBMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUQoJMDW3p0ZtVbBUs9OFsdGWk\n3QAwHwYDVR0jBBgwFoAU+pVK2h0lsxG509WjQ9uoNzhZlSMwCgYIKoZIzj0EAwID\nSAAwRQIhAO8W3xQ2M4/63DqSVvi/KNAB3scCao6HVhlg/PE6ANXHAiAGZW7yaUJj\n+Q1Bf85FSU9D+UoROMULt58dFP7g1sZjtg==\n-----END CERTIFICATE-----";
const SUBCA2 = "-----BEGIN CERTIFICATE-----\nMIIB/TCCAaOgAwIBAgIUFk26YtCiPNcZbNZh+Zx7HZ6xrzswCgYIKoZIzj0EAwIw\nSTELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kxHzAdBgNV\nBAMMFkFyc2VuYWwgVGVzdCBQb2xpY3kgQ0EwHhcNMjUwMTAxMDAwMDAwWhcNMzAw\nMTAxMDAwMDAwWjBMMQswCQYDVQQGEwJCUjEZMBcGA1UECgwQQXJzZW5hbCBUZXN0\nIFBLSTEiMCAGA1UEAwwZQXJzZW5hbCBUZXN0IElzc3VpbmcgQ0EgMzBZMBMGByqG\nSM49AgEGCCqGSM49AwEHA0IABLk7fKApu9m5EYmKsKEaMOoC5nnTtW9R4noHKDJa\n4vQC3SG/8k6k8SLnyhLyNihXPUaxGtNCDtweXdFgxxXWjZejZjBkMBIGA1UdEwEB\n/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgGGMB0GA1UdDgQWBBQ3JXAvkGg3JP9O\naWuzSeEN3quSFTAfBgNVHSMEGDAWgBRCgkwNbenRm1VsFSz04Wx0ZaTdADAKBggq\nhkjOPQQDAgNIADBFAiEA4JmWw6KA7wbBtCwcp88FKa2n24ADX0eiLDJxi873Fv8C\nIHSjl5taH1E+Cm68txWHatN3TdeK0XA2qzOJEBWKv/P4\n-----END CERTIFICATE-----";
const LEAF7 = "-----BEGIN CERTIFICATE-----\nMIICCzCCAbKgAwIBAgIUZv1iW/4PN6isS97CJQc5Hijhva0wCgYIKoZIzj0EAwIw\nTDELMAkGA1UEBhMCQlIxGTAXBgNVBAoMEEFyc2VuYWwgVGVzdCBQS0kxIjAgBgNV\nBAMMGUFyc2VuYWwgVGVzdCBJc3N1aW5nIENBIDMwHhcNMjYwMTAxMDAwMDAwWhcN\nMjcwMTAxMDAwMDAwWjAlMSMwIQYDVQQDDBp0aHJlZS10aWVyLnRlc3Qucm9udXR6\nLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABKZjaGA3sAjpYq7VSlmbuTji\nA78ig0LoKazDV2emhXDYRNzOs8UggyKJEdbdUnN6sBRLWGhzblRuNQeq9AXdueij\ngZgwgZUwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYI\nKwYBBQUHAwEwIAYDVR0RBBkwF4IVY2hhaW4udGVzdC5yb251dHouY29tMB0GA1Ud\nDgQWBBRHnPyVnzrVSGvOE5eVXQ4BbDRncDAfBgNVHSMEGDAWgBQ3JXAvkGg3JP9O\naWuzSeEN3quSFTAKBggqhkjOPQQDAgNHADBEAiAHb2yXeJxmWHihbQS8VYbtNlb0\noQoWClqQWeX2NypPbAIgJxjQNPaNLPi1uO1FTyG1hwDbDDjRp3hFreVBuVdz6vg=\n-----END CERTIFICATE-----";
const LE_LEAF = "-----BEGIN CERTIFICATE-----\nMIIFGjCCBAKgAwIBAgISBuGpyoHQJ/W4lq6sEzghe2OUMA0GCSqGSIb3DQEBCwUA\nMDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD\nEwNZUjEwHhcNMjYwOTIzMTczODM0WhcNMjYxMjIyMTczODMzWjArMSkwJwYDVQQD\nEyB2YWxpZC1pc3Jncm9vdHgxLmxldHNlbmNyeXB0Lm9yZzCCASIwDQYJKoZIhvcN\nAQEBBQADggEPADCCAQoCggEBALMxNG7z03siE8sdhyieiYKZpdZJh+0m6RuvRXqE\nF7d7Io/aQafHH4U7ZttJipLZvwZmcxpg4XgR5Sk4JqR1jbbLbRfx7OzTBWZT/GyJ\niFtt4tds2KgOxdMZ1R3Fnr9qk60xAZEjggm10I3uI81tczLPKZUlZ9tpasOd/avh\nZl2WTWePGfHZk6hQhaDIxgLgpO3EZ7qySz0NewekNcLBjR0n1D0+yN3L4OmmfRly\nbBTg6BD+sPJ+eET47gD4cid3xdFogEIh/RrvaWCq/POeHtWgVaa2q1sEhMRojYFn\nzsz2oEKZKCGinUpYgJh0G0ytWVHprds09XJtR4Lh6PxXgZECAwEAAaOCAi4wggIq\nMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8E\nAjAAMB0GA1UdDgQWBBQOVGxtl/fiQaqYTe1/fHb4d96BkTAfBgNVHSMEGDAWgBQf\nLzW+RhSCzUCxrnksVXj699Ro+zAzBggrBgEFBQcBAQQnMCUwIwYIKwYBBQUHMAKG\nF2h0dHA6Ly95cjEuaS5sZW5jci5vcmcvMCsGA1UdEQQkMCKCIHZhbGlkLWlzcmdy\nb290eDEubGV0c2VuY3J5cHQub3JnMBMGA1UdIAQMMAowCAYGZ4EMAQIBMC4GA1Ud\nHwQnMCUwI6AhoB+GHWh0dHA6Ly95cjEuYy5sZW5jci5vcmcvMjEuY3JsMIIBDAYK\nKwYBBAHWeQIEAgSB/QSB+gD4AHYAlE5Dh/rswe+B8xkkJqgYZQHH0184AgE/cmd9\nVTcuGdgAAAGgz46ZSgAABAMARzBFAiAQ37utTVh88ya6Xi6B9nhGHnf5UYWs3cag\n5AluhXtALgIhANmYewf2LnP5bXRpyOXDc+LQFhOIq8rPWLc9oQKMDoGnAH4AJuNk\nblhpISO8ND9HJDWbN5LNJFqI2BXTkzP9mRirRyMAAAGgz46Q3wAIAAAFAEWWLL8E\nAwBHMEUCIQDPUppTk/1vpD1dDQECeNz9tjcYiF+ggls3uEsdoS3KggIgFPqFYdvJ\njvmDlH8nlLxvPGSVqEfbXbzOk3ev4FmaUzwwDQYJKoZIhvcNAQELBQADggEBACPY\nnN2RCjuTGdTQWZKDFhp5NivI9/99jTC7ufZQzVMkPJ8XMfV9Ss5NfhH+Ucj2OPOj\nlrFepg+JGy+cmQUDdBnMkP5UxwSCF+wOHUOZTFx3CzF6NynD4bW6zPgVVhSFo/KQ\nFU1ZAKWwz+DeflX21DcFAxaSuQVgORMKSIc23kTlA73g+eHrn07/tesRVzaag2dU\nNF7O1KOcfIvKox/Pv74x5R6Qz7L0MRt2px6IXJyPNs/DqvSTFE4PGqslstWIRf9D\nBjrLwNPJz2u7nxxCiYwIQguIOWdxK3u2xaGAF2SJlz40CWiy+2J3jHtMlt5JPNpe\nkWSZeRBiRN1184gETNg=\n-----END CERTIFICATE-----";
const LE_YR1 = "-----BEGIN CERTIFICATE-----\nMIIE2zCCAsOgAwIBAgIRAKICU/FfJpHAXcHOE7m8yk4wDQYJKoZIhvcNAQELBQAw\nLjELMAkGA1UEBhMCVVMxDTALBgNVBAoTBElTUkcxEDAOBgNVBAMTB1Jvb3QgWVIw\nHhcNMjUwOTAzMDAwMDAwWhcNMjgwOTAyMjM1OTU5WjAzMQswCQYDVQQGEwJVUzEW\nMBQGA1UEChMNTGV0J3MgRW5jcnlwdDEMMAoGA1UEAxMDWVIxMIIBIjANBgkqhkiG\n9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoVi8X2xCYgMXvJxNPKp/oF13UMgmPABB07VC\nLNDtoXmt9luEZNJSBV10VyT1Pz6LD8Zq1d2gc43WNl1AdRrj4sEnazbOiz0nPpmG\nBp2hui49oZtDIY6wdKeZAi5BbNU20CH6RSBBMLSQ9cXrH8dxdv4PAJ45ssGML68U\nSE3BsjC2a6cAN9L5CgXVIQi5tfNiTPoFZZ3S0OlXqLmmtdV95udWAb5b6e/F49Di\nCsH0Y00Ag72BVIb1hzynmKe+X0mERBTtsb3BwmpV9ipeBjMLoR/D9cHxHQCWoi5l\nTmXwY015J5rGelz1nZjJuxc2kioaX29XJBnhMkP531rSdG5uMwIDAQABo4HuMIHr\nMA4GA1UdDwEB/wQEAwIBhjATBgNVHSUEDDAKBggrBgEFBQcDATASBgNVHRMBAf8E\nCDAGAQH/AgEAMB0GA1UdDgQWBBQfLzW+RhSCzUCxrnksVXj699Ro+zAfBgNVHSME\nGDAWgBTe51tg0CJtQCh9Pw0B/qS1UrRRlDAyBggrBgEFBQcBAQQmMCQwIgYIKwYB\nBQUHMAKGFmh0dHA6Ly95ci5pLmxlbmNyLm9yZy8wEwYDVR0gBAwwCjAIBgZngQwB\nAgEwJwYDVR0fBCAwHjAcoBqgGIYWaHR0cDovL3lyLmMubGVuY3Iub3JnLzANBgkq\nhkiG9w0BAQsFAAOCAgEA0+zvMq3kHig1ddTmmm+RibTr9/RpX7k4buanMMRqbV/y\nIvP82zAHN3mvaw+cASuVsdpd0ikjhr4hnhJQLQOzOp2ccKrsdGOAgo0vddeISFAq\nEWEV4lmUM3vFF796up+bSgmJ1u6RupDCMxDgF8M3eLvGuj6L0lu3zkQ0KuQLnKxL\ntB0oQqn1Idg5CuuGpMvQzk29Pa3D/qHurc0EIM9SxukQuJqq63lxsYyRQFU8yMBO\nhq1w5LbfaWNRrz1uklOfI/pYkAb2E2MTZrAMQkBIE2S8Jt1F8gRc96o/xOsrgvSk\na84AisX6xq1lz1Z7jGvrnXc4TMcjxZTjiTaihcYI1JIXZiLtEMSCa5l3cu8YWd6z\ndLRQlqRdclVjuQfNHawRJ6GWlkK0QJosivTKwdBw3KxEtzGo8yMHERbsy57gP1UX\nHOMcmZYQC0gtyR3SxfenIM/MxC3Ia2Ypab/kQ/CTnlIn2KQ5JUC6NYrGCbhFN9bp\n5lKJStEwCUnLpntcrXk5XVDCNv/5RyWpRThkGOV7GetKkQ0qAY8hCzWK6oqnAhDZ\ncjlYVdWfqOw3DIOX6EDNBgAqHarRVxyF9QZdOaXSyPJ0ueD2BYJEBgaCGQ8rAaU/\nQc123V5LTXDZW4CcsPBDyhy4v+c8hClAyw/IkJlfBqxB9D+/wvIMHgECZ4ptP6o=\n-----END CERTIFICATE-----";
const LE_ROOT_YR_X1 = "-----BEGIN CERTIFICATE-----\nMIIF9DCCA9ygAwIBAgIRAPJLbRf52a18scn+p4eCaZ8wDQYJKoZIhvcNAQELBQAw\nTzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh\ncmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjYwNTEzMDAwMDAw\nWhcNMzIwOTAyMjM1OTU5WjAuMQswCQYDVQQGEwJVUzENMAsGA1UEChMESVNSRzEQ\nMA4GA1UEAxMHUm9vdCBZUjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB\nANvGJnN78CTJdWL3+eGfsLN5TrNBJs+VH9hRXqRbwxu9sGNiB0BD1fcOxbSUQCJI\nM1xE13Db+5Cw1w0s0EBYsvuIP/6joF0w8cuImbgR1OGgYbSQ4OpzI+DG8SGuTlcE\n873OCS+kh3srlo6vl43M5OJg4Aeo1sfHp6kTJDoIiFBNJAY+OKfX/FUvYKuhjT+n\no49lmqmupSBI5PkBQiqrEGtWU5uxU/cQWHGu8jSjFBznZqvbNPLMXMLFxCb3WTfr\nJBXXjqvWG+v4bjzxjjeAtOlU7qarRDvNOyAuQYLln904M+faKx8hnLCpJ15ZqaEg\ncNlY+9MMWcC5yvL2A2j3l9+2buggZX+dOE91zYmIdawTvSZuVvlbRrAlLxIB6pwM\nBjneXCjYQ8+3BCCjssbSNpZU3hTcBDdhfAlEDlYr6pEatnMdmDT5BqnKC92bd0Eh\nM1fbLHioLccLCuievT8ZkPhZrq7Mii7gNXAcUEAR8+lzYal+9zTg7C5DALyVOeG/\nCqfRAMn1KSHCR0NSA6P8tn/mGRlnCct5rtVCLnVySVpU6H1qGg3DgTOuskf8eahT\nMiYbI5ezPJmO5ertalskQ1utp74+eDy92PI4ftHKTbq9IWhH4YZKh3WnJEIt+oQv\nlYZbY8tpEroKrFB6PFGzrJIDRyts4HqvuH52RFj2zv/BAgMBAAGjgeswgegwDgYD\nVR0PAQH/BAQDAgEGMBMGA1UdJQQMMAoGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMB\nAf8wHQYDVR0OBBYEFN7nW2DQIm1AKH0/DQH+pLVStFGUMB8GA1UdIwQYMBaAFHm0\nWeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcwAoYW\naHR0cDovL3gxLmkubGVuY3Iub3JnLzATBgNVHSAEDDAKMAgGBmeBDAECATAnBgNV\nHR8EIDAeMBygGqAYhhZodHRwOi8veDEuYy5sZW5jci5vcmcvMA0GCSqGSIb3DQEB\nCwUAA4ICAQA8spSI95KKfn2W6GMmDpHBJSPaLbsS3W93cijJCRCYAc1fsJgL1FIL\n7C0C9ecPOdcwB2fi0Dk2p94j9iTJCxmt5CFSKLRWwnXT2MMSXexVxqoVB79BdWPx\nVXETkVme/qYSAuKVHh5Ps+5BixgmwS1JkjSAc+MfrUbNssVEEnH0aEiAh+rotXAV\nJSP/Ye7LJPEwD9DWG72vVWbhAcuOf5OLjz57Ctk7MgQHynZ7+PlHJtajroCaIbtC\nr6tcZZaAwUQm+jQyeWdV+2hv9deOYFmKeQyjjcSrN5Nadrw+L9DZJLbA1HqeNvLh\nBgqpP0fvJq2N6EtD574N6eMI7uMsJTnji2UDz9el5XLSv9fqJMuDQtYVb2oTNoKp\noUqhxPVC0aq4eG5MESaIdn8b5ZGSSeAJLMHXljEdlNza+ncfkviXk1POLnnFdvx8\n/gk6M374WbLWFXw8N141B/Rl/tINGfl1TxOIiqtiMYkL02RSGb1kq34BL9NPP27z\nRGMuHGnzS3hFIrRTfKxrzUZ9RzQWzEG3K6fJ3r2nqSltkeytis9DIBoFY9VmVyjL\nM71DMi+y1+TRSJVClEMwvA4yL++7q9XZx5r5wBRWB4kQTKH5qyoZnDw7iiuh1lID\nyDFx8r7i9vIJU5HS3moZLkYWAOilMaV9N56A9Bgb6dNcHkvg3NoaYA==\n-----END CERTIFICATE-----";
const ISRG_ROOT_X1 = "-----BEGIN CERTIFICATE-----\nMIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw\nTzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh\ncmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4\nWhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu\nZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY\nMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc\nh77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+\n0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U\nA5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW\nT8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH\nB5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC\nB5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv\nKBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn\nOlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn\njh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw\nqHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI\nrU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV\nHRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq\nhkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL\nubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ\n3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK\nNFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5\nORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur\nTkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC\njNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc\noyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq\n4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA\nmRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d\nemyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=\n-----END CERTIFICATE-----";

/** What a vector pins: enough of the result to catch any behavioural change. */
export interface ChainExpect {
  verdict: Verdict;
  /** 1-based input positions of the path, target first. */
  order: number[];
  endsAtSelfSigned: boolean;
  missingIssuer: string | null;
  extras: number[];
  /** Every finding as "severity:code@at>other=detail" (1-based positions, "-" for none). */
  findings: string[];
  /** Lengths of the two ordered PEM strings. */
  pemLengths: [number, number];
}

export interface ChainGoldenVector {
  id: string;
  why: string;
  input: ChainInput;
  expect: ChainExpect;
}

/** Projects a result onto the pinned shape. */
export function pin(r: ChainResult): ChainExpect {
  const pos = (i: number | null) => (i === null ? "-" : String(i + 1));
  return {
    verdict: r.verdict,
    order: r.order.map((i) => i + 1),
    endsAtSelfSigned: r.endsAtSelfSigned,
    missingIssuer: r.missingIssuer?.name ?? null,
    extras: r.extras.map((i) => i + 1),
    findings: r.findings.map((f) => `${f.severity}:${f.code}@${pos(f.at)}>${pos(f.other)}=${f.detail ?? "-"}`),
    pemLengths: [r.orderedPem.withoutRoot.length, r.orderedPem.withRoot.length],
  };
}

export const GOLDEN_VECTORS: ChainGoldenVector[] = [
  // Leaf, intermediate, root, already in order: complete; the root is included.
  { id: "in-order-with-root", why: "Leaf, intermediate, root, already in order: complete; the root is included.", input: { text: LEAF + "\n" + INTER + "\n" + ROOT, now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"complete","order":[1,2,3],"endsAtSelfSigned":true,"missingIssuer":null,"extras":[],"findings":["info:root-included@3>-=-"],"pemLengths":[1501,2185]} },
  // Root first, then leaf, then intermediate: the same chain, reordered; order-differs says so.
  { id: "shuffled", why: "Root first, then leaf, then intermediate: the same chain, reordered; order-differs says so.", input: { text: ROOT + "\n" + LEAF + "\n" + INTER, now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"complete","order":[2,3,1],"endsAtSelfSigned":true,"missingIssuer":null,"extras":[],"findings":["info:order-differs@->-=2 > 3 > 1","info:root-included@1>-=-"],"pemLengths":[1501,2185]} },
  // Leaf and intermediate only: sound as far as it goes and stops at a CA whose issuer is absent, the normal TLS configuration.
  { id: "anchor-omitted", why: "Leaf and intermediate only: sound as far as it goes and stops at a CA whose issuer is absent, the normal TLS configuration.", input: { text: LEAF + "\n" + INTER, now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"anchor-omitted","order":[1,2],"endsAtSelfSigned":false,"missingIssuer":"CN=Arsenal Test Root, O=Arsenal Test PKI, C=BR","extras":[],"findings":["warning:issuer-not-found@2>-=CN=Arsenal Test Root, O=Arsenal Test PKI, C=BR","info:root-omitted@2>-=CN=Arsenal Test Root, O=Arsenal Test PKI, C=BR"],"pemLengths":[1501,1501]} },
  // A leaf alone: incomplete, the issuing CA is named as missing.
  { id: "leaf-alone", why: "A leaf alone: incomplete, the issuing CA is named as missing.", input: { text: LEAF, now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"incomplete","order":[1],"endsAtSelfSigned":false,"missingIssuer":"CN=Arsenal Test Issuing CA 1, O=Arsenal Test PKI, C=BR","extras":[],"findings":["error:issuer-not-found@1>-=CN=Arsenal Test Issuing CA 1, O=Arsenal Test PKI, C=BR"],"pemLengths":[760,760]} },
  // A sub-CA under an intermediate with pathLenConstraint 0: RFC 5280 s6.1.4 (l) fails on the sub-CA.
  { id: "pathlen-exceeded", why: "A sub-CA under an intermediate with pathLenConstraint 0: RFC 5280 s6.1.4 (l) fails on the sub-CA.", input: { text: LEAF2 + "\n" + SUBCA + "\n" + INTER + "\n" + ROOT, now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"invalid","order":[1,2,3,4],"endsAtSelfSigned":true,"missingIssuer":null,"extras":[],"findings":["error:pathlen-exceeded@2>3=0","info:root-included@4>-=-"],"pemLengths":[2234,2918]} },
  // An issuing CA whose keyUsage lacks keyCertSign: s6.1.4 (n).
  { id: "issuer-missing-keycertsign", why: "An issuing CA whose keyUsage lacks keyCertSign: s6.1.4 (n).", input: { text: LEAF3 + "\n" + INTER_NOCERTSIGN + "\n" + ROOT, now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"invalid","order":[1,2,3],"endsAtSelfSigned":true,"missingIssuer":null,"extras":[],"findings":["error:issuer-missing-keycertsign@2>1=-","info:root-included@3>-=-"],"pemLengths":[1538,2222]} },
  // An issuer with basicConstraints cA FALSE: s6.1.4 (k), and keyCertSign is absent too.
  { id: "issuer-not-ca", why: "An issuer with basicConstraints cA FALSE: s6.1.4 (k), and keyCertSign is absent too.", input: { text: LEAF4 + "\n" + NOTCA + "\n" + ROOT, now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"invalid","order":[1,2,3],"endsAtSelfSigned":true,"missingIssuer":null,"extras":[],"findings":["error:issuer-not-ca@2>1=-","error:issuer-missing-keycertsign@2>1=-","info:root-included@3>-=-"],"pemLengths":[1485,2169]} },
  // An intermediate that expires before its leaf, judged while both are valid: a warning naming the date.
  { id: "issuer-expires-first", why: "An intermediate that expires before its leaf, judged while both are valid: a warning naming the date.", input: { text: LEAF5 + "\n" + INTER_SHORT + "\n" + ROOT, now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"complete-with-warnings","order":[1,2,3],"endsAtSelfSigned":true,"missingIssuer":null,"extras":[],"findings":["warning:issuer-expires-before-subject@2>1=2026-11-01T00:00:00Z","info:root-included@3>-=-"],"pemLengths":[1513,2197]} },
  // The same chain judged after the intermediate's notAfter: expired, invalid.
  { id: "issuer-expired-at-instant", why: "The same chain judged after the intermediate's notAfter: expired, invalid.", input: { text: LEAF5 + "\n" + INTER_SHORT + "\n" + ROOT, now: "2026-12-01T12:00:00Z" }, expect: {"verdict":"invalid","order":[1,2,3],"endsAtSelfSigned":true,"missingIssuer":null,"extras":[],"findings":["error:cert-expired@2>-=2026-11-01T00:00:00Z","warning:issuer-expires-before-subject@2>1=2026-11-01T00:00:00Z","info:root-included@3>-=-"],"pemLengths":[1513,2197]} },
  // No key identifiers on either side: the link is made by name, and said to be.
  { id: "name-only-chaining", why: "No key identifiers on either side: the link is made by name, and said to be.", input: { text: LEAF6 + "\n" + INTER_NOSKI + "\n" + ROOT, now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"complete","order":[1,2,3],"endsAtSelfSigned":true,"missingIssuer":null,"extras":[],"findings":["info:issuer-matched-by-name-only@1>2=-","info:issuer-matched-by-name-only@2>3=-","info:root-included@3>-=-"],"pemLengths":[1367,2051]} },
  // A root with the same name but a different key: the AKI does not match its SKI, so it is not the issuer; incomplete, and the mismatch is named.
  { id: "rolled-over-root-by-name", why: "A root with the same name but a different key: the AKI does not match its SKI, so it is not the issuer; incomplete, and the mismatch is named.", input: { text: LEAF + "\n" + INTER + "\n" + ROOT2, now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"incomplete","order":[1,2],"endsAtSelfSigned":false,"missingIssuer":"CN=Arsenal Test Root, O=Arsenal Test PKI, C=BR","extras":[3],"findings":["error:issuer-name-matches-key-differs@2>3=-","info:root-omitted@2>-=CN=Arsenal Test Root, O=Arsenal Test PKI, C=BR","info:extra-certificate@3>-=-"],"pemLengths":[1501,1501]} },
  // Both roots present: the AKI picks the right one; the other is extra.
  { id: "two-roots-same-name", why: "Both roots present: the AKI picks the right one; the other is extra.", input: { text: LEAF + "\n" + INTER + "\n" + ROOT2 + "\n" + ROOT, now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"complete","order":[1,2,4],"endsAtSelfSigned":true,"missingIssuer":null,"extras":[3],"findings":["info:extra-certificate@3>-=-","info:root-included@4>-=-"],"pemLengths":[1501,2185]} },
  // pathLenConstraint 1 above a pathLenConstraint 0 sub-CA: within the limit, complete.
  { id: "three-tier-within-pathlen", why: "pathLenConstraint 1 above a pathLenConstraint 0 sub-CA: within the limit, complete.", input: { text: LEAF7 + "\n" + SUBCA2 + "\n" + INTER_PL1 + "\n" + ROOT, now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"complete","order":[1,2,3,4],"endsAtSelfSigned":true,"missingIssuer":null,"extras":[],"findings":["info:root-included@4>-=-"],"pemLengths":[2258,2942]} },
  // The intermediate pasted twice and an unrelated self-signed certificate: one duplicate, one extra, the chain unaffected.
  { id: "duplicate-and-stray", why: "The intermediate pasted twice and an unrelated self-signed certificate: one duplicate, one extra, the chain unaffected.", input: { text: LEAF + "\n" + INTER + "\n" + INTER + "\n" + STRAY + "\n" + ROOT, now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"complete","order":[1,2,5],"endsAtSelfSigned":true,"missingIssuer":null,"extras":[4],"findings":["info:duplicate-certificate@3>2=-","info:extra-certificate@4>-=-","info:root-included@5>-=-"],"pemLengths":[1501,2185]} },
  // A self-signed root alone: nothing to build; described, not faulted.
  { id: "root-alone", why: "A self-signed root alone: nothing to build; described, not faulted.", input: { text: ROOT, now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"complete","order":[1],"endsAtSelfSigned":true,"missingIssuer":null,"extras":[],"findings":["info:single-self-signed@1>-=-","info:target-is-ca@1>-=-"],"pemLengths":[683,683]} },
  // The chain valid-isrgrootx1.letsencrypt.org served on 2026-10-04: leaf, YR1, and ISRG Root YR cross-signed by ISRG Root X1; X1 itself omitted, as a trust anchor may be.
  { id: "lets-encrypt-served-chain", why: "The chain valid-isrgrootx1.letsencrypt.org served on 2026-10-04: leaf, YR1, and ISRG Root YR cross-signed by ISRG Root X1; X1 itself omitted, as a trust anchor may be.", input: { text: LE_LEAF + "\n" + LE_YR1 + "\n" + LE_ROOT_YR_X1, now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"anchor-omitted","order":[1,2,3],"endsAtSelfSigned":false,"missingIssuer":"CN=ISRG Root X1, O=Internet Security Research Group, C=US","extras":[],"findings":["warning:issuer-not-found@3>-=CN=ISRG Root X1, O=Internet Security Research Group, C=US","info:revocation-pointers@->-=3","info:subject-predates-issuer@2>3=2026-05-13T00:00:00Z","info:root-omitted@3>-=CN=ISRG Root X1, O=Internet Security Research Group, C=US"],"pemLengths":[5699,5699]} },
  // The same chain with ISRG Root X1 pasted too: complete, four certificates, root included.
  { id: "lets-encrypt-with-x1", why: "The same chain with ISRG Root X1 pasted too: complete, four certificates, root included.", input: { text: LE_LEAF + "\n" + LE_YR1 + "\n" + LE_ROOT_YR_X1 + "\n" + ISRG_ROOT_X1, now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"complete","order":[1,2,3,4],"endsAtSelfSigned":true,"missingIssuer":null,"extras":[],"findings":["info:revocation-pointers@->-=3","info:subject-predates-issuer@2>3=2026-05-13T00:00:00Z","info:root-included@4>-=-"],"pemLengths":[5699,7638]} },
  // No instant given: the windows are reported, nothing is judged expired.
  { id: "no-instant", why: "No instant given: the windows are reported, nothing is judged expired.", input: { text: LEAF + "\n" + INTER + "\n" + ROOT }, expect: {"verdict":"complete","order":[1,2,3],"endsAtSelfSigned":true,"missingIssuer":null,"extras":[],"findings":["info:root-included@3>-=-"],"pemLengths":[1501,2185]} },
  // Empty input.
  { id: "error-empty", why: "Empty input.", input: { text: "", now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"unreadable","order":[],"endsAtSelfSigned":false,"missingIssuer":null,"extras":[],"findings":["error:input-empty@->-=-"],"pemLengths":[0,0]} },
  // Text without a PEM block.
  { id: "error-no-certificates", why: "Text without a PEM block.", input: { text: "not a certificate", now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"unreadable","order":[],"endsAtSelfSigned":false,"missingIssuer":null,"extras":[],"findings":["error:input-no-certificates@->-=-"],"pemLengths":[0,0]} },
  // A corrupt block among good ones: reported by position, the chain still built from the rest.
  { id: "error-one-unreadable-block", why: "A corrupt block among good ones: reported by position, the chain still built from the rest.", input: { text: "-----BEGIN CERTIFICATE-----\nAAAA\n-----END CERTIFICATE-----" + "\n" + LEAF + "\n" + INTER + "\n" + ROOT, now: "2026-10-04T12:00:00Z" }, expect: {"verdict":"complete","order":[1,2,3],"endsAtSelfSigned":true,"missingIssuer":null,"extras":[],"findings":["error:cert-unreadable@->-=1:structure","info:root-included@3>-=-"],"pemLengths":[1501,2185]} },
];

/** Verifies every vector; the build's run-golden-vectors reads this shape. */
export function verifyVectors(): { setId: string; total: number; passed: number; failures: { id: string; expected: string; actual: string }[] } {
  const failures: { id: string; expected: string; actual: string }[] = [];
  for (const v of GOLDEN_VECTORS) {
    const expected = JSON.stringify(v.expect);
    const actual = JSON.stringify(pin(run(v.input)));
    if (expected !== actual) failures.push({ id: v.id, expected, actual });
  }
  return { setId: GOLDEN_VECTOR_SET_ID, total: GOLDEN_VECTORS.length, passed: GOLDEN_VECTORS.length - failures.length, failures };
}

// Re-exported so the manifest can describe the codes a vector exercises.
export const FINDING_CODES_COVERED: FindingCode[] = Array.from(
  new Set(GOLDEN_VECTORS.flatMap((v) => v.expect.findings.map((f) => f.split("@")[0].split(":")[1] as FindingCode))),
);
