// ============================================================================
// src/lib/tools/dig-command-builder/golden-vectors.ts
// ----------------------------------------------------------------------------
// GOLDEN VECTORS for the dig command builder: byte-exact commands, finding
// codes and the query summary over frozen intents. The assembler's canonical
// token order is part of the contract, so a reordering is a behaviour change
// and must be made on purpose. The first five vectors are the five examples
// of the BIND 9 dig manual (read 2026-10-04), written in this builder's order.
// GENERATED by the engine; regenerate rather than hand-edit.
// ============================================================================

import { run, type DigInput, type DigResult } from "./compute";

/** Identifies this vector set; bump the date when a vector is deliberately changed. */
export const GOLDEN_VECTOR_SET_ID = "dig-command-builder-golden-2026-10-04";

/** The pinned projection of a result: the command, the finding codes and the summary the page shows. */
export function pin(r: DigResult) {
  return {
    ok: r.ok,
    command: r.command,
    findings: r.findings.map((f) => `${f.severity}:${f.code}`),
    effective: r.effective ? { q: `${r.effective.question.name} ${r.effective.question.type} ${r.effective.question.klass}`, via: `${r.effective.transport}:${r.effective.port}`, rd: r.effective.recursionDesired, do: r.effective.dnssecOk, cd: r.effective.checkingDisabled, edns: r.effective.edns, bufsize: r.effective.bufsize, cookie: r.effective.cookie, fallback: r.effective.tcpFallback } : null,
  };
}

/** One vector: a frozen intent and the pinned result. */
export interface DigGoldenVector {
  id: string;
  why: string;
  input: DigInput;
  expect: ReturnType<typeof pin>;
}

/** The vectors. */
export const VECTORS: DigGoldenVector[] = [
  // The manual's first example: only the addresses for example.com.
  { id: "manual-short", why: "The manual's first example: only the addresses for example.com.", input: {"name":"example.com","output":"short"}, expect: {"ok":true,"command":"dig example.com +short","findings":[],"effective":{"q":"example.com A IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // The manual's second example: ask f.gtld-servers.net for example.com.
  { id: "manual-at-server", why: "The manual's second example: ask f.gtld-servers.net for example.com.", input: {"name":"example.com","server":"f.gtld-servers.net"}, expect: {"ok":true,"command":"dig @f.gtld-servers.net example.com","findings":[],"effective":{"q":"example.com A IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // The manual's third example, the TXT record; the type is written after the name in this builder's order.
  { id: "manual-txt", why: "The manual's third example, the TXT record; the type is written after the name in this builder's order.", input: {"name":"example.com","type":"txt"}, expect: {"ok":true,"command":"dig example.com TXT","findings":[],"effective":{"q":"example.com TXT IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // The manual's fourth example: a reverse lookup; dig derives 1.2.0.192.in-addr.arpa, PTR, IN.
  { id: "manual-reverse", why: "The manual's fourth example: a reverse lookup; dig derives 1.2.0.192.in-addr.arpa, PTR, IN.", input: {"reverse":"192.0.2.1"}, expect: {"ok":true,"command":"dig -x 192.0.2.1","findings":[],"effective":{"q":"1.2.0.192.in-addr.arpa PTR IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // The manual's fifth example: +noall then +answer, in that order, for records only.
  { id: "manual-noall-answer", why: "The manual's fifth example: +noall then +answer, in that order, for records only.", input: {"name":"example.com","output":"answer"}, expect: {"ok":true,"command":"dig example.com +noall +answer","findings":[],"effective":{"q":"example.com A IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // The page's example: a documentation-range resolver, MX, the DO bit set, records printed multi-line.
  { id: "example-mx-dnssec", why: "The page's example: a documentation-range resolver, MX, the DO bit set, records printed multi-line.", input: {"name":"example.com","server":"192.0.2.53","type":"MX","dnssec":true,"multiline":true}, expect: {"ok":true,"command":"dig @192.0.2.53 example.com MX +dnssec +multiline","findings":[],"effective":{"q":"example.com MX IN","via":"UDP:53","rd":true,"do":true,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // +trace already sets +dnssec and disables recursion, and @server then affects only the root query: three infos.
  { id: "trace-redundancies", why: "+trace already sets +dnssec and disables recursion, and @server then affects only the root query: three infos.", input: {"name":"example.com","server":"192.0.2.53","trace":true,"dnssec":true,"norecurse":true}, expect: {"ok":true,"command":"dig @192.0.2.53 example.com +trace +norecurse +dnssec","findings":["info:trace-sets-dnssec","info:redundant-norecurse","info:trace-server-root-only"],"effective":{"q":"example.com A IN","via":"UDP:53","rd":false,"do":true,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // +nssearch disables recursion itself; RD is clear in the summary.
  { id: "nssearch", why: "+nssearch disables recursion itself; RD is clear in the summary.", input: {"name":"example.com","nssearch":true}, expect: {"ok":true,"command":"dig example.com +nssearch","findings":[],"effective":{"q":"example.com A IN","via":"UDP:53","rd":false,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // A zone transfer without @server: dig would ask the local resolvers; AXFR always uses TCP, so +tcp is a no-op.
  { id: "axfr-no-server", why: "A zone transfer without @server: dig would ask the local resolvers; AXFR always uses TCP, so +tcp is a no-op.", input: {"name":"example.com","type":"AXFR","transport":"tcp"}, expect: {"ok":true,"command":"dig example.com AXFR +tcp","findings":["warning:transfer-needs-server","info:axfr-tcp","info:tcp-default-for-type"],"effective":{"q":"example.com AXFR IN","via":"TCP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":false}} },
  // IXFR is written ixfr=N with the client's serial; its default transport is TCP.
  { id: "ixfr-serial", why: "IXFR is written ixfr=N with the client's serial; its default transport is TCP.", input: {"name":"example.com","type":"IXFR","ixfrSerial":"2026100401","server":"ns1.example.com"}, expect: {"ok":true,"command":"dig @ns1.example.com example.com ixfr=2026100401","findings":[],"effective":{"q":"example.com ixfr=2026100401 IN","via":"TCP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":false}} },
  // IXFR without a serial cannot be built.
  { id: "ixfr-missing-serial", why: "IXFR without a serial cannot be built.", input: {"name":"example.com","type":"IXFR"}, expect: {"ok":false,"command":"","findings":["error:ixfr-needs-serial"],"effective":null} },
  // ANY: a warning that servers may answer minimally (RFC 8482); default transport TCP.
  { id: "any-minimal", why: "ANY: a warning that servers may answer minimally (RFC 8482); default transport TCP.", input: {"name":"example.com","type":"ANY"}, expect: {"ok":true,"command":"dig example.com ANY","findings":["warning:any-minimal"],"effective":{"q":"example.com ANY IN","via":"TCP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":false}} },
  // +bufsize=400 is treated as 512 by the server (RFC 6891 6.2.3): a warning.
  { id: "bufsize-under-512", why: "+bufsize=400 is treated as 512 by the server (RFC 6891 6.2.3): a warning.", input: {"name":"example.com","bufsize":"400"}, expect: {"ok":true,"command":"dig example.com +bufsize=400","findings":["warning:bufsize-under-512"],"effective":{"q":"example.com A IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":400,"cookie":true,"fallback":true}} },
  // The DNS Flag Day 2020 size, with the server identifying itself.
  { id: "bufsize-1232", why: "The DNS Flag Day 2020 size, with the server identifying itself.", input: {"name":"example.com","bufsize":"1232","nsid":true}, expect: {"ok":true,"command":"dig example.com +bufsize=1232 +nsid","findings":[],"effective":{"q":"example.com A IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":1232,"cookie":true,"fallback":true}} },
  // Above 65535 the manual's range is exceeded: an error.
  { id: "bufsize-too-large", why: "Above 65535 the manual's range is exceeded: an error.", input: {"name":"example.com","bufsize":"70000"}, expect: {"ok":false,"command":"","findings":["error:bad-bufsize"],"effective":null} },
  // +noedns against options that live in the OPT record: +noedns is not written and a warning says why.
  { id: "noedns-conflict", why: "+noedns against options that live in the OPT record: +noedns is not written and a warning says why.", input: {"name":"example.com","noedns":true,"dnssec":true}, expect: {"ok":true,"command":"dig example.com +dnssec","findings":["warning:noedns-conflict"],"effective":{"q":"example.com A IN","via":"UDP:53","rd":true,"do":true,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // +noedns alone: a query with no OPT record and therefore no cookie.
  { id: "noedns-plain", why: "+noedns alone: a query with no OPT record and therefore no cookie.", input: {"name":"example.com","noedns":true}, expect: {"ok":true,"command":"dig example.com +noedns","findings":[],"effective":{"q":"example.com A IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":false,"bufsize":null,"cookie":false,"fallback":true}} },
  // +subnet=0 asks the resolver not to use the client's address (RFC 7871).
  { id: "subnet-zero", why: "+subnet=0 asks the resolver not to use the client's address (RFC 7871).", input: {"name":"example.com","subnet":"0.0.0.0/0"}, expect: {"ok":true,"command":"dig example.com +subnet=0","findings":["info:subnet-zero"],"effective":{"q":"example.com A IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // DNS over TLS: brackets around the IPv6 literal are stripped, and -p 853 is the transport's default so it is not written.
  { id: "tls-default-port", why: "DNS over TLS: brackets around the IPv6 literal are stripped, and -p 853 is the transport's default so it is not written.", input: {"name":"example.com","server":"[2001:db8::53]","transport":"tls","port":"853"}, expect: {"ok":true,"command":"dig @2001:db8::53 example.com +tls","findings":["info:server-brackets","info:port-default"],"effective":{"q":"example.com A IN","via":"TLS:853","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":false}} },
  // DNS over HTTPS with the endpoint written out.
  { id: "https-endpoint", why: "DNS over HTTPS with the endpoint written out.", input: {"name":"example.com","server":"dns.example.net","transport":"https","httpsEndpoint":"/dns-query"}, expect: {"ok":true,"command":"dig @dns.example.net example.com +https=/dns-query","findings":[],"effective":{"q":"example.com A IN","via":"HTTPS:443","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":false}} },
  // +ignore only matters over UDP: an info when the transport is TCP.
  { id: "tcp-ignore-no-udp", why: "+ignore only matters over UDP: an info when the transport is TCP.", input: {"name":"example.com","transport":"tcp","ignore":true}, expect: {"ok":true,"command":"dig example.com +tcp +ignore","findings":["info:ignore-no-udp"],"effective":{"q":"example.com A IN","via":"TCP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":false}} },
  // -4 with an IPv6 server literal cannot connect: a warning.
  { id: "ipv-mismatch", why: "-4 with an IPv6 server literal cannot connect: a warning.", input: {"name":"example.com","server":"2001:db8::53","ipv":"4"}, expect: {"ok":true,"command":"dig @2001:db8::53 -4 example.com","findings":["warning:ipv-mismatch"],"effective":{"q":"example.com A IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // A non-standard port is written with -p.
  { id: "port-nonstandard", why: "A non-standard port is written with -p.", input: {"name":"example.com","server":"192.0.2.53","port":"5353"}, expect: {"ok":true,"command":"dig @192.0.2.53 -p 5353 example.com","findings":[],"effective":{"q":"example.com A IN","via":"UDP:5353","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // A name that is also a class or type mnemonic (the ch top-level domain) goes through -q.
  { id: "q-disambiguates", why: "A name that is also a class or type mnemonic (the ch top-level domain) goes through -q.", input: {"name":"ch","type":"NS"}, expect: {"ok":true,"command":"dig -q ch NS","findings":["info:q-disambiguates"],"effective":{"q":"ch NS IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // SRV owner names carry underscores.
  { id: "srv-underscores", why: "SRV owner names carry underscores.", input: {"name":"_sip._tcp.example.com","type":"SRV"}, expect: {"ok":true,"command":"dig _sip._tcp.example.com SRV","findings":[],"effective":{"q":"_sip._tcp.example.com SRV IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // An asterisk is quoted for the shell.
  { id: "wildcard-quoted", why: "An asterisk is quoted for the shell.", input: {"name":"*.example.com","type":"TXT"}, expect: {"ok":true,"command":"dig '*.example.com' TXT","findings":[],"effective":{"q":"*.example.com TXT IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // The root zone's name servers.
  { id: "root-ns", why: "The root zone's name servers.", input: {"name":".","type":"NS"}, expect: {"ok":true,"command":"dig . NS","findings":[],"effective":{"q":". NS IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // A CHAOS-class TXT query: the class is written after the type.
  { id: "chaos-version", why: "A CHAOS-class TXT query: the class is written after the type.", input: {"name":"version.bind","type":"TXT","klass":"CH","server":"192.0.2.53"}, expect: {"ok":true,"command":"dig @192.0.2.53 version.bind TXT CH","findings":[],"effective":{"q":"version.bind TXT CH","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // TYPE65 is written by its mnemonic, HTTPS; an unassigned number stays TYPEnn.
  { id: "type-number", why: "TYPE65 is written by its mnemonic, HTTPS; an unassigned number stays TYPEnn.", input: {"name":"example.com","type":"TYPE65"}, expect: {"ok":true,"command":"dig example.com HTTPS","findings":[],"effective":{"q":"example.com HTTPS IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // An unassigned type number is passed through as TYPEnn.
  { id: "type-unassigned", why: "An unassigned type number is passed through as TYPEnn.", input: {"name":"example.com","type":"TYPE65280"}, expect: {"ok":true,"command":"dig example.com TYPE65280","findings":[],"effective":{"q":"example.com TYPE65280 IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // A reverse lookup of an IPv6 address: dig derives the 32-nibble ip6.arpa name; a name typed alongside is ignored.
  { id: "reverse-ipv6", why: "A reverse lookup of an IPv6 address: dig derives the 32-nibble ip6.arpa name; a name typed alongside is ignored.", input: {"reverse":"2001:db8::1","name":"ignored.example"}, expect: {"ok":true,"command":"dig -x 2001:db8::1","findings":["info:reverse-ignores-name"],"effective":{"q":"1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa PTR IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // +timeout=0 and +tries=0 are silently raised to 1 by dig: two warnings.
  { id: "timing-clamps", why: "+timeout=0 and +tries=0 are silently raised to 1 by dig: two warnings.", input: {"name":"example.com","timeout":"0","tries":"0","retry":"1"}, expect: {"ok":true,"command":"dig example.com +timeout=0 +tries=0 +retry=1","findings":["warning:timeout-min","warning:tries-min"],"effective":{"q":"example.com A IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // +identify only shows the answering server with +short: an info, and nothing emitted.
  { id: "identify-needs-short", why: "+identify only shows the answering server with +short: an info, and nothing emitted.", input: {"name":"example.com","identify":true}, expect: {"ok":true,"command":"dig example.com","findings":["info:identify-needs-short"],"effective":{"q":"example.com A IN","via":"UDP:53","rd":true,"do":false,"cd":false,"edns":true,"bufsize":null,"cookie":true,"fallback":true}} },
  // Every remaining option at once, in the canonical order.
  { id: "everything", why: "Every remaining option at once, in the canonical order.", input: {"name":"example.com","type":"SOA","server":"2001:db8::53","source":"2001:db8::10#5300","keyfile":"/etc/dig/key.conf","norc":true,"ipv":"6","cd":true,"nocookie":true,"subnet":"198.51.100.0/24","timeout":"3","tries":"2","retry":"1","output":"yaml","ttlunits":true,"qr":true}, expect: {"ok":true,"command":"dig @2001:db8::53 -r -6 -b 2001:db8::10#5300 -k /etc/dig/key.conf example.com SOA +cd +nocookie +subnet=198.51.100.0/24 +timeout=3 +tries=2 +retry=1 +yaml +ttlunits +qr","findings":["info:tsig-keyfile"],"effective":{"q":"example.com SOA IN","via":"UDP:53","rd":true,"do":false,"cd":true,"edns":true,"bufsize":null,"cookie":false,"fallback":true}} },
  // A space in a name.
  { id: "error-bad-name", why: "A space in a name.", input: {"name":"exa mple.com"}, expect: {"ok":false,"command":"","findings":["error:bad-name"],"effective":null} },
  // A mnemonic the registry does not have.
  { id: "error-unknown-type", why: "A mnemonic the registry does not have.", input: {"name":"example.com","type":"FOO"}, expect: {"ok":false,"command":"","findings":["error:unknown-type"],"effective":null} },
  // A port inside @server belongs in -p.
  { id: "error-server-with-port", why: "A port inside @server belongs in -p.", input: {"name":"example.com","server":"ns1.example.com:53"}, expect: {"ok":false,"command":"","findings":["error:bad-server"],"effective":null} },
  // Nothing to look up.
  { id: "error-empty", why: "Nothing to look up.", input: {}, expect: {"ok":false,"command":"","findings":["error:empty"],"effective":null} },
];

/** Verifies every vector; the build's run-golden-vectors reads this shape. */
export function verifyVectors(): { setId: string; total: number; passed: number; failures: { id: string; expected: string; actual: string }[] } {
  // Collect mismatches.
  const failures: { id: string; expected: string; actual: string }[] = [];
  for (const v of VECTORS) {
    // Compare the pinned projections as JSON.
    const expected = JSON.stringify(v.expect);
    const actual = JSON.stringify(pin(run(v.input)));
    if (expected !== actual) failures.push({ id: v.id, expected, actual });
  }
  // The harness's shape.
  return { setId: GOLDEN_VECTOR_SET_ID, total: VECTORS.length, passed: VECTORS.length - failures.length, failures };
}
