// ============================================================================
// src/lib/tools/unicode-inspector/golden-vectors.ts
// ----------------------------------------------------------------------------
// GOLDEN VECTORS for the Unicode inspector
// (set "unicode-inspector-golden-2026-10-03"). GENERATED by scratchpad/chr/gv/gen-chr.mts.
//
// Three kinds of vector. A code point pins the whole record: name, aliases,
// category, block, script and Script_Extensions, age, UTF-8, UTF-16 and
// UTF-32, every escape and every flag. A text pins the counts, each row,
// the findings, bidirectional controls left open, mixed-script words, the
// cleaned text and the escapes in eight languages. A search pins the hits.
//
// Expected values were captured from compute.run() on 2026-10-03, with the full
// Unicode 18.0.0 name table. Characters outside printable ASCII are written as
// \uXXXX escapes so the file shows exactly which character each vector holds.
// 30 reference checks were evaluated in CPython 3.11 (html, unicodedata,
// urllib.parse, ast, json): 30 of 30 agree.
// Before writing, every escape form of 4,000 code points across all planes
// was decoded back by its own language (CPython, Node 22, GCC, Tcl 8.4.6,
// Chromium for HTML and CSS): no differences.
// ============================================================================

import { run, type UnicodeInspectorInput, type UnicodeInspectorResult, type UnicodeData } from "./compute";
import { unicodeName, aliasesOf, codePointOfName, searchNames } from "@/lib/unicode/names";

/** The set id: the tool slug and the date the expected values were captured. */
export const GOLDEN_VECTOR_SET_ID = "unicode-inspector-golden-2026-10-03";

/** The full name data the vectors run with (the API entry point passes the same). */
const FULL_DATA: UnicodeData = { nameOf: unicodeName, aliasOf: (cp: number) => aliasesOf(cp)[0]?.alias, cpOf: codePointOfName, aliases: aliasesOf, search: searchNames };

/** The fields a vector pins. */
export type UnicodeInspectorPinned = Record<string, unknown>;

/** One vector: a name, an input, and the pinned fields of its result. */
export interface UnicodeInspectorVector {
  // A short stable name.
  id: string;
  // The input, exactly as the tool takes it.
  input: UnicodeInspectorInput;
  // The pinned fields of the result.
  expect: UnicodeInspectorPinned;
}

/** Reduce a result to the fields a vector pins. */
export function pin(r: UnicodeInspectorResult): UnicodeInspectorPinned {
  // A code point: the whole record.
  if (r.mode === "codepoint") return { mode: r.mode, readAs: r.readAs, info: r.info };
  // A search: the hits.
  if (r.mode === "search") return { mode: r.mode, hits: r.hits, truncated: r.truncated };
  // A text: everything but the row labels (they repeat the code point).
  return { mode: r.mode, codePoints: r.codePoints, utf16Units: r.utf16Units, utf8Bytes: r.utf8Bytes, lines: r.lines, ascii: r.ascii, truncated: r.truncated, rows: r.rows.map((x) => [x.at, x.line, x.col, x.cp, x.name, x.gc, x.script, x.flags.join(" "), x.prototype]), findings: r.findings, openBidi: r.openBidi, mixed: r.mixed, cleaned: r.cleaned, changes: r.changes, escaped: r.escaped };
}

/** The vectors. */
export const VECTORS: UnicodeInspectorVector[] = [
  // A Latin letter: two UTF-8 bytes, a named reference, every escape.
  {
    id: "codepoint-e-acute",
    input: { mode: "codepoint", value: "U+00E9" },
    expect: {
      mode: "codepoint",
      readAs: "unicode",
      info: {
        cp: 233,
        label: "U+00E9",
        name: "LATIN SMALL LETTER E WITH ACUTE",
        nameKind: "name",
        aliases: [],
        gc: "Ll",
        block: "Latin-1 Supplement",
        script: "Latin",
        scriptCode: "Latn",
        scx: ["Latn"],
        age: "1.1",
        utf8: "C3 A9",
        utf16: "00E9",
        utf32: "000000E9",
        escapes: {
          json: "\\u00E9",
          javascript: "\\u00E9",
          python: "\\u00E9",
          html: "&#xE9;",
          css: "\\E9",
          url: "%C3%A9",
          c: "\\u00E9",
          tcl: "\\u00E9",
        },
        html: { dec: "&#233;", hex: "&#xE9;", named: ["&eacute;"] },
        flags: [],
      },
    },
  },
  // Beyond the BMP: four UTF-8 bytes, a UTF-16 surrogate pair, no Tcl 8.4 escape.
  {
    id: "codepoint-emoji",
    input: { mode: "codepoint", value: "\uD83D\uDE00" },
    expect: {
      mode: "codepoint",
      readAs: "character",
      info: {
        cp: 128512,
        label: "U+1F600",
        name: "GRINNING FACE",
        nameKind: "name",
        aliases: [],
        gc: "So",
        block: "Emoticons",
        script: "Common",
        scriptCode: "Zyyy",
        scx: ["Zyyy"],
        age: "6.1",
        utf8: "F0 9F 98 80",
        utf16: "D83D DE00",
        utf32: "0001F600",
        escapes: {
          json: "\\uD83D\\uDE00",
          javascript: "\\u{1F600}",
          python: "\\U0001F600",
          html: "&#x1F600;",
          css: "\\1F600",
          url: "%F0%9F%98%80",
          c: "\\U0001F600",
        },
        html: { dec: "&#128512;", hex: "&#x1F600;", named: [] },
        flags: [],
      },
    },
  },
  // RIGHT-TO-LEFT OVERRIDE: a bidirectional control and invisible.
  {
    id: "codepoint-rlo",
    input: { mode: "codepoint", value: "U+202E" },
    expect: {
      mode: "codepoint",
      readAs: "unicode",
      info: {
        cp: 8238,
        label: "U+202E",
        name: "RIGHT-TO-LEFT OVERRIDE",
        nameKind: "name",
        aliases: [{ alias: "RLO", type: "abbreviation" }],
        gc: "Cf",
        block: "General Punctuation",
        script: "Common",
        scriptCode: "Zyyy",
        scx: ["Zyyy"],
        age: "1.1",
        utf8: "E2 80 AE",
        utf16: "202E",
        utf32: "0000202E",
        escapes: {
          json: "\\u202E",
          javascript: "\\u202E",
          python: "\\u202E",
          html: "&#x202E;",
          css: "\\202E",
          url: "%E2%80%AE",
          c: "\\u202E",
          tcl: "\\u202E",
        },
        html: { dec: "&#8238;", hex: "&#x202E;", named: [] },
        flags: ["bidi", "invisible"],
      },
    },
  },
  // Found by an abbreviation alias: BOM is U+FEFF ZERO WIDTH NO-BREAK SPACE.
  {
    id: "codepoint-bom-by-alias",
    input: { mode: "codepoint", value: "BOM" },
    expect: {
      mode: "codepoint",
      readAs: "name",
      info: {
        cp: 65279,
        label: "U+FEFF",
        name: "ZERO WIDTH NO-BREAK SPACE",
        nameKind: "name",
        aliases: [
          { alias: "BYTE ORDER MARK", type: "alternate" },
          { alias: "BOM", type: "abbreviation" },
          { alias: "ZWNBSP", type: "abbreviation" },
        ],
        gc: "Cf",
        block: "Arabic Presentation Forms-B",
        script: "Common",
        scriptCode: "Zyyy",
        scx: ["Zyyy"],
        age: "1.1",
        utf8: "EF BB BF",
        utf16: "FEFF",
        utf32: "0000FEFF",
        escapes: {
          json: "\\uFEFF",
          javascript: "\\uFEFF",
          python: "\\uFEFF",
          html: "&#xFEFF;",
          css: "\\FEFF",
          url: "%EF%BB%BF",
          c: "\\uFEFF",
          tcl: "\\uFEFF",
        },
        html: { dec: "&#65279;", hex: "&#xFEFF;", named: [] },
        flags: ["invisible"],
      },
    },
  },
  // Cyrillic a: UTS #39 maps it to the ASCII prototype a.
  {
    id: "codepoint-cyrillic-a",
    input: { mode: "codepoint", value: "U+0430" },
    expect: {
      mode: "codepoint",
      readAs: "unicode",
      info: {
        cp: 1072,
        label: "U+0430",
        name: "CYRILLIC SMALL LETTER A",
        nameKind: "name",
        aliases: [],
        gc: "Ll",
        block: "Cyrillic",
        script: "Cyrillic",
        scriptCode: "Cyrl",
        scx: ["Cyrl"],
        age: "1.1",
        utf8: "D0 B0",
        utf16: "0430",
        utf32: "00000430",
        escapes: {
          json: "\\u0430",
          javascript: "\\u0430",
          python: "\\u0430",
          html: "&#x430;",
          css: "\\430",
          url: "%D0%B0",
          c: "\\u0430",
          tcl: "\\u0430",
        },
        html: { dec: "&#1072;", hex: "&#x430;", named: ["&acy;"] },
        flags: ["confusable"],
        prototype: "a",
        sharing: ["a"],
      },
    },
  },
  // A surrogate code point: no name, no UTF-8, labelled <surrogate-D800>.
  {
    id: "codepoint-surrogate",
    input: { mode: "codepoint", value: "U+D800" },
    expect: {
      mode: "codepoint",
      readAs: "unicode",
      info: {
        cp: 55296,
        label: "U+D800",
        name: "<surrogate-D800>",
        nameKind: "label",
        aliases: [],
        gc: "Cs",
        block: "High Surrogates",
        script: "Unknown",
        scriptCode: "Zzzz",
        scx: ["Zzzz"],
        age: "2.0",
        utf16: "D800",
        utf32: "0000D800",
        escapes: { json: "\\uD800", javascript: "\\uD800", python: "\\uD800", tcl: "\\uD800" },
        html: { dec: "&#55296;", hex: "&#xD800;", named: [], note: "surrogate" },
        flags: ["surrogate"],
      },
    },
  },
  // A character new in Unicode 18.0: named by the SMALL SEAL CHARACTER- pattern.
  {
    id: "codepoint-small-seal",
    input: { mode: "codepoint", value: "U+3D000" },
    expect: {
      mode: "codepoint",
      readAs: "unicode",
      info: {
        cp: 249856,
        label: "U+3D000",
        name: "SMALL SEAL CHARACTER-3D000",
        nameKind: "name",
        aliases: [],
        gc: "Lo",
        block: "Seal",
        script: "Seal",
        scriptCode: "Seal",
        scx: ["Seal"],
        age: "18.0",
        utf8: "F0 BD 80 80",
        utf16: "D8B4 DC00",
        utf32: "0003D000",
        escapes: {
          json: "\\uD8B4\\uDC00",
          javascript: "\\u{3D000}",
          python: "\\U0003D000",
          html: "&#x3D000;",
          css: "\\3D000",
          url: "%F0%BD%80%80",
          c: "\\U0003D000",
        },
        html: { dec: "&#249856;", hex: "&#x3D000;", named: [] },
        flags: [],
      },
    },
  },
  // A noncharacter: U+FFFE.
  {
    id: "codepoint-noncharacter",
    input: { mode: "codepoint", value: "U+FFFE" },
    expect: {
      mode: "codepoint",
      readAs: "unicode",
      info: {
        cp: 65534,
        label: "U+FFFE",
        name: "<noncharacter-FFFE>",
        nameKind: "label",
        aliases: [],
        gc: "Cn",
        block: "Specials",
        script: "Unknown",
        scriptCode: "Zzzz",
        scx: ["Zzzz"],
        age: "1.1",
        utf8: "EF BF BE",
        utf16: "FFFE",
        utf32: "0000FFFE",
        escapes: {
          json: "\\uFFFE",
          javascript: "\\uFFFE",
          python: "\\uFFFE",
          html: "&#xFFFE;",
          css: "\\FFFE",
          url: "%EF%BF%BE",
          c: "\\uFFFE",
          tcl: "\\uFFFE",
        },
        html: { dec: "&#65534;", hex: "&#xFFFE;", named: [], note: "noncharacter" },
        flags: ["noncharacter"],
      },
    },
  },
  // An unassigned code point: <reserved-0378>.
  {
    id: "codepoint-reserved",
    input: { mode: "codepoint", value: "U+0378" },
    expect: {
      mode: "codepoint",
      readAs: "unicode",
      info: {
        cp: 888,
        label: "U+0378",
        name: "<reserved-0378>",
        nameKind: "label",
        aliases: [],
        gc: "Cn",
        block: "Greek and Coptic",
        script: "Unknown",
        scriptCode: "Zzzz",
        scx: ["Zzzz"],
        age: "Unassigned",
        utf8: "CD B8",
        utf16: "0378",
        utf32: "00000378",
        escapes: {
          json: "\\u0378",
          javascript: "\\u0378",
          python: "\\u0378",
          html: "&#x378;",
          css: "\\378",
          url: "%CD%B8",
          c: "\\u0378",
          tcl: "\\u0378",
        },
        html: { dec: "&#888;", hex: "&#x378;", named: [] },
        flags: ["unassigned"],
      },
    },
  },
  // NEXT LINE: a control with no name, only aliases, and a line break other tools may not see.
  {
    id: "codepoint-nel",
    input: { mode: "codepoint", value: "U+0085" },
    expect: {
      mode: "codepoint",
      readAs: "unicode",
      info: {
        cp: 133,
        label: "U+0085",
        name: "NEXT LINE",
        nameKind: "alias",
        aliases: [{ alias: "NEXT LINE", type: "control" }, { alias: "NEL", type: "abbreviation" }],
        gc: "Cc",
        block: "Latin-1 Supplement",
        script: "Common",
        scriptCode: "Zyyy",
        scx: ["Zyyy"],
        age: "1.1",
        utf8: "C2 85",
        utf16: "0085",
        utf32: "00000085",
        escapes: {
          json: "\\u0085",
          javascript: "\\u0085",
          python: "\\u0085",
          css: "\\85",
          url: "%C2%85",
          tcl: "\\u0085",
        },
        html: { dec: "&#133;", hex: "&#x85;", named: [], note: "c1" },
        flags: ["line-break"],
      },
    },
  },
  // Names with words starting zero and width.
  {
    id: "search-zero-width",
    input: { mode: "search", query: "zero width" },
    expect: {
      mode: "search",
      hits: [
        { cp: 8203, label: "U+200B", name: "ZERO WIDTH SPACE" },
        { cp: 8204, label: "U+200C", name: "ZERO WIDTH NON-JOINER" },
        { cp: 8205, label: "U+200D", name: "ZERO WIDTH JOINER" },
        { cp: 65279, label: "U+FEFF", name: "ZERO WIDTH NO-BREAK SPACE" },
      ],
      truncated: false,
    },
  },
  // A word that mixes Latin and Cyrillic (UTS #39 resolved script set is empty).
  {
    id: "inspect-mixed-script",
    input: { mode: "inspect", text: "pay to p\u0430ypal" },
    expect: {
      mode: "inspect",
      codePoints: 13,
      utf16Units: 13,
      utf8Bytes: 14,
      lines: 1,
      ascii: 12,
      truncated: false,
      rows: [
        [0, 1, 1, 112, "LATIN SMALL LETTER P", "Ll", "Latn", "ascii", null],
        [1, 1, 2, 97, "LATIN SMALL LETTER A", "Ll", "Latn", "ascii", null],
        [2, 1, 3, 121, "LATIN SMALL LETTER Y", "Ll", "Latn", "ascii", null],
        [3, 1, 4, 32, "SPACE", "Zs", "Zyyy", "ascii", null],
        [4, 1, 5, 116, "LATIN SMALL LETTER T", "Ll", "Latn", "ascii", null],
        [5, 1, 6, 111, "LATIN SMALL LETTER O", "Ll", "Latn", "ascii", null],
        [6, 1, 7, 32, "SPACE", "Zs", "Zyyy", "ascii", null],
        [7, 1, 8, 112, "LATIN SMALL LETTER P", "Ll", "Latn", "ascii", null],
        [8, 1, 9, 1072, "CYRILLIC SMALL LETTER A", "Ll", "Cyrl", "confusable", "a"],
        [9, 1, 10, 121, "LATIN SMALL LETTER Y", "Ll", "Latn", "ascii", null],
        [10, 1, 11, 112, "LATIN SMALL LETTER P", "Ll", "Latn", "ascii", null],
        [11, 1, 12, 97, "LATIN SMALL LETTER A", "Ll", "Latn", "ascii", null],
        [12, 1, 13, 108, "LATIN SMALL LETTER L", "Ll", "Latn", "ascii", null],
      ],
      findings: { confusable: [8] },
      openBidi: [],
      mixed: [{ word: "p\u0430ypal", at: 7, line: 1, col: 8, scripts: ["Latn", "Cyrl"] }],
      cleaned: "pay to p\u0430ypal",
      changes: { removed: 0, spaces: 0, punctuation: 0, folded: 0 },
      escaped: {
        json: "pay to p\\u0430ypal",
        javascript: "pay to p\\u0430ypal",
        python: "pay to p\\u0430ypal",
        html: "pay to p&#x430;ypal",
        css: "pay to p\\430ypal",
        url: "pay%20to%20p%D0%B0ypal",
        c: "pay to p\\u0430ypal",
        tcl: "pay to p\\u0430ypal",
      },
    },
  },
  // Bidirectional controls left open at the end of the line (the Trojan Source pattern).
  {
    id: "inspect-trojan-source",
    input: {
      mode: "inspect",
      text: "if access_level != \"user\u202E \u2066// Check if admin\u2069 \u2066\" {",
    },
    expect: {
      mode: "inspect",
      codePoints: 50,
      utf16Units: 50,
      utf8Bytes: 58,
      lines: 1,
      ascii: 46,
      truncated: false,
      rows: [
        [0, 1, 1, 105, "LATIN SMALL LETTER I", "Ll", "Latn", "ascii", null],
        [1, 1, 2, 102, "LATIN SMALL LETTER F", "Ll", "Latn", "ascii", null],
        [2, 1, 3, 32, "SPACE", "Zs", "Zyyy", "ascii", null],
        [3, 1, 4, 97, "LATIN SMALL LETTER A", "Ll", "Latn", "ascii", null],
        [4, 1, 5, 99, "LATIN SMALL LETTER C", "Ll", "Latn", "ascii", null],
        [5, 1, 6, 99, "LATIN SMALL LETTER C", "Ll", "Latn", "ascii", null],
        [6, 1, 7, 101, "LATIN SMALL LETTER E", "Ll", "Latn", "ascii", null],
        [7, 1, 8, 115, "LATIN SMALL LETTER S", "Ll", "Latn", "ascii", null],
        [8, 1, 9, 115, "LATIN SMALL LETTER S", "Ll", "Latn", "ascii", null],
        [9, 1, 10, 95, "LOW LINE", "Pc", "Zyyy", "ascii", null],
        [10, 1, 11, 108, "LATIN SMALL LETTER L", "Ll", "Latn", "ascii", null],
        [11, 1, 12, 101, "LATIN SMALL LETTER E", "Ll", "Latn", "ascii", null],
        [12, 1, 13, 118, "LATIN SMALL LETTER V", "Ll", "Latn", "ascii", null],
        [13, 1, 14, 101, "LATIN SMALL LETTER E", "Ll", "Latn", "ascii", null],
        [14, 1, 15, 108, "LATIN SMALL LETTER L", "Ll", "Latn", "ascii", null],
        [15, 1, 16, 32, "SPACE", "Zs", "Zyyy", "ascii", null],
        [16, 1, 17, 33, "EXCLAMATION MARK", "Po", "Zyyy", "ascii", null],
        [17, 1, 18, 61, "EQUALS SIGN", "Sm", "Zyyy", "ascii", null],
        [18, 1, 19, 32, "SPACE", "Zs", "Zyyy", "ascii", null],
        [19, 1, 20, 34, "QUOTATION MARK", "Po", "Zyyy", "ascii", null],
        [20, 1, 21, 117, "LATIN SMALL LETTER U", "Ll", "Latn", "ascii", null],
        [21, 1, 22, 115, "LATIN SMALL LETTER S", "Ll", "Latn", "ascii", null],
        [22, 1, 23, 101, "LATIN SMALL LETTER E", "Ll", "Latn", "ascii", null],
        [23, 1, 24, 114, "LATIN SMALL LETTER R", "Ll", "Latn", "ascii", null],
        [24, 1, 25, 8238, "RIGHT-TO-LEFT OVERRIDE", "Cf", "Zyyy", "bidi invisible", null],
        [25, 1, 26, 32, "SPACE", "Zs", "Zyyy", "ascii", null],
        [26, 1, 27, 8294, "LEFT-TO-RIGHT ISOLATE", "Cf", "Zyyy", "bidi invisible", null],
        [27, 1, 28, 47, "SOLIDUS", "Po", "Zyyy", "ascii", null],
        [28, 1, 29, 47, "SOLIDUS", "Po", "Zyyy", "ascii", null],
        [29, 1, 30, 32, "SPACE", "Zs", "Zyyy", "ascii", null],
        [30, 1, 31, 67, "LATIN CAPITAL LETTER C", "Lu", "Latn", "ascii", null],
        [31, 1, 32, 104, "LATIN SMALL LETTER H", "Ll", "Latn", "ascii", null],
        [32, 1, 33, 101, "LATIN SMALL LETTER E", "Ll", "Latn", "ascii", null],
        [33, 1, 34, 99, "LATIN SMALL LETTER C", "Ll", "Latn", "ascii", null],
        [34, 1, 35, 107, "LATIN SMALL LETTER K", "Ll", "Latn", "ascii", null],
        [35, 1, 36, 32, "SPACE", "Zs", "Zyyy", "ascii", null],
        [36, 1, 37, 105, "LATIN SMALL LETTER I", "Ll", "Latn", "ascii", null],
        [37, 1, 38, 102, "LATIN SMALL LETTER F", "Ll", "Latn", "ascii", null],
        [38, 1, 39, 32, "SPACE", "Zs", "Zyyy", "ascii", null],
        [39, 1, 40, 97, "LATIN SMALL LETTER A", "Ll", "Latn", "ascii", null],
        [40, 1, 41, 100, "LATIN SMALL LETTER D", "Ll", "Latn", "ascii", null],
        [41, 1, 42, 109, "LATIN SMALL LETTER M", "Ll", "Latn", "ascii", null],
        [42, 1, 43, 105, "LATIN SMALL LETTER I", "Ll", "Latn", "ascii", null],
        [43, 1, 44, 110, "LATIN SMALL LETTER N", "Ll", "Latn", "ascii", null],
        [44, 1, 45, 8297, "POP DIRECTIONAL ISOLATE", "Cf", "Zyyy", "bidi invisible", null],
        [45, 1, 46, 32, "SPACE", "Zs", "Zyyy", "ascii", null],
        [46, 1, 47, 8294, "LEFT-TO-RIGHT ISOLATE", "Cf", "Zyyy", "bidi invisible", null],
        [47, 1, 48, 34, "QUOTATION MARK", "Po", "Zyyy", "ascii", null],
        [48, 1, 49, 32, "SPACE", "Zs", "Zyyy", "ascii", null],
        [49, 1, 50, 123, "LEFT CURLY BRACKET", "Ps", "Zyyy", "ascii", null],
      ],
      findings: { bidi: [24, 26, 44, 46], invisible: [24, 26, 44, 46] },
      openBidi: [{ line: 1, open: ["U+202E", "U+2066"] }],
      mixed: [],
      cleaned: "if access_level != \"user // Check if admin \" {",
      changes: { removed: 4, spaces: 0, punctuation: 0, folded: 0 },
      escaped: {
        json: "if access_level != \\\"user\\u202E \\u2066// Check if admin\\u2069 \\u2066\\\" {",
        javascript: "if access_level != \\\"user\\u202E \\u2066// Check if admin\\u2069 \\u2066\\\" {",
        python: "if access_level != \\\"user\\u202E \\u2066// Check if admin\\u2069 \\u2066\\\" {",
        html: "if access_level != &quot;user&#x202E; &#x2066;// Check if admin&#x2069; &#x2066;&quot; {",
        css: "if access_level != \\22user\\202E  \\2066// Check if admin\\2069  \\2066\\22  {",
        url: "if%20access_level%20%21%3D%20%22user%E2%80%AE%20%E2%81%A6%2F%2F%20Check%20if%20admin%E2%81%A9%20%E2%81%A6%22%20%7B",
        c: "if access_level != \\\"user\\u202E \\u2066// Check if admin\\u2069 \\u2066\\\" {",
        tcl: "if access_level != \\\"user\\u202E \\u2066// Check if admin\\u2069 \\u2066\\\" {",
      },
    },
  },
  // A no-break space and a zero width space, and the cleaned text.
  {
    id: "inspect-invisible",
    input: { mode: "inspect", text: "Hi\u00A0there\u200B!" },
    expect: {
      mode: "inspect",
      codePoints: 10,
      utf16Units: 10,
      utf8Bytes: 13,
      lines: 1,
      ascii: 8,
      truncated: false,
      rows: [
        [0, 1, 1, 72, "LATIN CAPITAL LETTER H", "Lu", "Latn", "ascii", null],
        [1, 1, 2, 105, "LATIN SMALL LETTER I", "Ll", "Latn", "ascii", null],
        [2, 1, 3, 160, "NO-BREAK SPACE", "Zs", "Zyyy", "space confusable compat-ascii", " "],
        [3, 1, 4, 116, "LATIN SMALL LETTER T", "Ll", "Latn", "ascii", null],
        [4, 1, 5, 104, "LATIN SMALL LETTER H", "Ll", "Latn", "ascii", null],
        [5, 1, 6, 101, "LATIN SMALL LETTER E", "Ll", "Latn", "ascii", null],
        [6, 1, 7, 114, "LATIN SMALL LETTER R", "Ll", "Latn", "ascii", null],
        [7, 1, 8, 101, "LATIN SMALL LETTER E", "Ll", "Latn", "ascii", null],
        [8, 1, 9, 8203, "ZERO WIDTH SPACE", "Cf", "Zyyy", "invisible", null],
        [9, 1, 10, 33, "EXCLAMATION MARK", "Po", "Zyyy", "ascii", null],
      ],
      findings: { space: [2], confusable: [2], "compat-ascii": [2], invisible: [8] },
      openBidi: [],
      mixed: [],
      cleaned: "Hi there!",
      changes: { removed: 1, spaces: 1, punctuation: 0, folded: 0 },
      escaped: {
        json: "Hi\\u00A0there\\u200B!",
        javascript: "Hi\\u00A0there\\u200B!",
        python: "Hi\\xA0there\\u200B!",
        html: "Hi&#xA0;there&#x200B;!",
        css: "Hi\\A0there\\200B!",
        url: "Hi%C2%A0there%E2%80%8B%21",
        c: "Hi\\u00A0there\\u200B!",
        tcl: "Hi\\u00A0there\\u200B!",
      },
    },
  },
  // Typographic quotes and an en dash, cleaned to ASCII.
  {
    id: "inspect-smart-punctuation",
    input: { mode: "inspect", text: "\u201Csmart\u201D \u2013 quotes" },
    expect: {
      mode: "inspect",
      codePoints: 16,
      utf16Units: 16,
      utf8Bytes: 22,
      lines: 1,
      ascii: 13,
      truncated: false,
      rows: [
        [0, 1, 1, 8220, "LEFT DOUBLE QUOTATION MARK", "Pi", "Zyyy", "quote confusable", "''"],
        [1, 1, 2, 115, "LATIN SMALL LETTER S", "Ll", "Latn", "ascii", null],
        [2, 1, 3, 109, "LATIN SMALL LETTER M", "Ll", "Latn", "ascii", null],
        [3, 1, 4, 97, "LATIN SMALL LETTER A", "Ll", "Latn", "ascii", null],
        [4, 1, 5, 114, "LATIN SMALL LETTER R", "Ll", "Latn", "ascii", null],
        [5, 1, 6, 116, "LATIN SMALL LETTER T", "Ll", "Latn", "ascii", null],
        [6, 1, 7, 8221, "RIGHT DOUBLE QUOTATION MARK", "Pf", "Zyyy", "quote confusable", "''"],
        [7, 1, 8, 32, "SPACE", "Zs", "Zyyy", "ascii", null],
        [8, 1, 9, 8211, "EN DASH", "Pd", "Zyyy", "dash confusable", "-"],
        [9, 1, 10, 32, "SPACE", "Zs", "Zyyy", "ascii", null],
        [10, 1, 11, 113, "LATIN SMALL LETTER Q", "Ll", "Latn", "ascii", null],
        [11, 1, 12, 117, "LATIN SMALL LETTER U", "Ll", "Latn", "ascii", null],
        [12, 1, 13, 111, "LATIN SMALL LETTER O", "Ll", "Latn", "ascii", null],
        [13, 1, 14, 116, "LATIN SMALL LETTER T", "Ll", "Latn", "ascii", null],
        [14, 1, 15, 101, "LATIN SMALL LETTER E", "Ll", "Latn", "ascii", null],
        [15, 1, 16, 115, "LATIN SMALL LETTER S", "Ll", "Latn", "ascii", null],
      ],
      findings: { quote: [0, 6], confusable: [0, 6, 8], dash: [8] },
      openBidi: [],
      mixed: [],
      cleaned: "\"smart\" - quotes",
      changes: { removed: 0, spaces: 0, punctuation: 3, folded: 0 },
      escaped: {
        json: "\\u201Csmart\\u201D \\u2013 quotes",
        javascript: "\\u201Csmart\\u201D \\u2013 quotes",
        python: "\\u201Csmart\\u201D \\u2013 quotes",
        html: "&#x201C;smart&#x201D; &#x2013; quotes",
        css: "\\201Csmart\\201D  \\2013  quotes",
        url: "%E2%80%9Csmart%E2%80%9D%20%E2%80%93%20quotes",
        c: "\\u201Csmart\\u201D \\u2013 quotes",
        tcl: "\\u201Csmart\\u201D \\u2013 quotes",
      },
    },
  },
  // Fullwidth letters, folded to ASCII when asked.
  {
    id: "inspect-fullwidth-folded",
    input: {
      mode: "inspect",
      text: "\uFF46\uFF55\uFF4C\uFF4C\uFF57\uFF49\uFF44\uFF54\uFF48",
      options: { foldLookalikes: true },
    },
    expect: {
      mode: "inspect",
      codePoints: 9,
      utf16Units: 9,
      utf8Bytes: 27,
      lines: 1,
      ascii: 0,
      truncated: false,
      rows: [
        [0, 1, 1, 65350, "FULLWIDTH LATIN SMALL LETTER F", "Ll", "Latn", "confusable compat-ascii", "f"],
        [1, 1, 2, 65365, "FULLWIDTH LATIN SMALL LETTER U", "Ll", "Latn", "confusable compat-ascii", "u"],
        [2, 1, 3, 65356, "FULLWIDTH LATIN SMALL LETTER L", "Ll", "Latn", "confusable compat-ascii", "l"],
        [3, 1, 4, 65356, "FULLWIDTH LATIN SMALL LETTER L", "Ll", "Latn", "confusable compat-ascii", "l"],
        [4, 1, 5, 65367, "FULLWIDTH LATIN SMALL LETTER W", "Ll", "Latn", "confusable compat-ascii", "w"],
        [5, 1, 6, 65353, "FULLWIDTH LATIN SMALL LETTER I", "Ll", "Latn", "confusable compat-ascii", "i"],
        [6, 1, 7, 65348, "FULLWIDTH LATIN SMALL LETTER D", "Ll", "Latn", "confusable compat-ascii", "d"],
        [7, 1, 8, 65364, "FULLWIDTH LATIN SMALL LETTER T", "Ll", "Latn", "confusable compat-ascii", "t"],
        [8, 1, 9, 65352, "FULLWIDTH LATIN SMALL LETTER H", "Ll", "Latn", "confusable compat-ascii", "h"],
      ],
      findings: { confusable: [0, 1, 2, 3, 4, 5, 6, 7, 8], "compat-ascii": [0, 1, 2, 3, 4, 5, 6, 7, 8] },
      openBidi: [],
      mixed: [],
      cleaned: "fullwidth",
      changes: { removed: 0, spaces: 0, punctuation: 0, folded: 9 },
      escaped: {
        json: "\\uFF46\\uFF55\\uFF4C\\uFF4C\\uFF57\\uFF49\\uFF44\\uFF54\\uFF48",
        javascript: "\\uFF46\\uFF55\\uFF4C\\uFF4C\\uFF57\\uFF49\\uFF44\\uFF54\\uFF48",
        python: "\\uFF46\\uFF55\\uFF4C\\uFF4C\\uFF57\\uFF49\\uFF44\\uFF54\\uFF48",
        html: "&#xFF46;&#xFF55;&#xFF4C;&#xFF4C;&#xFF57;&#xFF49;&#xFF44;&#xFF54;&#xFF48;",
        css: "\\FF46\\FF55\\FF4C\\FF4C\\FF57\\FF49\\FF44\\FF54\\FF48",
        url: "%EF%BD%86%EF%BD%95%EF%BD%8C%EF%BD%8C%EF%BD%97%EF%BD%89%EF%BD%84%EF%BD%94%EF%BD%88",
        c: "\\uFF46\\uFF55\\uFF4C\\uFF4C\\uFF57\\uFF49\\uFF44\\uFF54\\uFF48",
        tcl: "\\uFF46\\uFF55\\uFF4C\\uFF4C\\uFF57\\uFF49\\uFF44\\uFF54\\uFF48",
      },
    },
  },
  // U+2028 LINE SEPARATOR: a line break for an editor, not for most languages.
  {
    id: "inspect-line-separator",
    input: { mode: "inspect", text: "if (x)\u2028return;" },
    expect: {
      mode: "inspect",
      codePoints: 14,
      utf16Units: 14,
      utf8Bytes: 16,
      lines: 2,
      ascii: 13,
      truncated: false,
      rows: [
        [0, 1, 1, 105, "LATIN SMALL LETTER I", "Ll", "Latn", "ascii", null],
        [1, 1, 2, 102, "LATIN SMALL LETTER F", "Ll", "Latn", "ascii", null],
        [2, 1, 3, 32, "SPACE", "Zs", "Zyyy", "ascii", null],
        [3, 1, 4, 40, "LEFT PARENTHESIS", "Ps", "Zyyy", "ascii", null],
        [4, 1, 5, 120, "LATIN SMALL LETTER X", "Ll", "Latn", "ascii", null],
        [5, 1, 6, 41, "RIGHT PARENTHESIS", "Pe", "Zyyy", "ascii", null],
        [6, 1, 7, 8232, "LINE SEPARATOR", "Zl", "Zyyy", "line-break confusable", " "],
        [7, 2, 1, 114, "LATIN SMALL LETTER R", "Ll", "Latn", "ascii", null],
        [8, 2, 2, 101, "LATIN SMALL LETTER E", "Ll", "Latn", "ascii", null],
        [9, 2, 3, 116, "LATIN SMALL LETTER T", "Ll", "Latn", "ascii", null],
        [10, 2, 4, 117, "LATIN SMALL LETTER U", "Ll", "Latn", "ascii", null],
        [11, 2, 5, 114, "LATIN SMALL LETTER R", "Ll", "Latn", "ascii", null],
        [12, 2, 6, 110, "LATIN SMALL LETTER N", "Ll", "Latn", "ascii", null],
        [13, 2, 7, 59, "SEMICOLON", "Po", "Zyyy", "ascii", null],
      ],
      findings: { "line-break": [6], confusable: [6] },
      openBidi: [],
      mixed: [],
      cleaned: "if (x)\nreturn;",
      changes: { removed: 0, spaces: 1, punctuation: 0, folded: 0 },
      escaped: {
        json: "if (x)\\u2028return;",
        javascript: "if (x)\\u2028return;",
        python: "if (x)\\u2028return;",
        html: "if (x)&#x2028;return;",
        css: "if (x)\\2028return;",
        url: "if%20%28x%29%E2%80%A8return%3B",
        c: "if (x)\\u2028return;",
        tcl: "if (x)\\u2028return;",
      },
    },
  },
  // One text written as escapes in eight languages.
  {
    id: "inspect-escapes",
    input: { mode: "inspect", text: "caf\u00E9 \u2615 \uD83D\uDE00" },
    expect: {
      mode: "inspect",
      codePoints: 8,
      utf16Units: 9,
      utf8Bytes: 14,
      lines: 1,
      ascii: 5,
      truncated: false,
      rows: [
        [0, 1, 1, 99, "LATIN SMALL LETTER C", "Ll", "Latn", "ascii", null],
        [1, 1, 2, 97, "LATIN SMALL LETTER A", "Ll", "Latn", "ascii", null],
        [2, 1, 3, 102, "LATIN SMALL LETTER F", "Ll", "Latn", "ascii", null],
        [3, 1, 4, 233, "LATIN SMALL LETTER E WITH ACUTE", "Ll", "Latn", "", null],
        [4, 1, 5, 32, "SPACE", "Zs", "Zyyy", "ascii", null],
        [5, 1, 6, 9749, "HOT BEVERAGE", "So", "Zyyy", "", null],
        [6, 1, 7, 32, "SPACE", "Zs", "Zyyy", "ascii", null],
        [7, 1, 8, 128512, "GRINNING FACE", "So", "Zyyy", "", null],
      ],
      findings: {},
      openBidi: [],
      mixed: [],
      cleaned: "caf\u00E9 \u2615 \uD83D\uDE00",
      changes: { removed: 0, spaces: 0, punctuation: 0, folded: 0 },
      escaped: {
        json: "caf\\u00E9 \\u2615 \\uD83D\\uDE00",
        javascript: "caf\\u00E9 \\u2615 \\u{1F600}",
        python: "caf\\xE9 \\u2615 \\U0001F600",
        html: "caf&#xE9; &#x2615; &#x1F600;",
        css: "caf\\E9  \\2615  \\1F600",
        url: "caf%C3%A9%20%E2%98%95%20%F0%9F%98%80",
        c: "caf\\u00E9 \\u2615 \\U0001F600",
      },
    },
  },
  // Han, Hiragana and Katakana in one word: one writing system (Jpan), not mixed.
  {
    id: "inspect-japanese",
    input: { mode: "inspect", text: "\u65E5\u672C\u8A9E\u306E\u30C6\u30AD\u30B9\u30C8" },
    expect: {
      mode: "inspect",
      codePoints: 8,
      utf16Units: 8,
      utf8Bytes: 24,
      lines: 1,
      ascii: 0,
      truncated: false,
      rows: [
        [0, 1, 1, 26085, "CJK UNIFIED IDEOGRAPH-65E5", "Lo", "Hani", "", null],
        [1, 1, 2, 26412, "CJK UNIFIED IDEOGRAPH-672C", "Lo", "Hani", "", null],
        [2, 1, 3, 35486, "CJK UNIFIED IDEOGRAPH-8A9E", "Lo", "Hani", "", null],
        [3, 1, 4, 12398, "HIRAGANA LETTER NO", "Lo", "Hira", "", null],
        [4, 1, 5, 12486, "KATAKANA LETTER TE", "Lo", "Kana", "", null],
        [5, 1, 6, 12461, "KATAKANA LETTER KI", "Lo", "Kana", "", null],
        [6, 1, 7, 12473, "KATAKANA LETTER SU", "Lo", "Kana", "", null],
        [7, 1, 8, 12488, "KATAKANA LETTER TO", "Lo", "Kana", "", null],
      ],
      findings: {},
      openBidi: [],
      mixed: [],
      cleaned: "\u65E5\u672C\u8A9E\u306E\u30C6\u30AD\u30B9\u30C8",
      changes: { removed: 0, spaces: 0, punctuation: 0, folded: 0 },
      escaped: {
        json: "\\u65E5\\u672C\\u8A9E\\u306E\\u30C6\\u30AD\\u30B9\\u30C8",
        javascript: "\\u65E5\\u672C\\u8A9E\\u306E\\u30C6\\u30AD\\u30B9\\u30C8",
        python: "\\u65E5\\u672C\\u8A9E\\u306E\\u30C6\\u30AD\\u30B9\\u30C8",
        html: "&#x65E5;&#x672C;&#x8A9E;&#x306E;&#x30C6;&#x30AD;&#x30B9;&#x30C8;",
        css: "\\65E5\\672C\\8A9E\\306E\\30C6\\30AD\\30B9\\30C8",
        url: "%E6%97%A5%E6%9C%AC%E8%AA%9E%E3%81%AE%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88",
        c: "\\u65E5\\u672C\\u8A9E\\u306E\\u30C6\\u30AD\\u30B9\\u30C8",
        tcl: "\\u65E5\\u672C\\u8A9E\\u306E\\u30C6\\u30AD\\u30B9\\u30C8",
      },
    },
  },
  // e followed by a combining acute accent: two code points that draw as one.
  {
    id: "inspect-combining",
    input: { mode: "inspect", text: "cafe\u0301" },
    expect: {
      mode: "inspect",
      codePoints: 5,
      utf16Units: 5,
      utf8Bytes: 6,
      lines: 1,
      ascii: 4,
      truncated: false,
      rows: [
        [0, 1, 1, 99, "LATIN SMALL LETTER C", "Ll", "Latn", "ascii", null],
        [1, 1, 2, 97, "LATIN SMALL LETTER A", "Ll", "Latn", "ascii", null],
        [2, 1, 3, 102, "LATIN SMALL LETTER F", "Ll", "Latn", "ascii", null],
        [3, 1, 4, 101, "LATIN SMALL LETTER E", "Ll", "Latn", "ascii", null],
        [4, 1, 5, 769, "COMBINING ACUTE ACCENT", "Mn", "Zinh", "combining", null],
      ],
      findings: {},
      openBidi: [],
      mixed: [],
      cleaned: "cafe\u0301",
      changes: { removed: 0, spaces: 0, punctuation: 0, folded: 0 },
      escaped: {
        json: "cafe\\u0301",
        javascript: "cafe\\u0301",
        python: "cafe\\u0301",
        html: "cafe&#x301;",
        css: "cafe\\301",
        url: "cafe%CC%81",
        c: "cafe\\u0301",
        tcl: "cafe\\u0301",
      },
    },
  },
];

/** What verifyVectors reports (the shape scripts/run-golden-vectors.mts reads). */
export interface VerifyReport {
  // The set id.
  setId: string;
  // Vectors run.
  total: number;
  // Vectors whose pinned fields matched.
  passed: number;
  // The ones that did not, with the first difference.
  failures: { id: string; reason: string }[];
}

/** Run every vector and compare its pinned fields byte for byte. */
export function verifyVectors(): VerifyReport {
  // Failures found.
  const failures: { id: string; reason: string }[] = [];
  // Each vector.
  for (const v of VECTORS) {
    // A throw is a failure too.
    try {
      // Run and reduce (through JSON, as the expected values were captured).
      const got = JSON.stringify(pin(run(v.input, FULL_DATA)));
      // The expected text.
      const want = JSON.stringify(v.expect);
      // Compare.
      if (got !== want) {
        // The first differing character, for a readable reason.
        let k = 0;
        // Walk to it.
        while (k < got.length && got[k] === want[k]) k++;
        // Record.
        failures.push({ id: v.id, reason: `differs at ${k}: got ...${got.slice(Math.max(0, k - 30), k + 50)}... want ...${want.slice(Math.max(0, k - 30), k + 50)}...` });
      }
    } catch (e) {
      // The error.
      failures.push({ id: v.id, reason: `threw: ${(e as Error).message}` });
    }
  }
  // The report.
  return { setId: GOLDEN_VECTOR_SET_ID, total: VECTORS.length, passed: VECTORS.length - failures.length, failures };
}
