// ============================================================================
// src/app/[locale]/about/earlier-sites/[site]/page.tsx
// ----------------------------------------------------------------------------
// ONE RECONSTRUCTED SITE, NAVIGABLE (PRIME, 2026-10-05 11:03: "fetch the whole
// lot, and let users navigate a modernized local CLONE of the old sites.
// Complete with animated banner and the tools that were available on the
// historical sites"). Two pages, one per clone: /about/earlier-sites/
// nutzmann-net-2004/ and /about/earlier-sites/ntz-com-br-2013/.
//
// What the page is: the dated frame around a clone. The clone itself is static
// files under /archive/sites/<slug>/ (generated by scripts/old-sites/
// build-clone.py from the author's own server export of 5 March 2013), shown
// here in an iframe at the 800 px width the sites were designed for, with a
// link to open it in a window of its own. Around the frame: what was kept,
// what was changed and how often (every number from the generator's manifest,
// src/content/about/old-sites/<slug>.json, never typed in), the page list with
// the Internet Archive capture of each file where one exists, what is not here,
// the tools that were there, how the path is served (the headers block that
// allows same-origin framing for the clones only), the other reconstruction,
// the sources.
//
// Why a frame and not a link alone: the 2004 site is a frameset that expects
// to be the top document of an 800 px window; shown inside this page it keeps
// its proportions and the reader keeps the dated context around it. The frame
// is allowed by a path-scoped Content-Security-Policy (frame-ancestors 'self')
// in public/_headers; the global policy still says 'none' everywhere else.
//
// Title only in generateMetadata, with a description: ogImages() would name a
// social card under public/og/page/ that gen-og does not generate for these
// slugs (the same reason the earlier-sites page keeps the default card).
// ============================================================================

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { Link } from "@/i18n/navigation";
import { routing } from "@/i18n/routing";
import Header from "@/components/Header";
import SiteFooter from "@/components/SiteFooter";
import { captureDate, waybackUrl } from "@/content/about/earlier-sites";
import {
  CHANGE_KINDS,
  CLONE_CDX_READ_DATE,
  CLONE_EXPORT_DATE,
  CLONE_MADE,
  OLD_SITE_CLONES,
  captureFor,
  cloneUrl,
  cloneWrapperPath,
  findClone,
} from "@/content/about/old-sites";

/** Every locale times every clone: the static export needs the full list. */
export function generateStaticParams() {
  return routing.locales.flatMap((locale) => OLD_SITE_CLONES.map((c) => ({ locale, site: c.slug })));
}

/** Title and description per clone, from the authored copy (see the header on why no social card). */
export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string; site: string }>;
}): Promise<Metadata> {
  const { locale, site } = await params;
  const clone = findClone(site);
  if (!clone) return {};
  const t = await getTranslations({ locale, namespace: "earlierSites.clone" });
  return { title: t(`metaTitle.${clone.slug}`), description: t(`metaDescription.${clone.slug}`) };
}

/** The today's-equivalent links for the tools section, per clone. */
const TODAY_LINKS: Record<string, { href: string; key: "linkBits" | "linkCidr" | "linkCabling" }[]> = {
  "nutzmann-net-2004": [
    { href: "/tools/bits-bytes", key: "linkBits" },
    { href: "/tools/cidr", key: "linkCidr" },
    { href: "/learn/structured-cabling", key: "linkCabling" },
  ],
  "ntz-com-br-2013": [
    { href: "/tools/bits-bytes", key: "linkBits" },
    { href: "/learn/structured-cabling", key: "linkCabling" },
  ],
};

export default async function OldSiteClonePage({
  params,
}: {
  params: Promise<{ locale: string; site: string }>;
}) {
  const { locale, site } = await params;
  setRequestLocale(locale);
  const clone = findClone(site);
  if (!clone) notFound();
  const t = await getTranslations("earlierSites.clone");
  const tEs = await getTranslations("earlierSites");
  const tNav = await getTranslations("nav");
  const m = clone.manifest;
  // The other reconstruction, for the switcher.
  const others = OLD_SITE_CLONES.filter((c) => c.slug !== clone.slug);
  // The orphans as a set, for the mark in the page list.
  const orphans = new Set(m.orphans);
  // The dead paths and the unresolved references, named in the change lines.
  const deadList = Object.keys(m.dead).map((p) => `/${p}`).join(", ");
  const unresolvedList = m.unresolved.map((u) => `${u.url} (${u.page})`).join(", ");
  // The change kinds with a non-zero count, in display order.
  const kinds = CHANGE_KINDS.filter((k) => (m.changes[k] ?? 0) > 0);

  return (
    <>
      <a href="#main" className="skip-link" data-pagefind-ignore>
        {tNav("skipToContent")}
      </a>
      <Header />
      <main id="main">
        <article>
          {/* Hero: back link, eyebrow, title, lede with the generator's counts. */}
          <section className="era-hero">
            <div className="container era-container">
              <Link href="/about/earlier-sites" className="article-back">
                &#8592; {t("backToSites")}
              </Link>
              <p className="era-years mono">{t("eyebrow")}</p>
              <h1 className="era-title">{t(`title.${clone.slug}`)}</h1>
              <p className="era-subtitle">{t("lede", { exportDate: CLONE_EXPORT_DATE, pages: m.pageCount, assets: m.assets })}</p>
            </div>
          </section>

          {/* The frame: the clone at its own width, and the way out of the frame. */}
          <section className="section">
            <div className="container era-container">
              <div className="es-clone-bar">
                <a className="btn btn-primary es-clone-open" href={cloneUrl(clone)} target="_blank" rel="noopener noreferrer">
                  {t("openOwnWindow")} <span aria-hidden="true">&#8599;</span>
                </a>
                <span className="es-clone-url mono">{cloneUrl(clone)}</span>
              </div>
              <figure className="es-clone-figure">
                {/* The clone's own CSP allows this same-origin frame; nothing else on the site may be framed. */}
                <iframe className="es-clone-frame" src={cloneUrl(clone)} title={t("frameTitle", { domain: clone.domain, year: clone.year })} width={800} height={720} />
                <figcaption className="es-clone-caption">{t("frameNote")}</figcaption>
              </figure>
            </div>
          </section>

          {/* Kept and changed: the rules of the reproduction, with the generator's counts. */}
          <section className="section era-body-section">
            <div className="container era-container">
              <h2 className="es-h2">{t("keptTitle")}</h2>
              <p className="es-clone-body">{t("keptBody", { year: clone.year })}</p>
              <h2 className="es-h2 es-clone-h2">{t("changedTitle")}</h2>
              <ul className="es-clone-changes">
                {kinds.map((k) => (
                  <li key={k} className="es-clone-change">
                    <span className="es-clone-count mono">{m.changes[k]}</span>
                    <span>{t(`changes.${k}`, { count: m.changes[k], made: CLONE_MADE, pages: Object.keys(m.dead).length, list: deadList })}</span>
                  </li>
                ))}
                <li className="es-clone-change">
                  <span className="es-clone-count mono">{m.pageCount}</span>
                  <span>{t("noindexNote")}</span>
                </li>
              </ul>
              {m.unresolved.length > 0 && <p className="es-clone-note">{t("unresolvedNote", { count: m.unresolved.length, list: unresolvedList })}</p>}
              {m.orphans.length > 0 && <p className="es-clone-note">{t("orphansNote", { count: m.orphans.length })}</p>}
            </div>
          </section>

          {/* The pages: every file written, its title as published, its archive capture when the inventory has one. */}
          <section className="section">
            <div className="container era-container">
              <details className="es-inventory" open>
                <summary className="es-inventory-summary">
                  <span className="es-inventory-title">{t("pagesTitle")}</span>
                  <span className="es-inventory-count">{t("pagesSummary", { count: m.pageCount, orphans: m.orphans.length })}</span>
                </summary>
                <div className="es-table-wrap">
                  <table className="es-table">
                    <thead>
                      <tr>
                        <th scope="col">{tEs("colFile")}</th>
                        <th scope="col">{tEs("colTitle")}</th>
                        <th scope="col">{t("colArchive")}</th>
                      </tr>
                    </thead>
                    <tbody>
                      {m.pages.map((p) => {
                        const cap = captureFor(clone, p.path);
                        return (
                          <tr key={p.path}>
                            <td className="mono es-cell-file">
                              <a href={cloneUrl(clone, p.path)} target="_blank" rel="noopener noreferrer">{p.path}</a>
                              {orphans.has(p.path) && <span className="es-clone-orphan">{t("orphanMark")}</span>}
                            </td>
                            <td className="es-cell-title">{p.title || tEs("untitled")}</td>
                            <td className="es-cell-link">
                              {cap ? (
                                <a href={waybackUrl(cap)} rel="noopener noreferrer" target="_blank">{captureDate(cap)}</a>
                              ) : (
                                <span className="es-clone-nocapture">{t("noCapture")}</span>
                              )}
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              </details>
            </div>
          </section>

          {/* What is not here, the tools that were there, how the path is served. */}
          <section className="section">
            <div className="container era-container">
              <h2 className="es-h2">{t("excludedTitle")}</h2>
              <p className="es-clone-body">{t("excludedBody", { count: m.excluded.length })}</p>
              <h2 className="es-h2 es-clone-h2">{t("toolsTitle")}</h2>
              <p className="es-clone-body">{t(`toolsBody.${clone.slug}`)}</p>
              <p className="es-clone-links">
                <a href={cloneUrl(clone, clone.calculator)} target="_blank" rel="noopener noreferrer">{t("toolCalculator")} <span aria-hidden="true">&#8599;</span></a>
                {/* The never-published tools: their reconstruction pages, at the paths the site linked. */}
                {Object.keys(m.toolsMissing).map((path) => (
                  <a key={path} href={cloneUrl(clone, path)} target="_blank" rel="noopener noreferrer" className="mono">/{path} <span aria-hidden="true">&#8599;</span></a>
                ))}
                {TODAY_LINKS[clone.slug].map((l) => (
                  <Link key={l.href} href={l.href}>{t("toolToday")}: {tEs(l.key)} <span aria-hidden="true">&#8594;</span></Link>
                ))}
              </p>
              <h2 className="es-h2 es-clone-h2">{t("headersTitle")}</h2>
              <p className="es-clone-body">
                {t.rich("headersBody", { cspTool: (chunks) => <Link href="/tools/csp-evaluator">{chunks}</Link> })}
              </p>
            </div>
          </section>

          {/* The other reconstruction and the inventory. */}
          <section className="section">
            <div className="container era-container">
              <h2 className="es-h2">{t("switchTitle")}</h2>
              <ul className="es-links">
                {others.map((o) => (
                  <li key={o.slug}><Link href={cloneWrapperPath(o)}>{t(`title.${o.slug}`)}</Link></li>
                ))}
                <li><Link href={`/about/earlier-sites#${clone.era}`}>{t("switchInventory")}</Link></li>
              </ul>
            </div>
          </section>

          {/* Sources: the export, the archive index, the encodes, the generator. */}
          <section className="section era-closer-section">
            <div className="container era-container">
              <h2 className="es-h2">{tEs("sourcesTitle")}</h2>
              <p className="es-sources">{t("sourcesBody", { exportDate: CLONE_EXPORT_DATE, cdxDate: CLONE_CDX_READ_DATE, made: CLONE_MADE })}</p>
            </div>
          </section>
        </article>
      </main>
      <SiteFooter />
    </>
  );
}
