// ============================================================================
// src/lib/tools/python-playground/engine.ts
// ----------------------------------------------------------------------------
// GENERATED by scripts/gen-wasm-engine.mts on 2026-10-04 from node_modules/pyodide
// 314.0.7. DO NOT EDIT BY HAND: run `npm run gen-wasm-engine` after a
// deliberate upgrade and review the diff. The prebuild guard
// scripts/check-wasm-engines.mts refuses a build whose node_modules disagree
// with this file, and copies the five browser files into public/wasm/ (which
// is not committed) only after their digests match.
//
// Every figure here is a fact about the pinned package: the version and
// licence from its package.json, the Python version, ABI and platform from its
// own pyodide-lock.json, the sizes and SHA-256 digests measured on the files,
// the standard-library module names and the import failures measured by
// importing every module in the real engine under Node.
// ============================================================================

/** One of the files the browser downloads on first use. */
export interface EngineFile {
  /** File name under publicPath. */
  name: string;
  /** Size in bytes as shipped (before any transfer compression). */
  bytes: number;
  /** SHA-256 of the file, lower-case hex. */
  sha256: string;
}

/** The engine: what runs, where it comes from, what it costs. */
export const ENGINE = Object.freeze({
  /** The interpreter's name as the pill shows it. */
  name: "Pyodide",
  /** Who compiles CPython to WebAssembly. */
  project: "the Pyodide project",
  /** The project's site and repository, under the url: key the citation liveness audit collects (check-citation-fields). */
  links: [
    { label: "Pyodide", url: "https://pyodide.org/" },
    { label: "pyodide/pyodide on GitHub", url: "https://github.com/pyodide/pyodide" },
  ] as readonly { label: string; url: string }[],
  /** The pinned npm package and its version. */
  npmPackage: "pyodide",
  version: "314.0.7",
  /** The lockfile's integrity for that package (npm verifies it on install). */
  npmIntegrity: "sha512-0YvXxEhfEdpLfb/XkM2BFAeMROq0iMUX2bzzH9pOttyMcWkwq+HbE5uyuGD82LN7y2q+SNvi/6V5JEsOlD2R1A==",
  /** The Python the engine embeds, from its own lock file and confirmed by the running interpreter. */
  python: "3.14.2",
  abi: "2026_0",
  platform: "emscripten_5_0_3",
  arch: "wasm32",
  /** The licence the package declares (SPDX). */
  licence: "MPL-2.0",
  /** Where the files are served from on this site, versioned so a cache never mixes two engines. */
  publicPath: "/wasm/pyodide/314.0.7/",
  /** The files, in the order the loader fetches them. */
  files: [
    { name: "pyodide.mjs", bytes: 17931, sha256: "6f1d60f7bf529beb300f0f47983c921d3982363640ba20af0e38efdddbc66109" },
    { name: "pyodide.asm.mjs", bytes: 1250344, sha256: "f7cdc8ece80678ceb712f8e65ebe6d3a83203a180c399865f49612a051693635" },
    { name: "pyodide.asm.wasm", bytes: 9598218, sha256: "cc36e3cab04fdfc9a63ff13eb52eae2b911bf46c025cc7b281f394bd3de1d5e6" },
    { name: "python_stdlib.zip", bytes: 2545637, sha256: "fa1957e5777068fc4f7437f96d860ae2fbe9c19732ba06c84e004ec16dd7dd7a" },
    { name: "pyodide-lock.json", bytes: 119077, sha256: "5dc2fc119108bc148c7457dc86e7675b5c87e1cafd420b9c34c1eaef7b36c010" },
  ] as readonly EngineFile[],
  /** The sum of the file sizes: the first-use download before transfer compression. */
  bytesWire: 13531207,
  /** How many packages the distribution's lock file lists; none of them ships here (decision 4). */
  packagesInDistribution: 357,
  /** Standard-library modules reported by the engine, and how many fail to import in this build. */
  stdlibModules: 297,
  stdlibUnavailable: 40,
  /** The novelty modules the import probe skipped on purpose. */
  probeSkipped: ["antigravity","this","__hello__","__phello__"] as readonly string[],
  /** The date the figures were read from the package. */
  generatedAt: "2026-10-04",
});

/** The package names in the engine's own lock file: available to Pyodide, not loaded in this version. */
export const DISTRIBUTION_PACKAGES: readonly string[] = [
  "Bottleneck", "Cartopy", "Cartopy-tests", "Jinja2", "MarkupSafe", "Pillow", "Pygments",
  "affine", "affine-tests", "aiohappyeyeballs", "aiohttp", "aiohttp-tests", "aiosignal",
  "altair", "annotated-doc", "annotated-types", "annotated-types-tests", "anyio", "argon2-cffi",
  "argon2-cffi-bindings", "astropy", "astropy_iers_data", "astropy_iers_data-tests", "asttokens",
  "async-timeout", "asyncpg", "atomicwrites", "attrs", "audioop-lts", "b2d", "bcrypt",
  "beautifulsoup4", "bilby.cython", "bilby.cython-tests", "biopython", "bitarray",
  "bitarray-tests", "bitstring", "bleach", "bokeh", "boost-histogram", "brotli", "cachetools",
  "casadi", "cbor-diag", "certifi", "cffi", "cffi_example", "cftime", "charset-normalizer",
  "clarabel", "click", "cligj", "clingo", "cloudpickle", "cmyt", "cobs", "colorspacious",
  "contourpy", "coolprop", "coolprop-tests", "coverage", "crc32c", "crcmod", "cryptography",
  "cssselect", "cvxpy-base", "cvxpy-base-tests", "cycler", "cysignals", "cytoolz",
  "cytoolz-tests", "decorator", "demes", "deprecated", "deprecation", "diskcache", "distlib",
  "distro", "dnspython", "docutils", "donfig", "donfig-tests", "duckdb", "ewah_bool_utils",
  "ewah_bool_utils-tests", "exceptiongroup", "executing", "fastapi", "fiona", "fonttools",
  "freesasa", "frozenlist", "fsspec", "fsspec-tests", "future", "future-tests", "galpy",
  "geopandas", "geopandas-tests", "gmpy2", "google-crc32c", "h11", "h3", "h5py", "h5py-tests",
  "healpy", "healpy-tests", "highspy", "html5lib", "httpcore", "httpx", "idna", "igraph",
  "imageio", "iminuit", "iniconfig", "inspice", "ipython", "ipython-tests", "jedi", "jedi-tests",
  "jiter", "joblib", "joblib-tests", "jsonpatch", "jsonpointer", "jsonschema",
  "jsonschema-tests", "jsonschema_specifications", "jsonschema_specifications-tests",
  "kiwisolver", "lakers-python", "lazy-object-proxy", "lazy_loader", "libblis", "libcrc32c",
  "libcst", "libcst-tests", "libgdal", "libgeos", "libhdf5", "libheif", "libngspice",
  "libopenblas", "libproj", "librt", "libsuitesparse", "libtaglib", "lightgbm", "logbook",
  "lxml", "lz4", "matplotlib", "matplotlib-inline", "matplotlib-tests", "memory-allocator",
  "micropip", "ml_dtypes", "mmh3", "more-itertools", "mpmath", "mpmath-tests", "msgpack",
  "msgspec", "msprime", "multidict", "munch", "mypy", "mypy-tests", "mysqlclient", "narwhals",
  "ndindex", "ndindex-tests", "netcdf4", "networkx", "networkx-tests", "newick", "nh3", "nlopt",
  "nltk", "nltk-tests", "numcodecs", "numcodecs-tests", "numpy", "numpy-tests", "openai",
  "opencv-python", "optlang", "optlang-tests", "orjson", "packaging", "pandas", "pandas-tests",
  "parso", "patsy", "patsy-tests", "pcodec", "peewee", "peewee-tests", "phispy", "pi-heif",
  "pillow-heif", "pkgconfig", "platformdirs", "pluggy", "ply", "polars", "prompt_toolkit",
  "propcache", "protobuf", "psycopg", "psycopg-binary", "psycopg-c", "pure-eval", "py",
  "pyarrow", "pyclipper", "pycparser", "pycryptodome", "pycryptodome-tests", "pydantic",
  "pydantic_core", "pydoc_data", "pyerfa", "pyerfa-tests", "pygame-ce", "pyheif", "pyiceberg",
  "pyinstrument", "pymongo", "pynacl", "pyodide-http", "pyodide-unix-timezones", "pyparsing",
  "pyproj", "pyroaring", "pyrodigal", "pyrodigal-tests", "pyrsistent", "pysam", "pyshp",
  "pytaglib", "pytest", "pytest-asyncio", "pytest-benchmark", "pytest_httpx", "python-calamine",
  "python-dateutil", "python-flirt", "python-sat", "python-solvespace", "pytz", "pywavelets",
  "pywavelets-tests", "pyxirr", "pyyaml", "rasterio", "rateslib", "rebound", "reboundx",
  "referencing", "referencing-tests", "regex", "regex-tests", "requests", "retrying", "rich",
  "rpds-py", "ruamel.yaml", "safetensors", "scikit-image", "scikit-image-tests", "scikit-learn",
  "scikit-learn-tests", "scipy", "scipy-tests", "screed", "screed-tests", "sentencepiece",
  "setuptools", "setuptools-tests", "shapely", "shapely-tests", "simplejson", "simplejson-tests",
  "sisl", "sisl-tests", "six", "smart-open", "sniffio", "sniffio-tests", "sortedcontainers",
  "soundfile", "soupsieve", "sourmash", "soxr", "sparseqr", "sqlalchemy", "sqlalchemy-tests",
  "stack-data", "starlette", "statsmodels", "strictyaml", "svgwrite", "swiglpk", "sympy",
  "sympy-tests", "tblib", "termcolor", "texttable", "texture2ddecoder", "threadpoolctl",
  "tiktoken", "tomli", "tomli-w", "toolz", "toolz-tests", "tqdm", "traitlets", "traitlets-tests",
  "traits", "traits-tests", "tree-sitter", "tree-sitter-go", "tree-sitter-java",
  "tree-sitter-python", "tskit", "typing-extensions", "typing-inspection", "tzdata", "ujson",
  "uncertainties", "unyt", "unyt-tests", "urllib3", "vega-datasets", "vega-datasets-tests",
  "vrplib", "wcwidth", "webencodings", "wordcloud", "wrapt", "xarray", "xarray-tests", "xgboost",
  "xlrd", "xxhash", "xyzservices", "xyzservices-tests", "yarl", "yt", "zarr", "zarr-tests",
  "zengl", "zfpy", "zstandard",
];

/** sys.stdlib_module_names of the embedded Python. */
export const STDLIB_MODULES: readonly string[] = [
  "__future__", "_abc", "_aix_support", "_android_support", "_apple_support", "_ast",
  "_ast_unparse", "_asyncio", "_bisect", "_blake2", "_bz2", "_codecs", "_codecs_cn",
  "_codecs_hk", "_codecs_iso2022", "_codecs_jp", "_codecs_kr", "_codecs_tw", "_collections",
  "_collections_abc", "_colorize", "_compat_pickle", "_contextvars", "_csv", "_ctypes",
  "_curses", "_curses_panel", "_datetime", "_dbm", "_decimal", "_elementtree",
  "_frozen_importlib", "_frozen_importlib_external", "_functools", "_gdbm", "_hashlib", "_heapq",
  "_hmac", "_imp", "_interpchannels", "_interpqueues", "_interpreters", "_io", "_ios_support",
  "_json", "_locale", "_lsprof", "_lzma", "_markupbase", "_md5", "_multibytecodec",
  "_multiprocessing", "_opcode", "_opcode_metadata", "_operator", "_osx_support", "_overlapped",
  "_pickle", "_posixshmem", "_posixsubprocess", "_py_abc", "_py_warnings", "_pydatetime",
  "_pydecimal", "_pyio", "_pylong", "_pyrepl", "_queue", "_random", "_remote_debugging",
  "_scproxy", "_sha1", "_sha2", "_sha3", "_signal", "_sitebuiltins", "_socket", "_sqlite3",
  "_sre", "_ssl", "_stat", "_statistics", "_string", "_strptime", "_struct", "_suggestions",
  "_symtable", "_sysconfig", "_thread", "_threading_local", "_tkinter", "_tokenize",
  "_tracemalloc", "_types", "_typing", "_uuid", "_warnings", "_weakref", "_weakrefset",
  "_winapi", "_wmi", "_zoneinfo", "_zstd", "abc", "annotationlib", "antigravity", "argparse",
  "array", "ast", "asyncio", "atexit", "base64", "bdb", "binascii", "bisect", "builtins", "bz2",
  "cProfile", "calendar", "cmath", "cmd", "code", "codecs", "codeop", "collections", "colorsys",
  "compileall", "compression", "concurrent", "configparser", "contextlib", "contextvars", "copy",
  "copyreg", "csv", "ctypes", "curses", "dataclasses", "datetime", "dbm", "decimal", "difflib",
  "dis", "doctest", "email", "encodings", "ensurepip", "enum", "errno", "faulthandler", "fcntl",
  "filecmp", "fileinput", "fnmatch", "fractions", "ftplib", "functools", "gc", "genericpath",
  "getopt", "getpass", "gettext", "glob", "graphlib", "grp", "gzip", "hashlib", "heapq", "hmac",
  "html", "http", "idlelib", "imaplib", "importlib", "inspect", "io", "ipaddress", "itertools",
  "json", "keyword", "linecache", "locale", "logging", "lzma", "mailbox", "marshal", "math",
  "mimetypes", "mmap", "modulefinder", "msvcrt", "multiprocessing", "netrc", "nt", "ntpath",
  "nturl2path", "numbers", "opcode", "operator", "optparse", "os", "pathlib", "pdb", "pickle",
  "pickletools", "pkgutil", "platform", "plistlib", "poplib", "posix", "posixpath", "pprint",
  "profile", "pstats", "pty", "pwd", "py_compile", "pyclbr", "pydoc", "pydoc_data", "pyexpat",
  "queue", "quopri", "random", "re", "readline", "reprlib", "resource", "rlcompleter", "runpy",
  "sched", "secrets", "select", "selectors", "shelve", "shlex", "shutil", "signal", "site",
  "smtplib", "socket", "socketserver", "sqlite3", "sre_compile", "sre_constants", "sre_parse",
  "ssl", "stat", "statistics", "string", "stringprep", "struct", "subprocess", "symtable", "sys",
  "sysconfig", "syslog", "tabnanny", "tarfile", "tempfile", "termios", "textwrap", "this",
  "threading", "time", "timeit", "tkinter", "token", "tokenize", "tomllib", "trace", "traceback",
  "tracemalloc", "tty", "turtle", "turtledemo", "types", "typing", "unicodedata", "unittest",
  "urllib", "uuid", "venv", "warnings", "wave", "weakref", "webbrowser", "winreg", "winsound",
  "wsgiref", "xml", "xmlrpc", "zipapp", "zipfile", "zipimport", "zlib", "zoneinfo",
];

/** Standard-library modules that fail to import in this WebAssembly build, with the engine's own error. */
export const STDLIB_UNAVAILABLE: readonly { module: string; error: string }[] = [
  { module: "_aix_support", error: "ModuleNotFoundError: No module named '_aix_support'" },
  { module: "_android_support", error: "ModuleNotFoundError: No module named '_android_support'" },
  { module: "_apple_support", error: "ModuleNotFoundError: No module named '_apple_support'" },
  { module: "_curses", error: "ModuleNotFoundError: No module named '_curses'" },
  { module: "_curses_panel", error: "ModuleNotFoundError: No module named '_curses_panel'" },
  { module: "_dbm", error: "ModuleNotFoundError: No module named '_dbm'" },
  { module: "_gdbm", error: "ModuleNotFoundError: No module named '_gdbm'" },
  { module: "_hashlib", error: "ModuleNotFoundError: No module named '_hashlib'" },
  { module: "_interpchannels", error: "ModuleNotFoundError: No module named '_interpchannels'" },
  { module: "_interpqueues", error: "ModuleNotFoundError: No module named '_interpqueues'" },
  { module: "_interpreters", error: "ModuleNotFoundError: No module named '_interpreters'" },
  { module: "_ios_support", error: "ModuleNotFoundError: No module named '_ios_support'" },
  { module: "_multiprocessing", error: "ModuleNotFoundError: No module named '_multiprocessing'" },
  { module: "_osx_support", error: "ModuleNotFoundError: No module named '_osx_support'" },
  { module: "_overlapped", error: "ModuleNotFoundError: No module named '_overlapped'" },
  { module: "_posixshmem", error: "ModuleNotFoundError: No module named '_posixshmem'" },
  { module: "_pydecimal", error: "ModuleNotFoundError: No module named '_pydecimal'" },
  { module: "_scproxy", error: "ModuleNotFoundError: No module named '_scproxy'" },
  { module: "_tkinter", error: "ModuleNotFoundError: No module named '_tkinter'" },
  { module: "_uuid", error: "ModuleNotFoundError: No module named '_uuid'" },
  { module: "_winapi", error: "ModuleNotFoundError: No module named '_winapi'" },
  { module: "_wmi", error: "ModuleNotFoundError: No module named '_wmi'" },
  { module: "curses", error: "ModuleNotFoundError: No module named 'curses'" },
  { module: "dbm", error: "ModuleNotFoundError: No module named 'dbm'" },
  { module: "ensurepip", error: "ModuleNotFoundError: No module named 'ensurepip'" },
  { module: "grp", error: "ModuleNotFoundError: No module named 'grp'" },
  { module: "idlelib", error: "ModuleNotFoundError: No module named 'idlelib'" },
  { module: "msvcrt", error: "ModuleNotFoundError: No module named 'msvcrt'" },
  { module: "nt", error: "ModuleNotFoundError: No module named 'nt'" },
  { module: "pwd", error: "ModuleNotFoundError: No module named 'pwd'" },
  { module: "pydoc_data", error: "ModuleNotFoundError: No module named 'pydoc_data'" },
  { module: "readline", error: "ModuleNotFoundError: No module named 'readline'" },
  { module: "resource", error: "ModuleNotFoundError: No module named 'resource'" },
  { module: "syslog", error: "ModuleNotFoundError: No module named 'syslog'" },
  { module: "tkinter", error: "ModuleNotFoundError: No module named 'tkinter'" },
  { module: "turtle", error: "ModuleNotFoundError: No module named 'turtle'" },
  { module: "turtledemo", error: "ModuleNotFoundError: No module named 'turtledemo'" },
  { module: "venv", error: "ModuleNotFoundError: No module named 'venv'" },
  { module: "winreg", error: "ModuleNotFoundError: No module named 'winreg'" },
  { module: "winsound", error: "ModuleNotFoundError: No module named 'winsound'" },
];
