// ============================================================================
// src/lib/tools/http-message-decoder/registry-fields.ts
// ----------------------------------------------------------------------------
// THE IANA HTTP FIELD NAME REGISTRY, permanent, deprecated and obsoleted rows,
// read 2026-10-05 from https://www.iana.org/assignments/http-fields/field-names.csv
// (the provisional rows are left out: a decoder should not promote a provisional
// name to "registered"). Each row keeps the registry's own reference text. The
// `group` column is editorial: it files each field under the part of the HTTP
// specifications that defines it (RFC 9110 sections 6 to 14, RFC 9111 caching,
// RFC 9112 framing, the cookie draft, the WHATWG Fetch and HTML specifications
// for the security and CORS fields), so the decoder can present a message's
// fields by what they are for rather than in paste order.
// ============================================================================

/** How the registry files a name. */
export type FieldStatus = "permanent" | "deprecated" | "obsoleted";

/** The editorial group a field is presented under. */
export type FieldGroup = "framing" | "routing" | "message" | "representation" | "request-context" | "response-context" | "authentication" | "negotiation" | "conditional" | "range" | "caching" | "cookies" | "security-policy" | "cors" | "fetch-metadata" | "websocket" | "proxies" | "webdav" | "other-registered";

/** One registry row. */
export interface FieldRecord {
  /** The field name as registered (its casing is the conventional one). */
  name: string;
  /** permanent, deprecated or obsoleted. */
  status: FieldStatus;
  /** The registry's reference, as written there. */
  reference: string;
  /** The editorial group. */
  group: FieldGroup;
}

/** The rows, in registry order. */
export const FIELD_REGISTRY: readonly FieldRecord[] = [
  { name: "A-IM", status: "permanent", reference: "RFC 3229: Delta encoding in HTTP", group: "representation" },
  { name: "Accept", status: "permanent", reference: "RFC 9110, Section 12.5.1: HTTP Semantics", group: "negotiation" },
  { name: "Accept-Additions", status: "permanent", reference: "RFC 2324: Hyper Text Coffee Pot Control Protocol (HTCPCP/1.0)", group: "other-registered" },
  { name: "Accept-CH", status: "permanent", reference: "RFC 8942, Section 3.1: HTTP Client Hints", group: "negotiation" },
  { name: "Accept-Charset", status: "deprecated", reference: "RFC 9110, Section 12.5.2: HTTP Semantics", group: "negotiation" },
  { name: "Accept-Datetime", status: "permanent", reference: "RFC 7089: HTTP Framework for Time-Based Access to Resource States -- Memento", group: "negotiation" },
  { name: "Accept-Encoding", status: "permanent", reference: "RFC 9110, Section 12.5.3: HTTP Semantics", group: "negotiation" },
  { name: "Accept-Features", status: "permanent", reference: "RFC 2295: Transparent Content Negotiation in HTTP", group: "negotiation" },
  { name: "Accept-Language", status: "permanent", reference: "RFC 9110, Section 12.5.4: HTTP Semantics", group: "negotiation" },
  { name: "Accept-Patch", status: "permanent", reference: "RFC 5789: PATCH Method for HTTP", group: "negotiation" },
  { name: "Accept-Post", status: "permanent", reference: "Linked Data Platform 1.0", group: "negotiation" },
  { name: "Accept-Query", status: "permanent", reference: "RFC 10008, Section 3: The HTTP QUERY Method", group: "negotiation" },
  { name: "Accept-Ranges", status: "permanent", reference: "RFC 9110, Section 14.3: HTTP Semantics", group: "range" },
  { name: "Accept-Signature", status: "permanent", reference: "RFC 9421, Section 5.1: HTTP Message Signatures", group: "authentication" },
  { name: "Access-Control", status: "obsoleted", reference: "Access Control for Cross-site Requests", group: "other-registered" },
  { name: "Access-Control-Allow-Credentials", status: "permanent", reference: "Fetch", group: "cors" },
  { name: "Access-Control-Allow-Headers", status: "permanent", reference: "Fetch", group: "cors" },
  { name: "Access-Control-Allow-Methods", status: "permanent", reference: "Fetch", group: "cors" },
  { name: "Access-Control-Allow-Origin", status: "permanent", reference: "Fetch", group: "cors" },
  { name: "Access-Control-Expose-Headers", status: "permanent", reference: "Fetch", group: "cors" },
  { name: "Access-Control-Max-Age", status: "permanent", reference: "Fetch", group: "cors" },
  { name: "Access-Control-Request-Headers", status: "permanent", reference: "Fetch", group: "cors" },
  { name: "Access-Control-Request-Method", status: "permanent", reference: "Fetch", group: "cors" },
  { name: "Age", status: "permanent", reference: "RFC 9111, Section 5.1: HTTP Caching", group: "caching" },
  { name: "Allow", status: "permanent", reference: "RFC 9110, Section 10.2.1: HTTP Semantics", group: "response-context" },
  { name: "ALPN", status: "permanent", reference: "RFC 7639, Section 2: The ALPN HTTP Header Field", group: "other-registered" },
  { name: "Alt-Svc", status: "permanent", reference: "RFC 7838: HTTP Alternative Services", group: "proxies" },
  { name: "Alt-Used", status: "permanent", reference: "RFC 7838: HTTP Alternative Services", group: "proxies" },
  { name: "Alternates", status: "permanent", reference: "RFC 2295: Transparent Content Negotiation in HTTP", group: "negotiation" },
  { name: "Apply-To-Redirect-Ref", status: "permanent", reference: "RFC 4437: Web Distributed Authoring and Versioning (WebDAV) Redirect Reference Resources", group: "webdav" },
  { name: "Authentication-Control", status: "permanent", reference: "RFC 8053, Section 4: HTTP Authentication Extensions for Interactive Clients", group: "authentication" },
  { name: "Authentication-Info", status: "permanent", reference: "RFC 9110, Section 11.6.3: HTTP Semantics", group: "authentication" },
  { name: "Authorization", status: "permanent", reference: "RFC 9110, Section 11.6.2: HTTP Semantics", group: "authentication" },
  { name: "Available-Dictionary", status: "permanent", reference: "RFC 9842, Section 2.2: Compression Dictionary Transport", group: "negotiation" },
  { name: "C-Ext", status: "obsoleted", reference: "RFC 2774: An HTTP Extension Framework", group: "other-registered" },
  { name: "C-Man", status: "obsoleted", reference: "RFC 2774: An HTTP Extension Framework", group: "other-registered" },
  { name: "C-Opt", status: "obsoleted", reference: "RFC 2774: An HTTP Extension Framework", group: "other-registered" },
  { name: "C-PEP", status: "obsoleted", reference: "PEP - an Extension Mechanism for HTTP", group: "other-registered" },
  { name: "C-PEP-Info", status: "deprecated", reference: "PEP - an Extension Mechanism for HTTP", group: "other-registered" },
  { name: "Cache-Control", status: "permanent", reference: "RFC 9111, Section 5.2: HTTP Caching", group: "caching" },
  { name: "Cache-Group-Invalidation", status: "permanent", reference: "RFC9875: HTTP Cache Groups", group: "caching" },
  { name: "Cache-Groups", status: "permanent", reference: "RFC9875: HTTP Cache Groups", group: "caching" },
  { name: "Cache-Status", status: "permanent", reference: "RFC 9211: The Cache-Status HTTP Response Header Field", group: "caching" },
  { name: "Cal-Managed-ID", status: "permanent", reference: "RFC 8607, Section 5.1: Calendaring Extensions to WebDAV (CalDAV): Managed Attachments", group: "webdav" },
  { name: "CalDAV-Timezones", status: "permanent", reference: "RFC 7809, Section 7.1: Calendaring Extensions to WebDAV (CalDAV): Time Zones by Reference", group: "webdav" },
  { name: "Capsule-Protocol", status: "permanent", reference: "RFC 9297: HTTP Datagrams and the Capsule Protocol", group: "other-registered" },
  { name: "CDN-Cache-Control", status: "permanent", reference: "RFC 9213: Targeted HTTP Cache Control", group: "caching" },
  { name: "CDN-Loop", status: "permanent", reference: "RFC 8586: Loop Detection in Content Delivery Networks (CDNs)", group: "proxies" },
  { name: "Cert-Not-After", status: "permanent", reference: "RFC 8739, Section 3.3: Support for Short-Term, Automatically Renewed (STAR) Certificates in the ACME", group: "other-registered" },
  { name: "Cert-Not-Before", status: "permanent", reference: "RFC 8739, Section 3.3: Support for Short-Term, Automatically Renewed (STAR) Certificates in the ACME", group: "other-registered" },
  { name: "Clear-Site-Data", status: "permanent", reference: "Clear Site Data", group: "security-policy" },
  { name: "Client-Cert", status: "permanent", reference: "RFC 9440, Section 2: Client-Cert HTTP Header Field", group: "authentication" },
  { name: "Client-Cert-Chain", status: "permanent", reference: "RFC 9440, Section 2: Client-Cert HTTP Header Field", group: "authentication" },
  { name: "Close", status: "permanent", reference: "RFC 9112, Section 9.6: HTTP/1.1", group: "framing" },
  { name: "Connection", status: "permanent", reference: "RFC 9110, Section 7.6.1: HTTP Semantics", group: "routing" },
  { name: "Content-Base", status: "obsoleted", reference: "RFC 2068: Hypertext Transfer Protocol -- HTTP/1.1", group: "representation" },
  { name: "Content-Digest", status: "permanent", reference: "RFC 9530, Section 2: Digest Fields", group: "representation" },
  { name: "Content-Disposition", status: "permanent", reference: "RFC 6266: Use of the Content-Disposition Header Field in the Hypertext Transfer Protocol", group: "representation" },
  { name: "Content-Encoding", status: "permanent", reference: "RFC 9110, Section 8.4: HTTP Semantics", group: "representation" },
  { name: "Content-ID", status: "deprecated", reference: "The HTTP Distribution and Replication Protocol", group: "representation" },
  { name: "Content-Language", status: "permanent", reference: "RFC 9110, Section 8.5: HTTP Semantics", group: "representation" },
  { name: "Content-Length", status: "permanent", reference: "RFC 9110, Section 8.6: HTTP Semantics", group: "representation" },
  { name: "Content-Location", status: "permanent", reference: "RFC 9110, Section 8.7: HTTP Semantics", group: "representation" },
  { name: "Content-MD5", status: "obsoleted", reference: "RFC 2616, Section 14.15: Hypertext Transfer Protocol -- HTTP/1.1", group: "representation" },
  { name: "Content-Range", status: "permanent", reference: "RFC 9110, Section 14.4: HTTP Semantics", group: "range" },
  { name: "Content-Script-Type", status: "obsoleted", reference: "HTML 4.01 Specification", group: "other-registered" },
  { name: "Content-Security-Policy", status: "permanent", reference: "Content Security Policy Level 3", group: "security-policy" },
  { name: "Content-Security-Policy-Report-Only", status: "permanent", reference: "Content Security Policy Level 3", group: "security-policy" },
  { name: "Content-Style-Type", status: "obsoleted", reference: "HTML 4.01 Specification", group: "other-registered" },
  { name: "Content-Type", status: "permanent", reference: "RFC 9110, Section 8.3: HTTP Semantics", group: "representation" },
  { name: "Content-Version", status: "obsoleted", reference: "RFC 2068: Hypertext Transfer Protocol -- HTTP/1.1", group: "representation" },
  { name: "Cookie", status: "permanent", reference: "RFC-ietf-httpbis-rfc6265bis-22, Section 5.8.1: Cookies: HTTP State Management Mechanism", group: "cookies" },
  { name: "Cookie2", status: "obsoleted", reference: "RFC 2965: HTTP State Management Mechanism", group: "cookies" },
  { name: "Cross-Origin-Embedder-Policy", status: "permanent", reference: "HTML", group: "security-policy" },
  { name: "Cross-Origin-Embedder-Policy-Report-Only", status: "permanent", reference: "HTML", group: "security-policy" },
  { name: "Cross-Origin-Opener-Policy", status: "permanent", reference: "HTML", group: "security-policy" },
  { name: "Cross-Origin-Opener-Policy-Report-Only", status: "permanent", reference: "HTML", group: "security-policy" },
  { name: "Cross-Origin-Resource-Policy", status: "permanent", reference: "Fetch", group: "security-policy" },
  { name: "DASL", status: "permanent", reference: "RFC 5323: Web Distributed Authoring and Versioning (WebDAV) SEARCH", group: "webdav" },
  { name: "Date", status: "permanent", reference: "RFC 9110, Section 6.6.1: HTTP Semantics", group: "message" },
  { name: "DAV", status: "permanent", reference: "RFC 4918: HTTP Extensions for Web Distributed Authoring and Versioning (WebDAV)", group: "webdav" },
  { name: "Default-Style", status: "obsoleted", reference: "HTML 4.01 Specification", group: "other-registered" },
  { name: "Delta-Base", status: "permanent", reference: "RFC 3229: Delta encoding in HTTP", group: "representation" },
  { name: "Deprecation", status: "permanent", reference: "RFC 9745, Section 2: The Deprecation HTTP Response Header Field", group: "representation" },
  { name: "Depth", status: "permanent", reference: "RFC 4918: HTTP Extensions for Web Distributed Authoring and Versioning (WebDAV)", group: "webdav" },
  { name: "Derived-From", status: "obsoleted", reference: "RFC 2068: Hypertext Transfer Protocol -- HTTP/1.1", group: "representation" },
  { name: "Destination", status: "permanent", reference: "RFC 4918: HTTP Extensions for Web Distributed Authoring and Versioning (WebDAV)", group: "webdav" },
  { name: "Detached-JWS", status: "permanent", reference: "RFC 9635: Grant Negotiation and Authorization Protocol (GNAP)", group: "authentication" },
  { name: "Differential-ID", status: "deprecated", reference: "The HTTP Distribution and Replication Protocol", group: "other-registered" },
  { name: "Dictionary-ID", status: "permanent", reference: "RFC 9842, Section 2.3: Compression Dictionary Transport", group: "negotiation" },
  { name: "Digest", status: "obsoleted", reference: "RFC 3230: Instance Digests in HTTP", group: "representation" },
  { name: "DPoP", status: "permanent", reference: "RFC 9449: OAuth 2.0 Demonstrating Proof of Possession (DPoP)", group: "authentication" },
  { name: "DPoP-Nonce", status: "permanent", reference: "RFC 9449: OAuth 2.0 Demonstrating Proof of Possession (DPoP)", group: "authentication" },
  { name: "Early-Data", status: "permanent", reference: "RFC 8470: Using Early Data in HTTP", group: "other-registered" },
  { name: "ETag", status: "permanent", reference: "RFC 9110, Section 8.8.3: HTTP Semantics", group: "representation" },
  { name: "Expect", status: "permanent", reference: "RFC 9110, Section 10.1.1: HTTP Semantics", group: "request-context" },
  { name: "Expect-CT", status: "deprecated", reference: "RFC 9163: Expect-CT Extension for HTTP", group: "security-policy" },
  { name: "Expires", status: "permanent", reference: "RFC 9111, Section 5.3: HTTP Caching", group: "caching" },
  { name: "Ext", status: "obsoleted", reference: "RFC 2774: An HTTP Extension Framework", group: "other-registered" },
  { name: "Forwarded", status: "permanent", reference: "RFC 7239: Forwarded HTTP Extension", group: "proxies" },
  { name: "From", status: "permanent", reference: "RFC 9110, Section 10.1.2: HTTP Semantics", group: "request-context" },
  { name: "GetProfile", status: "obsoleted", reference: "Implementation of OPS Over HTTP", group: "other-registered" },
  { name: "Hobareg", status: "permanent", reference: "RFC 7486, Section 6.1.1: HTTP Origin-Bound Authentication (HOBA)", group: "authentication" },
  { name: "Host", status: "permanent", reference: "RFC 9110, Section 7.2: HTTP Semantics", group: "routing" },
  { name: "HTTP2-Settings", status: "obsoleted", reference: "RFC 7540, Section 3.2.1: Hypertext Transfer Protocol Version 2 (HTTP/2)", group: "other-registered" },
  { name: "If", status: "permanent", reference: "RFC 4918: HTTP Extensions for Web Distributed Authoring and Versioning (WebDAV)", group: "webdav" },
  { name: "If-Match", status: "permanent", reference: "RFC 9110, Section 13.1.1: HTTP Semantics", group: "conditional" },
  { name: "If-Modified-Since", status: "permanent", reference: "RFC 9110, Section 13.1.3: HTTP Semantics", group: "conditional" },
  { name: "If-None-Match", status: "permanent", reference: "RFC 9110, Section 13.1.2: HTTP Semantics", group: "conditional" },
  { name: "If-Range", status: "permanent", reference: "RFC 9110, Section 13.1.5: HTTP Semantics", group: "conditional" },
  { name: "If-Schedule-Tag-Match", status: "permanent", reference: "RFC 6338: Scheduling Extensions to CalDAV", group: "webdav" },
  { name: "If-Unmodified-Since", status: "permanent", reference: "RFC 9110, Section 13.1.4: HTTP Semantics", group: "conditional" },
  { name: "IM", status: "permanent", reference: "RFC 3229: Delta encoding in HTTP", group: "representation" },
  { name: "Include-Referred-Token-Binding-ID", status: "permanent", reference: "RFC 8473: Token Binding over HTTP", group: "authentication" },
  { name: "Keep-Alive", status: "permanent", reference: "RFC 2068: Hypertext Transfer Protocol -- HTTP/1.1", group: "other-registered" },
  { name: "Label", status: "permanent", reference: "RFC 3253: Versioning Extensions to WebDAV: (Web Distributed Authoring and Versioning)", group: "webdav" },
  { name: "Last-Event-ID", status: "permanent", reference: "HTML", group: "other-registered" },
  { name: "Last-Modified", status: "permanent", reference: "RFC 9110, Section 8.8.2: HTTP Semantics", group: "representation" },
  { name: "Link", status: "permanent", reference: "RFC 8288: Web Linking", group: "representation" },
  { name: "Link-Template", status: "permanent", reference: "RFC 9652: The Link-Template HTTP Header Field", group: "representation" },
  { name: "Location", status: "permanent", reference: "RFC 9110, Section 10.2.2: HTTP Semantics", group: "response-context" },
  { name: "Lock-Token", status: "permanent", reference: "RFC 4918: HTTP Extensions for Web Distributed Authoring and Versioning (WebDAV)", group: "webdav" },
  { name: "Man", status: "obsoleted", reference: "RFC 2774: An HTTP Extension Framework", group: "other-registered" },
  { name: "Max-Forwards", status: "permanent", reference: "RFC 9110, Section 7.6.2: HTTP Semantics", group: "routing" },
  { name: "Memento-Datetime", status: "permanent", reference: "RFC 7089: HTTP Framework for Time-Based Access to Resource States -- Memento", group: "representation" },
  { name: "Meter", status: "permanent", reference: "RFC 2227: Simple Hit-Metering and Usage-Limiting for HTTP", group: "other-registered" },
  { name: "Method-Check", status: "obsoleted", reference: "Access Control for Cross-site Requests", group: "other-registered" },
  { name: "Method-Check-Expires", status: "obsoleted", reference: "Access Control for Cross-site Requests", group: "other-registered" },
  { name: "MIME-Version", status: "permanent", reference: "RFC 9112, Appendix B.1: HTTP/1.1", group: "framing" },
  { name: "Negotiate", status: "permanent", reference: "RFC 2295: Transparent Content Negotiation in HTTP", group: "negotiation" },
  { name: "NEL", status: "permanent", reference: "Network Error Logging", group: "security-policy" },
  { name: "OData-EntityId", status: "permanent", reference: "OData Version 4.01 Part 1: Protocol", group: "other-registered" },
  { name: "OData-Isolation", status: "permanent", reference: "OData Version 4.01 Part 1: Protocol", group: "other-registered" },
  { name: "OData-MaxVersion", status: "permanent", reference: "OData Version 4.01 Part 1: Protocol", group: "other-registered" },
  { name: "OData-Version", status: "permanent", reference: "OData Version 4.01 Part 1: Protocol", group: "other-registered" },
  { name: "Opt", status: "obsoleted", reference: "RFC 2774: An HTTP Extension Framework", group: "other-registered" },
  { name: "Optional-WWW-Authenticate", status: "permanent", reference: "RFC 8053, Section 3: HTTP Authentication Extensions for Interactive Clients", group: "authentication" },
  { name: "Ordering-Type", status: "permanent", reference: "RFC 3648: Web Distributed Authoring and Versioning (WebDAV) Ordered Collections Protocol", group: "webdav" },
  { name: "Origin", status: "permanent", reference: "RFC 6454: The Web Origin Concept", group: "security-policy" },
  { name: "Origin-Agent-Cluster", status: "permanent", reference: "HTML", group: "security-policy" },
  { name: "OSCORE", status: "permanent", reference: "RFC 8613, Section 11.1: Object Security for Constrained RESTful Environments (OSCORE)", group: "authentication" },
  { name: "OSLC-Core-Version", status: "permanent", reference: "OASIS Project Specification 01", group: "other-registered" },
  { name: "Overwrite", status: "permanent", reference: "RFC 4918: HTTP Extensions for Web Distributed Authoring and Versioning (WebDAV)", group: "webdav" },
  { name: "P3P", status: "obsoleted", reference: "The Platform for Privacy Preferences 1.0 (P3P1.0) Specification", group: "other-registered" },
  { name: "PEP", status: "obsoleted", reference: "PEP - an Extension Mechanism for HTTP", group: "other-registered" },
  { name: "PEP-Info", status: "obsoleted", reference: "PEP - an Extension Mechanism for HTTP", group: "other-registered" },
  { name: "PICS-Label", status: "obsoleted", reference: "PICS Label Distribution Label Syntax and Communication Protocols", group: "other-registered" },
  { name: "Ping-From", status: "permanent", reference: "HTML", group: "other-registered" },
  { name: "Ping-To", status: "permanent", reference: "HTML", group: "other-registered" },
  { name: "Position", status: "permanent", reference: "RFC 3648: Web Distributed Authoring and Versioning (WebDAV) Ordered Collections Protocol", group: "webdav" },
  { name: "Pragma", status: "deprecated", reference: "RFC 9111, Section 5.4: HTTP Caching", group: "caching" },
  { name: "Prefer", status: "permanent", reference: "RFC 7240: Prefer Header for HTTP", group: "other-registered" },
  { name: "Preference-Applied", status: "permanent", reference: "RFC 7240: Prefer Header for HTTP", group: "other-registered" },
  { name: "Priority", status: "permanent", reference: "RFC 9218: Extensible Prioritization Scheme for HTTP", group: "other-registered" },
  { name: "ProfileObject", status: "obsoleted", reference: "Implementation of OPS Over HTTP", group: "other-registered" },
  { name: "Protocol", status: "obsoleted", reference: "PICS Label Distribution Label Syntax and Communication Protocols", group: "other-registered" },
  { name: "Protocol-Info", status: "deprecated", reference: "White Paper: Joint Electronic Payment Initiative", group: "other-registered" },
  { name: "Protocol-Query", status: "deprecated", reference: "White Paper: Joint Electronic Payment Initiative", group: "other-registered" },
  { name: "Protocol-Request", status: "obsoleted", reference: "PICS Label Distribution Label Syntax and Communication Protocols", group: "other-registered" },
  { name: "Proxy-Authenticate", status: "permanent", reference: "RFC 9110, Section 11.7.1: HTTP Semantics", group: "authentication" },
  { name: "Proxy-Authentication-Info", status: "permanent", reference: "RFC 9110, Section 11.7.3: HTTP Semantics", group: "authentication" },
  { name: "Proxy-Authorization", status: "permanent", reference: "RFC 9110, Section 11.7.2: HTTP Semantics", group: "authentication" },
  { name: "Proxy-Features", status: "obsoleted", reference: "Notification for Proxy Caches", group: "other-registered" },
  { name: "Proxy-Instruction", status: "obsoleted", reference: "Notification for Proxy Caches", group: "other-registered" },
  { name: "Proxy-Public-Address", status: "permanent", reference: "RFC-ietf-masque-connect-udp-listen-16: Proxying Bound UDP in HTTP", group: "proxies" },
  { name: "Proxy-Status", status: "permanent", reference: "RFC 9209: The Proxy-Status HTTP Response Header Field", group: "proxies" },
  { name: "Public", status: "obsoleted", reference: "RFC 2068: Hypertext Transfer Protocol -- HTTP/1.1", group: "other-registered" },
  { name: "Public-Key-Pins", status: "permanent", reference: "RFC 7469: Public Key Pinning Extension for HTTP", group: "security-policy" },
  { name: "Public-Key-Pins-Report-Only", status: "permanent", reference: "RFC 7469: Public Key Pinning Extension for HTTP", group: "security-policy" },
  { name: "Range", status: "permanent", reference: "RFC 9110, Section 14.2: HTTP Semantics", group: "range" },
  { name: "Redirect-Ref", status: "permanent", reference: "RFC 4437: Web Distributed Authoring and Versioning (WebDAV) Redirect Reference Resources", group: "webdav" },
  { name: "Referer", status: "permanent", reference: "RFC 9110, Section 10.1.3: HTTP Semantics", group: "request-context" },
  { name: "Referer-Root", status: "obsoleted", reference: "Access Control for Cross-site Requests", group: "other-registered" },
  { name: "Referrer-Policy", status: "permanent", reference: "Referrer Policy", group: "security-policy" },
  { name: "Refresh", status: "permanent", reference: "HTML", group: "other-registered" },
  { name: "Replay-Nonce", status: "permanent", reference: "RFC 8555, Section 6.5.1: Automatic Certificate Management Environment (ACME)", group: "other-registered" },
  { name: "Repr-Digest", status: "permanent", reference: "RFC 9530, Section 3: Digest Fields", group: "representation" },
  { name: "Retry-After", status: "permanent", reference: "RFC 9110, Section 10.2.3: HTTP Semantics", group: "response-context" },
  { name: "Safe", status: "obsoleted", reference: "RFC 2310: The Safe Response Header Field", group: "other-registered" },
  { name: "Schedule-Reply", status: "permanent", reference: "RFC 6638: Scheduling Extensions to CalDAV", group: "webdav" },
  { name: "Schedule-Tag", status: "permanent", reference: "RFC 6338: Scheduling Extensions to CalDAV", group: "webdav" },
  { name: "Sec-Fetch-Dest", status: "permanent", reference: "https://www.w3.org/TR/fetch-metadata/#sec-fetch-dest-header", group: "fetch-metadata" },
  { name: "Sec-Fetch-Mode", status: "permanent", reference: "https://www.w3.org/TR/fetch-metadata/#sec-fetch-mode-header", group: "fetch-metadata" },
  { name: "Sec-Fetch-Site", status: "permanent", reference: "https://www.w3.org/TR/fetch-metadata/#sec-fetch-site-header", group: "fetch-metadata" },
  { name: "Sec-Fetch-User", status: "permanent", reference: "https://www.w3.org/TR/fetch-metadata/#sec-fetch-user-header", group: "fetch-metadata" },
  { name: "Sec-Purpose", status: "permanent", reference: "Fetch", group: "fetch-metadata" },
  { name: "Sec-Token-Binding", status: "permanent", reference: "RFC 8473: Token Binding over HTTP", group: "authentication" },
  { name: "Sec-WebSocket-Accept", status: "permanent", reference: "RFC 6455: The WebSocket Protocol", group: "websocket" },
  { name: "Sec-WebSocket-Extensions", status: "permanent", reference: "RFC 6455: The WebSocket Protocol", group: "websocket" },
  { name: "Sec-WebSocket-Key", status: "permanent", reference: "RFC 6455: The WebSocket Protocol", group: "websocket" },
  { name: "Sec-WebSocket-Protocol", status: "permanent", reference: "RFC 6455: The WebSocket Protocol", group: "websocket" },
  { name: "Sec-WebSocket-Version", status: "permanent", reference: "RFC 6455: The WebSocket Protocol", group: "websocket" },
  { name: "Security-Scheme", status: "obsoleted", reference: "RFC 2660: The Secure HyperText Transfer Protocol", group: "other-registered" },
  { name: "Server", status: "permanent", reference: "RFC 9110, Section 10.2.4: HTTP Semantics", group: "response-context" },
  { name: "Server-Timing", status: "permanent", reference: "Server Timing", group: "other-registered" },
  { name: "Set-Cookie", status: "permanent", reference: "RFC-ietf-httpbis-rfc6265bis-22, Section 5.8.1: Cookies: HTTP State Management Mechanism", group: "cookies" },
  { name: "Set-Cookie2", status: "obsoleted", reference: "RFC 2965: HTTP State Management Mechanism", group: "cookies" },
  { name: "Set-Txn", status: "permanent", reference: "RFC9967, Section 3: SCIM Profile for Security Event Tokens", group: "other-registered" },
  { name: "SetProfile", status: "obsoleted", reference: "Implementation of OPS Over HTTP", group: "other-registered" },
  { name: "Signature", status: "permanent", reference: "RFC 9421, Section 4.2: HTTP Message Signatures", group: "authentication" },
  { name: "Signature-Input", status: "permanent", reference: "RFC 9421, Section 4.1: HTTP Message Signatures", group: "authentication" },
  { name: "SLUG", status: "permanent", reference: "RFC 5023: The Atom Publishing Protocol", group: "other-registered" },
  { name: "SoapAction", status: "permanent", reference: "Simple Object Access Protocol (SOAP) 1.1", group: "other-registered" },
  { name: "Status-URI", status: "permanent", reference: "RFC 2518: HTTP Extensions for Distributed Authoring -- WEBDAV", group: "webdav" },
  { name: "Strict-Transport-Security", status: "permanent", reference: "RFC 6797: HTTP Strict Transport Security (HSTS)", group: "security-policy" },
  { name: "Sunset", status: "permanent", reference: "RFC 8594: The Sunset HTTP Header Field", group: "representation" },
  { name: "TCN", status: "permanent", reference: "RFC 2295: Transparent Content Negotiation in HTTP", group: "negotiation" },
  { name: "TE", status: "permanent", reference: "RFC 9110, Section 10.1.4: HTTP Semantics", group: "request-context" },
  { name: "Timeout", status: "permanent", reference: "RFC 4918: HTTP Extensions for Web Distributed Authoring and Versioning (WebDAV)", group: "webdav" },
  { name: "Topic", status: "permanent", reference: "RFC 8030, Section 5.4: Generic Event Delivery Using HTTP Push", group: "other-registered" },
  { name: "Traceparent", status: "permanent", reference: "Trace Context", group: "other-registered" },
  { name: "Tracestate", status: "permanent", reference: "Trace Context", group: "other-registered" },
  { name: "Trailer", status: "permanent", reference: "RFC 9110, Section 6.6.2: HTTP Semantics", group: "message" },
  { name: "Transfer-Encoding", status: "permanent", reference: "RFC 9112, Section 6.1: HTTP Semantics", group: "framing" },
  { name: "TTL", status: "permanent", reference: "RFC 8030, Section 5.2: Generic Event Delivery Using HTTP Push", group: "other-registered" },
  { name: "Unencoded-Digest", status: "permanent", reference: "RFC-ietf-httpbis-unencoded-digest-05, Section 3: HTTP Unencoded Digest", group: "representation" },
  { name: "Upgrade", status: "permanent", reference: "RFC 9110, Section 7.8: HTTP Semantics", group: "routing" },
  { name: "Urgency", status: "permanent", reference: "RFC 8030, Section 5.3: Generic Event Delivery Using HTTP Push", group: "other-registered" },
  { name: "URI", status: "obsoleted", reference: "RFC 2068: Hypertext Transfer Protocol -- HTTP/1.1", group: "other-registered" },
  { name: "Use-As-Dictionary", status: "permanent", reference: "RFC 9842, Section 2.1: Compression Dictionary Transport", group: "negotiation" },
  { name: "User-Agent", status: "permanent", reference: "RFC 9110, Section 10.1.5: HTTP Semantics", group: "request-context" },
  { name: "Variant-Vary", status: "permanent", reference: "RFC 2295: Transparent Content Negotiation in HTTP", group: "negotiation" },
  { name: "Vary", status: "permanent", reference: "RFC 9110, Section 12.5.5: HTTP Semantics", group: "negotiation" },
  { name: "Via", status: "permanent", reference: "RFC 9110, Section 7.6.3: HTTP Semantics", group: "routing" },
  { name: "Want-Content-Digest", status: "permanent", reference: "RFC 9530, Section 4: Digest Fields", group: "representation" },
  { name: "Want-Digest", status: "obsoleted", reference: "RFC 3230: Instance Digests in HTTP", group: "representation" },
  { name: "Want-Repr-Digest", status: "permanent", reference: "RFC 9530, Section 4: Digest Fields", group: "representation" },
  { name: "Want-Unencoded-Digest", status: "permanent", reference: "RFC-ietf-httpbis-unencoded-digest-05, Section 4: HTTP Unencoded Digest", group: "representation" },
  { name: "Warning", status: "obsoleted", reference: "RFC 9111, Section 5.5: HTTP Caching", group: "caching" },
  { name: "WWW-Authenticate", status: "permanent", reference: "RFC 9110, Section 11.6.1: HTTP Semantics", group: "authentication" },
  { name: "X-Content-Type-Options", status: "permanent", reference: "Fetch", group: "security-policy" },
  { name: "X-Frame-Options", status: "permanent", reference: "HTML", group: "security-policy" },
];

/** Look a name up case-insensitively (field names are case-insensitive, RFC 9110 Section 5.1). */
const BY_LOWER: Map<string, FieldRecord> = new Map(FIELD_REGISTRY.map((f) => [f.name.toLowerCase(), f]));

/** The registry row for a name, or undefined when the name is not registered as permanent, deprecated or obsoleted. */
export function lookupField(name: string): FieldRecord | undefined {
  // Case-insensitive.
  return BY_LOWER.get(name.toLowerCase());
}

/** The date the registry was read. */
export const FIELD_REGISTRY_READ_DATE = "2026-10-05";
