// ============================================================================
// src/lib/tools/ascii-table/golden-vectors.ts
// ----------------------------------------------------------------------------
// GOLDEN VECTORS for the ASCII table explorer
// (set "ascii-table-golden-2026-10-03"). GENERATED by scratchpad/chr/gv/gen-chr.mts.
//
// Three kinds of vector. A look-up pins what the box read (an ASCII code, a
// code point outside ASCII with its name, or nothing) and, for ASCII, every
// detail the page shows: numbers, column/row, names, escapes in five
// languages, HTML references, the URL form, white space, bit flips. A text
// pins each character's code point, bytes and flags. A table pins the codes
// listed.
//
// Expected values were captured from compute.run() on 2026-10-03, with the full
// Unicode 18.0.0 name table. Characters outside printable ASCII are written as
// \uXXXX escapes so the file shows exactly which character each vector holds.
// 23 reference checks were evaluated in CPython 3.11 (html, unicodedata,
// urllib.parse, ast, json): 23 of 23 agree.
// Before writing, every escape, HTML reference and white-space set of all
// 128 codes was checked against CPython, Node 22, GCC (C11), Tcl 8.4.6 and
// Chromium: no differences.
// ============================================================================

import { run, type AsciiTableInput, type AsciiTableResult, type NameData } from "./compute";
import { unicodeName, aliasesOf, codePointOfName } from "@/lib/unicode/names";

/** The set id: the tool slug and the date the expected values were captured. */
export const GOLDEN_VECTOR_SET_ID = "ascii-table-golden-2026-10-03";

/** The full name data the vectors run with (the API entry point passes the same). */
const FULL_NAMES: NameData = { nameOf: unicodeName, aliasOf: (cp: number) => aliasesOf(cp)[0]?.alias, cpOf: codePointOfName };

/** The fields a vector pins. */
export type AsciiTablePinned = Record<string, unknown>;

/** One vector: a name, an input, and the pinned fields of its result. */
export interface AsciiTableVector {
  // A short stable name.
  id: string;
  // The input, exactly as the tool takes it.
  input: AsciiTableInput;
  // The pinned fields of the result.
  expect: AsciiTablePinned;
}

/** Reduce a result to the fields a vector pins. */
export function pin(r: AsciiTableResult): AsciiTablePinned {
  // A look-up: what was read, and the whole detail for an ASCII code.
  if (r.mode === "lookup") return { mode: r.mode, result: r.result, detail: r.detail };
  // A text: the totals and each character.
  if (r.mode === "text") return { mode: r.mode, ascii: r.ascii, outside: r.outside, truncated: r.truncated, chars: r.chars };
  // A table: the codes listed.
  return { mode: r.mode, codes: r.codes };
}

/** The vectors. */
export const VECTORS: AsciiTableVector[] = [
  // A character typed as itself.
  {
    id: "lookup-character",
    input: { mode: "lookup", value: "A" },
    expect: {
      mode: "lookup",
      result: { kind: "ascii", code: 65, readAs: "character" },
      detail: {
        row: { code: 65, glyph: "A", name: "LATIN CAPITAL LETTER A", category: "Lu" },
        kind: "upper",
        dec: "65",
        hex: "0x41",
        oct: "0o101",
        bin7: "1000001",
        bin8: "01000001",
        columnRow: "4/1",
        otherCase: "a",
        escapes: {
          c: { text: "A", how: "plain" },
          json: { text: "A", how: "plain" },
          javascript: { text: "A", how: "plain" },
          python: { text: "A", how: "plain" },
          tcl: { text: "A", how: "plain" },
        },
        html: { dec: "&#65;", hex: "&#x41;", named: [] },
        url: { encoded: "%41", cls: "unreserved" },
        whitespace: [],
        unicode: "U+0041",
        flips: [64, 67, 69, 73, 81, 97, 1],
      },
    },
  },
  // RFC 20's own example: K is column 4, row 11.
  {
    id: "lookup-column-row",
    input: { mode: "lookup", value: "4/11" },
    expect: {
      mode: "lookup",
      result: { kind: "ascii", code: 75, readAs: "column-row" },
      detail: {
        row: { code: 75, glyph: "K", name: "LATIN CAPITAL LETTER K", category: "Lu" },
        kind: "upper",
        dec: "75",
        hex: "0x4B",
        oct: "0o113",
        bin7: "1001011",
        bin8: "01001011",
        columnRow: "4/11",
        otherCase: "k",
        escapes: {
          c: { text: "K", how: "plain" },
          json: { text: "K", how: "plain" },
          javascript: { text: "K", how: "plain" },
          python: { text: "K", how: "plain" },
          tcl: { text: "K", how: "plain" },
        },
        html: { dec: "&#75;", hex: "&#x4B;", named: [] },
        url: { encoded: "%4B", cls: "unreserved" },
        whitespace: [],
        unicode: "U+004B",
        flips: [74, 73, 79, 67, 91, 107, 11],
      },
    },
  },
  // &tilde; is U+02DC SMALL TILDE, not the ASCII tilde (126 has no named reference).
  {
    id: "lookup-tilde",
    input: { mode: "lookup", value: "&tilde;" },
    expect: {
      mode: "lookup",
      result: {
        kind: "outside",
        cp: 732,
        label: "U+02DC",
        name: "SMALL TILDE",
        nameKind: "name",
        prototype: "~",
        readAs: "html-named",
      },
    },
  },
  // &minus; is U+2212 MINUS SIGN; the ASCII hyphen-minus (45) has no named reference.
  {
    id: "lookup-minus",
    input: { mode: "lookup", value: "&minus;" },
    expect: {
      mode: "lookup",
      result: {
        kind: "outside",
        cp: 8722,
        label: "U+2212",
        name: "MINUS SIGN",
        nameKind: "name",
        hidden: "dash",
        prototype: "-",
        readAs: "html-named",
      },
    },
  },
  // A hexadecimal character reference.
  {
    id: "lookup-hex-reference",
    input: { mode: "lookup", value: "&#x41;" },
    expect: {
      mode: "lookup",
      result: { kind: "ascii", code: 65, readAs: "html-hex" },
      detail: {
        row: { code: 65, glyph: "A", name: "LATIN CAPITAL LETTER A", category: "Lu" },
        kind: "upper",
        dec: "65",
        hex: "0x41",
        oct: "0o101",
        bin7: "1000001",
        bin8: "01000001",
        columnRow: "4/1",
        otherCase: "a",
        escapes: {
          c: { text: "A", how: "plain" },
          json: { text: "A", how: "plain" },
          javascript: { text: "A", how: "plain" },
          python: { text: "A", how: "plain" },
          tcl: { text: "A", how: "plain" },
        },
        html: { dec: "&#65;", hex: "&#x41;", named: [] },
        url: { encoded: "%41", cls: "unreserved" },
        whitespace: [],
        unicode: "U+0041",
        flips: [64, 67, 69, 73, 81, 97, 1],
      },
    },
  },
  // Caret notation: ^[ is ESC, the character 64 below [.
  {
    id: "lookup-caret",
    input: { mode: "lookup", value: "^[" },
    expect: {
      mode: "lookup",
      result: { kind: "ascii", code: 27, readAs: "caret" },
      detail: {
        row: { code: 27, abbr: "ESC", name: "ESCAPE", category: "Cc", rfc20: { abbr: "ESC", name: "Escape" } },
        kind: "control",
        dec: "27",
        hex: "0x1B",
        oct: "0o033",
        bin7: "0011011",
        bin8: "00011011",
        columnRow: "1/11",
        caret: "^[",
        caretOf: "[",
        escapes: {
          c: { text: "\\033", how: "numeric", note: "c-octal" },
          json: { text: "\\u001B", how: "numeric", note: "json-must" },
          javascript: { text: "\\x1B", how: "numeric" },
          python: { text: "\\x1B", how: "numeric" },
          tcl: { text: "\\033", how: "numeric", note: "tcl-octal" },
        },
        html: { dec: "&#27;", hex: "&#x1B;", named: [], note: "control" },
        url: { encoded: "%1B", cls: "other" },
        whitespace: [],
        unicode: "U+001B",
        flips: [26, 25, 31, 19, 11, 59, 91],
      },
    },
  },
  // A control looked up by its ISO 6429 name (a Unicode formal alias).
  {
    id: "lookup-control-name",
    input: { mode: "lookup", value: "line feed" },
    expect: {
      mode: "lookup",
      result: { kind: "ascii", code: 10, readAs: "name" },
      detail: {
        row: {
          code: 10,
          abbr: "LF",
          name: "LINE FEED",
          aliases: ["NEW LINE", "END OF LINE"],
          abbrAliases: ["NL", "EOL"],
          unicode1: "LINE FEED (LF)",
          category: "Cc",
          rfc20: { abbr: "LF", name: "Line Feed", cls: "FE" },
          html: ["&NewLine;"],
        },
        kind: "control",
        dec: "10",
        hex: "0x0A",
        oct: "0o012",
        bin7: "0001010",
        bin8: "00001010",
        columnRow: "0/10",
        caret: "^J",
        caretOf: "J",
        escapes: {
          c: { text: "\\n", how: "simple" },
          json: { text: "\\n", how: "simple", note: "json-must" },
          javascript: { text: "\\n", how: "simple" },
          python: { text: "\\n", how: "simple" },
          tcl: { text: "\\n", how: "simple" },
        },
        html: { dec: "&#10;", hex: "&#xA;", named: ["&NewLine;"] },
        url: { encoded: "%0A", cls: "other" },
        whitespace: ["c", "json", "whatwg", "python", "javascript"],
        unicode: "U+000A",
        flips: [11, 8, 14, 2, 26, 42, 74],
      },
    },
  },
  // Percent-encoding.
  {
    id: "lookup-percent",
    input: { mode: "lookup", value: "%7E" },
    expect: {
      mode: "lookup",
      result: { kind: "ascii", code: 126, readAs: "percent" },
      detail: {
        row: {
          code: 126,
          glyph: "~",
          name: "TILDE",
          category: "Sm",
          rfc20: { name: "Overline", alt: "Tilde; General Accent", agree: true },
        },
        kind: "punct",
        dec: "126",
        hex: "0x7E",
        oct: "0o176",
        bin7: "1111110",
        bin8: "01111110",
        columnRow: "7/14",
        escapes: {
          c: { text: "~", how: "plain" },
          json: { text: "~", how: "plain" },
          javascript: { text: "~", how: "plain" },
          python: { text: "~", how: "plain" },
          tcl: { text: "~", how: "plain" },
        },
        html: { dec: "&#126;", hex: "&#x7E;", named: [] },
        url: { encoded: "%7E", cls: "unreserved" },
        whitespace: [],
        unicode: "U+007E",
        flips: [127, 124, 122, 118, 110, 94, 62],
      },
    },
  },
  // Eight binary digits are read as bits: 00100101 is 37, the percent sign.
  {
    id: "lookup-bits",
    input: { mode: "lookup", value: "00100101" },
    expect: {
      mode: "lookup",
      result: { kind: "ascii", code: 37, readAs: "binary" },
      detail: {
        row: {
          code: 37,
          glyph: "%",
          name: "PERCENT SIGN",
          category: "Po",
          rfc20: { name: "Percent" },
          html: ["&percnt;"],
        },
        kind: "punct",
        dec: "37",
        hex: "0x25",
        oct: "0o045",
        bin7: "0100101",
        bin8: "00100101",
        columnRow: "2/5",
        escapes: {
          c: { text: "%", how: "plain" },
          json: { text: "%", how: "plain" },
          javascript: { text: "%", how: "plain" },
          python: { text: "%", how: "plain" },
          tcl: { text: "%", how: "plain" },
        },
        html: { dec: "&#37;", hex: "&#x25;", named: ["&percnt;"] },
        url: { encoded: "%25", cls: "other" },
        whitespace: [],
        unicode: "U+0025",
        flips: [36, 39, 33, 45, 53, 5, 101],
      },
    },
  },
  // An octal escape, as C, Python and Tcl write it.
  {
    id: "lookup-octal-escape",
    input: { mode: "lookup", value: "\\101" },
    expect: {
      mode: "lookup",
      result: { kind: "ascii", code: 65, readAs: "escape-octal" },
      detail: {
        row: { code: 65, glyph: "A", name: "LATIN CAPITAL LETTER A", category: "Lu" },
        kind: "upper",
        dec: "65",
        hex: "0x41",
        oct: "0o101",
        bin7: "1000001",
        bin8: "01000001",
        columnRow: "4/1",
        otherCase: "a",
        escapes: {
          c: { text: "A", how: "plain" },
          json: { text: "A", how: "plain" },
          javascript: { text: "A", how: "plain" },
          python: { text: "A", how: "plain" },
          tcl: { text: "A", how: "plain" },
        },
        html: { dec: "&#65;", hex: "&#x41;", named: [] },
        url: { encoded: "%41", cls: "unreserved" },
        whitespace: [],
        unicode: "U+0041",
        flips: [64, 67, 69, 73, 81, 97, 1],
      },
    },
  },
  // RFC 20's name for the backslash.
  {
    id: "lookup-rfc20-name",
    input: { mode: "lookup", value: "Reverse Slant" },
    expect: {
      mode: "lookup",
      result: { kind: "ascii", code: 92, readAs: "name" },
      detail: {
        row: {
          code: 92,
          glyph: "\\",
          name: "REVERSE SOLIDUS",
          unicode1: "BACKSLASH",
          category: "Po",
          rfc20: { name: "Reverse Slant", agree: true },
          html: ["&bsol;"],
        },
        kind: "punct",
        dec: "92",
        hex: "0x5C",
        oct: "0o134",
        bin7: "1011100",
        bin8: "01011100",
        columnRow: "5/12",
        escapes: {
          c: { text: "\\\\", how: "simple" },
          json: { text: "\\\\", how: "simple", note: "json-must" },
          javascript: { text: "\\\\", how: "simple" },
          python: { text: "\\\\", how: "simple" },
          tcl: { text: "\\\\", how: "simple" },
        },
        html: { dec: "&#92;", hex: "&#x5C;", named: ["&bsol;"] },
        url: { encoded: "%5C", cls: "other" },
        whitespace: [],
        unicode: "U+005C",
        flips: [93, 94, 88, 84, 76, 124, 28],
      },
    },
  },
  // DEL: not a control in RFC 20's strict sense, a control (Cc) in Unicode.
  {
    id: "lookup-delete",
    input: { mode: "lookup", value: "DEL" },
    expect: {
      mode: "lookup",
      result: { kind: "ascii", code: 127, readAs: "name" },
      detail: {
        row: { code: 127, abbr: "DEL", name: "DELETE", category: "Cc", rfc20: { abbr: "DEL", name: "Delete" } },
        kind: "delete",
        dec: "127",
        hex: "0x7F",
        oct: "0o177",
        bin7: "1111111",
        bin8: "01111111",
        columnRow: "7/15",
        caret: "^?",
        caretOf: "?",
        escapes: {
          c: { text: "\\177", how: "numeric", note: "c-octal" },
          json: { text: "\u007F", how: "plain", note: "json-del" },
          javascript: { text: "\\x7F", how: "numeric" },
          python: { text: "\\x7F", how: "numeric" },
          tcl: { text: "\\177", how: "numeric", note: "tcl-octal" },
        },
        html: { dec: "&#127;", hex: "&#x7F;", named: [], note: "control" },
        url: { encoded: "%7F", cls: "other" },
        whitespace: [],
        unicode: "U+007F",
        flips: [126, 125, 123, 119, 111, 95, 63],
      },
    },
  },
  // An en dash pasted in: outside ASCII, a dash.
  {
    id: "lookup-en-dash",
    input: { mode: "lookup", value: "\u2013" },
    expect: {
      mode: "lookup",
      result: {
        kind: "outside",
        cp: 8211,
        label: "U+2013",
        name: "EN DASH",
        nameKind: "name",
        hidden: "dash",
        prototype: "-",
        readAs: "character",
      },
    },
  },
  // A Unicode name outside ASCII, matched loosely.
  {
    id: "lookup-unicode-name",
    input: { mode: "lookup", value: "en dash" },
    expect: {
      mode: "lookup",
      result: {
        kind: "outside",
        cp: 8211,
        label: "U+2013",
        name: "EN DASH",
        nameKind: "name",
        hidden: "dash",
        prototype: "-",
        readAs: "name",
      },
    },
  },
  // U+0085 has no name, only aliases: NEXT LINE.
  {
    id: "lookup-c1-control",
    input: { mode: "lookup", value: "U+0085" },
    expect: {
      mode: "lookup",
      result: {
        kind: "outside",
        cp: 133,
        label: "U+0085",
        name: "NEXT LINE",
        nameKind: "alias",
        hidden: "space",
        readAs: "unicode",
      },
    },
  },
  // Nothing the box can read.
  {
    id: "lookup-unknown",
    input: { mode: "lookup", value: "zzz" },
    expect: { mode: "lookup", result: { kind: "unknown" } },
  },
  // Typographic quotes pasted into a text: two characters outside ASCII.
  {
    id: "text-smart-quotes",
    input: { mode: "text", text: "Hi \u201Cx\u201D\n" },
    expect: {
      mode: "text",
      ascii: 5,
      outside: 2,
      truncated: false,
      chars: [
        { char: "H", cp: 72, ascii: true, label: "U+0048", bytes: "48" },
        { char: "i", cp: 105, ascii: true, label: "U+0069", bytes: "69" },
        { char: " ", cp: 32, ascii: true, label: "U+0020", bytes: "20" },
        {
          char: "\u201C",
          cp: 8220,
          ascii: false,
          label: "U+201C",
          bytes: "E2 80 9C",
          name: "LEFT DOUBLE QUOTATION MARK",
          nameKind: "name",
          hidden: "quote",
          prototype: "''",
        },
        { char: "x", cp: 120, ascii: true, label: "U+0078", bytes: "78" },
        {
          char: "\u201D",
          cp: 8221,
          ascii: false,
          label: "U+201D",
          bytes: "E2 80 9D",
          name: "RIGHT DOUBLE QUOTATION MARK",
          nameKind: "name",
          hidden: "quote",
          prototype: "''",
        },
        { char: "\n", cp: 10, ascii: true, label: "U+000A", bytes: "0A" },
      ],
    },
  },
  // The 32 controls (DEL is listed on its own).
  {
    id: "table-controls",
    input: { mode: "table", kind: "control" },
    expect: {
      mode: "table",
      codes: [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
      ],
    },
  },
  // The eleven positions RFC 20's note 3 reserves for agreement in international interchange.
  {
    id: "table-agree",
    input: { mode: "table", kind: "agree" },
    expect: { mode: "table", codes: [35, 64, 91, 92, 93, 94, 96, 123, 124, 125, 126] },
  },
];

/** What verifyVectors reports (the shape scripts/run-golden-vectors.mts reads). */
export interface VerifyReport {
  // The set id.
  setId: string;
  // Vectors run.
  total: number;
  // Vectors whose pinned fields matched.
  passed: number;
  // The ones that did not, with the first difference.
  failures: { id: string; reason: string }[];
}

/** Run every vector and compare its pinned fields byte for byte. */
export function verifyVectors(): VerifyReport {
  // Failures found.
  const failures: { id: string; reason: string }[] = [];
  // Each vector.
  for (const v of VECTORS) {
    // A throw is a failure too.
    try {
      // Run and reduce (through JSON, as the expected values were captured).
      const got = JSON.stringify(pin(run(v.input, FULL_NAMES)));
      // The expected text.
      const want = JSON.stringify(v.expect);
      // Compare.
      if (got !== want) {
        // The first differing character, for a readable reason.
        let k = 0;
        // Walk to it.
        while (k < got.length && got[k] === want[k]) k++;
        // Record.
        failures.push({ id: v.id, reason: `differs at ${k}: got ...${got.slice(Math.max(0, k - 30), k + 50)}... want ...${want.slice(Math.max(0, k - 30), k + 50)}...` });
      }
    } catch (e) {
      // The error.
      failures.push({ id: v.id, reason: `threw: ${(e as Error).message}` });
    }
  }
  // The report.
  return { setId: GOLDEN_VECTOR_SET_ID, total: VECTORS.length, passed: VECTORS.length - failures.length, failures };
}
