// ============================================================================
// scripts/check-og.mjs
// ----------------------------------------------------------------------------
// BUILD GUARD: the OG social-preview system must stay complete and in sync.
//
// The OG images are generated by scripts/gen-og.mts into public/og/ and wired
// into page metadata via src/lib/og.ts (ogImages). This gate runs AFTER
// generation in the prebuild chain and fails the build if the generated set
// does not cover every route kind, so a page can never ship pointing at a
// missing card (which would unfurl blank).
//
// Checks:
//   1. the generator ran (public/og/manifest.json + default.png exist);
//   2. every built tool (TOOL_PAGES), article, glossary entry, study guide,
//      vendor, and static page has a card for BOTH locales, at the extension
//      src/lib/og.ts expects (jpeg for brand pages, png otherwise);
//   3. the manifest and the files on disk agree (no orph files / missing).
//
// Plain node; structural reads, same technique as the other gates.
// ============================================================================

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => fs.readFileSync(path.join(ROOT, p), "utf8");
const exists = (p) => fs.existsSync(path.join(ROOT, p));

const LOCALES = ["en", "pt-BR"];
const JPEG_PAGES = new Set(["home", "about", "training", "red-education"]);
const errors = [];

// 1. generator ran
if (!exists("public/og/manifest.json")) errors.push("public/og/manifest.json missing - run scripts/gen-og.mts (prebuild).");
if (!exists("public/og/default.png")) errors.push("public/og/default.png missing.");

// ---- enumerate the same route sets the generator + site use ----------------
const routeSrc = read("src/app/[locale]/tools/[slug]/page.tsx");
const tpStart = routeSrc.indexOf("const TOOL_PAGES");
const tpSeg = routeSrc.slice(tpStart, routeSrc.indexOf("generateStaticParams", tpStart));
const tools = [...tpSeg.matchAll(/^ {2}"?([a-z0-9-]+)"?:\s*\{/gm)].map((m) => m[1]);

const articles = fs.readdirSync(path.join(ROOT, "src/content/learn/en")).filter((f) => f.endsWith(".mdx")).map((f) => f.replace(/\.mdx$/, ""));
const glossary = [...read("src/content/glossary/glossary.ts").matchAll(/slug:\s*"([a-z0-9-]+)"/g)].map((m) => m[1]);
const guideReg = read("src/content/certifications/study-guides.ts");
const guides = [...guideReg.slice(guideReg.indexOf("export const studyGuides")).matchAll(/slug:\s*"([a-z0-9-]+)"/g)].map((m) => m[1]);
const vendors = ["f5", "fortinet", "netskope", "extreme"];
const staticPages = ["home", "tools", "learn", "certifications", "glossary", "training", "about", "red-education"];

const kinds = [
  ["tool", tools],
  ["article", articles],
  ["glossary", glossary],
  ["guide", guides],
  ["vendor", vendors],
  ["page", staticPages],
];

// 2. every (kind, slug, locale) card exists at the expected extension
let expected = 0;
for (const [kind, slugs] of kinds) {
  for (const slug of slugs) {
    const ext = kind === "page" && JPEG_PAGES.has(slug) ? "jpeg" : "png";
    for (const locale of LOCALES) {
      expected++;
      const rel = `public/og/${kind}/${locale}/${slug}.${ext}`;
      if (!exists(rel)) errors.push(`missing OG card: ${rel}`);
    }
  }
}

// 3. manifest count sanity (allows default.png not being in manifest)
if (exists("public/og/manifest.json")) {
  const manifest = JSON.parse(read("public/og/manifest.json"));
  const have = Object.keys(manifest).length;
  if (have < expected) errors.push(`manifest has ${have} entries but ${expected} cards are expected.`);
}

if (errors.length) {
  console.error("[check-og] FAILED:");
  for (const e of errors.slice(0, 40)) console.error("  - " + e);
  if (errors.length > 40) console.error(`  ... and ${errors.length - 40} more`);
  process.exit(1);
}
console.log(`[check-og] OK: ${expected} OG cards present across ${kinds.length} kinds x ${LOCALES.length} locales (+ default).`);
