#!/usr/bin/env tsx
// SPDX-FileCopyrightText: 2026 Rodolfo Nützmann <https://ronutz.com>
// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// scripts/gen-input-detectors.mts
// ----------------------------------------------------------------------------
// THE INPUT DETECTORS, GATHERED FOR THE BROWSER (E3 of Round 1, "paste what
// you have", 2026-10-05).
//
// Every tool manifest (src/lib/tools/<slug>/index.ts) declares inputDetectors:
// anchored regular expressions that say "this text looks like my input", with
// a priority and an example. Until tonight nothing ran them: they fed one
// example each to the API documentation and nothing else. The /tools page now
// has a box that runs every regex detector over whatever the reader pastes and
// offers the tools that match, ranked by priority.
//
// WHY A GENERATED FILE. The manifests live beside their compute modules, and a
// client component that imported 183 manifests would pull 183 engines into the
// page bundle. This script imports each manifest at build time, keeps only the
// regex detectors (kind, priority, pattern, example) and writes a small JSON
// module the component imports instead. Heuristic and structured-form detectors
// carry no pattern and are left out; their tools are reached by intent.
//
// EVERY PATTERN IS COMPILED HERE. A detector nobody ever ran may not be a valid
// JavaScript regular expression; compiling it at build time turns that into a
// build failure with the slug named, rather than a thrown exception in the
// reader's browser. Patterns are also kept short of catastrophic shapes by the
// manifests' own dangerousInputHandling rules; the component bounds the input.
//
// Output: src/lib/tools/input-detectors.generated.json, sorted by slug, stable
// across runs so the diff is only ever the change that caused it.
// ============================================================================
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const toolsDir = path.join(here, "..", "src", "lib", "tools");
const outFile = path.join(toolsDir, "input-detectors.generated.json");

/** One detector as the component needs it. */
interface GeneratedDetector {
  slug: string;
  family: string;
  priority: number;
  pattern: string;
  example: string;
}

// Every tool directory with a manifest; the registry is the arbiter of what is live, but a manifest that exists
// and compiles is enough for a detector to be useful, and the component only offers tools it can link.
const slugs = fs
  .readdirSync(toolsDir, { withFileTypes: true })
  .filter((d) => d.isDirectory() && fs.existsSync(path.join(toolsDir, d.name, "index.ts")))
  .map((d) => d.name)
  .sort();

const out: GeneratedDetector[] = [];
const invalid: string[] = [];
let manifests = 0;
for (const slug of slugs) {
  // Dynamic import of the TypeScript module, as build-openapi.mts does; tsx compiles it on the fly.
  const mod = (await import(path.join(toolsDir, slug, "index.ts"))) as { manifest?: { toolFamily?: string; inputDetectors?: unknown[] } };
  const m = mod.manifest;
  if (!m || !Array.isArray(m.inputDetectors)) continue;
  manifests += 1;
  for (const raw of m.inputDetectors) {
    const d = raw as { kind?: string; priority?: number; pattern?: string; example?: string };
    if (d.kind !== "regex" || typeof d.pattern !== "string") continue;
    // Compile once here: an invalid pattern fails the build with its slug.
    try {
      new RegExp(d.pattern);
    } catch (e) {
      invalid.push(`${slug}: ${(e as Error).message}`);
      continue;
    }
    out.push({
      slug,
      family: typeof m.toolFamily === "string" ? m.toolFamily : "",
      priority: typeof d.priority === "number" ? d.priority : 100,
      pattern: d.pattern,
      example: typeof d.example === "string" ? d.example : "",
    });
  }
}

if (invalid.length) {
  console.error(`\n[gen-input-detectors] FAIL: ${invalid.length} detector pattern(s) do not compile as JavaScript regular expressions.\n`);
  for (const i of invalid) console.error(`  - ${i}`);
  console.error("");
  process.exit(1);
}

// Stable order: slug, then priority, then pattern.
out.sort((a, b) => a.slug.localeCompare(b.slug) || a.priority - b.priority || a.pattern.localeCompare(b.pattern));
const doc = {
  about: "Generated by scripts/gen-input-detectors.mts from every tool manifest's regex inputDetectors; do not edit by hand. Read by src/components/PasteWhatYouHave.tsx.",
  detectors: out,
};
const text = JSON.stringify(doc, null, 2) + "\n";
// Write only when the content changed, so an unchanged run leaves no diff.
const prev = fs.existsSync(outFile) ? fs.readFileSync(outFile, "utf8") : "";
if (prev !== text) fs.writeFileSync(outFile, text);
console.log(`[gen-input-detectors] OK: ${out.length} regex detector(s) from ${manifests} manifest(s) across ${new Set(out.map((d) => d.slug)).size} tool(s), every pattern compiled; wrote ${path.relative(path.join(here, ".."), outFile)}${prev === text ? " (unchanged)" : ""}.`);
