// SPDX-FileCopyrightText: 2026 Rodolfo Nützmann <https://ronutz.com>
// SPDX-License-Identifier: Apache-2.0

// ============================================================================
// src/content/milestones/milestones.ts
// ----------------------------------------------------------------------------
// MILESTONES — the physics and engineering the company timeline sits on top of.
//
// WHY THIS IS SEPARATE FROM `/industry` (PRIME, 2026-08-02).
// The company timeline starts in the 1830s only because one distributor's
// parent traded lumber. Everything else on it is a firm. Faraday is not a firm,
// and putting 1831 on a page whose next card is a networking vendor changes
// what that page is claiming to be. So these live at `/industry/milestones`:
// same idea, its own structure, cross-linked both ways.
//
// WHAT EARNS A PLACE HERE. Not "important events in science" - the test is
// narrower and it is this: **could a network engineer's working day be
// explained without it?** Induction, the transistor, Shannon's channel
// capacity, the first hard disk, Ethernet. Things that are upstream of the job
// rather than adjacent to it.
//
// EVERY ENTRY CARRIES `why` — what it means for the work, not just what
// happened. An entry that only says what happened belongs in an encyclopaedia,
// and there is a good one already.
// ============================================================================

/** Which thread of the story an entry belongs to. */
export type MilestoneStrand =
  /** Making, moving and understanding electrical energy. */
  | "electricity"
  /** Controlling it: valves, transistors, integrated circuits. */
  | "electronics"
  /** Representing information as discrete symbols, and reasoning about it. */
  | "digital"
  /** Keeping it: tape, disk, flash. */
  | "storage"
  /** Moving it: telegraph, telephone, radio, packets, fibre. */
  | "transfer"
  /**
   * MAKING IT (PRIME 2026-08-11). The five strands above record what was
   * invented. None of them records HOW ANY OF IT GETS BUILT - and the answer
   * changed the industry more than several of the inventions did. A networking
   * vendor today designs a product it does not manufacture, on silicon it does
   * not fabricate, using a processor architecture it licenses rather than owns.
   * Every step of that arrangement was invented by somebody, on a date.
   */
  | "making";

export const MILESTONE_STRANDS: readonly MilestoneStrand[] = [
  "electricity",
  "electronics",
  "digital",
  "storage",
  "transfer",
  "making",
] as const;

export interface Milestone {
  slug: string;
  /** The year attributed. Where sources disagree, `dateNote` says so. */
  year: number;
  title: string;
  strand: MilestoneStrand;
  /** Who did it, where a person or team is properly attributable. */
  who?: string;
  /** What happened, in a sentence or two. */
  what: string;
  /** *** Why it matters to the work this site is about. Required. *** */
  why: string;
  /** Recorded disagreement about dating or attribution. */
  dateNote?: string;
  /**
   * WHERE IT HAPPENED (PRIME 2026-08-13). ISO 3166-1 alpha-2 codes, and an
   * ARRAY because a milestone is frequently not one country's: Shortest Path
   * Bridging came out of a standards body, the transistor came out of one lab
   * but the people in it came from several places, and a company founded in one
   * country can do the work in another.
   *
   * THE RULE APPLIED HERE: the country is WHERE THE WORK WAS DONE, not where
   * the person was born and not where the company was later headquartered.
   * Where two places genuinely share the work, both are listed and the order is
   * chronological rather than ranked.
   *
   * Empty is legitimate. A milestone that belongs to no particular country -
   * an idea, a standard with no single home - carries none rather than being
   * assigned one for the sake of a flag.
   */
  countries?: string[];
  sources: { label: string; url?: string }[];
}

// ============================================================================
// The entries. Chronological within the file for readability; sorted at render.
// ============================================================================

export const MILESTONES: Milestone[] = [
  // -- ELECTRICITY ----------------------------------------------------------
  {
    slug: "voltaic-pile",
    year: 1800,
    title: "The voltaic pile",
    strand: "electricity",
    countries: ["IT"],
    who: "Alessandro Volta",
    what: "A stack of alternating zinc and copper discs separated by brine-soaked cloth, producing a steady electric current rather than the momentary discharge of a static machine.",
    why: "Everything downstream needs current that keeps flowing. Static electricity had been known for centuries and was useless for it. This is the first thing on the list because without a continuous source there is nothing to modulate, switch or send.",
    sources: [{ label: "Volta's 1800 letter to the Royal Society describing the pile", url: "https://en.wikipedia.org/wiki/Voltaic_pile" }],
  },
  {
    slug: "oersted-magnetism",
    year: 1820,
    title: "A current deflects a compass needle",
    strand: "electricity",
    countries: ["DK"],
    who: "Hans Christian Ørsted",
    what: "A wire carrying current was observed to move a nearby compass needle, showing that electricity and magnetism are aspects of one phenomenon rather than two curiosities.",
    why: "Every motor, every transformer, every read head over a disk platter and every signal induced onto the wrong pair in a cable bundle is this observation, applied. Crosstalk is Ørsted's experiment happening when you did not ask for it.",
    sources: [{ label: "Ørsted's 1820 report on the effect of a current on a magnetic needle", url: "https://en.wikipedia.org/wiki/Hans_Christian_%C3%98rsted" }],
  },
  {
    slug: "faraday-induction",
    year: 1831,
    title: "Electromagnetic induction",
    strand: "electricity",
    countries: ["GB"],
    who: "Michael Faraday",
    what: "A changing magnetic field induces a current in a nearby conductor. The reciprocal of Ørsted: not only does current make magnetism, changing magnetism makes current.",
    why: "This is generation, transformation and every inductive coupling problem in one law. It is also why twisted pair works: twist the conductors and the interference induced into each is roughly equal, so the difference between them - the thing the receiver actually reads - is largely clean.",
    sources: [{ label: "Faraday's Experimental Researches in Electricity, first series, 1831", url: "https://en.wikipedia.org/wiki/Faraday%27s_law_of_induction" }],
  },
  {
    slug: "maxwell-equations",
    year: 1865,
    title: "A dynamical theory of the electromagnetic field",
    strand: "electricity",
    countries: ["GB"],
    who: "James Clerk Maxwell",
    what: "A set of equations describing electricity, magnetism and light as one field phenomenon, predicting that electromagnetic waves propagate at the speed of light.",
    why: "The prediction came before the demonstration, which is worth noticing: radio existed on paper for two decades before anyone made it. Every wireless standard is an engineering treatment of this result, and propagation, attenuation and antenna design are all applied Maxwell.",
    sources: [{ label: "Maxwell, A Dynamical Theory of the Electromagnetic Field, Philosophical Transactions, 1865", url: "https://en.wikipedia.org/wiki/A_Dynamical_Theory_of_the_Electromagnetic_Field" }],
  },
  {
    slug: "hertz-waves",
    year: 1887,
    title: "Electromagnetic waves demonstrated",
    strand: "electricity",
    countries: ["DE"],
    who: "Heinrich Hertz",
    what: "A spark-gap transmitter and a loop receiver, showing that the waves Maxwell had predicted existed, could be reflected and refracted, and travelled at the predicted speed.",
    why: "The moment radio became an engineering problem rather than a mathematical one. Hertz reportedly saw no use for it, which is a useful reminder about the distance between a demonstration and an application.",
    sources: [{ label: "Hertz's 1887-88 experiments on electromagnetic waves", url: "https://en.wikipedia.org/wiki/Heinrich_Hertz" }],
  },

  // -- ELECTRONICS ----------------------------------------------------------
  {
    slug: "fleming-valve",
    year: 1904,
    title: "The thermionic valve",
    strand: "electronics",
    countries: ["GB"],
    who: "John Ambrose Fleming",
    what: "A heated filament in an evacuated tube, allowing current in one direction only - the first electronic diode.",
    why: "Rectification is the first thing you can do to a signal that is not simply carrying it. Detection of radio signals starts here, and so does the idea that a device can act on a signal rather than merely conduct it.",
    sources: [{ label: "Fleming's 1904 patent for the oscillation valve", url: "https://en.wikipedia.org/wiki/Fleming_valve" }],
  },
  {
    slug: "cp-40-hypervisor",
    year: 1967,
    title: "A machine pretending to be many",
    strand: "digital",
    countries: ["US"],
    who: "IBM Cambridge Scientific Center",
    what: "A control program that ran whole operating systems as guests, in production use from January 1967.",
    why: "Sharing one expensive machine safely is the idea the entire cloud rests on, and it was working before most of this timeline's later entries existed. It then vanished for fifteen years, because cheap personal hardware removed the reason for it - which is the clearest evidence that a technology survives on whether its constraint still exists, not on merit.",
    sources: [{ label: "IBM CP-40, in production use from January 1967 and widely credited as the first hypervisor", url: "https://en.wikipedia.org/wiki/IBM_CP-40" }],
  },
  {
    slug: "low-loss-fibre",
    year: 1966,
    title: "The loss that was not fundamental",
    strand: "transfer",
    countries: ["GB"],
    who: "Charles Kao and George Hockham",
    what: "A paper arguing that the enormous losses in glass fibre came from impurities rather than from physics, and specifying what a working system would need.",
    why: "The idea was widely ridiculed, and Corning proved it right four years later. Kao built nothing; he identified that a limit everyone accepted was not a law. Every long-distance link since runs on that distinction, and the Nobel arrived forty-three years after the paper.",
    sources: [{ label: "IEEE Spectrum on Kao and the fibre-optic revolution, and the Corning group reaching 17 decibels per kilometre in 1970", url: "https://spectrum.ieee.org/how-charles-kao-beat-bell-labs-to-the-fiberoptic-revolution" }],
  },
  {
    slug: "aloha-random-access",
    year: 1971,
    title: "Transmit, collide, try again",
    strand: "transfer",
    countries: ["US"],
    who: "Norman Abramson, Franklin Kuo and colleagues",
    what: "A radio network across four Hawaiian islands in which stations transmitted whenever they had data and dealt with the collisions.",
    why: "Every prior design assumed access to a shared channel had to be arranged in advance. Refusing that assumption is what made cheap shared media possible, and Metcalfe credited it directly when building Ethernet. The university had no office to commercialise it, so it went into the public domain - which is why Wi-Fi, mobile, cable and Ethernet could all build on it without asking.",
    sources: [{ label: "IEEE milestone for the 1971 ALOHA demonstration, and Metcalfe crediting ALOHA for Ethernet and CSMA/CD", url: "https://ethw.org/Milestones:Demonstration_of_the_ALOHA_Packet_Radio_Data_Network,_1971" }],
  },
  {
    slug: "first-networked-email",
    year: 1971,
    title: "A message to another machine",
    strand: "transfer",
    countries: ["US"],
    who: "Ray Tomlinson",
    what: "Messaging between users of one computer already existed; Tomlinson grafted a file transfer program onto it so a message could reach a person on a different machine, and chose the at sign to say which one.",
    why: "It was not an assignment - he was looking for something to do with the ARPANET. The address format he improvised has outlived every system built to replace it, and the mailbox became the recovery path for nearly every other account, making it the de facto root credential of a digital life.",
    sources: [{ label: "Tomlinson at BBN modifying SNDMSG with code from his CPYNET file transfer program, on his own initiative", url: "https://www.prolateral.com/help/kb/smtp/420-when-was-the-first-smtp-email.html" }],
  },
  {
    slug: "the-certificate",
    year: 1978,
    title: "A name bound to a key",
    strand: "digital",
    countries: ["US"],
    who: "Loren Kohnfelder",
    what: "An undergraduate thesis describing digital certificates and revocation lists, so that a trusted party could vouch for a public key in advance instead of being asked at the time.",
    why: "Public-key cryptography solved key distribution and left you unable to tell whose key you had. This closed that gap, and the structure it described still carries commerce on the internet. The piece that made public-key cryptography usable at scale was a bachelor's thesis.",
    sources: [{ label: "Loren Kohnfelder, who invented what is now called public key infrastructure in his May 1978 MIT bachelor thesis, introducing the terms certificate and certificate revocation list", url: "https://en.wikipedia.org/wiki/Loren_Kohnfelder" }],
  },
  {
    slug: "spanning-tree",
    year: 1985,
    title: "One path, agreed by everyone",
    strand: "transfer",
    countries: ["US"],
    who: "Radia Perlman",
    what: "An algorithm that lets bridges elect a root and disable every link not on the resulting tree, so redundant connections can exist without frames circulating forever.",
    why: "Redundancy is what makes a network survivable and, without this, what makes a bridged network fail catastrophically. She was handed the problem as probably unsolvable, woke in the night with the answer, and wrote the specification the next morning with a twelve-line poem describing it. The whole layer exists because the industry mistook a link for a network.",
    sources: [{ label: "National Inventors Hall of Fame on Perlman and the spanning tree algorithm, which transformed Ethernet from a few hundred nodes in one building into networks of hundreds of thousands", url: "https://www.invent.org/inductees/radia-perlman" }],
  },
  {
    slug: "morris-worm",
    year: 1988,
    title: "A program that would not stop copying itself",
    strand: "transfer",
    countries: ["US"],
    who: "Robert Tappan Morris",
    what: "A graduate student released a self-replicating program onto the internet; a flaw in how often it re-infected made it consume the machines it reached.",
    why: "It produced the first felony conviction under American computer crime law and the first coordinated emergency response team, so the professions of incident response and vulnerability coordination both date from it. The damage came from a mistake in the replication rate rather than from intent, which is the earliest demonstration that on a network a small error and an attack are indistinguishable from the outside.",
    sources: [{ label: "The Morris worm of November 1988 and the founding of the first computer emergency response team in its aftermath", url: "https://en.wikipedia.org/wiki/Morris_worm" }],
  },
  {
    slug: "first-commercial-firewall",
    year: 1991,
    title: "A place on the network to say no",
    strand: "transfer",
    countries: ["US"],
    who: "Digital Equipment Corporation, with Marcus Ranum",
    what: "The first commercial firewall was configured and delivered to its first customer on 13 June 1991, combining a bastion host, a filtering gateway and an internal mail hub.",
    why: "Nobody invented the firewall; it was argued into existence over six years by people who disagreed about everything except that a network needed a boundary. The first product was already a hybrid of proxies and packet filtering, which is what firewalls have been ever since whatever the marketing says.",
    sources: [{ label: "Fred Avolio on the first commercial firewall delivered 13 June 1991, and the SEAL architecture", url: "https://avolio.com/fw2hundred/" }],
  },
  {
    slug: "ethernet-switch",
    year: 1990,
    title: "A wire each",
    strand: "transfer",
    countries: ["US"],
    who: "Kalpana",
    what: "A seven-port switch gave every device its own segment instead of a share of one, ending collisions and making full duplex possible.",
    why: "The same bridging function, in silicon, per port. It let Ethernet scale to speeds a shared medium could never have carried, and it was a substantial security improvement sold purely as a performance upgrade - capture had been trivial on a hub and was not on a switch. The mirror ports monitoring depends on exist to deliberately undo it.",
    sources: [{ label: "Kalpana, founded 1990 in Sunnyvale, and the seven-port EtherSwitch, the first multiport Ethernet switch", url: "https://en.wikipedia.org/wiki/Kalpana,_Inc." }],
  },
  {
    slug: "napster",
    year: 1999,
    title: "Distribution stops asking permission",
    strand: "transfer",
    countries: ["US"],
    who: "Shawn Fanning and Sean Parker",
    what: "A service that let strangers search each other's music collections and copy directly between machines, reaching tens of millions of users before the courts closed it.",
    why: "It was shut down and it won anyway. An industry that sold physical objects discovered that copying costs nothing and that demand for unbundled, instant, catalogue-wide access was enormous - and every legal streaming service since is built on the behaviour Napster proved existed. Piracy is frequently the market research that a rights holder refuses to commission.",
    sources: [{ label: "Napster, the peer-to-peer file sharing service founded in 1999 and shut down by court order in 2001", url: "https://en.wikipedia.org/wiki/Napster" }],
  },
  {
    slug: "february-2000-ddos",
    year: 2000,
    title: "A fifteen-year-old empties the shops",
    strand: "transfer",
    countries: ["CA","US"],
    who: "Michael Calce, and the people whose tools he used",
    what: "Over three days, Yahoo, Amazon, eBay, CNN, Dell and others were made unreachable by traffic from machines with weak passwords, using attack tools the attacker had not written.",
    why: "Steven Bellovin was five minutes into a conference keynote on denial-of-service attacks when the room emptied to deal with it. The community understood the threat well enough to schedule a talk about it and that did not help. It also established the asymmetry that has never closed: attacking is cheap and needs no original work, and defending requires capacity only a handful of organisations can afford.",
    sources: [{ label: "The February 2000 attacks, and Bellovin delivering the NANOG 18 keynote on denial of service as they began", url: "https://www.senki.org/ddos-attack-preparation-workbook/history-of-denial-of-services-dos-attacks/" }],
  },
  {
    slug: "utility-computing",
    year: 2006,
    title: "A computer you rent by the hour",
    strand: "digital",
    countries: ["US"],
    who: "Amazon Web Services",
    what: "Storage and virtual machines sold on demand, by the hour, with a credit card and no negotiation.",
    why: "Capital expenditure became operating expenditure and provisioning went from months to minutes, which changed who could start a company. It also relocated the industry's infrastructure into a handful of providers, so the same decade that made computing available to anyone made most of it dependent on very few.",
    sources: [{ label: "Amazon Web Services launching S3 in March 2006 and EC2 in August 2006", url: "https://en.wikipedia.org/wiki/Amazon_Web_Services" }],
  },
  {
    slug: "the-smartphone",
    year: 2007,
    title: "The network in a pocket",
    strand: "transfer",
    countries: ["US"],
    who: "Apple, and the industry that followed",
    what: "A general-purpose networked computer with a touchscreen, sold as a phone, with software distributed through a single store.",
    why: "It ended the assumption that a user sits at a desk inside a building, which is the assumption every perimeter security model had been built on. Remote work, mobile device management, application-layer identity and the collapse of the network boundary all follow from putting a full internet host in a pocket.",
    sources: [{ label: "The iPhone announced January 2007, and the App Store in 2008", url: "https://en.wikipedia.org/wiki/IPhone_(1st_generation)" }],
  },
  {
    slug: "stuxnet",
    year: 2010,
    title: "Code that broke machinery",
    strand: "digital",
    countries: ["IL","US"],
    who: "Attributed to state actors; never officially claimed",
    what: "Malware that crossed from information systems into industrial controllers and damaged physical centrifuges by altering what they did while reporting normal readings.",
    why: "It made state-built offensive code a public fact rather than an assumption, and it demonstrated that the gap between a network and a physical process is a matter of engineering rather than of principle. Every argument about critical infrastructure security since is conducted with this as the reference case.",
    sources: [{ label: "Stuxnet, discovered in 2010, targeting programmable logic controllers and causing physical damage to centrifuges", url: "https://en.wikipedia.org/wiki/Stuxnet" }],
  },
  {
    slug: "container-packaging",
    year: 2013,
    title: "Shipping the environment with the program",
    strand: "digital",
    countries: ["US"],
    who: "Docker",
    what: "A usable interface over Linux isolation features that had existed for years, packaging an application together with everything it needs to run.",
    why: "The isolation mechanisms were not new; the packaging and the workflow were. It moved the unit of deployment from a machine to an image, which made the software supply chain a security problem: what is in the base layer, who built it, and when was it last rebuilt.",
    sources: [{ label: "Docker, released 2013, building on Linux namespaces and control groups", url: "https://en.wikipedia.org/wiki/Docker_(software)" }],
  },
  {
    slug: "free-certificates",
    year: 2015,
    title: "Encryption stops being a budget line",
    strand: "digital",
    countries: ["US"],
    who: "Let's Encrypt and the ACME protocol",
    what: "Automated, free certificate issuance, replacing a manual purchase that cost hundreds of dollars a year.",
    why: "Most of the web was unencrypted because encryption was an expense and a chore. Removing both moved the web from mostly plaintext to mostly encrypted within a few years - and with it went network inspection, payload-based detection and the assumption that a sensor in the middle can see anything.",
    sources: [{ label: "Let's Encrypt, the free automated certificate authority, launched publicly in 2015", url: "https://en.wikipedia.org/wiki/Let's_Encrypt" }],
  },
  {
    slug: "mirai",
    year: 2016,
    title: "An attack made of other people's cameras",
    strand: "transfer",
    countries: ["US"],
    who: "Paras Jha and others, later prosecuted",
    what: "A botnet assembled from consumer devices with default credentials, used against a naming provider and taking down services that were never attacked.",
    why: "There is no patch a target can apply to an attack built from somebody else's negligence. And the victim was not the target: the services that went dark had merely pointed at the provider being hit, which is the clearest demonstration that a dependency is a more efficient thing to attack than a company.",
    sources: [{ label: "The Mirai botnet attack on Dyn in October 2016, built from devices with default credentials", url: "https://en.wikipedia.org/wiki/Mirai_(malware)" }],
  },
  {
    slug: "conversational-models",
    year: 2022,
    title: "A machine that answers in prose",
    strand: "digital",
    countries: ["US"],
    who: "OpenAI, and the research lineage behind it",
    what: "A large language model released with a conversational interface, reaching mass use faster than any previous software product.",
    why: "The interface, not the model, is what changed things - the capability existed and was unreachable without one. For the work this site is about it altered the economics of writing code, reading logs and producing documentation, and introduced a supply chain question nobody has answered: what a system that learned from public repositories owes to them, and what it should be trusted to assert.",
    sources: [{ label: "ChatGPT released 30 November 2022, reaching an estimated hundred million users within two months", url: "https://en.wikipedia.org/wiki/ChatGPT" }],
  },
  {
    slug: "peltier-effect",
    year: 1834,
    title: "Cold from a current",
    strand: "electricity",
    countries: ["FR"],
    who: "Jean-Charles Peltier",
    what: "A clockmaker found that passing current through a junction of two dissimilar metals heats one side and cools the other, depending on direction.",
    why: "It is the only way to move heat with no moving parts and no working fluid, and it stayed a curiosity for about 120 years because it needed semiconductors to be efficient enough to matter. The devices built on it now hold laser temperature steady inside optical transceivers, so a discovery from 1834 is what keeps a wavelength where the specification says it should be.",
    sources: [{ label: "Britannica on Peltier, a clockmaker who retired at thirty for science and discovered the effect in 1834", url: "https://www.britannica.com/biography/Jean-Charles-Athanase-Peltier" }],
  },
  {
    slug: "portable-measurement",
    year: 1888,
    title: "Electricity becomes measurable in the field",
    strand: "electricity",
    countries: ["US"],
    who: "Edward Weston",
    what: "The first accurate portable direct-reading voltmeters and ammeters, followed in 1893 by a chemical cell stable enough to calibrate them.",
    why: "He was working on dynamos, found the available instruments too clumsy for his own experiments, built better ones and abandoned everything else when they worked. His cell was the international standard for electromotive force from 1911 until 1990. An industry cannot be billed, tuned or trusted until it can be measured.",
    sources: [{ label: "IEEE milestone, Weston Meters 1887-1893, and the Weston cell as international standard for electromotive force from 1911 to 1990", url: "https://ethw.org/Milestones:Weston_Meters,_1887-1893" }],
  },
  {
    slug: "television-demonstrated",
    year: 1926,
    title: "Nobody in the room wrote it down",
    strand: "transfer",
    countries: ["GB"],
    who: "John Logie Baird",
    what: "Working television shown to members of the Royal Institution on the evening of 26 January 1926.",
    why: "Not one attending member published a comment afterwards, and the only first-hand account was a short item in a newspaper two days later. The date is now called the birth of television and was, on the day, unremarkable to the experts present. His mechanical system then lost within a decade to the all-electronic approach built on the cathode ray tube.",
    sources: [{ label: "The Conversation on Baird's 26 January 1926 demonstration, after which none of the attending members published any comment", url: "https://theconversation.com/a-century-ago-john-logie-baird-achieved-a-landmark-moment-in-television-history-the-viewers-werent-convinced-274089" }],
  },
  {
    slug: "hardware-security-module",
    year: 1973,
    title: "A secret you can use and cannot take",
    strand: "digital",
    countries: ["US"],
    who: "Mohamed Atalla",
    what: "A tamper-resistant box that performed cryptographic operations and held the keys so they could be used but never extracted, built for banking personal identification numbers.",
    why: "Atalla had invented the MOSFET at Bell Labs, watched it be overlooked, resigned, and twelve years later built this. Fifty years of computing has produced no better answer to the requirement, only cheaper versions. Fearing he would dominate, the banks then wrote an international standard - so a good deal of the industry's interoperability exists because somebody was frightened of a monopoly.",
    sources: [{ label: "Utimaco Atalla: founded 1972 by Mohamed M. Atalla, with the Atalla Box released in 1973 as the first hardware security module", url: "https://en.wikipedia.org/wiki/Utimaco_Atalla" }],
  },
  {
    slug: "data-encryption-standard",
    year: 1977,
    title: "A cipher the public could read",
    strand: "digital",
    countries: ["US"],
    who: "IBM, the National Bureau of Standards and the National Security Agency",
    what: "A block cipher published as a federal standard on 23 November 1977, developed from Horst Feistel's Lucifer after the government asked the public for a design it was unwilling to build itself.",
    why: "Civilian cryptography starts here. The agency's changes shortened the key, exactly as critics said - and also made the cipher resistant to an attack technique the academic world would not rediscover for seventeen years. The suspicion was half right and half exactly backwards, and the open competition that replaced it in 2001 was designed so nobody would have to take anyone's word again.",
    sources: [{ label: "NIST cyber history on cryptography: the 1973 and 1974 solicitations, the 1976 public workshops and the issue of FIPS 46 on 23 November 1977", url: "https://csrc.nist.gov/nist-cyber-history/cryptography/chapter" }],
  },
  {
    slug: "domain-name-system",
    year: 1983,
    title: "Authority given away on purpose",
    strand: "transfer",
    countries: ["US"],
    who: "Paul Mockapetris",
    what: "A distributed naming system replacing a single text file that staff at one institute updated by hand and distributed twice a week.",
    why: "The file's limit was human: the people maintaining it worked business hours and took holidays, and an always-on network cannot have a naming system that closes at five. Asked to reconcile five existing proposals, he wrote his own instead. It survives because it delegates authority rather than holding it - and because it sees every question, it became the internet's most convenient point of control and of censorship.",
    sources: [{ label: "ACM Software System Award to Mockapetris, who single-authored RFCs 882 and 883 in 1983 and wrote the first implementation", url: "https://awards.acm.org/award-recipients/mockapetris_3342151" }],
  },
  {
    slug: "network-time",
    year: 1985,
    title: "Everyone agrees what time it is",
    strand: "transfer",
    countries: ["US"],
    who: "David L. Mills",
    what: "A protocol for steering clocks across a network using four timestamps per exchange, first specified in September 1985.",
    why: "Certificates, tickets, log correlation and one-time codes all fail when clocks drift, and none of them lists time as a dependency. Mills also built the Fuzzball, the first modern software router. Fragments of the 1985 implementation are still running, which is the strongest longevity claim available in this timeline.",
    sources: [{ label: "Mills, A Brief History of NTP Time: version 0 implemented in 1985, with fragments of that code surviving in the software running today", url: "https://www.ntp.org/reflib/papers/history.pdf" }],
  },
  {
    slug: "intrusion-detection-model",
    year: 1986,
    title: "Watching for the abnormal",
    strand: "digital",
    countries: ["US"],
    who: "Dorothy Denning and Peter Neumann",
    what: "A model for detecting intrusion in real time by building a statistical profile of normal behaviour and flagging deviation from it.",
    why: "The field began as a filing problem - records existed and nobody read them - and this turned it into a discipline. The prototype already contained both halves the industry still argues about, learning normal behaviour and encoding known attacks. The anomaly half was correct in 1986 and impractical for twenty-five years for want of storage; the current behavioural products are that original idea finally affordable.",
    sources: [{ label: "Denning, An Intrusion-Detection Model, presented at the 1986 IEEE Symposium on Security and Privacy", url: "https://www.cs.colostate.edu/~cs656/reading/ieee-se-13-2.pdf" }],
  },
  {
    slug: "snmp",
    year: 1988,
    title: "One way to ask any device",
    strand: "transfer",
    countries: ["US"],
    who: "Jeffrey Case, Mark Fedor, Martin Schoffstall and James Davin",
    what: "A management protocol whose working group had been told to keep it simple, published in August 1988 and intended as a temporary measure.",
    why: "Before it, each manufacturer had its own management protocol, so three vendors meant three systems. It was meant to be interim and its simplicity made it permanent, complete with a password sent in the clear that the industry ran for thirty years because replacing it cost more than the risk appeared to. Its acknowledgements name people from Proteon, Sytek, Excelan and Bridge - companies that no longer exist, in a document still in production.",
    sources: [{ label: "RFC 1067, A Simple Network Management Protocol, August 1988", url: "https://www.ietf.org/rfc/rfc1067.txt" }],
  },
  {
    slug: "ldap",
    year: 1993,
    title: "Throwing away most of the standard",
    strand: "digital",
    countries: ["US"],
    who: "Tim Howes, Wengyik Yeong and Steve Kille",
    what: "A directory access protocol that kept the data model of X.500 and discarded the stack it required, so ordinary machines could actually use it.",
    why: "X.500 was correct and undeployable: most desktop computers of the era could not talk to it at all. Three engineers published a stripped version that ran over a plain connection, and the stripped version is what the world runs. A specification can be technically excellent and unusable at the same time, and this industry has never been good at telling those apart in advance.",
    sources: [{ label: "RFC 1487, the July 1993 X.500 Lightweight Directory Access Protocol, aimed at reducing the high cost of entry of the technology", url: "https://www.ietf.org/rfc/rfc1487" }],
  },
  {
    slug: "open-signatures",
    year: 1998,
    title: "Giving the detection away",
    strand: "digital",
    countries: ["US"],
    who: "Martin Roesch",
    what: "A free intrusion detection engine whose rules were readable and writable by anyone, released on 22 December 1998.",
    why: "It did for detection what a free toolkit had done for firewalls five years earlier: turned an expensive product category into something an engineer could study, and made the rule language a shared vocabulary. The pattern recurs across this timeline - the thing given away becomes the thing everyone builds on, and the company that gave it away is bought by the incumbent later.",
    sources: [{ label: "GIAC on the history of intrusion detection: Snort released by Marty Roesch on 22 December 1998", url: "https://www.giac.org/paper/gsec/1294/history-evolution-intrusion-detection/100570" }],
  },
  {
    slug: "separating-control-and-forwarding",
    year: 2008,
    title: "A protest that was bought",
    strand: "transfer",
    countries: ["US"],
    who: "Martin Casado, Nick McKeown and Scott Shenker",
    what: "An open protocol between a controller and a switch, published in 2008 out of research that described itself as a protest against the ossification of networks.",
    why: "Within four years the protest had a foundation whose founding members were the vendors it objected to, and the company was sold for over a billion dollars. The protocol itself largely failed in enterprises; the idea won completely, and every cloud network is centrally controlled today. What propagates is rarely a mechanism - it is a way of thinking about the problem.",
    sources: [{ label: "Grokipedia on software-defined networking: the Ethane prototype, the NOX controller of 2008, and the Open Networking Foundation of March 2011", url: "https://grokipedia.com/page/Software-defined_networking" }],
  },
  {
    slug: "de-forest-triode",
    year: 1906,
    title: "The triode, and amplification",
    strand: "electronics",
    countries: ["US"],
    who: "Lee de Forest",
    what: "A third electrode added to the valve, letting a small voltage control a much larger current.",
    why: "Amplification is the property that makes long-distance anything possible. A signal that weakens with distance can now be rebuilt. Every repeater, every line amplifier and eventually every logic gate is a descendant of controlling a large current with a small one.",
    sources: [{ label: "de Forest's audion patents, 1906-1908", url: "https://en.wikipedia.org/wiki/Audion" }],
  },
  {
    slug: "transistor",
    year: 1947,
    title: "The transistor",
    strand: "electronics",
    countries: ["US"],
    who: "John Bardeen, Walter Brattain and William Shockley, Bell Labs",
    what: "A solid-state device doing the valve's job - amplifying and switching - without a vacuum, a heater or the fragility of glass.",
    why: "The valve worked but could not scale: it was large, hot, power-hungry and it failed. Everything about modern computing follows from being able to make this device small, cheap and reliable, and then to make a great many of them at once.",
    sources: [{ label: "Bell Labs, December 1947 demonstration of the point-contact transistor", url: "https://en.wikipedia.org/wiki/Point-contact_transistor" }],
  },
  {
    slug: "integrated-circuit",
    year: 1958,
    title: "The integrated circuit",
    strand: "electronics",
    countries: ["US"],
    who: "Jack Kilby at Texas Instruments, and Robert Noyce at Fairchild",
    what: "Multiple components fabricated on a single piece of semiconductor rather than wired together as discrete parts.",
    dateNote:
      "Two independent inventions, months apart, with different approaches: Kilby's demonstration was in 1958, Noyce's planar process work in 1959. The planar approach is the one that scaled. Both are credited.",
    why: "The step from 'we can make a transistor' to 'we can make a million of them and they are all connected correctly'. Wiring components by hand has a hard ceiling; photolithography does not have one in the same way, which is the whole of the last sixty years.",
    sources: [{ label: "Kilby's 1958 demonstration at Texas Instruments; Noyce's 1959 planar integrated circuit at Fairchild", url: "https://en.wikipedia.org/wiki/Integrated_circuit" }],
  },

  // -- DIGITAL --------------------------------------------------------------
  {
    slug: "shannon-switching",
    year: 1937,
    title: "Boolean algebra describes switching circuits",
    strand: "digital",
    countries: ["US"],
    who: "Claude Shannon",
    what: "A master's thesis showing that relay and switching circuits can be analysed and designed using Boolean algebra.",
    why: "This is the hinge between electrical engineering and logic. Before it, a switching circuit was something you built and tested; after it, it is something you can reason about symbolically and prove correct. Every piece of digital design rests on this equivalence.",
    sources: [{ label: "Shannon, A Symbolic Analysis of Relay and Switching Circuits, MIT, 1937", url: "https://en.wikipedia.org/wiki/A_Symbolic_Analysis_of_Relay_and_Switching_Circuits" }],
  },
  {
    slug: "turing-computable",
    year: 1936,
    title: "On computable numbers",
    strand: "digital",
    countries: ["GB"],
    who: "Alan Turing",
    what: "A definition of what it means for something to be computable, by way of an abstract machine, together with a proof that some questions cannot be decided by any such machine.",
    why: "It establishes both that a general-purpose computing machine is possible and that there are limits to what it can be asked. The second half matters more often than people expect: a great many practical problems in this field are unsolvable in general and are handled with heuristics that mostly work.",
    sources: [{ label: "Turing, On Computable Numbers, Proceedings of the London Mathematical Society, 1936", url: "https://en.wikipedia.org/wiki/Turing%27s_proof" }],
  },
  {
    slug: "shannon-information",
    year: 1948,
    title: "A mathematical theory of communication",
    strand: "digital",
    countries: ["US"],
    who: "Claude Shannon",
    what: "Information given a precise measure in bits, and a proof that every channel has a capacity above which reliable communication is impossible and below which it is achievable however noisy the channel is.",
    why: "This is the most load-bearing single result on this page for anyone who works with networks. It says a noisy link is not simply a worse link - it is a link with a number attached, and that number is not negotiable by engineering effort. Every modulation scheme, every error-correcting code and every argument about how much can be pushed down a given piece of copper is an attempt to approach a bound Shannon proved exists.",
    sources: [{ label: "Shannon, A Mathematical Theory of Communication, Bell System Technical Journal, 1948", url: "https://en.wikipedia.org/wiki/A_Mathematical_Theory_of_Communication" }],
  },

  // -- STORAGE --------------------------------------------------------------
  {
    slug: "magnetic-tape",
    year: 1928,
    title: "Magnetic tape",
    strand: "storage",
    countries: ["DE", "US"],
    who: "Fritz Pfleumer",
    what: "Iron oxide bonded to a paper, later plastic, strip - a flexible medium that could be magnetised in a pattern and read back.",
    why: "The first storage medium that was cheap per unit of capacity and physically compact. It is also the ancestor of a distinction that still governs backup design: tape is sequential, and sequential media are excellent at throughput and terrible at random access.",
    sources: [{ label: "Pfleumer's 1928 patent for magnetic recording on paper tape", url: "https://en.wikipedia.org/wiki/Fritz_Pfleumer" }],
  },
  {
    slug: "ramac-350",
    year: 1956,
    title: "The first hard disk drive",
    strand: "storage",
    countries: ["US"],
    who: "IBM, RAMAC 305 with the 350 disk unit",
    what: "Fifty rotating 24-inch platters storing about five million characters, with a moving head that could reach any record without winding through everything before it.",
    why: "Random access is the point, not capacity. A tape must be traversed; a disk can be addressed. Every database, filesystem and index assumes you can go straight to a location, and that assumption starts here. The capacity was trivial and the idea was not.",
    sources: [{ label: "IBM 350 disk storage unit, shipped with the RAMAC 305, 1956", url: "https://en.wikipedia.org/wiki/IBM_305_RAMAC" }],
  },
  {
    slug: "punched-card-80-column",
    year: 1928,
    title: "The 80-column punched card",
    strand: "storage",
    countries: ["US"],
    who: "IBM",
    what: "A rectangular-hole card holding eighty characters, which became the dominant format for machine-readable data for the next four decades.",
    why: "Eighty columns is why terminals are eighty columns wide, and why so much software still assumes an eighty-character line. A physical constraint from a cardboard rectangle propagated into screens, then into style guides, then into linters, long after the last card was punched. Formats outlive their reasons.",
    sources: [{ label: "IBM's 80-column card, introduced 1928", url: "https://en.wikipedia.org/wiki/Punched_card" }],
  },
  {
    slug: "floppy-disk",
    year: 1971,
    title: "The floppy disk",
    strand: "storage",
    countries: ["US"],
    who: "IBM",
    what: "A flexible magnetic disk in a protective sleeve, originally shipped to load microcode into mainframes, then adopted as removable storage.",
    why: "It made data portable in a way tape never quite managed for ordinary use, and in doing so created the software industry's distribution model and its first serious piracy problem in the same object. The save icon on software written this decade is still a picture of one.",
    sources: [{ label: "IBM's 8-inch flexible disk, 1971", url: "https://en.wikipedia.org/wiki/Floppy_disk" }],
  },
  {
    slug: "gigabyte-drive",
    year: 1980,
    title: "A gigabyte in one cabinet",
    strand: "storage",
    countries: ["US"],
    who: "IBM 3380",
    what: "The first disk product to reach a gigabyte of capacity, in a unit the size of a large refrigerator and priced accordingly.",
    why: "Useful as a yardstick rather than a breakthrough. A capacity that needed a refrigerator-sized cabinet and a six-figure price in 1980 now costs less than lunch and fits on a fingernail - and every architectural assumption made when storage was scarce was made under the earlier conditions.",
    sources: [{ label: "IBM 3380, announced 1980", url: "https://en.wikipedia.org/wiki/IBM_3380" }],
  },
  {
    slug: "compact-disc",
    year: 1982,
    title: "The compact disc",
    strand: "storage",
    countries: ["NL", "JP"],
    who: "Philips and Sony",
    what: "Digital audio on an optical disc, standardised jointly and released in 1982, with the data-carrying CD-ROM specification following.",
    why: "The first mass-market medium that was digital end to end, and the first time consumers encountered error correction as a product feature - a scratched disc still played, which was startling to anyone used to vinyl. It also proved that two competing manufacturers agreeing on one standard beats either of them winning.",
    sources: [{ label: "The Red Book standard, Philips and Sony, with commercial release in 1982", url: "https://en.wikipedia.org/wiki/Compact_Disc_Digital_Audio" }],
  },
  {
    slug: "flash-memory",
    year: 1980,
    title: "Flash memory",
    strand: "storage",
    countries: ["JP"],
    who: "Fujio Masuoka, Toshiba",
    what: "Non-volatile solid-state memory that can be erased and rewritten in blocks, without moving parts.",
    dateNote:
      "Invention is usually dated to around 1980 with the first public presentation in 1984 and commercialisation later in the decade. The gap between invention and market is the interesting part rather than a discrepancy.",
    why: "It removes the last mechanical component from the storage path. That changes latency by orders of magnitude and changes what a filesystem should optimise for - and it introduces wear as a design constraint, which rotating media never had in the same way.",
    sources: [{ label: "Masuoka's flash memory work at Toshiba, presented 1984", url: "https://en.wikipedia.org/wiki/Flash_memory" }],
  },

  {
    slug: "pearl-street",
    year: 1882,
    title: "Commercial electricity distribution",
    strand: "electricity",
    countries: ["US"],
    who: "Thomas Edison's Pearl Street Station, New York",
    what: "A central generating station selling electricity to paying customers over a distribution network, rather than each building generating its own.",
    why: "The first utility, and therefore the first argument about centralised versus local provision - the same argument that later produced timesharing, then the data centre, then cloud. The economics that favour a shared plant over a private one have not changed since 1882; only the plant has.",
    sources: [{ label: "Pearl Street Station, in service September 1882", url: "https://en.wikipedia.org/wiki/Pearl_Street_Station" }],
  },
  {
    slug: "electron-discovered",
    year: 1897,
    title: "The electron",
    strand: "electricity",
    countries: ["GB"],
    who: "J. J. Thomson",
    what: "Cathode rays shown to consist of particles far lighter than any atom, carrying negative charge.",
    why: "Everything before this treated electricity as a fluid or a field without knowing what was actually moving. Knowing the carrier is what makes the valve, the transistor and semiconductor physics possible - you cannot deliberately control something you have not identified.",
    sources: [{ label: "Thomson's 1897 cathode ray experiments at the Cavendish Laboratory", url: "https://en.wikipedia.org/wiki/J._J._Thomson" }],
  },
  {
    slug: "moores-law",
    year: 1965,
    title: "Moore's law",
    strand: "electronics",
    countries: ["US"],
    who: "Gordon Moore",
    what: "An observation, in a trade magazine article, that the number of components on an integrated circuit had been doubling roughly annually and would likely continue.",
    why: "It is an observation that became a plan. The industry organised its roadmaps around it, which made it partly self-fulfilling for half a century. Worth understanding as economics rather than physics: the doubling continued because enormous capital was deployed on the assumption that it would.",
    sources: [{ label: "Moore, Cramming more components onto integrated circuits, Electronics, April 1965", url: "https://en.wikipedia.org/wiki/Moore%27s_law" }],
  },
  {
    slug: "microprocessor",
    year: 1971,
    title: "The microprocessor",
    strand: "electronics",
    countries: ["US"],
    who: "Intel 4004, designed by Federico Faggin, Ted Hoff, Stanley Mazor and Masatoshi Shima",
    what: "A complete central processing unit on one chip, originally built for a calculator.",
    why: "The point is not the chip but the change in who could build a computer. Once a processor is a component you buy rather than a system you design, computers stop being capital projects. Everything on the company timeline after 1975 depends on this being true.",
    sources: [{ label: "Intel 4004, announced November 1971", url: "https://en.wikipedia.org/wiki/Intel_4004" }],
  },
  {
    slug: "jacquard-loom",
    year: 1804,
    title: "Punched cards control a machine",
    strand: "digital",
    countries: ["FR"],
    who: "Joseph Marie Jacquard",
    what: "A loom whose woven pattern is determined by a chain of punched cards, each row of holes selecting which warp threads lift.",
    why: "The first separation of a program from the machine that runs it. The loom does not know what it is weaving; the cards do. That distinction - hardware that is general, instructions that are specific - is the one every computer since has been built on, and it arrived a century and a half early in a textile mill.",
    sources: [{ label: "Jacquard's loom, demonstrated from 1801 and widely adopted after 1804", url: "https://en.wikipedia.org/wiki/Jacquard_machine" }],
  },
  {
    slug: "boole-laws-of-thought",
    year: 1854,
    title: "An investigation of the laws of thought",
    strand: "digital",
    countries: ["GB", "IE"],
    who: "George Boole",
    what: "An algebra in which variables take only two values and logical reasoning becomes calculation.",
    why: "Boole was doing philosophy, not engineering, and there were no electrical circuits to apply it to. Eighty-three years later Shannon noticed the correspondence between his algebra and switching circuits. A result can sit unused for three generations and then turn out to be the foundation of an industry, which is worth remembering about anything currently filed as impractical.",
    sources: [{ label: "Boole, An Investigation of the Laws of Thought, 1854", url: "https://en.wikipedia.org/wiki/The_Laws_of_Thought" }],
  },
  {
    slug: "von-neumann-architecture",
    year: 1945,
    title: "The stored-program computer",
    strand: "digital",
    countries: ["US"],
    who: "John von Neumann, drawing on the EDVAC group's work",
    what: "A draft report describing a machine that holds its instructions in the same memory as its data, so a program can be loaded, changed and even modified while running.",
    dateNote:
      "Circulated as the First Draft of a Report on the EDVAC under von Neumann's name alone, which has been contested ever since: the design work involved Eckert, Mauchly and others, and the sole attribution was a consequence of how the draft was distributed rather than a claim about who did what.",
    why: "Before this, changing what a computer did meant rewiring it. Afterwards it meant loading different data. Every idea downstream - operating systems, compilers, malware, virtualisation - depends on instructions and data being the same kind of thing in the same place.",
    sources: [{ label: "First Draft of a Report on the EDVAC, 1945", url: "https://en.wikipedia.org/wiki/First_Draft_of_a_Report_on_the_EDVAC" }],
  },
  {
    slug: "ascii",
    year: 1963,
    title: "ASCII",
    strand: "digital",
    countries: ["US"],
    what: "A standard assignment of numbers to characters, so that machines from different manufacturers could exchange text and agree on what it said.",
    why: "Agreement is the product, not the encoding. Any consistent mapping would have worked; what mattered was that everyone used the same one. The same lesson is relearned constantly, and the cost of relearning it is visible in every mojibake bug and every system that still assumes one byte per character.",
    sources: [{ label: "ASA X3.4-1963, the first ASCII standard", url: "https://en.wikipedia.org/wiki/ASCII" }],
  },
  {
    slug: "unicode",
    year: 1991,
    title: "Unicode",
    strand: "digital",
    countries: ["US"],
    what: "A single character set intended to cover every writing system, replacing the patchwork of incompatible national encodings.",
    why: "ASCII solved agreement for one language and created a problem for everyone else. Unicode is the admission that text is harder than it looks: normalisation, collation, bidirectional text and the fact that a user-visible character is not a code point. This site's own translation rules exist because of what is in this entry - proper diacritics are cheap now and were not always.",
    sources: [{ label: "The Unicode Standard, version 1.0, 1991", url: "https://en.wikipedia.org/wiki/Unicode" }],
  },
  // -- TRANSFER -------------------------------------------------------------
  {
    slug: "electric-telegraph",
    year: 1837,
    title: "The electric telegraph",
    strand: "transfer",
    countries: ["GB", "US"],
    who: "Cooke and Wheatstone in Britain; Morse and Vail in the United States",
    what: "Messages encoded as electrical signals and sent along a wire, arriving faster than any physical carrier could travel.",
    why: "The first separation of a message from its messenger, and therefore the beginning of everything this site is about. It also produced the first version of a problem still with us: a shared medium, contention for it, and the need for a code that a receiver can unambiguously decode.",
    sources: [{ label: "Cooke and Wheatstone's 1837 patent; Morse's demonstrations in the same period", url: "https://en.wikipedia.org/wiki/Electrical_telegraph" }],
  },
  {
    slug: "transatlantic-telegraph",
    year: 1866,
    title: "A working transatlantic cable",
    strand: "transfer",
    countries: ["GB", "US"],
    what: "After failures in 1857 and 1858, a submarine telegraph cable between Ireland and Newfoundland that stayed in service.",
    why: "Intercontinental latency drops from weeks to minutes. It is also the first time the industry learns that a long cable is not a short cable scaled up - dispersion, attenuation and the physics of a very long conductor forced the theory that made later cables possible.",
    sources: [{ label: "The 1866 Atlantic Telegraph cable, following the failures of 1857 and 1858", url: "https://en.wikipedia.org/wiki/Transatlantic_telegraph_cable" }],
  },
  {
    slug: "marconi-transatlantic",
    year: 1901,
    title: "Radio across the Atlantic",
    strand: "transfer",
    countries: ["GB", "CA"],
    who: "Guglielmo Marconi",
    what: "A signal reported received in Newfoundland from Cornwall, over a distance many believed impossible given the curvature of the earth.",
    dateNote:
      "The 1901 reception has been questioned - the evidence was a faint sequence of clicks heard by ear, and later analysis has debated whether it could have been the intended signal. Subsequent transmissions were unambiguous. Recorded as reported, with the doubt noted.",
    why: "It established that radio was not limited to line of sight, which nobody could then explain - the ionosphere had not been described. A working technology outrunning its own theory is a recurring pattern in this industry.",
    sources: [{ label: "Marconi's reported transatlantic reception at Signal Hill, December 1901", url: "https://en.wikipedia.org/wiki/Guglielmo_Marconi" }],
  },
  {
    slug: "arpanet",
    year: 1969,
    title: "The first ARPANET links",
    strand: "transfer",
    countries: ["US"],
    what: "Packet-switched links between four university sites in the United States, using Interface Message Processors as the first routers.",
    why: "Packet switching rather than circuit switching: the network stops reserving a path for a conversation and starts forwarding self-describing chunks independently. Everything about congestion, routing and best-effort delivery follows from that single choice.",
    sources: [{ label: "The first four ARPANET nodes, 1969", url: "https://en.wikipedia.org/wiki/ARPANET" }],
  },
  {
    slug: "ethernet-memo",
    year: 1973,
    title: "Ethernet",
    strand: "transfer",
    countries: ["US"],
    who: "Robert Metcalfe and David Boggs, Xerox PARC",
    what: "A memo describing a broadcast network over shared coaxial cable, with stations listening before transmitting and backing off after collisions.",
    why: "The design that won, and it won by being tolerant rather than correct. It did not guarantee delivery or fair access; it assumed collisions would happen and made recovery cheap. Modern switched Ethernet has no collisions and keeps the frame format, the addressing and the name - which is a lesson about what actually persists in a standard.",
    sources: [{ label: "Metcalfe's 1973 memo at Xerox PARC describing the Ethernet concept", url: "https://en.wikipedia.org/wiki/Ethernet" }],
  },
  {
    slug: "tcp-paper",
    year: 1974,
    title: "A protocol for packet network intercommunication",
    strand: "transfer",
    countries: ["US"],
    who: "Vint Cerf and Robert Kahn",
    what: "A design for connecting different packet networks to each other, with gateways between them and a common protocol above.",
    why: "Internetworking, as distinct from networking. The insight is that the networks themselves need not agree on anything much, provided something above them does. That is why the internet absorbed every physical medium invented since without redesigning itself.",
    sources: [{ label: "Cerf and Kahn, A Protocol for Packet Network Intercommunication, IEEE Transactions on Communications, 1974", url: "https://en.wikipedia.org/wiki/Transmission_Control_Protocol" }],
  },
  {
    slug: "telephone",
    year: 1876,
    title: "The telephone",
    strand: "transfer",
    countries: ["US"],
    who: "Alexander Graham Bell, with contested priority",
    what: "Speech transmitted electrically, rather than a code standing in for words.",
    dateNote:
      "Priority is genuinely disputed - Elisha Gray filed a caveat the same day, and Antonio Meucci's earlier work is recognised by some accounts. The dispute is recorded rather than adjudicated here.",
    why: "It introduced the requirement that would dominate networks for a century: a continuous, low-latency, always-available path between two points. Circuit switching exists to provide that, and packet switching exists because it turned out to be a wasteful way to carry anything but speech.",
    sources: [{ label: "Bell's 1876 patent; Gray's same-day caveat; Meucci's earlier demonstrations", url: "https://en.wikipedia.org/wiki/Invention_of_the_telephone" }],
  },
  {
    slug: "first-modem",
    year: 1958,
    title: "The modem",
    strand: "transfer",
    countries: ["US"],
    what: "The Bell 101, converting digital data into audible tones so it could travel over telephone lines built for speech.",
    why: "The first time digital data was carried on infrastructure designed for something else, which is the pattern for everything since - DSL, cable, mobile data. It also sets the constraint the whole field then worked against: the telephone channel is about three kilohertz wide, and Shannon's theorem says exactly what that permits.",
    sources: [{ label: "The Bell 101 dataset, 1958", url: "https://en.wikipedia.org/wiki/Bell_101_modem" }],
  },
  {
    slug: "telstar",
    year: 1962,
    title: "Communications by satellite",
    strand: "transfer",
    countries: ["US", "GB", "FR"],
    what: "Telstar 1 relayed the first live transatlantic television pictures and telephone calls.",
    why: "It established a second path between continents that owed nothing to cable, and introduced a latency floor set by the speed of light and the height of the orbit. Every argument about geostationary versus low-earth-orbit constellations is a re-run of the trade this made visible.",
    sources: [{ label: "Telstar 1, launched July 1962", url: "https://en.wikipedia.org/wiki/Telstar" }],
  },
  {
    slug: "low-loss-fibre",
    year: 1970,
    title: "Low-loss optical fibre",
    strand: "transfer",
    countries: ["US"],
    who: "Robert Maurer, Donald Keck and Peter Schultz, Corning",
    what: "Glass fibre pure enough to carry light for kilometres rather than metres, crossing the threshold below which optical transmission becomes practical.",
    why: "Fibre had been understood for years and was useless because the glass was too dirty. This is a materials achievement rather than a communications one, and it is the reason bandwidth stopped being scarce. Almost every capacity figure elsewhere on this site rests on it.",
    sources: [{ label: "Corning's 1970 demonstration of fibre with attenuation below 20 decibels per kilometre", url: "https://en.wikipedia.org/wiki/Optical_fiber" }],
  },
  {
    slug: "tcpip-flag-day",
    year: 1983,
    title: "The ARPANET switches to TCP/IP",
    strand: "transfer",
    countries: ["US"],
    what: "On 1 January 1983 the network cut over from its older host protocol to TCP/IP, with no gradual transition.",
    why: "A hard cutover on a working network, which nobody would attempt today, and it is the moment the internet's protocol stack becomes the internet's protocol stack. It is also the best available demonstration that migrations succeed when the deadline is real and everyone has the same one.",
    sources: [{ label: "The ARPANET TCP/IP transition, 1 January 1983", url: "https://en.wikipedia.org/wiki/Flag_day_%28computing%29" }],
  },
  {
    slug: "world-wide-web",
    year: 1991,
    title: "The World Wide Web made public",
    strand: "transfer",
    countries: ["CH", "GB"],
    who: "Tim Berners-Lee, CERN",
    what: "Hypertext over the internet, with a naming scheme, a transfer protocol and a markup language - released for anyone to implement.",
    why: "The internet existed for two decades before most people had a reason to touch it. The web is that reason, and the decision to put it in the public domain rather than license it is why there is one web rather than several incompatible ones. Every tool on this site is delivered through it.",
    sources: [{ label: "The World Wide Web project made publicly available in 1991; CERN's public-domain release in 1993", url: "https://en.wikipedia.org/wiki/World_Wide_Web" }],
  },
  {
    slug: "tat-8",
    year: 1988,
    title: "The first transatlantic fibre cable",
    strand: "transfer",
    countries: ["US", "GB", "FR"],
    what: "TAT-8, carrying roughly 40,000 simultaneous telephone circuits across the Atlantic on optical fibre.",
    why: "Capacity per cable jumps by orders of magnitude, and the economics of long-distance traffic change permanently. Almost every argument about where data physically travels, and whose jurisdiction it passes through, dates from the fibre era beginning here.",
    sources: [{ label: "TAT-8, the first transatlantic fibre-optic cable, in service 1988", url: "https://en.wikipedia.org/wiki/TAT-8" }],
  },
  // -- MAKING ---------------------------------------------------------------
  // PRIME 2026-08-11: silicon belongs on the milestones, with the factories.
  // These seven are the arrangement a networking vendor actually depends on and
  // never documents: the process that made chips manufacturable, the machine
  // that prints them, the split between designing and fabricating, the company
  // that fabricates for everyone, the architecture nobody owns outright, the
  // factory that builds everybody's hardware, and the instruction-set argument
  // that decided what the chips look like inside.
  {
    slug: "planar-process",
    year: 1959,
    title: "The planar process",
    strand: "making",
    countries: ["US"],
    who: "Jean Hoerni at Fairchild Semiconductor",
    what: "A way of building transistors flat on the surface of a silicon wafer, protected by an oxide layer, so that many can be made and interconnected in one sequence of steps.",
    why: "The integrated circuit is an idea; the planar process is why it could be manufactured. Everything about modern electronics that depends on making millions of identical things reliably descends from this, and it is the reason Noyce's version of the integrated circuit scaled and Kilby's did not.",
    sources: [{ label: "The planar process, developed at Fairchild Semiconductor", url: "https://en.wikipedia.org/wiki/Planar_process" }],
  },
  {
    slug: "photolithography",
    year: 1955,
    title: "Printing circuits with light",
    strand: "making",
    countries: ["US"],
    what: "Patterning a wafer by projecting an image onto light-sensitive resist and etching what the light defines, rather than placing or wiring anything by hand.",
    why: "This is the machine that makes Moore's law an economic statement rather than a wish. Shrinking a feature costs a better lens and a shorter wavelength, not more labour - so the cost per transistor falls as the transistor gets smaller. No comparable manufacturing technique exists in any other industry.",
    dateNote: "Photolithography as a printing technique is far older; the date here marks its adoption in semiconductor manufacturing, which is a process rather than an event.",
    sources: [{ label: "Photolithography in semiconductor manufacturing", url: "https://en.wikipedia.org/wiki/Photolithography" }],
  },
  {
    slug: "risc",
    year: 1980,
    title: "Reduced instruction sets",
    strand: "making",
    countries: ["US"],
    who: "Work at Berkeley and Stanford, building on IBM research",
    what: "The argument that a processor with fewer, simpler, uniform instructions can be made faster and smaller than one with a large complex instruction set.",
    why: "It settled what the inside of a chip looks like. Almost every processor in networking equipment, in phones and in the machines reading this page is the descendant of that argument, and the ones that are not implement a complex instruction set on top of a simple core - which is the same conclusion arrived at from the other side.",
    sources: [{ label: "Reduced instruction set computer", url: "https://en.wikipedia.org/wiki/Reduced_instruction_set_computer" }],
  },
  {
    slug: "contract-manufacturing",
    year: 1974,
    title: "Somebody else's factory",
    strand: "making",
    countries: ["TW"],
    what: "Electronics manufacturing services: a company that owns factories and builds other companies' products, at a scale none of them could justify alone.",
    why: "The reason a networking vendor can design a switch without owning a production line, and the reason a small vendor can exist at all. It also means the badge on the front of an enterprise appliance and the building it was assembled in have no necessary relationship - a fact worth knowing before drawing conclusions about where equipment comes from.",
    dateNote: "Dated to the founding of Foxconn, now the largest firm in the category. Contract assembly existed earlier; the industrial scale did not.",
    sources: [
      { label: "Contract manufacturing in electronics", url: "https://en.wikipedia.org/wiki/Contract_manufacturer" },
      { label: "Foxconn, founded 1974", url: "https://en.wikipedia.org/wiki/Foxconn" },
    ],
  },
  {
    slug: "the-foundry",
    year: 1987,
    title: "A factory that designs nothing",
    strand: "making",
    countries: ["TW"],
    who: "Morris Chang, founding TSMC",
    what: "A semiconductor company that manufactures other companies' designs and competes with none of them.",
    why: "This is the structural change that made the modern industry possible. Before it, designing a chip meant owning a fabrication plant, so only large companies designed chips. After it, anybody with a design and a purchase order could have silicon - which is why the networking equipment on this timeline contains custom chips from companies that have never built a factory.",
    sources: [{ label: "TSMC, the pure-play foundry model", url: "https://en.wikipedia.org/wiki/TSMC" }],
  },
  {
    slug: "fabless",
    year: 1987,
    title: "Designing without building",
    strand: "making",
    countries: ["US"],
    what: "The complementary half of the foundry: companies that design and sell semiconductors while owning no manufacturing at all.",
    why: "It separated two things that had been one business and had very different economics. A fabrication plant is a capital problem measured in billions and depreciating from the day it opens; a design team is a payroll. Splitting them let small teams produce competitive silicon, and it is why specialised networking chips exist rather than only general-purpose processors.",
    sources: [{ label: "Fabless manufacturing", url: "https://en.wikipedia.org/wiki/Fabless_manufacturing" }],
  },
  {
    slug: "licensed-architecture",
    year: 1990,
    title: "An architecture nobody sells",
    strand: "making",
    countries: ["GB"],
    who: "Arm, founded as a joint venture",
    what: "A processor design licensed to other companies to manufacture, rather than sold as a chip by the company that designed it.",
    why: "It completed the separation. Manufacturing was already separable from design; now the instruction set architecture was separable from both. A vendor can license a core, add its own logic, have a foundry fabricate it and a contract manufacturer assemble the product - and own none of those four things. Most networking equipment is built exactly that way.",
    sources: [{ label: "Arm Holdings and the licensing model", url: "https://en.wikipedia.org/wiki/Arm_Holdings" }],
  },
  {
    slug: "silicon-isle",
    year: 1989,
    title: "A country decides to be a factory",
    strand: "making",
    countries: ["IE"],
    who: "IDA Ireland, and the manufacturers it recruited",
    what: "Ireland\u2019s industrial policy of attracting foreign electronics manufacturing through low manufacturing taxation, grants and an English-speaking engineering workforce, anchored by Intel\u2019s decision to build at Leixlip.",
    why: "It is the clearest case of a small country deciding what part of the industry it would occupy and then occupying it. Analog Devices came to Limerick in 1976, Apple to Cork in 1980, and Intel chose Leixlip in 1989 for its first wafer fabrication plant outside the United States. For two decades a large share of the computing equipment sold in Europe was assembled, configured or duplicated on that island.",
    dateNote: "Dated to Intel\u2019s Leixlip decision, which is the anchor most accounts use. The policy is older: a 10% manufacturing tax rate from 1980, preceded by an IDA tax holiday running from 1965, and by the shift away from protectionism set out in 1958.",
    sources: [
      { label: "Silicon Republic - Ireland\u2019s semiconductor history: Analog Devices in Limerick from 1976, Intel choosing Leixlip in 1989 for its first wafer fab outside the US", url: "https://www.siliconrepublic.com/machines/chips-ireland-semiconductor-industry-europe-ida" },
      { label: "IDA Ireland - the agency\u2019s own account of recruiting technology manufacturers", url: "https://www.idaireland.com/latest-news/insights/ireland-is-home-to-14-of-the-world%E2%80%99s-top-semiconductor-companies" },
    ],
  },
  {
    slug: "localisation",
    year: 1983,
    title: "Localisation gets its name",
    strand: "making",
    countries: ["IE"],
    who: "Production staff at Apple\u2019s Cork facility",
    what: "Assembling supplementary packs for the Apple IIe containing ROM components that configured a machine for a particular country - its character set, its keyboard layout, its video display format.",
    why: "The word this industry uses for adapting a product to a language and a place began as a name for a procedure on a factory floor in Cork. It described fitting different chips into a box, not translating a menu. When packaged software took the term over, it kept the shape of the original: a set of country-specific parts, assembled late, so that one product can ship everywhere.",
    dateNote: "The Cork plant opened in 1980; the configuration work and the in-house term date from January 1983. In February 1985 Softrans International in Dublin became the first company to define its business as localisation, its founder having encountered the word at Apple.",
    sources: [{ label: "Software localisation in Ireland 1982-2002, a timeline: Apple\u2019s Cork facility, the Apple IIe configuration packs, and the in-house term that became an industry", url: "https://techarchives.irish/software-localisation-in-ireland-1982-2002/" }],
  },
  {
    slug: "xliff",
    year: 2000,
    title: "A file format for translation",
    strand: "digital",
    countries: ["IE"],
    who: "Ian Dunlop at Novell, Paul Quigley at Oracle and Liz Tierney at Sun, in Dublin",
    what: "XLIFF, the XML Localization Interchange File Format: one representation for the text, glossaries, translation memory and code that pass between a software company and the people translating its product.",
    why: "Before it, every vendor and every translation supplier exchanged work in its own format, so effort spent on one product could not be reused on another. A shared format makes translation memory portable, which is what turns translating a product into an accumulating asset rather than a repeated cost. The first specification was published freely and taken to OASIS as an open standard.",
    sources: [{ label: "Software localisation in Ireland 1982-2002, a timeline: three Dublin-based localisation engineers initiate XLIFF in September 2000; the consortium completed a first specification in April 2001 and asked OASIS to approve it as an open standard", url: "https://techarchives.irish/software-localisation-in-ireland-1982-2002/" }],
  },
  {
    slug: "market-reserve",
    year: 1984,
    title: "A country decides to be a factory for itself",
    strand: "making",
    countries: ["BR"],
    who: "The Brazilian government, under the Politica Nacional de Informatica",
    what: "A reserve of the domestic market for computing equipment made by Brazilian-owned firms, closing it to foreign manufacturers for a defined class of products.",
    why: "It is the opposite answer to the same question Ireland answered, in the same decade. Ireland offered itself as the place where anybody\u2019s products would be manufactured; Brazil closed its market so that its own products would be. One country ended up assembling much of the equipment sold in Europe, the other ended up with Cobra, Scopus, Itautec and Sisco - and, when the reserve ended, with a generation of engineers who had built machines rather than only installed them.",
    dateNote: "Dated to the informatics law of 1984, which gave the policy its legal form. The reserve was dismantled in the early 1990s.",
    sources: [
      { label: "Politica Nacional de Informatica (Portuguese Wikipedia)", url: "https://pt.wikipedia.org/wiki/Pol%C3%ADtica_Nacional_de_Inform%C3%A1tica" },
      { label: "DIO - the informatics market reserve in Brazil, 1984-1992", url: "https://www.dio.me/articles/direto-ao-ponto-16-a-reserva-de-mercado-da-informatica-no-brasil-1984-1992" },
    ],
  },
];

/** Milestones on one strand, oldest first. */
export function milestonesByStrand(strand: MilestoneStrand): Milestone[] {
  return MILESTONES.filter((m) => m.strand === strand).sort((a, b) => a.year - b.year);
}

/** All milestones, oldest first. */
export function milestonesChronological(): Milestone[] {
  return [...MILESTONES].sort((a, b) => a.year - b.year);
}
