// ============================================================================
// src/lib/tools/dhcp-option-43/golden-vectors.ts
// ----------------------------------------------------------------------------
// Golden + reject vectors for the DHCP Option 43 encoder.
//
// EVERY GOLDEN VECTOR BELOW IS A WORKED EXAMPLE FROM THE VENDOR'S OWN
// DOCUMENTATION, not a value this module produced and then enshrined. That
// distinction is the whole point of a golden set: a vector generated by the
// code under test proves only that the code is consistent with itself. Each
// entry names its source so a future reader can check it against the vendor
// rather than against us.
//
// The Cisco and Ruckus expectations in particular are the exact strings printed
// in cisco.com and support.ruckuswireless.com documentation.
// ============================================================================

import { run, Option43Error, type Option43ErrorCode } from "./compute";

export const GOLDEN_VECTOR_SET_ID = "dhcp-option-43-golden-v1";

interface Expect {
  hex?: string;
  text?: string;
  option?: number;
  encoding?: string;
}

interface Vector {
  vendor: string;
  input: string;
  expect: Expect;
  /** Where the expected value comes from. */
  source: string;
}

export const OPTION43_GOLDEN_VECTORS: readonly Vector[] = [
  {
    vendor: "cisco-wlc",
    input: "192.168.10.5 192.168.10.20",
    expect: { hex: "f108c0a80a05c0a80a14", option: 43, encoding: "hex" },
    source:
      "cisco.com 97066: 'The type is 0xf1. The length is 2 * 4 = 8 = 0x08 ... it yields f108c0a80a05c0a80a14'",
  },
  {
    vendor: "cisco-wlc",
    input: "10.5.11.193 10.5.12.191",
    expect: { hex: "f1080a050bc10a050cbf", option: 43 },
    source: "developer.cisco.com cisco43calc worked example",
  },
  {
    vendor: "cisco-wlc",
    input: "192.168.10.10",
    expect: { hex: "f104c0a80a0a", option: 43 },
    source: "cisco.com 97066: single controller, length 0x04",
  },
  {
    vendor: "ruckus-smartzone",
    input: "192.168.0.200",
    expect: { hex: "060d3139322e3136382e302e323030", option: 43 },
    source:
      "support.ruckuswireless.com 000008703: sub-option 06, 13 characters (0x0d), IP as ASCII",
  },
  {
    vendor: "ruckus-zonedirector",
    input: "192.168.1.1",
    expect: { hex: "030b3139322e3136382e312e31", option: 43 },
    source:
      "support.ruckuswireless.com 000008703: sub-option 03 for ZoneDirector; '192.168.1.1 = 11 characters ... in Hex is 0B'",
  },
  {
    vendor: "unifi-ip",
    input: "192.168.3.10",
    expect: { hex: "0104c0a8030a", option: 43 },
    source:
      "help.ui.com 204909754: 'Start with 0104, then add your static IP ... 192.168.3.10 would be entered as 0104 c0a8030a'",
  },
  {
    vendor: "aruba",
    input: "10.0.2.15",
    expect: { text: "10.0.2.15", option: 43, encoding: "string" },
    source:
      "arubanetworking.hpe.com: option 43 format String, 'Mobility Controller IP Address. Example: 10.0.2.15'; option 60 must be ArubaAP",
  },
  {
    vendor: "fortiap",
    input: "10.10.70.1",
    expect: { option: 138, encoding: "other-option" },
    source:
      "docs.fortinet.com 540137: 'The FortiAP acquires the IP address of an AC in DHCP option 138 (the factory default)'",
  },
  {
    vendor: "extreme-wireless",
    input: "10.20.30.40",
    expect: { text: "10.20.30.40", option: 43, encoding: "string" },
    source:
      "documentation.extremenetworks.com XIQC 10.06 DG: sub-option type 1, data format String, VCI required",
  },
];

/** Inputs that must be REFUSED, and the code they must be refused with. */
export const OPTION43_REJECT_VECTORS: readonly {
  vendor: string;
  input: string;
  code: Option43ErrorCode;
  why: string;
}[] = [
  { vendor: "cisco-wlc", input: "", code: "empty", why: "no address given" },
  {
    vendor: "cisco-wlc",
    input: "192.168.1.256",
    code: "bad-address",
    why: "octet above 255",
  },
  {
    vendor: "cisco-wlc",
    input: "192.168.010.5",
    code: "bad-address",
    why: "leading zero: some DHCP servers read 010 as octal",
  },
  {
    vendor: "cisco-wlc",
    input: "192.168.1",
    code: "bad-address",
    why: "not a dotted quad",
  },
  {
    vendor: "ruckus-smartzone",
    input: "10.0.0.1 10.0.0.2",
    code: "too-many",
    why: "Ruckus takes a single address in this sub-option",
  },
  {
    vendor: "nonexistent-vendor",
    input: "10.0.0.1",
    code: "unknown-vendor",
    why: "no such profile",
  },
];

export function verifyVectors(): { passed: number; failures: string[] } {
  const failures: string[] = [];
  let passed = 0;

  for (const v of OPTION43_GOLDEN_VECTORS) {
    try {
      const r = run(v.vendor, v.input);
      const checks: [string, unknown, unknown][] = [];
      if (v.expect.hex !== undefined) checks.push(["hex", r.hex, v.expect.hex]);
      if (v.expect.text !== undefined) checks.push(["text", r.text, v.expect.text]);
      if (v.expect.option !== undefined) checks.push(["option", r.option, v.expect.option]);
      if (v.expect.encoding !== undefined) checks.push(["encoding", r.encoding, v.expect.encoding]);
      let ok = true;
      for (const [field, got, want] of checks) {
        if (got !== want) {
          failures.push(
            `${v.vendor} "${v.input}": ${field} was ${JSON.stringify(got)}, vendor doc says ${JSON.stringify(want)} (${v.source})`
          );
          ok = false;
        }
      }
      if (ok) passed++;
    } catch (e) {
      failures.push(`${v.vendor} "${v.input}": threw ${(e as Error).message}`);
    }
  }

  for (const v of OPTION43_REJECT_VECTORS) {
    try {
      run(v.vendor, v.input);
      failures.push(`${v.vendor} "${v.input}": was ACCEPTED but must be refused (${v.why})`);
    } catch (e) {
      if (e instanceof Option43Error && e.code === v.code) passed++;
      else
        failures.push(
          `${v.vendor} "${v.input}": refused with ${(e as Option43Error).code ?? "?"}, expected ${v.code}`
        );
    }
  }

  return { passed, failures };
}
