// ============================================================================
// src/app/[locale]/advisory/page.tsx
// ----------------------------------------------------------------------------
// ADVISORY — independent advice on decisions, offered through the PJ.
//
// *** THIS PAGE IS DELIBERATELY NOT LINKED FROM ANYWHERE (PRIME 2026-08-06).***
// No nav entry, no card, no footer link. It builds, it renders, and it is
// picked up automatically by sitemap.xml and llms.txt because those are
// generated by walking out/ - which is exactly the requested state: reachable
// by URL and by machines, invisible to a browsing reader, while the structure
// is worked on. Publishing it later means adding a link, nothing else.
//
// WHY "ADVISORY" RATHER THAN "CONSULTING" (PRIME's ruling, 2026-08-06). The
// distinction is not cosmetic. A client who buys "consulting" from a network
// security specialist will telephone at two in the morning when the WAF fails
// and will not think that unreasonable, because that is what consulting means
// in this industry. "Advisory" signals judgement, scoped and scheduled, and
// does boundary work that no amount of small print achieves afterwards. The
// scope section below states the same boundary in words.
//
// WHAT IS DELIBERATELY ABSENT: training and enablement of every kind. PRIME's
// standing position is that ALL education flows through Red Education, and the
// page says so explicitly rather than staying silent, because silence would
// invite exactly the enquiry that has to be redirected.
//
// ENTITY NAMING: the contracting company is NOT named here. §9.4 of the
// Architecture and Build Spec keeps Mindstream out of ordinary public copy, and
// a services page does not need a legal entity to do its job - contracting
// details belong in a proposal, not on a landing page. Flagged to PRIME as a
// question rather than assumed to be settled.
//
// STRUCTURE: hero -> availability framing -> scope in/out -> the kinds of work
// -> by-arrangement tier -> independence -> the practice corpus -> how an
// engagement runs -> contact.
// ============================================================================

import { getTranslations, setRequestLocale } from "next-intl/server";
import { ogImages } from "@/lib/og";
import { Link } from "@/i18n/navigation";
import Header from "@/components/Header";
import SiteFooter from "@/components/SiteFooter";

import ReduBrand from "@/components/ReduBrand";
export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "advisory" });
  return { ...ogImages("page", "advisory", locale, t("title")) };
}

export default async function AdvisoryPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);

  const t = await getTranslations("advisory");
  const tNav = await getTranslations("nav");

  // The five kinds of work, rendered as equals. PRIME's instruction was to
  // frame this as AVAILABILITY rather than to lead with one specialism, because
  // he is employed full time and is not trying to build a single-offer funnel.
  // So: no ordering by preference, no "most popular", no highlighted card.
  const offers = [
    { key: "offerReview" },
    { key: "offerSpec" },
    { key: "offerAssess" },
    { key: "offerSelect" },
    { key: "offerPostmortem" },
    // The by-arrangement tier, promoted from its own section into the card set
    // (PRIME 2026-08-06). It was previously set apart and deliberately
    // unfeatured; as a card it reads as one of the things on offer, which it
    // is, without the separate section implying it is a different class of
    // thing that needs explaining.
    { key: "offerArrangement" },
    // Speaking, added 2026-08-06: it is a paid engagement like the others and
    // was reachable only from the nav-less /speaking page.
    { key: "offerSpeaking" },
  ] as const;

  return (
    <>
      <a href="#main" className="skip-link">
        {tNav("skipToContent")}
      </a>
      <Header />

      <main id="main">
        <article>
          {/* Hero */}
          <section className="section">
            <div className="container section-narrow">
              <p className="hero-eyebrow">{t("eyebrow")}</p>
              <h1 className="page-hero-title">{t("title")}</h1>
              <p className="page-hero-lede">{t("lede")}</p>
            </div>
          </section>

          {/* --- YOUR ADVISOR (PRIME 2026-08-16) ---
               Mirrors the "Your instructor" block on /training: same eyebrow,
               same card, same position immediately after the hero, so a reader
               who has seen one page recognises the other. The classes are the
               teach-instructor ones, reused rather than duplicated - the block
               is the same idea on a second page, and a parallel set of
               advisory-* rules would be two things to keep in step.

               The bare `teach-instructor` class is deliberately NOT copied:
               check-css-classes showed it has no rule behind it even on
               /training, where it has been carrying nothing. The -eyebrow,
               -card, -text, -name and -body classes below are the ones that
               actually style this block. */}
          <section className="section teach-advisor">
            <div className="container teach-container">
              <p className="teach-instructor-eyebrow">{t("advisorEyebrow")}</p>

              <div className="teach-instructor-card">
                <div className="teach-instructor-text">
                  <h2 className="teach-instructor-name">Rodolfo Nützmann</h2>
                  <p className="teach-instructor-body">{t("advisorBody")}</p>
                </div>

                {/* The body says the credentials, the career record and what
                    past clients say are A CLICK AWAY. Until now the page made
                    that promise and provided one link, to /about.

                    The classes are teach-instructor-link*, which the stylesheet
                    has carried unused since /training moved these to cards
                    further down its own page. Here they are the right answer
                    rather than residue: this page has no such cards, and the
                    sentence above needs somewhere to go. */}
                <div className="teach-instructor-links">
                  <Link href="/about/credentials" className="teach-instructor-link teach-instructor-link--primary">
                    {t("advisorLinkCreds")}
                  </Link>
                  <Link href="/industry/chapters" className="teach-instructor-link">
                    {t("advisorLinkCareer")}
                  </Link>
                  <Link href="/endorsements" className="teach-instructor-link">
                    {t("advisorLinkEndorsements")}
                  </Link>
                </div>
              </div>
            </div>
          </section>

          {/* DISCLAIMER, NOW BELOW THE HERO (PRIME 2026-08-12).

              SUPERSEDES THE 2026-08-06 PLACEMENT, which put this above the
              eyebrow on the reasoning that a page leading with its own
              limitation is more credible. That argument was sound for the text
              it was written against - a notice whose substance was an
              AVAILABILITY CONSTRAINT, telling a reader who wanted training that
              they were in the wrong place.

              The notice was rewritten on 2026-08-11 and no longer says that.
              It now states who contracts the work, that pricing comes only
              after a scoping call, and whose outcome PRIME advocates for. That
              is not a warning to be met before reading; it is CONTEXT FOR AN
              OFFER THE READER HAS NOT SEEN YET. Above the hero it asked a
              stranger to absorb contracting detail before knowing what was
              being contracted.

              So the placement follows the content: the reader learns what
              advisory IS, then immediately how it works. The redirect for
              somebody who wanted training still happens on this screen, one
              paragraph later. */}
          <section className="section">
            <div className="container section-narrow">
              <div className="vendor-note">
                <p className="vendor-note-title">{t("disclaimerTitle")}</p>
                <p className="vendor-note-body"><ReduBrand>{t("disclaimerBody")}</ReduBrand></p>
              </div>
            </div>
          </section>

          {/* Availability framing. This sits before the list of offers on
              purpose: it tells the reader how to read the list. */}
          <section className="section">
            <div className="container section-narrow">
              <h2 className="section-title">{t("availabilityTitle")}</h2>
              <p className="section-body">{t("availabilityBody")}</p>
            </div>
          </section>

          {/* Scope, both directions. Saying what is not offered reads as
              seniority rather than limitation, and it prevents the enquiry
              that would otherwise have to be turned down by hand. */}
          <section className="section section-accent">
            <div className="container section-narrow">
              <h2 className="section-title">{t("scopeTitle")}</h2>
              <p className="section-body">{t("scopeIn")}</p>

              {/* Scoped class, not a change to .vendor-note-title: that rule is shared by
                  the about page, vendor pages and Practice articles, and carries no
                  margin-top at all - so the gap here was only the preceding
                  paragraph's bottom margin. PRIME 2026-08-09: widen it, on this page
                  only, so "Not offered here" reads as a turn rather than a continuation. */}
              <h3 className="vendor-note-title advisory-scope-out-title">
                {t("scopeOutTitle")}
              </h3>
              <ul className="advisory-exclusions">
                {/* Each exclusion is a TERM and an EXPLANATION, which is how the
                    copy was always written - it was previously rendered as one
                    undifferentiated run of prose per line, so four long
                    sentences sat under a heading with nothing to scan. The term
                    now leads on its own line and the explanation follows, which
                    is the difference between a list somebody reads and a list
                    somebody skips. */}
                {[1, 2, 3, 4].map((n) => (
                  <li key={n}>
                    <span className="advisory-exclusion-term">
                      {t(`exclusion${n}Term`)}
                    </span>
                    <span className="advisory-exclusion-body">
                      <ReduBrand>{t(`exclusion${n}Body`)}</ReduBrand>
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          </section>

          {/* The kinds of work */}
          <section className="section">
            <div className="container">
              <h2 className="section-title">{t("offersTitle")}</h2>
              {/* Reuses the learn-card pattern rather than introducing new
                  classes (standing CSS rule: reuse only). These are not links -
                  there is nowhere to go yet - so they render as plain cards. */}
              <ul className="learn-grid">
                {offers.map(({ key }) => (
                  <li key={key} className="learn-grid-item">
                    <div className="learn-card">
                      <h3 className="learn-card-title">{t(`${key}Title`)}</h3>
                      <p className="learn-card-summary">{t(`${key}Body`)}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          </section>

          {/* Independence. The argument the whole page rests on, and the one
              thing here that cannot be copied by someone with a similar CV. */}
          <section className="section section-accent">
            <div className="container section-narrow">
              <h2 className="section-title">{t("independenceTitle")}</h2>
              {/* The evidence paragraph and its two callouts were REMOVED
                  (PRIME 2026-08-06). They pointed at the industry timeline and
                  the tools as proof of judgement, which turned a claim about
                  independence into a claim about output - and sent a reader
                  weighing an engagement off to read company histories. The
                  independence argument stands on the first paragraph alone:
                  no product, no quota, no margin. */}
              <p className="section-body">{t("independenceBody")}</p>
            </div>
          </section>

          {/* THE PRACTICE SECTION REMOVED (PRIME 2026-08-06). The corpus is
              still linked from the homepage map and the Learn index, so it
              loses a door here and keeps two - which is the right ratio for
              free writing on a page about paid work. */}

          {/* How an engagement runs */}
          <section className="section">
            <div className="container section-narrow">
              <h2 className="section-title">{t("howTitle")}</h2>
              <ol className="course-list">
                <li>{t("howStep1")}</li>
                <li>{t("howStep2")}</li>
                <li>{t("howStep3")}</li>
                <li>{t("howStep4")}</li>
              </ol>
            </div>
          </section>

          {/* Contact */}
          <section className="section section-accent">
            <div className="container section-narrow">
              <h2 className="section-title">{t("ctaTitle")}</h2>
              <p className="section-body">{t("ctaBody")}</p>
              <p className="section-cta">
                <Link href="/contact" className="btn btn-primary">
                  {t("ctaButton")}
                </Link>
              </p>
            </div>
          </section>
        </article>
      </main>

      <SiteFooter />
    </>
  );
}
