// ============================================================================
// src/app/[locale]/advisory/page.tsx
// ----------------------------------------------------------------------------
// ADVISORY — independent advice on decisions, offered through the PJ.
//
// *** THIS PAGE IS DELIBERATELY NOT LINKED FROM ANYWHERE (PRIME 2026-08-06).***
// No nav entry, no card, no footer link. It builds, it renders, and it is
// picked up automatically by sitemap.xml and llms.txt because those are
// generated by walking out/ - which is exactly the requested state: reachable
// by URL and by machines, invisible to a browsing reader, while the structure
// is worked on. Publishing it later means adding a link, nothing else.
//
// WHY "ADVISORY" RATHER THAN "CONSULTING" (PRIME's ruling, 2026-08-06). The
// distinction is not cosmetic. A client who buys "consulting" from a network
// security specialist will telephone at two in the morning when the WAF fails
// and will not think that unreasonable, because that is what consulting means
// in this industry. "Advisory" signals judgement, scoped and scheduled, and
// does boundary work that no amount of small print achieves afterwards. The
// scope section below states the same boundary in words.
//
// WHAT IS DELIBERATELY ABSENT: training and enablement of every kind. PRIME's
// standing position is that ALL education flows through Red Education, and the
// page says so explicitly rather than staying silent, because silence would
// invite exactly the enquiry that has to be redirected.
//
// ENTITY NAMING: the contracting company is NOT named here. §9.4 of the
// Architecture and Build Spec keeps Mindstream out of ordinary public copy, and
// a services page does not need a legal entity to do its job - contracting
// details belong in a proposal, not on a landing page. Flagged to PRIME as a
// question rather than assumed to be settled.
//
// STRUCTURE: hero -> availability framing -> scope in/out -> the kinds of work
// -> by-arrangement tier -> independence -> the practice corpus -> how an
// engagement runs -> contact.
// ============================================================================

import { getTranslations, setRequestLocale } from "next-intl/server";
import { ogImages } from "@/lib/og";
import { Link } from "@/i18n/navigation";
import Header from "@/components/Header";
import SiteFooter from "@/components/SiteFooter";

import ReduBrand from "@/components/ReduBrand";
import { TESTIMONIALS } from "@/content/testimonials/data";
export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "advisory" });
  return { title: t("title"), ...ogImages("page", "advisory", locale, t("title")) };
}

export default async function AdvisoryPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);

  const t = await getTranslations("advisory");
  const tNav = await getTranslations("nav");

  // The five kinds of work, rendered as equals. PRIME's instruction was to
  // frame this as AVAILABILITY rather than to lead with one specialism, because
  // he is employed full time and is not trying to build a single-offer funnel.
  // So: no ordering by preference, no "most popular", no highlighted card.
  // THREE TIERS (PRIME 2026-09-05). The page used to present one flat list
  // headed "Where I bring the most value", which was no longer true: the
  // operational engagements below are where the value CAME FROM, over the first
  // twenty-four years, and they are not what is being sold now. Splitting them
  // says that plainly instead of letting a reader infer the wrong offer.
  //
  // Tier 1 is the offer. Tier 2 is a smaller, real offer kept deliberately
  // below it. Tier 3 is the record that makes tier 1 credible.
  const primaryOffer = { key: "offerExecutive" } as const;

  const secondaryOffers = [{ key: "offerSpeaking" }] as const;

  const trackRecord = [
    { key: "offerReview" },
    { key: "offerSpec" },
    { key: "offerAssess" },
    { key: "offerSelect" },
    { key: "offerEstate" },
    { key: "offerPostmortem" },
  ] as const;

  return (
    <>
      <a href="#main" className="skip-link">
        {tNav("skipToContent")}
      </a>
      <Header />

      <main id="main">
        <article>
          {/* Hero */}
          <section className="section">
            <div className="container section-narrow">
              <p className="hero-eyebrow">{t("eyebrow")}</p>
              <h1 className="page-hero-title">{t("title")}</h1>
              <p className="page-hero-lede">{t("lede")}</p>
            </div>
          </section>

          {/* --- YOUR ADVISOR (PRIME 2026-08-16) ---
               Mirrors the "Your instructor" block on /training: same eyebrow,
               same card, same position immediately after the hero, so a reader
               who has seen one page recognises the other. The classes are the
               teach-instructor ones, reused rather than duplicated - the block
               is the same idea on a second page, and a parallel set of
               advisory-* rules would be two things to keep in step.

               The bare `teach-instructor` class is deliberately NOT copied:
               check-css-classes showed it has no rule behind it even on
               /training, where it has been carrying nothing. The -eyebrow,
               -card, -text, -name and -body classes below are the ones that
               actually style this block. */}
          <section className="section teach-advisor">
            <div className="container teach-container">
              <p className="teach-instructor-eyebrow">{t("advisorEyebrow")}</p>

              <div className="teach-instructor-card">
                <div className="teach-instructor-text">
                  <h2 className="teach-instructor-name">Rodolfo Nützmann</h2>
                  <p className="teach-instructor-body">{t("advisorBody")}</p>
                </div>

                {/* The body says the credentials, the career record and what
                    past clients say are A CLICK AWAY. Until now the page made
                    that promise and provided one link, to /about.

                    The classes are teach-instructor-link*, which the stylesheet
                    has carried unused since /training moved these to cards
                    further down its own page. Here they are the right answer
                    rather than residue: this page has no such cards, and the
                    sentence above needs somewhere to go. */}
                <div className="teach-instructor-links">
                  <Link href="/about/credentials" className="teach-instructor-link teach-instructor-link--primary">
                    {t("advisorLinkCreds")}
                  </Link>
                  <Link href="/industry/chapters" className="teach-instructor-link">
                    {t("advisorLinkCareer")}
                  </Link>
                  <Link href="/endorsements" className="teach-instructor-link">
                    {t("advisorLinkEndorsements")}
                  </Link>
                </div>
              </div>
            </div>
          </section>

          {/* DISCLAIMER, NOW BELOW THE HERO (PRIME 2026-08-12).

              SUPERSEDES THE 2026-08-06 PLACEMENT, which put this above the
              eyebrow on the reasoning that a page leading with its own
              limitation is more credible. That argument was sound for the text
              it was written against - a notice whose substance was an
              AVAILABILITY CONSTRAINT, telling a reader who wanted training that
              they were in the wrong place.

              The notice was rewritten on 2026-08-11 and no longer says that.
              It now states who contracts the work, that pricing comes only
              after a scoping call, and whose outcome PRIME advocates for. That
              is not a warning to be met before reading; it is CONTEXT FOR AN
              OFFER THE READER HAS NOT SEEN YET. Above the hero it asked a
              stranger to absorb contracting detail before knowing what was
              being contracted.

              So the placement follows the content: the reader learns what
              advisory IS, then immediately how it works. The redirect for
              somebody who wanted training still happens on this screen, one
              paragraph later. */}
          <section className="section">
            <div className="container section-narrow">
              <div className="vendor-note">
                <p className="vendor-note-title">{t("disclaimerTitle")}</p>
                {/* AMBER PHRASE (PRIME 2026-09-05). "and contracted through"
                    is the contractual fact the rest of the paragraph turns on,
                    so it carries the same amber as the card's title and stripe.
                    t.rich keeps the phrase inside the translated string rather
                    than splitting the sentence in the component, so translators
                    can move it where their grammar needs it. */}
                <p className="vendor-note-body">
                  <ReduBrand>
                    {t.rich("disclaimerBody", {
                      amber: (chunks) => (
                        <span className="vendor-note-emphasis">{chunks}</span>
                      ),
                    })}
                  </ReduBrand>
                </p>
              </div>
            </div>
          </section>

          {/* Availability framing. This sits before the list of offers on
              purpose: it tells the reader how to read the list. */}
          <section className="section">
            <div className="container section-narrow">
              <h2 className="section-title">{t("availabilityTitle")}</h2>
              <p className="section-body">{t("availabilityBody")}</p>
            </div>
          </section>

          {/* Scope, both directions. Saying what is not offered reads as
              seniority rather than limitation, and it prevents the enquiry
              that would otherwise have to be turned down by hand. */}
          <section className="section section-accent">
            <div className="container section-narrow">
              <h2 className="section-title">{t("scopeTitle")}</h2>
              <p className="section-body">{t("scopeIn")}</p>

              {/* Scoped class, not a change to .vendor-note-title: that rule is shared by
                  the about page, vendor pages and Practice articles, and carries no
                  margin-top at all - so the gap here was only the preceding
                  paragraph's bottom margin. PRIME 2026-08-09: widen it, on this page
                  only, so "Not offered here" reads as a turn rather than a continuation. */}
              <h3 className="vendor-note-title advisory-scope-out-title">
                {t("scopeOutTitle")}
              </h3>
              <ul className="advisory-exclusions">
                {/* Each exclusion is a TERM and an EXPLANATION, which is how the
                    copy was always written - it was previously rendered as one
                    undifferentiated run of prose per line, so four long
                    sentences sat under a heading with nothing to scan. The term
                    now leads on its own line and the explanation follows, which
                    is the difference between a list somebody reads and a list
                    somebody skips. */}
                {[1, 2, 3, 4].map((n) => (
                  <li key={n}>
                    <span className="advisory-exclusion-term">
                      {t(`exclusion${n}Term`)}
                    </span>
                    <span className="advisory-exclusion-body">
                      <ReduBrand>{t(`exclusion${n}Body`)}</ReduBrand>
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          </section>

          {/* The kinds of work */}
          {/* THE PROBLEM (PRIME 2026-09-05, informed by the boutique-services
              literature, whose opening chapter is THE PROBLEM - before the
              client, the service or the go-to-market). The page described what
              is offered without ever naming what it is for, which leaves a
              reader to infer the need themselves. Placed above the offer,
              because an answer only carries weight once the question is on the
              table. */}
          <section className="section section-accent">
            <div className="container section-narrow">
              <h2 className="section-title">{t("problemTitle")}</h2>
              <p className="section-body" style={{ whiteSpace: "pre-line" }}>
                {t("problemBody")}
              </p>
            </div>
          </section>

          {/* TIER 1 - the offer. Given its own section and full width so it
              is not read as one card among several. */}
          <section className="section">
            <div className="container section-narrow">
              <h2 className="section-title">{t("offersTitle")}</h2>
              <p className="section-body" style={{ marginBottom: "1.5rem" }}>
                {t("offersLede")}
              </p>
              <div className="learn-card">
                <h3 className="learn-card-title">{t(`${primaryOffer.key}Title`)}</h3>
                <p className="learn-card-summary">{t(`${primaryOffer.key}Body`)}</p>
              </div>
            </div>
          </section>

          {/* TIER 2 - speaking. A real offer, deliberately placed and sized
              below the advisory one. */}
          <section className="section">
            <div className="container section-narrow">
              <h2 className="section-title">{t("secondaryTitle")}</h2>
              <ul className="learn-grid">
                {secondaryOffers.map(({ key }) => (
                  <li key={key} className="learn-grid-item">
                    <div className="learn-card">
                      <h3 className="learn-card-title">{t(`${key}Title`)}</h3>
                      <p className="learn-card-summary">{t(`${key}Body`)}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          </section>

          {/* TIER 3 - the record. These are not on offer; they are what the
              advice is made of. The heading says so, so that nobody reads the
              list as a menu. */}
          <section className="section section-accent">
            <div className="container">
              <h2 className="section-title">{t("recordTitle")}</h2>
              <p className="section-body" style={{ marginBottom: "2rem", maxWidth: "70ch" }}>
                {t("recordBody")}
              </p>

              {/* FEATURED CLIENT ENDORSEMENT (PRIME 2026-09-06, record #63).
                  Chosen over every colleague's word because it is a CLIENT's,
                  from the financial sector, describing design and conception
                  led across several suppliers - which is the independence
                  argument this page makes, evidenced from 2008. Rendered from
                  the verbatim catalogue by id; the English is the recorded
                  translation, never a paraphrase. */}
              {(() => {
                const q = TESTIMONIALS.find((x) => x.id === "63");
                if (!q) return null;
                const text = q.textEnglish ?? q.text;
                return (
                  <figure className="about-featured-quote">
                    <blockquote className="about-featured-quote-text">
                      {text.split("\n").map((line, i) => (
                        <p key={i}>{line}</p>
                      ))}
                    </blockquote>
                    <figcaption className="about-featured-quote-meta">
                      <span className="about-featured-quote-author">{q.author}</span>
                      {q.title ? <span className="about-featured-quote-title">{q.title}</span> : null}
                      {q.relationship ? (
                        <span className="about-featured-quote-title">{q.relationship}</span>
                      ) : null}
                      <span className="about-featured-quote-source">
                        {q.source} &middot; {q.date}
                        {q.lang !== "EN" ? " \u00b7 translated from the original" : ""}
                      </span>
                    </figcaption>
                  </figure>
                );
              })()}
              <ul className="learn-grid">
                {trackRecord.map(({ key }) => (
                  <li key={key} className="learn-grid-item">
                    <div className="learn-card">
                      <h3 className="learn-card-title">{t(`${key}Title`)}</h3>
                      <p className="learn-card-summary">{t(`${key}Body`)}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          </section>

          {/* Independence. The argument the whole page rests on, and the one
              thing here that cannot be copied by someone with a similar CV. */}
          <section className="section section-accent">
            <div className="container section-narrow">
              <h2 className="section-title">{t("independenceTitle")}</h2>
              {/* The evidence paragraph and its two callouts were REMOVED
                  (PRIME 2026-08-06). They pointed at the industry timeline and
                  the tools as proof of judgement, which turned a claim about
                  independence into a claim about output - and sent a reader
                  weighing an engagement off to read company histories. The
                  independence argument stands on the first paragraph alone:
                  no product, no quota, no margin. */}
              <p className="section-body">{t("independenceBody")}</p>
            </div>
          </section>

          {/* EARNING THE RIGHT (PRIME 2026-09-05, informed by the advisory
              literature). The page was strong on credibility and thin on the
              other terms of trustworthiness, which is the standard imbalance in
              professional-services copy. This section is the counterweight: it
              states what will NOT happen, which is the only kind of promise a
              reader cannot check against a competitor's identical claim. */}
          <section className="section">
            <div className="container section-narrow">
              <h2 className="section-title">{t("earnTitle")}</h2>
              <p className="section-body">{t("earnBody")}</p>
            </div>
          </section>

          {/* THE PRACTICE SECTION REMOVED (PRIME 2026-08-06). The corpus is
              still linked from the homepage map and the Learn index, so it
              loses a door here and keeps two - which is the right ratio for
              free writing on a page about paid work. */}

          {/* How an engagement runs */}
          <section className="section">
            <div className="container section-narrow">
              <h2 className="section-title">{t("howTitle")}</h2>
              <ol className="course-list">
                <li>{t("howStep1")}</li>
                <li>{t("howStep2")}</li>
                <li>{t("howStep3")}</li>
                <li>{t("howStep4")}</li>
              </ol>
            </div>
          </section>

          {/* Contact */}
          <section className="section section-accent">
            <div className="container section-narrow">
              <h2 className="section-title">{t("ctaTitle")}</h2>
              <p className="section-body">{t("ctaBody")}</p>
              <p className="section-cta">
                <Link href="/contact" className="btn btn-primary">
                  {t("ctaButton")}
                </Link>
              </p>
            </div>
          </section>
        </article>
      </main>

      <SiteFooter />
    </>
  );
}
