// ============================================================================
// src/lib/tools/chmod-permission-calculator/golden-vectors.ts
// ----------------------------------------------------------------------------
// GOLDEN VECTORS for the chmod permission calculator
// (set "chmod-permission-calculator-golden-2026-10-04").
//
// Each vector is one input in one of the three spellings (octal, ls string,
// symbolic clauses on a base under a umask). The pinned fields are the whole
// visible answer: ok and error, the recognised form and kind, the four octal
// digits, the nine- and ten-character strings, the binary, the flags, the three
// commands, the umask equivalent, and the clause trace. Expected values were
// captured from compute.run() on 2026-10-04 and checked by hand against POSIX
// chmod and ls and chmod(1) from coreutils 9.11 (see SOURCES in compute.ts).
// The file was generated by a script so that no expected value was retyped.
// ============================================================================

import { run, type ChmodInput, type ChmodResult } from "./compute";

/** The set id: the tool slug and the date the expected values were captured. */
export const GOLDEN_VECTOR_SET_ID = "chmod-permission-calculator-golden-2026-10-04";

/** The fields a vector pins (the steps as compact rows: clause, op, perm, mode after, notes). */
export interface ChmodPinned {
  ok: boolean; error: string | null; errorAt: string | null; form: string | null; kind: string;
  octal4: string; symbolic: string; ls: string; binary: string; flags: string[];
  commands: ChmodResult["commands"]; umaskEquivalent: ChmodResult["umaskEquivalent"];
  base: string | null; umaskUsed: string | null; steps: (string)[][] | null;
}

/** One vector: a stable name, the reason it exists, the input, and the pinned answer. */
export interface ChmodVector {
  // A short stable name (the page's Example button loads "octal-755").
  id: string;
  // Why this vector is in the set.
  why: string;
  // The input, exactly as the tool takes it.
  input: ChmodInput;
  // The pinned fields of the result.
  expect: ChmodPinned;
}

/** Reduce a result to the fields a vector pins. */
export function pin(r: ChmodResult): ChmodPinned {
  // Optional fields become null so the JSON comparison is stable; steps become compact rows.
  return {
    ok: r.ok, error: r.error ?? null, errorAt: r.errorAt ?? null, form: r.form ?? null, kind: r.kind,
    octal4: r.octal4, symbolic: r.symbolic, ls: r.ls, binary: r.binary, flags: r.flags,
    commands: r.commands, umaskEquivalent: r.umaskEquivalent,
    base: r.base ?? null, umaskUsed: r.umaskUsed ?? null,
    steps: r.steps ? r.steps.map((s) => [s.clause, s.op, s.perm, s.after, s.notes.join("|")]) : null,
  };
}

/** The vectors. */
export const VECTORS: ChmodVector[] = [
  // The everyday executable: three digits, no special bits.
  { id: "octal-755", why: "The everyday executable: three digits, no special bits.", input: {"mode":"755"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"octal","kind":"file","octal4":"0755","symbolic":"rwxr-xr-x","ls":"-rwxr-xr-x","binary":"0001 1110 1101","flags":[],"commands":{"octal":"chmod 755 <path>","symbolicAbsolute":"chmod u=rwx,g=rx,o=rx <path>","fromBase":null},"umaskEquivalent":{"umask":null,"reason":"needs-execute"},"base":null,"umaskUsed":null,"steps":null} },
  // A leading zero changes nothing; the fourth digit is simply zero.
  { id: "octal-0644", why: "A leading zero changes nothing; the fourth digit is simply zero.", input: {"mode":"0644"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"octal","kind":"file","octal4":"0644","symbolic":"rw-r--r--","ls":"-rw-r--r--","binary":"0001 1010 0100","flags":[],"commands":{"octal":"chmod 644 <path>","symbolicAbsolute":"chmod u=rw,g=r,o=r <path>","fromBase":null},"umaskEquivalent":{"umask":"022"},"base":null,"umaskUsed":null,"steps":null} },
  // A set-user-ID program: 4000 added, shown as s in the owner's execute slot.
  { id: "setuid-4755", why: "A set-user-ID program: 4000 added, shown as s in the owner's execute slot.", input: {"mode":"4755"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"octal","kind":"file","octal4":"4755","symbolic":"rwsr-xr-x","ls":"-rwsr-xr-x","binary":"1001 1110 1101","flags":["setuid-file"],"commands":{"octal":"chmod 4755 <path>","symbolicAbsolute":"chmod u=rwxs,g=rx,o=rx <path>","fromBase":null},"umaskEquivalent":{"umask":null,"reason":"special-bits"},"base":null,"umaskUsed":null,"steps":null} },
  // A shared directory: set-group-ID on a directory means new entries inherit its group.
  { id: "setgid-dir-2775", why: "A shared directory: set-group-ID on a directory means new entries inherit its group.", input: {"mode":"2775","kind":"directory"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"octal","kind":"directory","octal4":"2775","symbolic":"rwxrwsr-x","ls":"drwxrwsr-x","binary":"0101 1111 1101","flags":["setgid-directory"],"commands":{"octal":"chmod 2775 <path>","symbolicAbsolute":"chmod u=rwx,g=rwxs,o=rx <path>","fromBase":null},"umaskEquivalent":{"umask":null,"reason":"special-bits"},"base":null,"umaskUsed":null,"steps":null} },
  // /tmp: world-writable with the restricted deletion flag, the t in the last slot.
  { id: "tmp-1777", why: "/tmp: world-writable with the restricted deletion flag, the t in the last slot.", input: {"mode":"1777","kind":"directory"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"octal","kind":"directory","octal4":"1777","symbolic":"rwxrwxrwt","ls":"drwxrwxrwt","binary":"0011 1111 1111","flags":["all-permissions","world-writable-dir-sticky","sticky-directory"],"commands":{"octal":"chmod 1777 <path>","symbolicAbsolute":"chmod u=rwx,g=rwx,o=rwxt <path>","fromBase":null},"umaskEquivalent":{"umask":null,"reason":"special-bits"},"base":null,"umaskUsed":null,"steps":null} },
  // The nine-character string read back to octal.
  { id: "ls-nine", why: "The nine-character string read back to octal.", input: {"mode":"rwxr-xr-x"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"ls","kind":"file","octal4":"0755","symbolic":"rwxr-xr-x","ls":"-rwxr-xr-x","binary":"0001 1110 1101","flags":[],"commands":{"octal":"chmod 755 <path>","symbolicAbsolute":"chmod u=rwx,g=rx,o=rx <path>","fromBase":null},"umaskEquivalent":{"umask":null,"reason":"needs-execute"},"base":null,"umaskUsed":null,"steps":null} },
  // A ten-character ls string with the type letter and a lowercase s.
  { id: "ls-ten-setuid", why: "A ten-character ls string with the type letter and a lowercase s.", input: {"mode":"-rwsr-xr-x"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"ls","kind":"file","octal4":"4755","symbolic":"rwsr-xr-x","ls":"-rwsr-xr-x","binary":"1001 1110 1101","flags":["setuid-file"],"commands":{"octal":"chmod 4755 <path>","symbolicAbsolute":"chmod u=rwxs,g=rx,o=rx <path>","fromBase":null},"umaskEquivalent":{"umask":null,"reason":"special-bits"},"base":null,"umaskUsed":null,"steps":null} },
  // The type letter d sets the kind; t means others can search.
  { id: "ls-ten-directory-sticky", why: "The type letter d sets the kind; t means others can search.", input: {"mode":"drwxrwxrwt"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"ls","kind":"directory","octal4":"1777","symbolic":"rwxrwxrwt","ls":"drwxrwxrwt","binary":"0011 1111 1111","flags":["all-permissions","world-writable-dir-sticky","sticky-directory"],"commands":{"octal":"chmod 1777 <path>","symbolicAbsolute":"chmod u=rwx,g=rwx,o=rwxt <path>","fromBase":null},"umaskEquivalent":{"umask":null,"reason":"special-bits"},"base":null,"umaskUsed":null,"steps":null} },
  // Capital S: set-user-ID without the owner's execute bit.
  { id: "ls-capital-s", why: "Capital S: set-user-ID without the owner's execute bit.", input: {"mode":"rwSr--r--"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"ls","kind":"file","octal4":"4644","symbolic":"rwSr--r--","ls":"-rwSr--r--","binary":"1001 1010 0100","flags":["setuid-without-execute"],"commands":{"octal":"chmod 4644 <path>","symbolicAbsolute":"chmod u=rws,g=r,o=r <path>","fromBase":null},"umaskEquivalent":{"umask":null,"reason":"special-bits"},"base":null,"umaskUsed":null,"steps":null} },
  // u+x then go-w on 644; the second clause finds nothing to remove.
  { id: "symbolic-two-clauses", why: "u+x then go-w on 644; the second clause finds nothing to remove.", input: {"mode":"u+x,go-w","base":"644"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"symbolic","kind":"file","octal4":"0744","symbolic":"rwxr--r--","ls":"-rwxr--r--","binary":"0001 1110 0100","flags":[],"commands":{"octal":"chmod 744 <path>","symbolicAbsolute":"chmod u=rwx,g=r,o=r <path>","fromBase":"chmod u+x <path>"},"umaskEquivalent":{"umask":null,"reason":"needs-execute"},"base":"0644","umaskUsed":"022","steps":[["u+x","+","x","0744",""],["go-w","-","w","0744",""]]} },
  // a=rX on a directory: X grants search because the target is a directory.
  { id: "symbolic-capital-x-directory", why: "a=rX on a directory: X grants search because the target is a directory.", input: {"mode":"a=rX","base":"644","kind":"directory"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"symbolic","kind":"directory","octal4":"0555","symbolic":"r-xr-xr-x","ls":"dr-xr-xr-x","binary":"0001 0110 1101","flags":[],"commands":{"octal":"chmod 555 <path>","symbolicAbsolute":"chmod u=rx,g=rx,o=rx <path>","fromBase":"chmod u+x,u-w,g+x,o+x <path>"},"umaskEquivalent":{"umask":"222"},"base":"0644","umaskUsed":"022","steps":[["a=rX","=","rX","0555",""]]} },
  // a+X on a plain file with no execute bit: X grants nothing (POSIX).
  { id: "symbolic-capital-x-file", why: "a+X on a plain file with no execute bit: X grants nothing (POSIX).", input: {"mode":"a+X","base":"644"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"symbolic","kind":"file","octal4":"0644","symbolic":"rw-r--r--","ls":"-rw-r--r--","binary":"0001 1010 0100","flags":[],"commands":{"octal":"chmod 644 <path>","symbolicAbsolute":"chmod u=rw,g=r,o=r <path>","fromBase":null},"umaskEquivalent":{"umask":"022"},"base":"0644","umaskUsed":"022","steps":[["a+X","+","X","0644","x-skipped"]]} },
  // g+s,o-rwx on 755: a group-shared directory closed to others.
  { id: "symbolic-setgid-dir", why: "g+s,o-rwx on 755: a group-shared directory closed to others.", input: {"mode":"g+s,o-rwx","base":"755","kind":"directory"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"symbolic","kind":"directory","octal4":"2750","symbolic":"rwxr-s---","ls":"drwxr-s---","binary":"0101 1110 1000","flags":["setgid-directory"],"commands":{"octal":"chmod 2750 <path>","symbolicAbsolute":"chmod u=rwx,g=rxs,o= <path>","fromBase":"chmod g+s,o-rx <path>"},"umaskEquivalent":{"umask":null,"reason":"special-bits"},"base":"0755","umaskUsed":"022","steps":[["g+s","+","s","2755",""],["o-rwx","-","rwx","2750",""]]} },
  // chmod 755 on a 2775 directory keeps set-group-ID (chmod(1): preserved unless 00755, -6000 or =755).
  { id: "gnu-dir-preserves-setgid", why: "chmod 755 on a 2775 directory keeps set-group-ID (chmod(1): preserved unless 00755, -6000 or =755).", input: {"mode":"755","base":"2775","kind":"directory"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"octal","kind":"directory","octal4":"2755","symbolic":"rwxr-sr-x","ls":"drwxr-sr-x","binary":"0101 1110 1101","flags":["setgid-directory"],"commands":{"octal":"chmod 2755 <path>","symbolicAbsolute":"chmod u=rwx,g=rxs,o=rx <path>","fromBase":"chmod g-w <path>"},"umaskEquivalent":{"umask":null,"reason":"special-bits"},"base":"2775","umaskUsed":null,"steps":[["755","=","755","2755","gnu-dir-preserves-special"]]} },
  // 00755 on the same directory clears it.
  { id: "gnu-five-digits-clear", why: "00755 on the same directory clears it.", input: {"mode":"00755","base":"2775","kind":"directory"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"octal","kind":"directory","octal4":"0755","symbolic":"rwxr-xr-x","ls":"drwxr-xr-x","binary":"0001 1110 1101","flags":[],"commands":{"octal":"chmod 755 <path>","symbolicAbsolute":"chmod u=rwx,g=rx,o=rx <path>","fromBase":"chmod g-ws <path>"},"umaskEquivalent":{"umask":"022"},"base":"2775","umaskUsed":null,"steps":null} },
  // =755 on the same directory clears it too.
  { id: "gnu-equals-numeric", why: "=755 on the same directory clears it too.", input: {"mode":"=755","base":"2775","kind":"directory"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"symbolic","kind":"directory","octal4":"0755","symbolic":"rwxr-xr-x","ls":"drwxr-xr-x","binary":"0001 1110 1101","flags":[],"commands":{"octal":"chmod 755 <path>","symbolicAbsolute":"chmod u=rwx,g=rx,o=rx <path>","fromBase":"chmod g-ws <path>"},"umaskEquivalent":{"umask":"022"},"base":"2775","umaskUsed":"022","steps":[["=755","=","755","0755","gnu-numeric-operator"]]} },
  // u=rwx,g=rx,o= on 666: an empty perm after = clears the class.
  { id: "symbolic-absolute-empty-perm", why: "u=rwx,g=rx,o= on 666: an empty perm after = clears the class.", input: {"mode":"u=rwx,g=rx,o=","base":"666"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"symbolic","kind":"file","octal4":"0750","symbolic":"rwxr-x---","ls":"-rwxr-x---","binary":"0001 1110 1000","flags":[],"commands":{"octal":"chmod 750 <path>","symbolicAbsolute":"chmod u=rwx,g=rx,o= <path>","fromBase":"chmod u+x,g+x,g-w,o-rw <path>"},"umaskEquivalent":{"umask":null,"reason":"needs-execute"},"base":"0666","umaskUsed":"022","steps":[["u=rwx","=","rwx","0766",""],["g=rx","=","rx","0756",""],["o=","=","","0750",""]]} },
  // +x with no class under umask 022: the umask has no execute bits, so all three are set.
  { id: "umask-no-who", why: "+x with no class under umask 022: the umask has no execute bits, so all three are set.", input: {"mode":"+x","base":"644","umask":"022"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"symbolic","kind":"file","octal4":"0755","symbolic":"rwxr-xr-x","ls":"-rwxr-xr-x","binary":"0001 1110 1101","flags":[],"commands":{"octal":"chmod 755 <path>","symbolicAbsolute":"chmod u=rwx,g=rx,o=rx <path>","fromBase":"chmod u+x,g+x,o+x <path>"},"umaskEquivalent":{"umask":null,"reason":"needs-execute"},"base":"0644","umaskUsed":"022","steps":[["+x","+","x","0755",""]]} },
  // +w with no class under umask 022: group and other write are masked out.
  { id: "umask-masks-write", why: "+w with no class under umask 022: group and other write are masked out.", input: {"mode":"+w","base":"644","umask":"022"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"symbolic","kind":"file","octal4":"0644","symbolic":"rw-r--r--","ls":"-rw-r--r--","binary":"0001 1010 0100","flags":[],"commands":{"octal":"chmod 644 <path>","symbolicAbsolute":"chmod u=rw,g=r,o=r <path>","fromBase":null},"umaskEquivalent":{"umask":"022"},"base":"0644","umaskUsed":"022","steps":[["+w","+","w","0644","umask-applied"]]} },
  // g=u copies the owner's bits to the group.
  { id: "permcopy", why: "g=u copies the owner's bits to the group.", input: {"mode":"g=u","base":"750"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"symbolic","kind":"file","octal4":"0770","symbolic":"rwxrwx---","ls":"-rwxrwx---","binary":"0001 1111 1000","flags":[],"commands":{"octal":"chmod 770 <path>","symbolicAbsolute":"chmod u=rwx,g=rwx,o= <path>","fromBase":"chmod g+w <path>"},"umaskEquivalent":{"umask":null,"reason":"needs-execute"},"base":"0750","umaskUsed":"022","steps":[["g=u","=","u","0770","permcopy"]]} },
  // o+w,u-r: write without read and others above the owner, both flagged.
  { id: "odd-combination", why: "o+w,u-r: write without read and others above the owner, both flagged.", input: {"mode":"o+w,u-r","base":"644"}, expect: {"ok":true,"error":null,"errorAt":null,"form":"symbolic","kind":"file","octal4":"0246","symbolic":"-w-r--rw-","ls":"--w-r--rw-","binary":"0000 1010 0110","flags":["world-writable-file","owner-write-without-read","owner-less-than-others"],"commands":{"octal":"chmod 246 <path>","symbolicAbsolute":"chmod u=w,g=r,o=rw <path>","fromBase":"chmod u-r,o+w <path>"},"umaskEquivalent":{"umask":"420"},"base":"0644","umaskUsed":"022","steps":[["o+w","+","w","0646",""],["u-r","-","r","0246",""]]} },
  // 8 is not an octal digit.
  { id: "error-octal-digit", why: "8 is not an octal digit.", input: {"mode":"789"}, expect: {"ok":false,"error":"octal-digit","errorAt":"8","form":null,"kind":"file","octal4":"0000","symbolic":"---------","ls":"----------","binary":"0000 0000 0000","flags":[],"commands":{"octal":"","symbolicAbsolute":"","fromBase":null},"umaskEquivalent":{"umask":null},"base":null,"umaskUsed":null,"steps":null} },
  // Ten permission letters with no type letter: an ls typo, named as such.
  { id: "error-ls-typo", why: "Ten permission letters with no type letter: an ls typo, named as such.", input: {"mode":"rwxrwxrwxx"}, expect: {"ok":false,"error":"ls-position","errorAt":"rwxrwxrwxx","form":null,"kind":"file","octal4":"0000","symbolic":"---------","ls":"----------","binary":"0000 0000 0000","flags":[],"commands":{"octal":"","symbolicAbsolute":"","fromBase":null},"umaskEquivalent":{"umask":null},"base":null,"umaskUsed":null,"steps":null} },
  // q is not a permission letter.
  { id: "error-symbolic-perm", why: "q is not a permission letter.", input: {"mode":"u+q"}, expect: {"ok":false,"error":"symbolic-perm","errorAt":"q","form":null,"kind":"file","octal4":"0000","symbolic":"---------","ls":"----------","binary":"0000 0000 0000","flags":[],"commands":{"octal":"","symbolicAbsolute":"","fromBase":null},"umaskEquivalent":{"umask":null},"base":null,"umaskUsed":null,"steps":null} },
  // Nothing to read.
  { id: "error-empty", why: "Nothing to read.", input: {"mode":""}, expect: {"ok":false,"error":"empty","errorAt":"","form":null,"kind":"file","octal4":"0000","symbolic":"---------","ls":"----------","binary":"0000 0000 0000","flags":[],"commands":{"octal":"","symbolicAbsolute":"","fromBase":null},"umaskEquivalent":{"umask":null},"base":null,"umaskUsed":null,"steps":null} },
];

/** What verifyVectors reports (the shape scripts/run-golden-vectors.mts reads). */
export interface VerifyReport {
  // The set id.
  setId: string;
  // Vectors run.
  total: number;
  // Vectors whose pinned fields matched.
  passed: number;
  // The ones that did not, with a reason each.
  failures: { id: string; reason: string }[];
}

/** Run every vector and compare its pinned fields byte for byte. */
export function verifyVectors(): VerifyReport {
  // Failures found.
  const failures: { id: string; reason: string }[] = [];
  // Each vector.
  for (const v of VECTORS) {
    // A throw is a failure too.
    try {
      // Run and reduce (through JSON, as the expected values were captured).
      const got = JSON.stringify(pin(run(v.input)));
      // The expected text.
      const want = JSON.stringify(v.expect);
      // Compare.
      if (got !== want) {
        // The first differing character, for a readable reason.
        let k = 0;
        // Walk to it.
        while (k < got.length && got[k] === want[k]) k++;
        // Record.
        failures.push({ id: v.id, reason: `differs at ${k}: got ...${got.slice(Math.max(0, k - 30), k + 50)}... want ...${want.slice(Math.max(0, k - 30), k + 50)}...` });
      }
    } catch (e) {
      // The error.
      failures.push({ id: v.id, reason: `threw: ${(e as Error).message}` });
    }
  }
  // The report.
  return { setId: GOLDEN_VECTOR_SET_ID, total: VECTORS.length, passed: VECTORS.length - failures.length, failures };
}
