// ============================================================================
// src/lib/tools/f5-bigip-license-explainer/golden-vectors.ts
// ----------------------------------------------------------------------------
// GOLDEN VECTORS for the BIG-IP license explainer engine.
//
// The two fixtures below are structure-faithful DISTILLATIONS of two real
// license files provided by the site author from lab systems (2026-07-03):
// one BIG-IQ-managed, one licensed directly on the BIG-IP. Every line shape,
// section, repeat-key pattern, and value variant observed in the originals is
// preserved; ALL registration keys, module keys, and cryptographic blobs are
// MASKED (AAAAA-... / short stand-ins) so nothing sensitive ever ships in the
// repository. The Service Check Date values are kept verbatim because the
// K7727 verdict they pin (via the sibling f5-service-check-date engine's
// vendored table) is part of what these vectors prove:
//   * 20240218 -> newest reachable 17.1.x (LCD 2023-02-08), blocked from
//     17.5.x (LCD 2025-02-12);
//   * 20171122 -> newest reachable 13.1.x (LCD 2017-09-12), blocked from
//     14.0.x (LCD 2018-07-11).
//
// Checks are dotted paths into the parsed result (with a token:<key> selector
// for the flat token list), so each vector reads as a compact spec of what
// the fixture must decode to.
// ============================================================================

import {
  run,
  BigipLicenseError,
  type BigipLicenseErrorCode,
  type LicenseToken,
} from "./compute";

export const GOLDEN_VECTOR_SET_ID = "f5-bigip-license-explainer-golden-v1";

// ----------------------------------------------------------------------------
// Fixtures (masked distillations - see header)
// ----------------------------------------------------------------------------

/** BIG-IQ-managed lab VE license (distilled; keys/blobs masked). */
export const FIXTURE_BIGIQ = `#
Auth vers :                        5b
#
#       BIG-IQ Product License File
#       DO NOT EDIT THIS FILE!!
#
Usage :                            Production
#
Vendor :                           F5 Networks, Inc.
#
#       Module List 
#
active module :                    BIG-IP, VE, LAB|AAAAAAA-AAAAAAA|Rate Shaping|External Interface and Network HSM, VE|SSL, Forward Proxy, VE|BIG-IP VE, Multicast Routing|Routing Bundle, VE|ASM, VE|SSL, VE|DNS VE Lab  (10K QPS)|Max Compression, VE|Advanced Protocols, VE|AFM, VE (LAB ONLY - NO ROUTING)|DNSSEC|VE, Carrier Grade NAT (AFM ONLY)|PSM, VE|APM, Lab, VE|Advanced Web Application Firewall, VE Lab|SSL Orchestrator, VE
optional module :                  Anti-Bot Mobile, VE 25 Mbps
optional module :                  App Mode (TMSH Only, No Root/Bash)
optional module :                  FIPS 140, BIG-IP VE-200M
optional module :                  IP Intelligence, 1Yr, VE-200M/VE-25M
optional module :                  IP Intelligence, 3Yr, VE-200M/VE-25M
optional module :                  ONAP
optional module :                  Threat Campaigns, 1Yr, VE-200M/VE-25M
optional module :                  Threat Campaigns, 3Yr, VE-200M/VE-25M
optional module :                  URL Filtering, 1Yr, VE
optional module :                  URL Filtering, 3Yr, VE
optional module :                  URL Filtering, VE-25M-1G, 500 Sessions, 1Yr
optional module :                  URL Filtering, VE-25M-1G, 500 Sessions, 3Yr
#
perf_SSL_Mbps :                    1
gtm_rate_limit :                   10000
apm_urlf_limited_sessions :        50
perf_VE_cores :                    8
#
#       License Tokens for Module BIG-IP, VE, LAB key AAAAAAA-AAAAAAA
waf_gc :                           enabled
perf_VE_throughput_Mbps :          10
mod_ltm :                          enabled
ltm_lb_pool_member_limit :         UNLIMITED
Exclusive_version :                11.6.*
Exclusive_version :                12.*.*
Exclusive_version :                13.*.*
Exclusive_version :                14.*.*
Exclusive_version :                15.*.*
Exclusive_version :                16.*.*
Exclusive_version :                5.*.*
Exclusive_version :                6.*.*
Exclusive_version :                7.*.*
Exclusive_version :                8.*.*
Exclusive_Platform :               Z100
Exclusive_Platform :               Z100A
Exclusive_Platform :               Z100a_icm
Exclusive_Platform :               Z100AlibabaCloud
Exclusive_Platform :               Z100AzureCloud
Exclusive_Platform :               Z100GoogleCloud
Exclusive_Platform :               Z100H
Exclusive_Platform :               Z100K
Exclusive_Platform :               Z100x
asm_apps :                         unlimited
Deny_version :                     10.*.*
Deny_version :                     11.0.*
Deny_version :                     9.*.*
#
license_manager_key :              LS0tMASKEDPUBLICKEYBLOBLS0t
#
#       Licensing Information 
#
Licensed date :                    20171103
Service check date :               20240218
#
#       Platform Information 
#
Registration Key :                 AAAAA-BBBBB-CCCCC-DDDDD-EEEEEEE
Licensed version :                 5.3.0
Platform ID :                      Z100
#
pool_license_information : QXV0aE1BU0tFRA==
Dossier : 01b6d3971a4a5eMASKED
Authorization : 179b386e9c6460MASKED
`;

/** Directly-licensed BIG-IP VE license (distilled; keys/blobs masked). */
export const FIXTURE_DIRECT = `#
Auth vers :                   5b
#
#       BIG-IP System License Key File
#       DO NOT EDIT THIS FILE!!
#
#       Install this file as "/config/bigip.license".
#
Usage :                       F5 Internal Product Development
#
Vendor :                      F5 Networks, Inc.
#
#       Module List 
#
active module :               Best Bundle, 1Gbps|BBBBBBB-BBBBBBB|SDN Services, VE|DNS-GTM, Base, 1Gbps|ASM, VE|AFM, VE|Acceleration Manager, VE|APM, Base, VE GBB (500 CCU)|Anti-Virus Checks|Routing Bundle, VE|PSM, VE|CGN, BIG-IP VE, AFM ONLY
active module :               LTM, 1 Gbps, VE|CCCCCCC-CCCCCCC|IPV6 Gateway|Rate Shaping|Ram Cache|50 MBPS COMPRESSION|SSL, 500 TPS Per Core|SSL, VE|Max Compression, VE
optional module :             Acceleration Manager, VE
optional module :             Advanced Protocols, VE
optional module :             AFM, VE
optional module :             APM, Base, VE
optional module :             ASM, VE
optional module :             Better Bundle, 1Gbps
optional module :             Routing Bundle, VE
optional module :             SDN Services, VE
optional module :             WOM, VE
#
gtm_licensed_objects :        25
apm_sessions :                500
apm_urlf_limited_sessions :   2510
perf_SSL_Mbps :               2000
perf_VE_throughput_Mbps :     1000
#
#       License Tokens for null on Base Key FFFFF-GGGGG-HHHHH-IIIII-JJJJJJJ
#
rlt_geoip :                   enable
#
#       License Tokens for SSL, Max TPS, VE on Base Key FFFFF-GGGGG-HHHHH-IIIII-JJJJJJJ
#
perf_SSL_total_TPS :          UNLIMITED
#
#       License Tokens for Module LTM, 1 Gbps, VE key CCCCCCC-CCCCCCC
#
mod_ltm :                     enabled
Exclusive_Platform :          Z100
Exclusive_Platform :          Z100H
Exclusive_Platform :          Z100K
Exclusive_Platform :          Z100x
#
#       Licensing Information 
#
Licensed date :               20171122
Service check date :          20171122
#
#       Platform Information 
#
Registration Key :            FFFFF-GGGGG-HHHHH-IIIII-JJJJJJJ
Licensed version :            13.0.0
Platform ID :                 Z100
#
certificate_auth :            v2
#
Dossier :                     1286c57cd91225faMASKED
Authorization :               ccdf88c24b224695MASKED
`;

// ----------------------------------------------------------------------------
// Vector shapes
// ----------------------------------------------------------------------------

export interface LicenseGoldenVector {
  id: string;
  description: string;
  input: string;
  /** Dotted-path assertions into the parsed result. Paths support array
   *  indices ("activeModules.0.name"), ".length", and the "token:<key>"
   *  selector into the flat token list ("token:perf_VE_cores.number"). */
  checks: Record<string, unknown>;
}

export interface LicenseRejectVector {
  id: string;
  description: string;
  input: string;
  expectCode: BigipLicenseErrorCode;
}

export const LICENSE_GOLDEN_VECTORS: LicenseGoldenVector[] = [
  {
    id: "bigiq-managed-lab-ve",
    description:
      "BIG-IQ-managed lab VE fixture: flavor, identity fields, module + list counts, token variants, K7727 verdict",
    input: FIXTURE_BIGIQ,
    checks: {
      "flavor": "bigiq-managed",
      "headerTitle": "BIG-IQ Product License File",
      "usage": "Production",
      "authVers": "5b",
      "registrationKey.value": "AAAAA-BBBBB-CCCCC-DDDDD-EEEEEEE",
      "registrationKey.shapeValid": true,
      "licensedVersion": "5.3.0",
      "platformId.id": "Z100",
      "platformId.decoded": "BIG-IP Virtual Edition (VE)",
      "licensedDate.compact": "20171103",
      "serviceCheckDate.compact": "20240218",
      "serviceCheckDate.k7727.newestReachable.label": "17.1.x",
      "serviceCheckDate.k7727.nextBlocked.label": "17.5.x",
      "activeModules.length": 1,
      "activeModules.0.name": "BIG-IP, VE, LAB",
      "activeModules.0.key": "AAAAAAA-AAAAAAA",
      "activeModules.0.keyShapeValid": true,
      "activeModules.0.features.length": 17,
      "optionalModules.length": 12,
      "exclusiveVersions.length": 10,
      "bigipVersionCeiling": "16.*.*",
      "denyVersions.length": 3,
      "exclusivePlatforms.length": 9,
      "validation.licenseManagerKey.present": true,
      "validation.poolLicenseInformation.present": true,
      "token:perf_VE_cores.kind": "number",
      "token:perf_VE_cores.number": 8,
      "token:ltm_lb_pool_member_limit.kind": "unlimited",
      "token:asm_apps.kind": "unlimited",
      "licenseStart": null,
      "licenseEnd": null,
      "applianceSN": null,
    },
  },
  {
    id: "direct-bigip-ve",
    description:
      "Directly-licensed fixture: two active-module lines with distinct keys, 'enable' variant, no Exclusive_version",
    input: FIXTURE_DIRECT,
    checks: {
      "flavor": "direct",
      "headerTitle": "BIG-IP System License Key File",
      "usage": "F5 Internal Product Development",
      "registrationKey.value": "FFFFF-GGGGG-HHHHH-IIIII-JJJJJJJ",
      "registrationKey.shapeValid": true,
      "licensedVersion": "13.0.0",
      "serviceCheckDate.compact": "20171122",
      "serviceCheckDate.k7727.newestReachable.label": "13.1.x",
      "serviceCheckDate.k7727.nextBlocked.label": "14.0.x",
      "activeModules.length": 2,
      "activeModules.0.name": "Best Bundle, 1Gbps",
      "activeModules.0.key": "BBBBBBB-BBBBBBB",
      "activeModules.0.features.length": 10,
      "activeModules.1.name": "LTM, 1 Gbps, VE",
      "activeModules.1.key": "CCCCCCC-CCCCCCC",
      "activeModules.1.features.length": 7,
      "optionalModules.length": 9,
      "exclusiveVersions.length": 0,
      "bigipVersionCeiling": null,
      "exclusivePlatforms.length": 4,
      "validation.licenseManagerKey.present": false,
      "validation.certificateAuth": "v2",
      "token:rlt_geoip.kind": "enabled",
      "token:perf_SSL_total_TPS.kind": "unlimited",
      "token:apm_urlf_limited_sessions.number": 2510,
    },
  },
  {
    id: "scd-with-service-status",
    description:
      "the Service Status line (F5 K42091606, shown when no active contract) is captured verbatim",
    input: "Service check date :          20240218\nService Status : As of 2026-07-03 there is no active service contract.\n",
    checks: {
      "recognized": true,
      "serviceCheckDate.compact": "20240218",
      "serviceStatus": "As of 2026-07-03 there is no active service contract.",
    },
  },
  {
    id: "scd-fragment-only",
    description:
      "a fragment carrying only the service-check-date line is still recognized and gets the K7727 verdict",
    input: "Service check date :               20210611\n",
    checks: {
      "recognized": true,
      "serviceCheckDate.compact": "20210611",
      "serviceCheckDate.k7727.newestReachable.label": "16.1.x",
      "flavor": "unknown",
      "activeModules.length": 0,
    },
  },
];

export const LICENSE_REJECT_VECTORS: LicenseRejectVector[] = [
  { id: "r-empty", description: "empty input", input: "   ", expectCode: "empty" },
  {
    id: "r-not-a-license",
    description: "text with no license markers at all",
    input: "hello world\nthis is not a license\n",
    expectCode: "notRecognized",
  },
];

// ----------------------------------------------------------------------------
// Runner
// ----------------------------------------------------------------------------

export interface VectorFailure {
  id: string;
  reason: string;
}

/** Resolve a dotted check path against the parsed result (see checks docs). */
function getPath(root: unknown, path: string): unknown {
  let cur: unknown = root;
  for (const seg of path.split(".")) {
    if (cur === null || cur === undefined) return cur;
    if (seg.startsWith("token:")) {
      const key = seg.slice("token:".length);
      const tokens = (cur as { tokens?: LicenseToken[] }).tokens ?? [];
      cur = tokens.find((t) => t.key === key);
      continue;
    }
    cur = (cur as Record<string, unknown>)[seg];
  }
  return cur;
}

/** Run every vector; return a pass/fail report (build/CI + standalone use). */
export function verifyVectors(): { passed: number; failed: number; failures: VectorFailure[] } {
  const failures: VectorFailure[] = [];
  let passed = 0;

  for (const v of LICENSE_GOLDEN_VECTORS) {
    try {
      const got = run(v.input);
      let ok = true;
      for (const [path, expected] of Object.entries(v.checks)) {
        const actual = getPath(got, path);
        if (actual !== expected) {
          failures.push({ id: v.id, reason: `${path}: got ${JSON.stringify(actual)}, want ${JSON.stringify(expected)}` });
          ok = false;
          break;
        }
      }
      if (ok) passed++;
    } catch (err) {
      failures.push({ id: v.id, reason: `threw ${(err as Error).message}` });
    }
  }

  for (const v of LICENSE_REJECT_VECTORS) {
    try {
      run(v.input);
      failures.push({ id: v.id, reason: "expected throw, got result" });
    } catch (err) {
      if (err instanceof BigipLicenseError && err.code === v.expectCode) passed++;
      else failures.push({ id: v.id, reason: `wrong error: ${(err as Error).message}` });
    }
  }

  return { passed, failed: failures.length, failures };
}
